import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'UABT8U4R';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));pub=json.loads((d/'publication.json').read_text(encoding='utf8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf8'))['draft'];body=Path(pub['note']).read_text(encoding='utf8');w.validate_structure(draft)
expected=[f'Figure {n}' for n in range(1,6)]+['Table 1']
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'eight_chapters':len(re.findall(r'^# ',body,re.M))==8,'no_h2':not re.search(r'^## ',body,re.M),'no_markers':'<!--FIGURE:' not in body,'all_urls_embedded':all(x['url'] in body for x in pub['images']),'all_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'all_six_graphics':sorted(x['label'] for x in pub['images'])==sorted(expected) and len(re.findall(r'!\[[^\]]*\]\(https://',body))==6,'source_review_pass':pub['source_review']['pass'],'classification_deferred':'文献笔记待归类' in pub['note'],'four_results_sections':len(re.findall(r'^### ',body,re.M))==4,'five_QA':len(re.findall(r'\*\*问题',body))==5,'no_silent_yield_correction':'0.2%' in body and '0.5%' in body and '不擅自将 50 nmol 改成 5 μmol' in body,'methods_results_discrepancy':'表达培养 18 hr' in body and '16 hr' in body,'butyryl_NMR_boundary':'标准品 NMR 不能移作酶促样品 NMR' in body,'retention_discrepancy':'8.53 ± 0.01 min' in body and '8.63 min' in body,'kinetic_unit_retained':'s⁻¹·nM⁻¹' in body,'competition_not_independent_kcat':'非天然供体由竞争产品比估计' in body,'distribution_not_export_proof':'不等于已识别主动外排机制' in body,'not_denovo_taxol':'它加工外源高级前体' in body,'human_review_not_claimed':'human_full_paper_review: false' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf8'));changed=[x['path'] for x in baseline if not(w.VAULT/x['path']).exists() or hashlib.sha256((w.VAULT/x['path']).read_bytes()).hexdigest()!=x['sha256']]
pubs=[json.loads(p.read_text(encoding='utf8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':pub['note'],'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'PicGo upload and remote GET SHA256 verified by publish','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'];w.write_json(w.ROOT/'codex-paper-integrity-uab-20261010.json',result);print(json.dumps(result,ensure_ascii=False))
