import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'JQXLNRA3';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));pub=json.loads((d/'publication.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];note=Path(pub['note']);body=note.read_text(encoding='utf-8');w.validate_structure(draft)
expected=['Figure '+str(i) for i in range(1,13)]+['Table 1']
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'four_review_chapters':len(re.findall(r'^# ',body,re.M))==4,'no_unresolved_figure_markers':'<!--FIGURE:' not in body,'all_image_urls_embedded':all(x['url'] in body for x in pub['images']),'all_local_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'image_embed_count':len(re.findall(r'!\[[^\]]*\]\(https://',body))==13,'all_original_graphics':sorted(x['label'] for x in pub['images'])==sorted(expected),'source_review_pass':pub['source_review']['pass'],'deferred_directory':'文献笔记待归类' in str(note),'five_theme_sections':len(re.findall(r'^### \(',body,re.M))==5,'correct_metadata':pub['draft_metadata']['source_article_type']=='Narrative review','Crossref_identity':json.loads((d/'codex-crossref.json').read_text(encoding='utf8'))['message']['DOI']==rec['doi'],'structure_conflict':'R1=Ac、R2=H' in body and 'R2=B' in body,'citation_mismatch':'[46] 实际为 Panax ginseng' in body,'combined_treatment_boundary':'不能把图中的全部增益归因于 MeJA 单项' in body,'duration_conflict':'36 天' in body and '30 天' in body,'bacIII_conflict':'55.63 mg/L' in body and '56.03 mg/L' in body,'immobilized_conflict':'43.5 mg/L' in body and '43.43 mg/L' in body,'total_not_PT':'不能把 74 mg/L 写为紫杉醇' in body,'error_type':'均值 ± SD' in body,'no_vacuole_percentage':'不能把 80% 直接改为' in body,'no_extracellular_ratio':'没有独立标明胞外曲线' in body,'historical_boundary':'属于作者当时的背景' in body,'funding_not_invented':'未见独立 Funding' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf-8'));changed=[]
for item in baseline:
 p=w.VAULT/item['path']
 if not p.exists() or hashlib.sha256(p.read_bytes()).hexdigest()!=item['sha256']:changed.append(item['path'])
pubs=[json.loads(p.read_text(encoding='utf-8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf-8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':str(note),'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'publish uses PicGo and GET content SHA256 per image','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'],result
w.write_json(w.ROOT/'codex-paper-integrity-jqx-20261009.json',result);print(json.dumps(result,ensure_ascii=False))
