import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'KHP3QFIE';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));pub=json.loads((d/'publication.json').read_text(encoding='utf8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf8'))['draft'];body=Path(pub['note']).read_text(encoding='utf8');w.validate_structure(draft)
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'eight_research_chapters':len(re.findall(r'^# ',body,re.M))==8,'no_h2':not re.search(r'^## ',body,re.M),'no_markers':'<!--FIGURE:' not in body,'all_urls_embedded':all(x['url'] in body for x in pub['images']),'all_local_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'two_complete_original_figures':sorted(x['label'] for x in pub['images'])==['Figure 1','Figure 2'] and len(re.findall(r'!\[[^\]]*\]\(https://',body))==2,'cross_page_coverage':len(draft['figures'][0]['pages'])==2 and draft['figures'][0]['panels']==list('ABCDEFGHIJ'),'figure2_all_panels':draft['figures'][1]['panels']==list('ABCDEFGHI'),'source_review_pass':pub['source_review']['pass'],'classification_deferred':'文献笔记待归类' in pub['note'],'five_results_sections':len(re.findall(r'^### ',body,re.M))==5,'at_least_three_QA':len(re.findall(r'\*\*问题',body))>=3,'article_type_correct':pub['draft_metadata']['source_article_type']=='Quick Report','SI_boundary':'本地没有这些补充文件' in body,'relative_abundance_boundary':'relative abundance' in body,'source_conflict':'Figure 2C' in body,'mechanism_boundary':'机制假说' in body,'FPP_identity_boundary':'farnesol' in body,'human_review_not_claimed':'human_full_paper_review: false' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf8'));changed=[x['path'] for x in baseline if not(w.VAULT/x['path']).exists() or hashlib.sha256((w.VAULT/x['path']).read_bytes()).hexdigest()!=x['sha256']]
pubs=[json.loads(p.read_text(encoding='utf8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':pub['note'],'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'PicGo upload and remote GET SHA256 verified by publish','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'];w.write_json(w.ROOT/'codex-paper-integrity-khp-20261009.json',result);print(json.dumps(result,ensure_ascii=False))
