import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'LB4V6BA2';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));pub=json.loads((d/'publication.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];note=Path(pub['note']);body=note.read_text(encoding='utf-8');w.validate_structure(draft)
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'four_review_chapters':len(re.findall(r'^# ',body,re.M))==4,'no_unresolved_figure_markers':'<!--FIGURE:' not in body,'all_image_urls_embedded':all(x['url'] in body for x in pub['images']),'all_local_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'image_embed_count':len(re.findall(r'!\[[^\]]*\]\(https://',body))==5,'all_original_graphics':sorted(x['label'] for x in pub['images'])==['Figure 1','Figure 2','Figure 3','Figure 4','Table 1'],'source_review_pass':pub['source_review']['pass'],'deferred_directory':'文献笔记待归类' in str(note),'five_theme_sections':len(re.findall(r'^### \(',body,re.M))==5,'correct_metadata':pub['draft_metadata']['source_article_type']=='Review','time_boundary':'均限定于 2021 年' in body,'species_boundary':'Ginkgo biloba cells' in body and '不能将其描述为已经克隆并验证的 Taxus' in body,'total_oxytaxanes_boundary':'不能写为 33 mg/L 紫杉醇' in body,'surrogate_boundary':'2′-deoxytaxol，而非图中直接生成紫杉醇' in body,'substrate_preparation_boundary':'底物制备步骤 a、b 不能写成植物体内' in body,'crystal_boundary':'晶体结构不是 Taxus DBAT 的晶体结构' in body,'sixfold_not_cell_titer':'不能把六倍催化效率写为整细胞' in body,'different_metrics':'catalytic activity 不自动等于前文 catalytic efficiency' in body,'TAT_activity_not_flux': '不代表 TAT 在整个细胞中承担 13.2%' in body,'PCL_putative':'putative PCL' in body,'sequence_boundary':'1323 nt、440 aa' in body,'limits':'精确 P 值' in body and '未逐篇下载全部原始数据' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf-8'));changed=[]
for item in baseline:
 p=w.VAULT/item['path']
 if not p.exists() or hashlib.sha256(p.read_bytes()).hexdigest()!=item['sha256']:changed.append(item['path'])
pubs=[json.loads(p.read_text(encoding='utf-8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf-8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':str(note),'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'publish uses PicGo and GET content SHA256 per image','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'],result
w.write_json(w.ROOT/'codex-paper-integrity-lb4-20261009.json',result);print(json.dumps(result,ensure_ascii=False))
