import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'RTPSCVUP';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));pub=json.loads((d/'publication.json').read_text(encoding='utf8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf8'))['draft'];body=Path(pub['note']).read_text(encoding='utf8');w.validate_structure(draft)
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'eight_research_chapters':len(re.findall(r'^# ',body,re.M))==8,'no_h2':not re.search(r'^## ',body,re.M),'no_markers':'<!--FIGURE:' not in body,'all_urls_embedded':all(x['url'] in body for x in pub['images']),'all_local_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'six_complete_original_figures':sorted(x['label'] for x in pub['images'])==['Figure '+str(i) for i in range(1,7)] and len(re.findall(r'!\[[^\]]*\]\(https://',body))==6,'Fig2_all14panels_and_complete_caption':draft['figures'][1]['panels']==list('ABCDEFGHIJKLMN') and '(N) Taxadiene concentration' in pub['images'][1]['caption'],'source_review_pass':pub['source_review']['pass'],'classification_deferred':'文献笔记待归类' in pub['note'],'five_results_sections':len(re.findall(r'^### ',body,re.M))==5,'five_QA':len(re.findall(r'\*\*问题',body))==5,'SI_boundary':'本地未附补充文件' in body,'precursors_only':'没有完整紫杉醇或糖基化皂苷' in body,'different_units':'mg/kg FW' in body and 'mg/kg DW' in body,'scale_distinguished':'8.52 mg/kg FW' in body and '不能把最优 W61' in body,'directparent_and_baselines':'1.431' in body and '5.921' in body and '15.191' in body,'pool_not_flux':'静态 GGPP 浓度' in body,'source_wording_conflicts':'paclitaxel 特征离子' in body and 'Figure 2I' in body,'reference_mismatch':'WsMYC2/withanolides' in body,'stats_not_invented':'双尾非配对' in body and '精确 P 值' in body,'human_review_not_claimed':'human_full_paper_review: false' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf8'));changed=[x['path'] for x in baseline if not(w.VAULT/x['path']).exists() or hashlib.sha256((w.VAULT/x['path']).read_bytes()).hexdigest()!=x['sha256']]
pubs=[json.loads(p.read_text(encoding='utf8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':pub['note'],'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'PicGo upload and remote GET SHA256 verified by publish','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'];w.write_json(w.ROOT/'codex-paper-integrity-rtps-20261010.json',result);print(json.dumps(result,ensure_ascii=False))
