import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'KM8C68IW';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));pub=json.loads((d/'publication.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];note=Path(pub['note']);body=note.read_text(encoding='utf-8');w.validate_structure(draft)
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'four_review_chapters':len(re.findall(r'^# ',body,re.M))==4,'no_unresolved_figure_markers':'<!--FIGURE:' not in body,'all_image_urls_embedded':all(x['url'] in body for x in pub['images']),'all_local_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'actual_image_embed_count':len(re.findall(r'!\[[^\]]*\]\(https://',body))==9,'all_main_figures':sorted(x['label'] for x in pub['images'])==['Figure '+str(i) for i in range(1,8)]+['Table 1','Table 2'],'source_review_pass':pub['source_review']['pass'],'deferred_directory':'文献笔记待归类' in str(note),'six_theme_sections':len(re.findall(r'^### \(',body,re.M))==6,'no_wrong_scheme_markers':'Scheme 1' not in body,'correct_review_metadata':pub['draft_metadata']['source_article_type']=='Review','PAM_conflict':'ammonia-lyase' in body and 'aminomutase' in body,'gene_conflict':'erg20' in body and 'erg12' in body,'late_product_citation_conflict':'Table 2 归于 [28]' in body and '归于 [29]' in body,'total_oxygenated_boundary':'不能改写为 570 mg/L T5OH' in body,'feeding_boundary':'不能称从简单碳源完成全部从头合成' in body,'FW_DW_boundary':'不能互相转换' in body,'CRISPR_source_boundary':'flavonol' in body and '不能据此声称它已在 Taxus' in body,'prediction_not_activity':'没有获得总体催化活性提高' in body,'error_types_not_invented':'SD、SEM' in body,'online_date':'10 月 1 日在线发表' in body,'sampling_arithmetic':'0.076%' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf-8'));changed=[]
for item in baseline:
 p=w.VAULT/item['path']
 if not p.exists() or hashlib.sha256(p.read_bytes()).hexdigest()!=item['sha256']:changed.append(item['path'])
pubs=[json.loads(p.read_text(encoding='utf-8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf-8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':str(note),'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'publish uses PicGo and GET content SHA256 per image','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'],result
w.write_json(w.ROOT/'codex-paper-integrity-km8-20261009.json',result);print(json.dumps(result,ensure_ascii=False))
