import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'IZ54BKA3';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));pub=json.loads((d/'publication.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];note=Path(pub['note']);body=note.read_text(encoding='utf-8');w.validate_structure(draft)
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'four_review_chapters':len(re.findall(r'^# ',body,re.M))==4,'no_unresolved_figure_markers':'<!--FIGURE:' not in body,'all_image_urls_embedded':all(x['url'] in body for x in pub['images']),'all_local_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'image_embed_count':len(re.findall(r'!\[[^\]]*\]\(https://',body))==4,'all_original_graphics':sorted(x['label'] for x in pub['images'])==['Box 1','Figure 1','Table 1','Table 2'],'source_review_pass':pub['source_review']['pass'],'deferred_directory':'文献笔记待归类' in str(note),'five_theme_sections':len(re.findall(r'^### \(',body,re.M))==5,'correct_metadata':pub['draft_metadata']['source_article_type']=='Expert View','publication_dates':'在线发表年为 2024，正式卷期年为 2025' in body,'feeding_quantities':'64.29 ng/g FW' in body and '29.39 ng/g FW' in body,'massbasis_boundary':'不能自行补写' in body,'ERF_conflict':'TcERF12' in body and 'TcERF15' in body and '方向相反' in body,'bHLH_conflict':'bHLH46' in body and 'TmbHLH14' in body,'hypothetical_boundary':'hypothetical intermediate' in body and '灰色' in body,'fold_boundary':'不能把 3.5 和 25 相乘' in body,'editing_direction_boundary':'潜在应用' in body and '不等于已经在老 Taxus' in body,'preprint_boundary':'bioRxiv 预印本' in body,'PAM_PAL_distinct':'Phenylalanine aminomutase' in body and 'phenylalanine ammonia-lyase' in body,'diagram_conflict':'一个带 CoA 的结构标作游离物' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf-8'));changed=[]
for item in baseline:
 p=w.VAULT/item['path']
 if not p.exists() or hashlib.sha256(p.read_bytes()).hexdigest()!=item['sha256']:changed.append(item['path'])
pubs=[json.loads(p.read_text(encoding='utf-8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf-8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':str(note),'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'publish uses PicGo and GET content SHA256 per image','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'],result
w.write_json(w.ROOT/'codex-paper-integrity-iz54-20261009.json',result);print(json.dumps(result,ensure_ascii=False))
