import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'7RETNCWI';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));pub=json.loads((d/'publication.json').read_text(encoding='utf8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf8'))['draft'];body=Path(pub['note']).read_text(encoding='utf8');w.validate_structure(draft)
expected=['Figure 1','Figure 2','Figure 3','Table I','Figure 4'];checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'eight_chapters':len(re.findall(r'^# ',body,re.M))==8,'no_h2':not re.search(r'^## ',body,re.M),'no_markers':'<!--FIGURE:' not in body,'all_urls_embedded':all(x['url'] in body for x in pub['images']),'all_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'all_five_graphics':sorted(x['label'] for x in pub['images'])==sorted(expected) and len(re.findall(r'!\[[^\]]*\]\(https://',body))==5,'TableI_manually_added':len(rec['figure_candidates'])==4 and len(draft['figures'])==5,'source_review_pass':pub['source_review']['pass'],'classification_deferred':'文献笔记待归类' in pub['note'],'four_results_sections':len(re.findall(r'^### ',body,re.M))==4,'five_QA':len(re.findall(r'\*\*问题',body))==5,'predicted_location_boundary':'直接测出的成熟蛋白切割位点' in body,'maximum_not_mean':'最高值当统一均值' in body and '0.6 mg/kg DW' in body,'FW_DW_boundary':'不能直接除出' in body,'mechanism_not_proved':'毒性' in body and '前体池' in body,'statistics_unreported':'未定义 SD 或 SEM' in body,'human_review_not_claimed':'human_full_paper_review: false' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf8'));changed=[x['path'] for x in baseline if not(w.VAULT/x['path']).exists() or hashlib.sha256((w.VAULT/x['path']).read_bytes()).hexdigest()!=x['sha256']]
pubs=[json.loads(p.read_text(encoding='utf8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':pub['note'],'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'PicGo upload and remote GET SHA256 verified by publish','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'];w.write_json(w.ROOT/'codex-paper-integrity-7ret-20261010.json',result);print(json.dumps(result,ensure_ascii=False))
