import json,hashlib,re,datetime
from pathlib import Path
import worker as w
d=w.ROOT/'sources'/'9IDKAPJ8';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));pub=json.loads((d/'publication.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];note=Path(pub['note']);body=note.read_text(encoding='utf-8');w.validate_structure(draft)
checks={'source_pdf_unchanged':hashlib.sha256(Path(rec['main_pdf']).read_bytes()).hexdigest()==rec['main_pdf_sha256'],'eight_research_chapters':len(re.findall(r'^# ',body,re.M))==8,'no_unresolved_figure_markers':'<!--FIGURE:' not in body,'all_image_urls_embedded':all(x['url'] in body for x in pub['images']),'all_local_crops_intact':all(hashlib.sha256(Path(x['file']).read_bytes()).hexdigest()==x['sha256'] for x in pub['images']),'actual_image_embed_count':len(re.findall(r'!\[[^\]]*\]\(https://',body))==5,'all_main_figures':sorted(x['label'] for x in pub['images'])==['Figure '+str(i) for i in range(1,5)]+['Table 1'],'source_review_pass':pub['source_review']['pass'],'deferred_directory':'文献笔记待归类' in str(note),'Km_microM':'Km（μM）' in body,'inactive_bounds':'<0.00001 s⁻¹' in body and '0.0001 s⁻¹' in body,'concentration_conflict':'50 μM' in body and '100 μM' in body,'marked_sum_preserved':'合计 99.0%' in body,'tentative_minor':'仍为暂定' in body,'I50_not_Ki':'不能把 I50 当 Ki' in body,'bound_intermediate_caveat':'不能与溶液交换' in body,'pseudomature_not_native':'不是已确定的天然序列' in body,'yield_not_titer':'并不等于培养产生多少 taxadiene' in body,'crosscolumn_caption':'右栏续注' in body,'derived_efficiency':'642 M⁻¹s⁻¹' in body and '3533 M⁻¹s⁻¹' in body}
assert all(checks.values()),checks
baseline=json.loads((w.ROOT/'existing-note-hashes.json').read_text(encoding='utf-8'));changed=[]
for item in baseline:
 p=w.VAULT/item['path']
 if not p.exists() or hashlib.sha256(p.read_bytes()).hexdigest()!=item['sha256']:changed.append(item['path'])
pubs=[json.loads(p.read_text(encoding='utf-8')) for p in (w.ROOT/'sources').glob('*/publication.json')];inv=json.loads((w.ROOT/'prepared-inventory.json').read_text(encoding='utf-8'))
result={'time':datetime.datetime.now().isoformat(),'new_notes':[{'key':rec['key'],'note':str(note),'images':len(pub['images']),'checks':checks}],'existing_baseline_files':len(baseline),'existing_baseline_unchanged':len(baseline)-len(changed),'existing_baseline_changed':changed,'remote_verification':'publish uses PicGo and GET content SHA256 per image','excluded_heptose_paper_has_no_publication':not(w.ROOT/'sources'/'2E5UEWNP'/'publication.json').exists(),'published_notes_total':len(pubs),'images_total':sum(len(x['images']) for x in pubs),'remaining_ready':sum(x.get('status')=='ready' and not(w.ROOT/'sources'/x['key']/'publication.json').exists() for x in inv['records'])}
assert not changed and result['excluded_heptose_paper_has_no_publication'],result
w.write_json(w.ROOT/'codex-paper-integrity-9id-20261009.json',result);print(json.dumps(result,ensure_ascii=False))
