from pathlib import Path
root=Path(__file__).parent
s=(root/'publish-9id-codex.py').read_text(encoding='utf-8').replace('9IDKAPJ8','W9Z8EZLL')
a=s.index("w.write_json(d/'codex-arithmetic.json'");b=s.index('labels=',a)
s=s[:a]+'''w.write_json(d/'codex-arithmetic.json',{'verticillene_specific_activity_dpm_microg':6,'taxadiene_specific_activity_dpm_microg':210,'specific_activity_ratio_percent':6/210*100,'ratio_is_total_flux_fraction':False,'D2O_product_single_D_percent':8,'D2O_error':2,'C10_product_single_D_percent':85,'C10_error':5,'error_type_verified':False,'D2O_rate_reduction_approx_percent':60,'intrinsic_KIE_calculated':False,'C20_three_D_retained':3,'C1_C20_five_D_retained':5,'C4_two_D_product_retained':1})
claims=[('Identity','Main1/10/liveZotero200','Title fiveauthors35(9)2968-2977 BI9526239 matched DOI bibliographicrecord; completeDOI notprinted; dateJan1notverified'),('Coverage','Main1-10','Allmainpages textread originalpagesviewed ninecompleteSchemes andTable1 finalcropsviewed withconditionlinesandfootnotes'),('Enzyme','MainMethods','NaturalTaxusbrevifolia partiallypurified preparation notrecombinantM60notuniformenzyme nohomogeneouskcat'),('Labels','MainMethods/Schemes2-6/Table1','C20threeC1C20five>95atomD C2single84 C4double91 C10single>95 exogenousracemicverticillene94; organic synthesesnotplantpath'),('Mass','Main6/7Scheme7Table1','Reference272257122 five277262127 three275260125 C4andC2 273258123; C-ringfragment supportedwithmultiplelabels'),('Statistics','Main7Table1','8plusminus2D2O and85plusminus5C10 backgroundcorrected noerror typenorindependentn verified blanknotzero'),('Ringformation','Main7/8Scheme8','C20andC1retention arguesagainstparticular4(20)isomerizationandcasbenemodel C4GGPPtoC5product lossof1D notlaterstereospecific4Rstudy'),('Conversions','Main7/8','3.6and4.0percent compared4.2parallelcontrol C4 4.1 compared4.3 differentparallelcontrols nointrinsicKIEcomputed'),('Externalolefins','Main6/8','9to14percentnonspecificinhibition15microM includesunrelatedcontrol direct5microMnone<.1percent<5pmolh cannotexcludeinternalnonexchangeableintermediate'),('Trapping','Main8','85percentrecovery6vs210dpmpermicrogram is2.86specificactivityratio nottotalfluxfraction'),('Hydrogen','Main8/9','D2O~60percentratedecrease8plusminus2D C10singleD85plusminus5 andC-ring122to123 directringlocalization C7 mostlikely notsiteNMR'),('Unknown','Main8','Unknownolefin~10percenttaxadienepeaklevel RtconsistentverticillenepartialSIMinsufficientidentification notconfirmednorcompleteproductfraction'),('Mechanism','Main9Scheme9','1996EnzBmediatedsamehydrogenreleaseandreturn tightlybound1Sverticillene hypotheticalbaseidentityuncapturedintermediates notlatermechanismoverwritten'),('Limits','Main1/10','Fundingretained noindependentCOIverified rawSIMmissing allreferencefulltextsnotread humanreviewfalse classificationdeferred')]
''' +s[b:]
s=s.replace('Current Codex readviewedall10mainPDFpages fivecompleteoriginalfiguretablecrops reviewed includingcrosscolumncaption; originalmicroMunits parameterconflicts andtentativeproducts preserved; independentarithmeticderivednotclaimednewmeasurement','Current Codex read and viewed all ten original pages and ten complete Scheme/table crops including chemical condition lines and table footnote; mass fragment inference, unidentified olefin and historical mechanism boundaries retained')
(root/'publish-w9-codex.py').write_text(s,encoding='utf-8')
s=(root/'audit-9id-codex.py').read_text(encoding='utf-8').replace('9IDKAPJ8','W9Z8EZLL').replace('integrity-9id-','integrity-w9-')
s=s.replace('))==5', '))==10').replace("['Figure '+str(i) for i in range(1,5)]+['Table 1']", "['Scheme '+str(i) for i in range(1,10)]+['Table 1']")
a=s.index(",'Km_microM'");b=s.index('\nassert all(checks.values())',a)
s=s[:a]+",'natural_partial_enzyme':'部分纯化' in body,'ring_vs_site':'most likely to C7' in body and 'C 环片段从 122 移至 123' in body,'error_type_unknown':'SD、SEM 或 95% CI' in body,'unknown_peak':'部分谱不足以鉴定' in body,'date_boundary':'准确发行日期' in body,'historical_model':'Enz:B' in body and '1996 年立体机制模型' in body,'ratio_not_flux':'截获了 2.86% 中间体' in body,'external_limit':'<0.1%' in body and '<0.05%' in body}"+s[b:]
(root/'audit-w9-codex.py').write_text(s,encoding='utf-8')
print('publication and audit scripts prepared')
