import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'58LFQAZJ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[35,500,563,748],['a','b','c','d']),('Table 1',3,[35,51,293,142],[]),('Figure 2',3,[35,580,563,748],['a','b','c','d']),('Table 2',5,[303,51,563,148],[]),('Figure 3',5,[35,175,563,737],['a','b','c','d','e']),('Figure 4',6,[35,538,563,748],['a','b']),('Table 3',7,[35,51,563,280],[]),('Figure 5',7,[35,440,563,748],[]),('Table 4',8,[303,51,563,162],[]),('Figure 6',8,[35,541,563,748],['a','b']),('Figure 7',9,[35,52,563,254],['a','b'])]
gaps=['All11mainpages read and viewed; sevenFiguresfourTablesall11completecrops; SIunavailableunread rawdataonrequestnotobtained','Title4authorsArticleJChromA17212024464815DOI10.1016/j.chroma.2024.464815 availableMarch19matched actualpublisherformattedfiledespiteattachmentsubmittedlabel','LRS5existingstrainCENPK21C no newgeneticengineering comparison endpointrecoverynotprovensynthesisfluxnotfullTaxol','ModelmoleculesSudan1paclitaxelnottaxadiene50%ethanolwatersolvent notculturemedium parametersnotdirecttransfer','Table1 BEMA40nameporogen40%notBEMA40%;CP140CP240differentmixture;photoinitiatorphotoabsorberw/v nottablemonomersv/v','Gyroidmacroporosity50%notnanoporeSEMdiameter;BETdriedgroundnotintactwetaccessiblearea unitsm2mLnotm2g','26hBEMA30BEMA40notstrictlyequilibrated linearisothermconditionlimited notsaturationcapacity','DpDf1.3491.150fittedsimplifiedmodelnotactualsuperfreediffusion;electrostaticovercuringhypothesesunvalidated noXraytomographythisstudy','Mainfig4fig6fig7n3SD sourceindependencelevelnotexplicit noinventbioln;ANOVAbiop.72taxadienep.001Tukey.01 no newPprecision','Taxadiene46plusminus2 54plusminus4 31plusminus2mgLnot55bodyconclusionconflictpreserved;noequivalence/noninferiorityfromnonsignificance','Nootherphase detectednotabsolute100%recovery noLODLOQspikerecoverytotalbalance;biosynthesisvslossvsextractionnotseparated','3%v/vculturechosenfromprior3%w/vstudy unitsnotsame doseoptimalityunverified load1.0/1.2unitmissingnotconverted','Table4paclitaxel32.3/11.9=2.714vsbody2.4ratio no changedtables;Kdlinearconditionalnotthermodynamic','NoindustrialLCAregenerationleachinglongtermsterilizationlargeportcloggingtest;firstpriorityauthorclaimnotindependentlyverified']
figs=[]
for l,p,b,a in spec:
 rect=doc[p-1].rect;figs.append({'label':l,'caption':'原文 '+l+'：完整图表及图注','panels':a,'pages':[{'page':p,'bbox':[b[0]/rect.width,b[1]/rect.height,b[2]/rect.width,b[3]/rect.height],'dpi':300}]})
draft={'identity_matches':True,'identity_reason':'All11pages titleauthorsJChromA1721464815DOI sourceverified','paper_type':'research','title_zh':'三维打印吸附材料用于酵母紫杉二烯原位回收的证据','filename_title':'三维打印吸附材料用于酵母紫杉二烯原位回收的证据','journal_short':'J Chromatogr A','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexdirect11mainpages SIunread'})
images=[]
for l,p,b,a in spec:
 out=d/('58LFQAZJ-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':'原文 '+l+'：完整图表及图注','page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'BEMA40_control_gain_percent':(46/31-1)*100,'HP20_control_gain_percent':(54/31-1)*100,'BEMA40_HP20_percent':46/54*100,'Sudan_HP20_BEMA40K':1338.4/416.5,'Paclitaxel_HP20_BEMA40K':309.4/32.3,'Paclitaxel_BEMA40_BEMA30K':32.3/11.9,'Paclitaxel_BEMA40_BEMAP2K':32.3/13.4,'Paclitaxel_BEMA40_BEMA60K':32.3/18.2,'note':'Actuallycomputed reportedmeanratios notrawreplicatestatistics'})
print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'rect':list(doc[0].rect),'images':[x['file'] for x in images]},ensure_ascii=False))
