import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'A4UKNEHC';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',1,[49,578,550,793],[]),('Scheme 1',2,[49,54,546,251],[]),('Figure 2',2,[305,264,546,437],[]),('Figure 3',2,[305,505,546,608],[]),('Figure 4',2,[305,621,546,790],[]),('Scheme 2',3,[49,55,546,345],[]),('Table 1',3,[49,356,293,654],[]),('Table 2',4,[48,54,546,294],[]),('Figure 5',4,[49,309,293,560],[]),('Scheme 3',5,[49,54,293,557],[]),('Scheme 4',5,[49,588,546,791],[]),('Figure 6',6,[49,53,293,623],['A','B','a','b','c','d','e']),('Figure 7',6,[305,54,546,227],['A','B']),('Table 3',6,[305,701,546,790],[]),('Scheme 5',7,[49,52,546,598],[]),('Scheme 6',8,[49,54,546,229],[])]
gaps=['All ten main physical pages read and viewed; seven Figures three Tables six Schemes sixteen crops; no separate GA; ESI additional spectra/conformer structures unread','Putative PMTS not cloned purified or mutated in this paper; source organism extracts not single enzyme product profile','Table1 title data of1 whereas body9a; C15 body37.69 table37.87 retained','Table2 entry3 9a25percent conflicts discussion9a never obtained BF3; no silent correction','La Table240C versus preparative28C; TiCl4 table-95C versus preparative-90C','GC area percentages not isolated or NMR yields; table9c35 versus preparative14;14table10 versus preparative2.9','Figure5 C3/C7 stereochemistry14 not determined; HRMS13b found272.2455 versus calc272.2504 values printed; rawSIunread','Taxadiene223ng0.004percentGCMS estimate from one tested condition no LODLOQreplicate/error report; not highyield or denovo enzyme route','Figure7 coeluting GC13a13b and HPLC9a9b 6plus13b; identities from combined standards fractionation not every single trace peak','Natural minor metabolites6/9b/13a/13b interpreted PMTS byproducts not direct enzyme assignment','Absolute config CDchemical comparison with disputed historicverticillol assignment not newly measured anomalous crystal','Table3 stable state HF631Gd energies referenceG not barriers; AtoD2.40 and AtoF-3.11 arithmetic;0.06 not activationenergy','No full enzyme or solvation model; conformer search constrained existing stereo; stable frequencies not transition states','Discussion active-site aromatic/volume/mutation hypotheses analogies not verified PMTS sequence residues mutation products','Feeding1.0/1.6mg isolated amounts no replicated flux analysis; four flasks experimental not automatically n4independent replicates']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':'原文 '+l+'：完整数据、结构与图注；表格保留全部行和脚注','panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a in spec]
draft={'identity_matches':True,'identity_reason':'Direct read all ten main pages DOI10.1039/b506411b six authors OBC3 2713-2722','paper_type':'research','title_zh':'共同碳正离子框架下phomactatriene与taxadiene分流机制的证据','filename_title':'共同碳正离子框架下phomactatriene与taxadiene分流机制的证据','journal_short':'Org Biomol Chem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'DirectCodexallmainpagesreadoriginalpageQA'})
images=[]
for l,p,b,a in spec:
 out=d/('A4UKNEHC-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':'原文 '+l+'：完整数据、结构与图注；表格保留全部行和脚注','page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
