import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'73ZWPHQB';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[45,85,550,440]),('Figure 2',4,[45,82,550,632]),('Chart 1',5,[60,82,550,372]),('Figure 3',6,[45,82,550,658]),('Figure 4',8,[45,82,550,660]),('Figure 5',9,[60,82,550,350]),('Figure 6',10,[45,82,550,590]),('Figure 7',11,[45,82,550,514]),('Figure 8',12,[45,82,550,550])]
gaps=['16mainpagesreadandoriginalsviewed; SI S1toS5TableS1S2actualfilesunread; Movie1onlypaperstaticposterreadnotvideo; Chart1internalindexexplicitnotauthornumber','OriginalFigure1to8includingFigure3internaltable andMovie1poster complete300dpi; databasesLC773268to270LC773267LC773708MK585542PRJDB15908notdownloaded','Abstract0.1mgLvsbodyFigure7 100uMsubstrate unresolved; Figure7acaptionTmNRT2.1vsTmNPF2.1 sourceerror','MSsignalnotabsoluteconcentration; belowdetectionnot100percentmolaryield noLODmassbalance; newproductspossibleMSstructuresnotfullNMRproof','NPF28foldGOenrichmentnotexpressiontransportfold; coexpressionnotcausality; nativesubcellularlocalizationessentialityunproved; pH5.3notdirectprotonflux','MGY2150sensitivityandW303bioconversiondifferentstrains; Figure6ODceiling8.88notexactbiomass; noinventednPstats','Figure7bfivebiologycd4biologySD; noexactPnorCIs; substrate12.5to200uM5days authorcurves','BAHDallelepossibilitynotfullyphased; singleexonHGTspeculation; sixproductscommon527fragmentnotintaction; hostdonorpoolconfounds pureenzyme specificity','Methods43daymetabolomicsNMR47differentendpoints;100uMMeJAregularvs1uMNMRseparate; referencesmetadataonly notindependentlyread']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'16pages title8authorsTPJ122e70146DOI verified','paper_type':'research','title_zh':'Taxus NPF转运蛋白介导紫杉烷底物利用及酵母生物转化的功能证据','filename_title':'Taxus NPF转运蛋白介导紫杉烷底物利用及酵母生物转化的功能证据','journal_short':'Plant J','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded16pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('73ZWPHQB-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
