import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'MFLGZ2V3';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',2,[303,50,562,350],[],'原文 Fig. 1：完整三模块、全部结构、虚线未来箭头和图注'),('Figure 2',3,[34,51,562,326],['A','B','C'],'原文 Fig. 2：完整 A–C 级联、全部缓冲色谱和迭代优化图注'),('Figure 3',4,[34,51,563,501],['A','B','C','D','E','F'],'原文 Fig. 3：完整 A–F、散点与所有长图注，补加次数及 SD 标示'),('Figure 4',5,[34,51,563,377],['A','B','C','D'],'原文 Fig. 4：完整 A–D 化学生物转换、色谱、全部酵母构型、图注')]
gaps=['Englishoriginalstudy ChinaaffiliationsnotChineseexclusion;allsevenmainpages/allfourfiguresread','SIallmethodsrawspectraenzymegelscontrolsrepeatsnotread;referenceoriginalsnotfullread','946.7mgLtaxadiene/48percentchemicalyield/15.8mgLoxygenatedacetate separatemodulesnotpaclitaxel/wholepathyield','MVAstart2.5mMplussevenhourly2.5mM=20mMconstantvolassumptionversustext17.5;effectivefeedingvolumeunreported','StoichiometryC20H32MW272.47fourMVAperproduct:946.7with17.5=>79.42percent with20=>69.49percent;reported79.6notindependentlydosingvalidated','Figure3E8hroughread470mgLversustext547.4;Fig3F8.0~547 final8.5~946.7 rawpointsnotavailable','Method4.2meansstandarderrorsvsFig3/4n3biologicallyindependentmeanSD;invitroindependentprepdefinitionunclear exactP/testmultiplicityunreported','Figure3CstarsnottranslateintoinventedexactP','IDIrelativeactivitynormalizedsystemoutputnotintrinsicenzymeKm/kcat;singlestepoptimizationnotfactorials','PPKstageddecreasevsincreasecontextchanges notuniversalsign;ATPfluxGGPPinhibitionandcontaminatingphosphatase inferrednotfullyquantified','Reference19usedforPPK2CpaN actuallyperovskiteLED;32/33usedT10beta prior actuallyDBAT/5alpha titlesmismatch','Figure2initialpH8differentlaterpH8.5 contextnotcontradiction','48percent abstractconversionversusresultsyield retained;chemicalNMRGCMSauthorSIreportnotowncompleteassignment','Taxadieneextractedpurifiedtransferred beforechemicalstep andyeast step;onepotonlyinitialmodule','T10beta1vs2datanotshown;newyeastproductGCMSm/z346 authorassignmentSIunreadnoNMRnewclaim','TAX06increasesP450andCPRconfigtogether nominalcopynotactualprotein;66.7baselineunclear;3.98constitutiveversusinducedcontextonly','2000foldcrosspaperfromxylosevsfedintermediate mismatch notuniversalhostranking;14.2productivitynotcostscaleproof','Palladiumreusepotentialnotactualrecycling/residual/costevidence;plantpathwayfullclaimvsunknownstepsnotupgrade']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'All7mainpages title12authors journal92024694–700DOIverified onlineMay13','paper_type':'research','title_zh':'MVA紫杉烷混合催化与转化率分母的证据边界','filename_title':'MVA紫杉烷混合催化与转化率分母的证据边界','journal_short':'Synth Syst Biotechnol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex direct originalsource reading and explicitlyassumed stoichiometry check'})
images=[]
for l,p,b,a,c in spec:
    out=d/('MFLGZ2V3-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':images},ensure_ascii=False))
