import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'G9BV86WS';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[51,49,564,418]),('Figure 2',4,[51,49,564,184]),('Figure 3',4,[51,380,302,734]),('Figure 4',4,[314,380,564,734]),('Figure 5',5,[51,49,564,665])]
gaps=['Research6pages2authorsPNAS9725:1359113596Dec52000 ContributedOct16notpublicationtitleauthorsDOIprintedvisualverified automatedfalseobsolete','AF297618paper only liveversion notdownloaded5figsoriginalsallread','Semi synthetic2debenzoyl713diacetylbaccatinIII surrogate product713diacetylbaccatinIII notTaxol naturalintermediate sequenceunproven','Figure2chemicalastep18hcaption16hMethods internaldifference91percent42percentchemicalyields99puritynotenzymeconversion','Sevenfullcandidates library60000notn hostXL1BlueMRF libraryJM109function pKW18TAX2 pCWoriplus extracts nowholecellcarbonproduction','Negativewithoutacceptorordono boiled emptyvector no detectedproduct limitunspecified','RadioHPLC21.9plusminus0.1UVradiocoincidence versusLCMS43.6plusminus0.1differentmethods full Figure3and4bothtraces no sameconditionconflict nstaterrornotdefined','1HNMRenzymeproductmatchauthorreported no independentenzymeproductNMRspectrum attached chemicalsubstratestandardshiftsnotactualnewproductrawdata','Partialpurifiedenzyme pH8half6.5and9.9 differentbuffersconfound Km0.64taxoid0.30benzoylCoA mMactualnotmicro R2.99LineweaverBurk no kcatnCIP no fullratepoints','acetylCoAVrel1.5percent saturation notzero notbindingaffinityno substitutedaroylCoAtestfutureanalogexpectation','10DABC2alreadybenzoylated negativeotherpositions notcompetitivefreeC2regioexperiment early2a5adiolinactive insufficienttomapallrequiredmodifications','ORF1320aa440MW50089 H158D162G163motifprednotmutationconfirmed fiveofsixsequences motif nocelllocalizationsequenceNTermnoneonly','DATinitial10acetylabbreviationDBATelsewhere versusDATCatharanthusFig5 fullnamespeciesretain fundingcompany noexplicitCOI humanreviewfalse deferclassification']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'6pages2authorsPNAS97:1359113596titleauthorsjournalpagesDOIprintedvisualverifiedliveZotero','paper_type':'research','source_article_type':'Research article','title_zh':'紫杉烷TBT克隆的产物鉴定与替代底物边界','filename_title':'紫杉烷TBT克隆的产物鉴定与替代底物边界','journal_short':'PNAS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded6pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('G9BV86WS-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
