import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'7RETNCWI';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',2,[311,22,555,592],list('AB')),('Figure 2',4,[311,22,555,391],list('AB')),('Figure 3',5,[40,398,284,711],list('AB')),('Table I',5,[297,533,541,711],[]),('Figure 4',6,[311,22,555,398],list('ABC'))]
for label,page,bbox,panels in specs:
 pg=doc[page-1];file=d/('7RETNCWI-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file));caption=next((x['caption'] for x in rec['figure_candidates'] if x['label']==label),'Table I. Characterization of transgenic plants constitutively overexpressing TXS. DW, dry weight; FW, fresh weight.')
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'Printedtitle sixauthors DOI BiotechBioeng88(2)168-175 matchliveZotero; PDFonline15Sept2004 vsZoterodate25Sept discrepancy preserved.','paper_type':'research','title_zh':'拟南芥紫杉二烯合成与诱导表达时序','filename_title':'拟南芥紫杉二烯合成与诱导表达时序','journal_short':'Biotechnol Bioeng','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['TableI误差定义/n/精确P/CI未报告；诱导up to600为最高值不是带误差均值','分级定位、开花/生长照片、连续DEX幼苗代谢为data not shown','GGPP池/通量和激素未直接测，毒性与前体调控机制未排他验证','质体切割位点为预测/推断，序列版本未下载；GCMS不等于完整NMR鉴定','成熟阶段/株系/表达量效应未充分独立拆分，全紫杉醇与规模产能未验证'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'up_to600_nggDW_as_mgkgDW':600/1000,'up_to600_to_approx20_ratio':600/20,'up_to600_to_C2_leafmean':600/24.64,'up_to600_to_C3_leafmean':600/17.52,'600_is_maximum_not_mean':True,'FW_DW_conversion_performed':False,'TableI_error_type_unreported':True,'TableI_n_unreported':True,'exact_P_unreported':True});print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
