import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'V6BKYU8Q';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',1,[316,443,560,674],[]),('Unnumbered Structure Graphic 1',2,[316,244,559,450],[]),('Scheme 1',3,[53,44,294,299],[]),('Figure 2',3,[316,44,559,187],[]),('Table 1',4,[53,43,559,421],[]),('Figure 3',4,[316,599,559,745],['a','b','c','d','e']),('Unnumbered Structure Graphic 2',4,[53,562,294,717],[]),('Table 2',5,[53,43,294,183],[]),('Figure 4',5,[316,43,559,475],[]),('Figure 5',6,[53,43,294,237],[]),('Figure 6',6,[316,43,559,240],[]),('Scheme 2',6,[316,243,559,466],[]),('Scheme 3',7,[53,44,294,274],[])]
captions={'Unnumbered Structure Graphic 1':'原文反应式 1：完整天然 GGPP 环化机制模型及结构编号','Unnumbered Structure Graphic 2':'原文反应式 2：完整含氟底物与三种主要产物、比例及未鉴定组分标注'}
gaps=['All9physicalpages7834–7842directreadandviewed6figures2tables3schemes2reactiongraphics;autoFigure6Schemesreactiongraphicsmissingrecovered','SIcompleteNMR/CIF/generalexperimentalnotreadnotindependentlyreanalyzed','AnalogstableproductsNOTdirectenzymeboundcarbocationobservation;electronvsconformationalternative retained','Threeidentifiedmajor b24=26 c23=25 d22=37;twoa/e7/5unidentified total12 notallfivefullyidentified','Total468ugabout11GCcalibratedentkaurene internalstandardnotallisolatedyieldorenzymekinetics','NoindependentrepeatsnerrorsPspecifiednotinvented;noKMkcatKi ormatchednaturalreactionkinetics','NMR22morecomplete23enrichedmixture24about90puritynotallpureproducts','23vinylH5.79Resultsversus5.59Experimentalunresolved;Table2reference20not22replicate','NOE19.7Figure4rounded20body;Figure4H11beta/H13alphavsbodyH11alpha/H13alphaunresolved;overlapnotindependentexactcontributions;Table2H18Z4.71vsTable1reference204.70;Scheme2substratelabel7fluoroGGPP17vsdefined6fluoroGGPPunresolved','Crystal(+)-verticillolpiodobenzoate1S11S absparam-.016(.016) notenzymeor22crystal','22H1betaabsoluteinitiallyassumedfromTSproduct plusNOECDreferencecorrelation1S11R;different11RSnotautomaticenantiomerconflict','Historicalallverticillane reversalclaimlinkedoldreference notallindependentlymeasuredorcurrentliteratureautomaticcorrection','Directintramolecularprotontransfernotexcludesenzymeinterioracceptorrelay authorsexplicitDiscussion','SubstratefinalorganicdiphosphatePPi14to1 notcompletelypure;1fluorounnaturalditerpenesnotTaxolproduction','Scheme2alternative11to3protontransferhypothesis24notdirectpathobservation;Schemes2/3modelsnotmeasuredenergybarrier']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':captions.get(l,'原文 '+l+'：完整图表、结构、数据标注及原图注'),'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a in spec]
draft={'identity_matches':True,'identity_reason':'Directread9physicalpages4authorsCoatescorr1277834–7842DOI2005May6','paper_type':'research','title_zh':'含氟底物截获紫杉二烯环化与绝对构型修订的证据边界','filename_title':'含氟底物截获紫杉二烯环化与绝对构型修订的证据边界','journal_short':'JACS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'DirectCodex9physicalmainpagesfullreadoriginalpageQA'})
images=[]
for l,p,b,a in spec:
 out=d/('V6BKYU8Q-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':captions.get(l,'原文 '+l+'：完整图表、结构、数据标注及原图注'),'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
