import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'W8HZP738';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[41,583,284,670]),('Scheme 1',2,[49,426,554,758])]
gaps=['Four complete main pages text and original pages read/viewed; Figure1 and complete Scheme1 allstructures allarrows conditions andcaption; no main tables no separate SI or raw spectra fulloperationrecord','Automated titlematchfalse overridden by actual printed complete title DOI authors46:2377-2380 correspondingHeinzFalk fiveauthorsJKULinz liveZotero200','ReceivedDec282004 revisedFeb7acceptedFeb142005 ZoteroApr4 no printedonline date; allrightsreserved FWF P16969 P15380 no explicit competinginterests statement','Authors arbitraryanthraquinone numberingNote1; naturalendocrocin-emodin relationship citationsnot currentbiosynthetic assays','Protection guidesC2 Marschalk target63percent isolatedyieldnotregioisomerratio no crudequant rawcompletebyproduct data; quinonemethide explanatory notdetected','Scheme b minus5to25 verifiedoriginal negative signs recovered from extractedtext; old minus70 background no matchedyieldtable','Poor directoxidation7 notquantified freephenolcause authors hypothesis; reprotected8 then aldehyde4 acid9 distinct endpoints notsameoxidationcomparison','Calculatedshownintegerstep product4 44.95845percent author45; endocrocin2 31.43991 vs32; cinnalutein3 34.26144vs35 precision unresolved notsilentlycorrected;10 29.02145 calculatedonly','EndocrocinNote18 C9 C10a COOHnotobserved insolubility; OHlabel3-OH conflicts1,6,8; compound10 duplicateC10aC3 labels not silently fixed','IR UVvis MS NMR selectedvalues plusauthorsHSQC HMBC NOESY reports no actual2Dplots independentlyverified; posnegadduct retained','Aldehyde4 potentialhypericinsynthon no newhypericindimer redshift or photodynamic bioassays; UV4max405notfinalredshiftproof','No independent replicates massscale detailed workup dosage materialbalance costs or industrialvalidation; classificationdeferred humanfalse refs18 includesextendedspectralnote not18independentstudies']
figs=[{'label':l,'caption':'原文 '+l+'：完整结构、图示及图注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Direct inspection printed complete title DOI fiveauthors and46:2377-2380 confirms source despite automatic titlefalse','paper_type':'research','source_article_type':'Research Letter','title_zh':'保护基控制的emodin区域修饰与endocrocin合成','filename_title':'保护基控制的emodin区域修饰与endocrocin合成','journal_short':'Tetrahedron Lett','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex four full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
