import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'W4IHDLC6';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf']);b=[55,68,538,315];rect=doc[2].rect
gaps=['All3physicalpagesread andviewed;page1publishercitation/recommendationsnotauthorreferences;actualmain2pages Commentary notoriginalresearch/systematicreview','JiangScience2024383(6683)622629 referredprimarynotindependentlyreread inthisinterpretation noSI','58CYP450and17CYP725A candidatecounts notreplicaten unknownscreenfullpanelLODstats','TOT1Taxusknockdownlevelsdecreased secondhand noeffectsizeexactP nrescueofftargetprovided','MDDFT ringmechanism computedproposed notdirectalltransientintermediates measurement crystallography barriers noinvented residuesCYPmembernumber','Ninecoregenes TOT1T9alphaH1 TXS T5alphaH T13alphaH T2alphaH T7betaH TAT TBT tobacco baccatinIII notwholepaclitaxel oryeastproduction','Figure1GGPPSupstream/BAPT/T2primealphaH/DBTNBTdownstream notallnine genes fulfilled;plantyeastgraphics futuredesign','50ngg-1 secondhand noFW/DWbasis harvesttimerecovery replicateserrors reported;notconvertedmgL productivity','Sourceexclusivelybarkabsolute and.01to.05%background authorframing notconfirmedsolecommercialsource/newquantcompared','Localizationexpressioncoordination authorinterpretation no microscopyfractionationtransportraw shown','NoindustrialcostLCAyieldstableoperation verified;no externalcurrentclaims introduced']
figs=[{'label':'Figure 1','caption':'原文 Figure 1：完整路线示意与图注，已报道结果和未来目标分开','panels':[],'pages':[{'page':3,'bbox':[b[0]/rect.width,b[1]/rect.height,b[2]/rect.width,b[3]/rect.height],'dpi':300}]}]
draft={'identity_matches':True,'identity_reason':'DU LIAO LU English Commentary CJNM202422(4)291292 DOI10.1016/S1875-5364(24)60624-2 titlepage2 originalmatched','paper_type':'review','title_zh':'缺失CYP450与baccatinIII重构短评的证据边界','filename_title':'缺失CYP450与baccatinIII重构短评的证据边界','journal_short':'Chin J Nat Med','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexdirectall3pages EnglishCommentary reviewtemplate'})
out=d/'W4IHDLC6-Figure-1-p3-complete.png';doc[2].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images=[{'label':'Figure 1','caption':figs[0]['caption'],'page':3,'file':str(target),'bbox':b,'panels':[],'sha256':sha}];w.write_json(d/'codex-crops.json',images)
print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
