import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'RQJU5L74';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[345,36,568,372]),('Scheme 1',2,[59,345,308,383]),('Table I',2,[59,32,309,244]),('Figure 2',2,[315,734,571,751])]
gaps=['ResearchcommunicationthreephysicalpagesJACS93(9)2325to2327May51971 footer ZoteroMay1 discrepancy ReceivedFeb16 notpublication fiveauthorsWaniTaylorWallCoggonMcPhail titleauthorsmanualidentity automatchfalse DOIZoteronotprinted', 'ActualTaxolstartsleftbottom2325thenright topstructurebelongsTaxol continued2326 ends2327lefttop adjacentphotochemistryexcluded includingadjacentTableI', 'Figure1 notebooklabel originalunnumberedstructuralplate allcompounds12345678 Scheme1notebooklabel originalequation1 TableIoriginal Figure2notebooklabel originalfootnote17 crop allactualvisualelementscovered', 'Taxolyield.02percent no rawmassdryfreshrecoverynotabsolutecontent historicaldifferentbatchnotcombined', 'ParentC47H51NO14853 split2C17H17NO4 and3C29H36O10 methylacetatenotisolated mildmethanolysisnorearrangementauthorassumption referencedtaxinine notdirectwholeTaxolmechanisticproof', 'Derivative4pBrC24H20BrNO5 C2Z4R.1251772obs derivative5bisiodoC33H38O12I2 P212121Z4R.1422305obs anomaloushalogensabsoluteconfigpaperclaim fullcrystalelsewhere noCIF parentnotdirectXray', '3NMRabsentinsolubility historicaltaxanenumberingretain TableIδJHznotstats baccatinVreferenceC13from13alphaacetate notsameunspecifiedconditions', 'Oxidation8C31H36O11mass584.2266calc584.2257 UV272IR1680H10δ6.46 arguesC13ester not9,10dioxo noHMBCinvented', 'ED50foot5and17Taxol5.5e-5notOCRminus6 compounds2and3 1e2and2.2e-2 unitsnotprinted no unit imported no nCIerrorcurve', 'Body3.001activity versus conditionalinverseED50ratio1/400 unexplained retainboth no cure speculationC13leavinggroupnotmicrotubulemechanism proof', 'NCI SA43ph4322 DukeEndowment NIHPR330 noexplicitCOI DOInolivesourceindependentverified humanfalseclassdeferred']
figs=[{'label':l,'caption':({'Figure 1':'原文未编号结构图，Figure 1为笔记编号','Scheme 1':'原文方程(1)，Scheme 1为笔记编号','Table I':'原文Table I完整表格与脚注','Figure 2':'原文脚注17，Figure 2为笔记编号'}[l]),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'3physicalpages5authorsJACS93:23252327May51971titleauthorspageboundaryoriginalsverifiedDOIfromZoteronotprinted live200','paper_type':'research','source_article_type':'Research communication','title_zh':'Taxol发现论文的降解结构证据与活性比较边界','filename_title':'Taxol发现论文的降解结构证据与活性比较边界','journal_short':'JACS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded6pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('RQJU5L74-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
