import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'G27YIFKJ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[60,55,564,454])]
gaps=['All three mainpages read viewed; onlyFigure1 fullAtoF allaxes proteinstructuregeneannotation genomiccoordinate andentirelongcaption300dpicrop; nosupplementlocal','Printed title DOI twoauthors AmmarTareenJustinBKinney ColdSpringHarbor ApplicationsNote36issue7pp2272-2274 liveZotero200 AlfonsoValenciaeditor notauthor','AdvanceAccessDec102019 volume2020 downloadedApril232024 notpublicationdate','InputDataFrame rowsposition columnscharacters valuesheights notalwaysprobability; matrices negativevalid noinputdataqualityautomaticguarantee','Figure1A CRP negativeDeltaDeltaG matrix Benergykcalmol PDB1CGP priorstructure notnewcrystalbindingproof; displayedroundedfirstrowzero notnormalizationprobability','C GENCODE human5primespliceprobability D WW PFAMRP15informationbits differentunits no exactsamplecounts orfilterdefaultsreported','E ARS1log2enrichment orangeWT notbeneficialmarker A B1 B2backgroundregions unpublishedJ B Kdata analogousmutARSseqnotfullsamepublishedexperiment','F U2SURPexon9 maskedDNNimportance adaptedpermission previousCellfigure notnewwetvalidation no genomebuild or alternativebasezeroeffectproof','Softwarematrixprocessingconversion described no completepseudocountbackgroundgapdefaults inarticle; no performancebenchmarks measuredtestcountcoverage accuracyadvantage','OriginalPython2.7and3.6 compatibilityhistoric notcurrentverified installed; no codeclone actualnotebookexecution orupstreamdatamodelreproduction thissession','Figure1script examplesfigureipynb citedhistoricalGitHub docavailability no currentAPIinspection; citedarticles include preprints notallindependentlyread','NIH1R35GM1337775P30CA045508 CSHLNorthwell support conflict none CC BY4 original notice humanreviewfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI twoauthors ColdSpringHarbor ApplicationsNote Bioinformatics36issue7pp2272-2274 online2019volume2020 liveZotero200','paper_type':'research','source_article_type':'Applications Note software methods','title_zh':'Logomaker的矩阵接口与序列图语义边界','filename_title':'Logomaker的矩阵接口与序列图语义边界','journal_short':'Bioinformatics','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full original pages read and viewed; software representation separated from upstream inference and unperformed reproduction'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
