import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'QIVCCQB8';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',2,[40,64,565,521],[],'原文 Figure 1：完整紫杉醇骨架与侧链装配示意、全部结构及图注'),('Figure 2',4,[40,629,292,752],[],'原文 Figure 2：Taxol、cephalomannine 与 taxol C 的完整结构、酰基差异及图注'),('Figure 3',5,[30,66,289,674],['A','B','C'],'原文 Figure 3：全部 A–C 放射色谱、峰编号、坐标与完整图注')]
gaps=['All8physicalmainPDFpagesread andviewed;2005preliminaryassessmentnotcompletedgeneidentification','BetaPhenylalanoylCoANOTtested;negativefreebetaPhe cannotexcludeallpretransferhydroxylation','Cellfeeding13tritiumlabelsretainedtaxanecoreuptake/esterasecleavage/reassembly confound;noexactconversionnstatistics','NdebenzoyltaxolintermediateNOTdirectlyobserved;terminalTaxol/B/Ccoupledproducts notpurifiedsingleenzymeassay','D5benzoylationnegative product supportspriorendogenousNacylationatlowtracerscale notwholepathquantitativeefficiency','Figure3authorA/Bsameproportions claim vsrelativefirstpeakheightvisualchange;nointegratedrawpeaksorquantitativeestimate','Resultsparenthetic2deoxytaxolvsphenylisoserinoylbaccatinidentityambiguity retained;OCR20resolvedvisual2prime notcoreC20','Two2deoxycongenerstandardsunavailable retentionestimated;minorpeaksesteraseassignmenthypothesisonly','Presumed2primeR supportednaturalproductcoelution no2primeSepimercomparison/fullNMR','Microsomalcofractionationnotproofintrinsicmembranetransferase/metabolon;channelinghypothesis','Activityapproximately1vsT5five nmol/h/mgmicrosomalprotein notpureenzymekcat;noindependentn/errorreports','O2NADPHflavinCOazolequalitativeP450evidence notidentifiedgene;occasionalFealphaKGascorbateNADPHflavinazoleactivity unexplained','Figure1historical2005pathwayframeworknotcurrentfinalcompletepath;ligaseundefinedthen','Main3figuresnoTableScheme;noSIprovidedread;humanfullpaperreviewfalse']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'Directreadall8mainpages title2authorsDOI338410–417;primeglyphvisualchecked','paper_type':'research','title_zh':'紫杉醇侧链2′羟化酶初步鉴定与反应顺序的证据边界','filename_title':'紫杉醇侧链2′羟化酶初步鉴定与反应顺序的证据边界','journal_short':'BBRC','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'DirectCodex8physicalmainpagesfullreadandoriginalpageQA'})
images=[]
for l,p,b,a,c in spec:
 out=d/('QIVCCQB8-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':images},ensure_ascii=False))
