import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'8KKY7LZT';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',4,[46,46,565,311],list('ab'),'原文 Fig. 1：完整 IRC/ERC 装置、细胞循环及图注'),('Figure 2',5,[46,484,565,758],[],'原文 Fig. 2：完整树脂、细胞、培养液分离与提取示意及图注'),('Figure 3',6,[46,508,565,758],list('ab'),'原文 Fig. 3：完整生长曲线、减速干预及图注'),('Table 1',7,[46,50,565,160],[],'原文 Table 1：全部流动参数、床高与前期数据脚注'),('Table 2',8,[46,50,303,143],[],'原文 Table 2：生长速率、OD600、干重与前期数据脚注'),('Figure 4',8,[46,159,303,397],[],'原文 Fig. 4：全部五组及三相分配、纵轴单位与图注'),('Figure 5',9,[46,46,565,297],list('ab'),'原文 Fig. 5：完整吸附负载、生产率、轴单位及图注')]
gaps=['Read all10physicalpages coverplus9mainpages; SI calibration/rawGC/fits andcitedpapers notread','Formal2024volume54issue1pages86–94 versusonline2023-05-10 Zotero2023; preserveboth','Prepared supplementflagwrong mainidentitytitleDOIauthorsverified','3percentIRC figuresandtables frompriorSantoyoGarcia2022 notcurrentparallelcomparison','Nominalworking160mL versus150mLquantification unexplained','ActualPDFmicro-units corrected fromtextfont extraction','q defined massproduct/massresin mg/g butFigure5aaxis mg/mL unresolved','Productivity totalrecoveredtiter/timetogrowthstationary notinstantflux/fullbatchturnover','Noindependentrepeatn/CI/P supplied formaincomparisons','12percentIRC extendedrun lowersagitation after125h notidenticalconstantconditions','Particlefraction98percent notwholeprocessrecovery/pureyield; nogasbalance volatilizationhypothesis','Flowrate/expansion differ acrossERC concentrations; columnscale/cost/reuse untested','Graph heights approximate only notrawprecisevalues']
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'OriginalDOIauthorsformal2024andonline2023 verified','paper_type':'research','title_zh':'紫杉二烯固体吸附回收的配置比较与证据边界','filename_title':'紫杉二烯固体吸附回收的配置比较与证据边界','journal_short':'Prep Biochem Biotechnol','category':None,'related_categories':[],'classification_reason':'全部笔记完成后统一归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex direct mainPDFreading'})
images=[]
with fitz.open(rec['main_pdf']) as doc:
    for l,p,b,a,c in spec:
        out=d/('8KKY7LZT-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
