import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'WC6HD3C7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[315,279,556,407]),('Unnumbered Structure Graphic',2,[51,58,293,175]),('Figure 1',2,[51,249,293,519]),('Figure 2',3,[51,58,556,309]),('Figure 3',3,[51,313,556,596]),('Scheme 1',3,[51,603,556,755])]
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':next((x['caption'] for x in rec['figure_candidates'] if x['label']==l),'原文摘要图或完整结构总图'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
gaps=['No localSI,NP-MRD orcitedprimarypapers read; rawMSMS andhandedchromatograms notindependentlyverified','Preparation supplementflagincorrect main8pagePDFconfirmed','1/2sixdipeptidylunits3five notsamecomposition','Natural1–3 distinctfromanalyticalmethylesters1a/2a','Figure2 2terminalconfiguration differs1 notcopy1assignment','28nominal CH2CH2exact28.031300 vsCO27.994915 arithmetic notrawinstrumentverification','3 connectionusesHRMSMSandcomparison notallindependentderivatizationsteps','Scheme1 M1SacidLVal M2RacidDVal; FDLAelutionorder conditionspecific','ExperimentalMTPA sectionmixesPGME/M1/M2labels','DiscussionD-Hiv-D-Ala conflictsValcomposition/structure','PANC1IC50 2=1.2 2a=1.7uM versusmethods20–100uM range; SIcurve notread','1/3 individualIC50notexplicitmain andnoerrornCItestorpositivecontroldetails','MTTnotdirectmechanism selectivityorinvivoefficacy','Hostdefense hypothesis noecologicalcausaltest','NRPSsimilarity andnotdetectedcyclicproduct notcatalyticpathwayproof','Lineararrangement disfavorssimpleopeningdegradation butnotallroutes; authoralternatives preserved','No cropinventedforSIactivity/genefigure; allmain6graphicscomplete']
draft={'identity_matches':True,'identity_reason':'Formal8pageJNP87 976–983 titleauthorsDOImatch','paper_type':'research','title_zh':'Cavomycins重复酯肽的连接与构型证据','filename_title':'Cavomycins重复酯肽的连接与构型证据','journal_short':'J Nat Prod','category':None,'related_categories':[],'classification_reason':'全库笔记完成后归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex sourcechecked directreading without externalmodel'})
images=w.crops(rec,draft,d)
with fitz.open(rec['main_pdf']) as doc:
    for i,(l,p,b) in enumerate(spec):
        out=d/('WC6HD3C7-'+l.replace(' ','-')+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images[i].update(file=str(target),sha256=sha,bbox=b)
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
