import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'5QMZSYED';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[49,51,280,275]),('Figure 2',2,[36,282,290,482]),('Figure 3',2,[309,48,565,166]),('Table 1',2,[304,177,562,318]),('Figure 4',3,[36,49,566,185])]
gaps=['All three main PDF pages read and viewed; four Figures plus Table1 complete crops; SI FigsS5S7 and raw spectra unavailable, references not all independently read','Live Zotero200 DOI title and eight authors matched; onlineDec32023 but volume134year2024; prepared title_matchfalse superseded manual printed title verification','PbpsA4170aa39percentidentity55similarityFlvA; flanking genes annotation not biochemical functional characterization','Figure2 HPLC210nm peak1 absentemptycontrol presentpbpsA andpbpsABCD; no calibratedtiter replicatecount orerrorbars','pbpsBCD no observableprofile change conditionalnegative notproof no nativefunction without expressionvalidation','1.2kg rice 50gx24 2.1mg isolated equals1.75mgkg recoveredmass notliquidmgL or trueyield; nativefungusproduction1 notshown','BodyC10H12O3 MplusH181.0860 calc181.0859C10H13O3 ppm.552 DBE5; ref22 printsC10H3O3 missing1 notsilentlyretainincorrectformula','Table1 tenC numbered2to11 ringoxygen1; H7H8J15.6supportsE; H11C3 andH8C6HMBC supportattachment, C4OH assignedbyremainingcomposition; no SI rawcrosspeakverification','BodyH5HMBCincludesitsownC5 notindependentlongrangeproof; Figure3allCOSYHMBCarrows retained no inventedcorrelations','Figure4 proposedtetraketide2 pathway notcurrentintermediateisolation orfeeding; endogenoushostethylation hypothesis no enzymename donor isotopeKO','RdomainLysAsn substitution functionalhypothesis no restoredsite orenzymeassay; recognitioncode LeuIle analogy cannotexcludebottomsupply','No product1bioactivityassays; backgroundothercompoundactivitiesnottransferred; noconflictdeclared dataonrequestnotrepository; humanreviewfalse classificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI eightauthors TetrahedronLetters1342024 154865 allthreepages liveZotero200','paper_type':'research','source_article_type':'Original research article','title_zh':'Pestalotiopsis杂合酶产生新吡喃酮的结构证据与宿主修饰假说','filename_title':'Pestalotiopsis杂合酶产生新吡喃酮的结构证据与宿主修饰假说','journal_short':'Tetrahedron Lett','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full original pages read and viewed; original research structure versus biosynthesis hypotheses distinguished'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
