import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'98APV48H';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[36,620,562,748]),('Figure 2',5,[36,606,294,748]),('Figure 3',5,[305,50,562,221]),('Figure 4',5,[305,230,562,526]),('Figure 5',6,[36,50,294,301]),('Figure 6',6,[36,540,294,748]),('Figure 7',7,[36,50,562,481]),('Table 1',3,[305,50,562,285])]
gaps=['9physicalpages1repositorycover8mainversionofrecordNewBiotech83:66to73fiveauthorsQuaxGroningen DOIprintedacceptJun29onlineJuly1ZoteroNov2024 coverJuly292026downloadnotpublication', 'All9pagesfulltextreadoriginalsviewed7Figures1Table8final300dpicropscomplete originals noSITablesS1S2FigS1to6fullseqrawchromatograms read norefs52independentlyverified', 'TaxadieneallreportedmgLbetaCaryophylleneequivalent SIMm122betaCaryIScalibration12.5to400 noTaxadienepurestandardresponsefactor directabsoluteconcentrationnotverified nofullNMRmain', 'Bsubtilis168TaxusbaccataTXSAY424738S cerevisiaefppsBsubtilisispAPantoeacrtEaccessionsauthornotdownloaded shortchainPTfusionnotTXSfusion 8means7MEPplusispA not8replicates', '2SR49mgL48hvs2YT3foldTSB10fold currentstrainnotindustrial reactor pH3gLpercentK2HPO4sourcewordingambiguous', 'Additionaldxs313.8equiv25.44perODlowestgrowth notdirectIPPDMAPPtoxiccause othergeneslittlebenefit noabsolutecontrolcoefficient TXSruntotalbiologicalcultures3MeanSD', 'qPCRrpoB2deltaCT5h two biofourtechnot8independent approximate5and30fold notproteinfold norfluxfold', 'ALEispAlinkercrtEFLEfppslinkercrtEELAreverseELFreverse solubleHisWB66.973.9kDa qualitative noprovenequalactivityorchanneling controlFEAEmethodseparateRBSoperonvsdiscussionwithoutlinker cannotassigndirectfusionwithoutseq', 'FLE320equiv12.8perOD OD25 combineddxsFLE390equiv26perOD48h max81hdecline compare313.8equiv25.44perOD totalratio1.243normalized1.022 no directtoxicisopreneidentity orIPPGGPPpools', '390/17.8 equals21.91foldvsnormalized26/1.98113.12 source13foldconcentrationclaimconflict do notsilentlycorrect historicalhighestnotcurrentverified', 'Discussion390assignedFLEvsresults320FLE390dxsFLE versionconflict;genomeintegrationresultslowgrowthproductionvsdiscussionnosignificantdifference noSI cannotresolve equivalencenotproved mediumcopy15to25quotednotactualmeasured', 'Intracellularfractionless1percentauthorreportedno rawfractionsmain no dataindependent mass;fedbatchpHaerationfutureonly nofinalTaxolhumanfalseclassificationdeferred CSC201806300121nocoi']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注' if l!='Figure 5' else '原文未编号摘要图，Figure 5为笔记编号'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'9physicalpagesGroningencover8mainNewBiotech2024fiveauthorsDOIprintedtitlelive20083:66to73 noSI','paper_type':'research','source_article_type':'Research Letter','title_zh':'DXS追加表达与短链prenyltransferase融合提升紫杉二烯当量产出','filename_title':'DXS追加表达与短链prenyltransferase融合提升紫杉二烯当量产出','journal_short':'New Biotechnol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded9physicalpages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('98APV48H-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
