import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'96VLQNFQ';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',3,[56,63,578,351],[]),('Figure 2',3,[321,614,578,712],[]),('Figure 3',5,[56,63,578,283],[]),('Figure 4',5,[56,449,313,712],[])]
for label,page,bbox,panels in specs:
 pg=doc[page-1];file=d/('96VLQNFQ-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file));caption=next(x['caption'] for x in rec['figure_candidates'] if x['label']==label)
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'OriginalPDFtitle7authors ArchBiochemBiophys364(2)273-279April15 1999 articleIDabbi.1999.1125 matchesliveZoteroDOI10.1006/abbi.1999.1125; automaticfalse title/DOI manuallyresolved.','paper_type':'research','title_zh':'紫杉二烯醇乙酰转移酶部分纯化与底物偏好','filename_title':'紫杉二烯醇乙酰转移酶部分纯化与底物偏好','journal_short':'Arch Biochem Biophys','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['Partially purified preparation notsingleidentifiedprotein no clonedgene accession;alternative substrateactivities mayincludeotherenzymes','Twoflasks oneinduced onecontrol longitudinalsampling no reportedindependentculturebatches or timecourseCI/P','Km plusminusmeaning SD/SEM/fittingerror notspecified;rawrate data andfullenzymeproductNMR notprovided','PDFextracted mM/mL corrupted micro units corrected againstoriginalpages; figurecaptions mayretainextraction alpha glyph artifacts','Oxetane model historicalhypothesis notassayedhere;CoAhighconcentration inhibition notestablishedphysiologicalregulation'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'taxol_medium_reported_mg_L':14,'control_reported_mg_L':.04,'descriptive_ratio':14/.04,'Km_taxadienol_uM':4.2,'Km_taxadienol_plusminus_unspecified':.8,'Km_acetylCoA_uM':5.5,'Km_acetylCoA_plusminus_unspecified':1.7,'relative_Vrel_over_Km_GGOH_to_taxadienol':1.5e-3/2.5e-3,'relative_Vrel_over_Km_farnesol_to_taxadienol':1.3e-3/2.5e-3,'relative_Vrel_over_Km_phytol_to_taxadienol':7.2e-5/2.5e-3,'activity_recovery_less_than_percent':5,'protein_removed_greater_than_percent':99,'protein_removal_not_purity':True,'gene_identified_here':False});print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
