import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'RWTI5U34';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[42,60,553,465])]
gaps=['Perspective4pages3authorsfirst2equal1corr no new experiments all21references unread independently','40mgkg equals40ugg0.004percent bark dryfresh undefined not comparable mgL','Three oxetane explanations TOT1 highlyacetylated substrate versus epoxidase taxusin versusCYP725A4 distinct hosts original primary structures unverified','Figure1B crossedinterconversion not obligatory sequential route allABC fullcaption viewed','genecluster here functional coexpression set not physical chromosome cluster 9left13right nine minusTOT1 plus5 equals13 TXS included starttaxadiene prose mismatch','Fernie2023 comparedYan2024 based wording not literal historical followup','FinalTaxol external benzoicacid Lphenylalanine baccatinIII not single condition full de novo','OCTisoOCT more65percent accumulated taxanes specific background no n errors remaining35 not allproductive','NativeTaxus notobserved accumulation cited2011review not universal absence metabolon partner microenvironment hypotheses only generalNatPlants2018ref not specificTaxolcomplex','NoLCA TEA titer industrial proof n P CI unreported humanreviewfalse deferclassification']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'4pages3authorsBioDesignResearch6:0035DOI liveZotero verified Perspective','paper_type':'review','source_article_type':'Perspective','title_zh':'紫杉醇代谢网络观点中的氧杂环争议与宿主差异','filename_title':'紫杉醇代谢网络观点中的氧杂环争议与宿主差异','journal_short':'BioDes Res','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded4pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('RWTI5U34-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
