from pathlib import Path
p=Path(__file__).parent/'prepare-73-codex.py'
s=p.read_text(encoding='utf-8').replace('73ZWPHQB','2BXAQGNW').replace('Taxus NPF转运蛋白介导紫杉烷底物利用及酵母生物转化的功能证据','红花UGT73AE1的宽谱OSN糖基化与糖转移耦联证据').replace('16pages title8authorsTPJ122e70146DOI verified','4mainpages7authorsOrgLett16p4874to4877DOIverified autoSIflagfalsebyactualmaintext').replace('CurrentCodexsourcegrounded16pages','CurrentCodexsourcegrounded4pages').replace("'Plant J'","'Org Lett'")
start=s.index('spec=');end=s.index('\nfigs=',start)
spec=[('Chart 1',1,[160,238,465,347]),('Figure 1',2,[58,64,568,469]),('Figure 2',3,[58,336,304,565]),('Figure 3',3,[322,216,568,437])]
gaps=['All4mainpagesread4originalsviewed4cropsincludinggraphicalabstractChart1internalindexnotauthornumber','PDFautoSIflagincorrectactualmaintexttitlejournalpages4874to4877 identityverified;SI S1toS12TablesS2S5rawNMRSDSbiochemicaldataactualunread','7authorsEnglishpaperChineseaffiliationnotChineselanguageexcluded;20140905PDFpublishednotZotero0919 fundingnofinancialCOIstatementverified','27members19representativetypes notsamecount14over80percent16aglycons20isolated4authornovelnotindependentnoveltysearch;3bnotisolated','BetaOSN2a14a17aJ9.6/6.8/8.4 HznotCglycosylation;nativeflavonoidGTtentative noS/Nnativefunctionproof','emodin8OnotRpUGT1emodin6O separateenzymeconditionsnotdirectefficiencyranking noRugulosinAsubstratetested','icariin7Odeglyco38percentHPLC;Keq7.5directionformulaSIunread notindependentlycomputed;coupled24/26percentdifferentdenominatorsnot50totalyield','50uMicariin25uMemodin2.5uMUDP coupled26percentconditional6.5uM2.6UDPturnsnotdirectmeasuredcycles;24percent12uMnotclosedmassbalance','ReactionvolumeSIfullmethodsnotverified1mgproteinnoconcentrationinvented;noexactnPstatsCI;FIG1panelbarsnoinventedexactpercentage','Biopharmaceuticalbenefitsreferencesnotcurrentdirectexperiment;industrialcostenvironmentalclaimsnotquantified;KJ956788notdownloaded']
s=s[:start]+'spec='+repr(spec)+'\ngaps='+repr(gaps)+s[end:]
s=s.replace('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）','原文首页图形摘要（内部索引 Chart 1，非作者正式图号）')
exec(compile(s,str(p),'exec'))
