import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'95JFRYUJ';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',3,[40,460,548,741],list('AB'),'Fig.1. Vector maps and promoter-region sequences. Complete A maps and B sequences with original caption.'),('Figure 2',5,[40,492,285,741],[],'Fig.2. DifferentIPTG concentrations 1.0/0.5/0.1mM; fusionproteinmass based500mlculture100mlextraction. Original fullplot andcaption.'),('Figure 3',6,[48,68,293,264],[],'Fig.3. Total versus soluble fusionprotein mass;500mlculture100mlextraction. Separate completecaption manuallysplitfrommergedautocandidate.'),('Figure 4',6,[310,68,556,398],[],'Fig.4. SDS-PAGE crude/partiallypurified GSTlanes1/2 His3/4 biotin5/6 andmarkerM;expected77170/51766/64251Da; completecaption.'),('Table 1',6,[48,589,556,738],[],'Table1. Purification and activity of fusionproteins. All6rows totalactivitynmol/min totalproteinmg specificactivitynmol/min/mg activityyield andpurificationfold.')]
for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('95JFRYUJ-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'Printed title twoauthors journal35 17-24 2004 and DOI matchliveZotero; all8originalpages readandvisuallyreviewed.','paper_type':'research','title_zh':'DBAT三种融合表达体系与活性回收','filename_title':'DBAT三种融合表达体系与活性回收','journal_short':'Protein Expr Purif','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['His largelysoluble abstract conflictsfixed1mM25C7h results25percentsoluble; condition-specific numbersretained','Methodsvectordescription GSTXa biotinthrombin swapped versuslater GSTthrombin biotinFactorXa; preserved notvalidatedprocedure','ORF1320nt440aa originalstopcountnotexplained;98percentfullcDNAcomparison97percentpeptidecomparison distinct','Culturemediahosts tags promoter translationlayout andresins covary; noisolatedtagpromotercausaltest','Detergentdoublesbiotinfusionsolubilization notnativeDBATmembranelocalizationproof; temperaturecleavagedenaturation hypothesesnoisolatingcontrols','Allpartialpurification tableactivitynonzero1.4-1.99percentrecovery abstractlostnotzero; separatefusionpercentagepurityproteinmassactivity','Noindependentrepeats uncertainty rawdensitometry fulllinearitycontrols orkineticplots; Kmnotkcat noPTXtitre','MeJA24hmaxproduction unpublishednotnewcurve; noSIorindependentreferencefulltextreview'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'GST_activity_start_nmol_min':2.308,'GST_activity_end':.046,'GST_activity_recovery_percent':.046/2.308*100,'His_activity_start':2.567,'His_activity_end':.043,'His_activity_recovery_percent':.043/2.567*100,'biotin_activity_start':.215,'biotin_activity_end':.003,'biotin_activity_recovery_percent':.003/.215*100,'reported_purificationfolds':[1.31,2.09,6.80],'specificactivities_start':[.0123,.0117,.0009],'specificactivities_end':[.0161,.0244,.0061],'reported_totalproteinpercent_His_GST_biotin':[3.2,1.8,.53],'reported_solubilitypercent_His_GST_biotin':[25,80,40],'derived_solublefusion_totalproteinpercent_His_GST_biotin':[3.2*.25,1.8*.8,.53*.4],'GST_His_solublemassfractionratio':(1.8*.8)/(3.2*.25),'His_Km_acetylCoA_uM':8.5,'His_Km_10DAB_uM':11,'purified_fusionfraction_GST_His_biotin_percent':[40,20,60],'activitynotzero':True,'noindustrialproducttitre':True})
z=json.loads((d/'codex-live-zotero.json').read_text(encoding='utf8'));print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'live_title':z['data']['title'],'live_DOI':z['data']['DOI'],'images':[x['file'] for x in images]},ensure_ascii=False))
