import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'9BZH5GCC';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[206,233,408,288],[],'原文摘要结构图：GGPP 类似物与单环终止产物'),('Figure 1',2,[52,49,297,237],[],'原文 Fig. 1：完整紫杉烷结构与编号、图注'),('Unnumbered Structure Graphic 1',2,[345,157,531,371],[],'原文式 1 及下方 8/9：完整既有机制、阳离子与中性骨架'),('Figure 2',3,[52,49,297,201],[],'原文 Fig. 2：10–13 与天然 GGPP，完整结构与图注'),('Scheme 1',4,[52,49,559,239],[],'原文 Scheme 1：完整 10/11 合成与全部编号'),('Scheme 2',4,[52,244,297,557],[],'原文 Scheme 2：完整 12/13 两条合成分支与全部编号'),('Figure 3',4,[315,421,561,744],list('abcd'),'原文 Fig. 3：完整 a–d TIC 色谱与阴性对照说明'),('Table 1',5,[52,49,297,218],[],'原文 Table 1：全部底物量、规模、烃类收率、盐型和估算脚注'),('Unnumbered Structure Graphic 2',5,[315,82,561,392],[],'原文式 2–5：完整 10–13 到 37–40 映射与副产物 41'),('Table 2',5,[52,490,559,744],[],'原文 Table 2：完整 37/38 NMR 20 位数据与构型指派限制脚注'),('Table 3',6,[52,49,559,300],[],'原文 Table 3：完整 39/40 NMR 与去甲基空位、脚注')]
gaps=['All7mainpagesreadandvisuallychecked;SI rawspectra synthesis andcitedsourcesunread','OnlinePDFNov2 vsZoteroNov1 preserved','Compoundnumbers paper-specific GGPP versustaxanenumberingdifferent','10R/S typo withinparagraph retainednoinventedstructuralcorrection','Crudesolublelysatenotpureenzyme;intrinsicPPasehypothesisnotmeasured','ActualsaltsBu4N2NH4 versusBu4N3 notuniformNH4 salts; noformcomparison','All37–40C1S explicitlyassumednotindependentlyabsoluteassigned;diastereotopicHalpha/betaunknown','Table1 totals hydrocarbonyields notmajorpureproducts;12estimated<1 and13approx3impuritybasednotpuremeasured','13earlysynthesis~10percentalltransGGPP impurity producedtaxadiene;Scheme2 cleanerproductnegligible; n.d.amountmass','No repeatedn/errorsP kineticconstants/extractionrecoveries/fullmassbalance','39 isC19desmethyl withC18absent notallC20','12poorhydrocarbonunexploredunreacted/hydrolysiswatercapture/inactivation;noneproven','Onlyminor41 identified from11;otherminorpeaksunknown','Abstractsupportsmonocyclicintermediate notdirectnaturalcarbocationcapture;C16base/affinityinterpretationsunverified']
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'All7mainpages titleauthorsDOIvolumepagesverified','paper_type':'research','title_zh':'GGPP类似物截停单环阶段的结构证据与机制边界','filename_title':'GGPP类似物截停单环阶段的结构证据与机制边界','journal_short':'J Org Chem','category':None,'related_categories':[],'classification_reason':'全部笔记完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex directsource reading'})
images=[]
with fitz.open(rec['main_pdf']) as doc:
    for l,p,b,a,c in spec:
        out=d/('9BZH5GCC-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
