import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'SY7IPB73';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',[(1,[323,248,558,370])],[]),('Figure 1',[(2,[51,58,556,403])],[]),('Table 1',[(3,[51,54,556,748]),(4,[51,57,556,140])],[]),('Figure 2',[(4,[51,145,556,547])],[]),('Table 2',[(5,[51,58,556,307])],[]),('Table 3',[(5,[51,313,556,499])],[]),('Figure 3',[(6,[51,58,556,549])],[]),('Figure 4',[(7,[51,58,556,402])],list('ABC'))]
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':next((x['caption'] for x in rec['figure_candidates'] if x['label']==l),'原文摘要图')+('；包括下一页续表及溶剂脚注' if l=='Table 1' else ''),'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300} for p,b in parts]} for l,parts,a in spec]
gaps=['No localSI/CIF NP-MRD/citedprimarypapers orgenedatabase independentverification','Formal10pagePDFnotSI despitepreparedflag','Only5singlecrystalFlack0.00(4) Hooft0.01(3)CCDC2309293;1–3tentativeabsoluteconfigurations','Table1 spansPDF3/4 fullcontinuationandsolventfootnotes;1CDCl3 2/3DMSO','Figure2captionmentionssugars1–4 but4nosugar','2printedneutralformulaC46H54O19 protonated911.333206 versusreported927.3281;O20matches927.328121,notrawMSverified','4multiplemothercorechanges notmatchedonlysugarcomparison','1MIC0.125 atlowestreportedrange notexactcontinuouspotency','1staphadvantagesnotallGpositive;MRSA991equalcontrol Bsubtilis>64 versus5 .125','6Gnegative32/64 notallcompoundszeroactivity','Cellcytotox±typenCItestdetailedmethod notclearlyreportedmain; antibacterialtwo replicates notconfirmedindependent','MICugmL andIC50uM notdivideintotherapyindex; noclinicalnormalselectivity targetanimalbactericidalkinetics','Candidatekeb40ORF homology50–89percent notallcatalyticproof','Figure3proposedroute; literatureenzymedata notcurrentvalidation','KebMT2 Figure4 enzyme/noenzyme/standard supports2to5 sugarOmethylation;Mgconditionenhancementnotessentiality','NoenzymeKm/kcat/substratescope/fullproductNMR/geneticknockoutcomplementation shownmain','Sourcegapsretained withoutinventedSIplots']
draft={'identity_matches':True,'identity_reason':'Formal10pageJNP87 1591–1600 titleDOIauthorsmatch','paper_type':'research','title_zh':'Kebanmycins结构活性与糖O甲基化证据','filename_title':'Kebanmycins结构活性与糖O甲基化证据','journal_short':'J Nat Prod','category':None,'related_categories':[],'classification_reason':'全库笔记完成后归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex sourcechecked directreading without externalmodel'})
images=w.crops(rec,draft,d);i=0
with fitz.open(rec['main_pdf']) as doc:
    for l,parts,a in spec:
        for p,b in parts:
            out=d/('SY7IPB73-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images[i].update(file=str(target),sha256=sha,bbox=b);i+=1
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
