import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'D5QBZ4FI';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[60,86,537,418]),('Figure 2',4,[60,401,537,722]),('Figure 3',6,[60,457,537,723]),('Table 1',2,[303,84,542,231]),('Table 2',3,[55,644,542,725])]
gaps=['Ten full main pages read and viewed; three figures and two tables; four SI files unavailable SuppTables1-2 Fig1-2 sequences calibration rawdata not read','Eight authors HulyaKaraca corresponding DOI printed 23:241 receivedMar29 acceptedAug19 onlineSep6 2024 live Zotero200','Beta-caryophyllene internal standard and calibration equation SIMm122; puretaxadiene responsefactor not verified; overlay culturevolume calculation not independently reconstructed do not multiply or divide ten','HK1-16SCIGS22a HK17-32MVA six additional genes; Figure1 depicts mixed engineering scope rely Table2; Figure2 B X-2 versus XI-2 wording unresolved','HK1 109.7 HK17 2.9; TS-GGPPS HK5 277.8 HK21 7.9 versus reverseHK9 76 HK25notdetected; orientation discussion conflicts preserve actual strains','Background already contains tHMG1 ERG20; plasmid extra genes not no-upstream engineering; tHMG1 HK22 11.4 HK10 4.9 not universal fifteen-fold effect','ERG20HK3 47 versusHK19 .08 contradicts universal MVA better; HK2764 highest MVA; contextdependent not all fusion controls equivalent','HK12 GGPPS-TS plus independenttHMG1ERG20 528.5 reported versus abstract528; HK16 GGPPS-ERG20 plus tHMG1TS445 versusHK3224.4; not onefactor fold','Five biological replicates in construction versus Figure3triplicate cultures MeanSD; no exactP CI tests or multiplecomparisons main','No actual RNA protein solubleWB intermediatepools flux or toxicity assays; channeling and mRNA stems hypotheses author explicitly notes missing followup','Table1Malci215 vs body251; referenced16year2014 and27year2013 and31volume194 source retained not all ref metadata verified','Culture72h20mL shakeflask no fedbatch or productstability growthnormalized evidence; nondetect notzero LODnotreported; highestclaim historical not2026; finalTaxolnotproduced','TUBITAK117Z246 Anadolu2008S091 CC BYNCND4 complete unaltered original figures no competing interests humanfalseclassificationdeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Tenpage Research printed DOI title eight authors MicrobCellFact23:241 liveZotero200','paper_type':'research','source_article_type':'Research Article','title_zh':'酵母紫杉二烯生产的宿主背景与融合模块组合效应','filename_title':'酵母紫杉二烯生产的宿主背景与融合模块组合效应','journal_short':'Microb Cell Fact','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex ten pages fully read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
