import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'TCHIIMI8';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',4,[44,319,503,675],list('ABC')),('Figure 2',5,[44,55,503,326],[]),('Figure 3',5,[282,467,503,668],[])]
for label,page,bbox,panels in specs:
 pg=doc[page-1];file=d/('TCHIIMI8-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 caption=next(b[4] for b in pg.get_text('blocks') if b[4].startswith('Fig. '+label.split()[-1]) and b[1]>300)
 meta={'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]};figures.append(meta);images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'OriginalPDFexacttitle sixauthors DOI matchliveZotero; automaticfalse titlematch manuallyresolved; online15Nov2006 distinct volume2007.','paper_type':'research','source_article_type':'Brief Communication','title_zh':'番茄果实代谢重定向与紫杉二烯制备','filename_title':'番茄果实代谢重定向与紫杉二烯制备','journal_short':'Transgenic Res','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['未给全部统计n、误差条定义、精确P/CI；五个BCTaxK初代株系不代表全部后代均值n','无匹配红果转基因对照及直接GGPP通量，不能独立量化yellowflesh前体竞争贡献','471分析均值与160mg实际分离样品/工艺不同，不计算回收率或鲜重换算','未提供完整序列/GenBank编号、二维谱和定量NMR验证；未附补充文件','Koepp1995参考题目taxa4(20)与正文/结构图4(5)命名不同，原文引用未另行核查'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'purified_BC_to_internal_estimate':279/310,'purified_RD_to_internal_estimate':381/395,'elite_RD_to_BC_fruit_mean':471/339,'elite_RD_increase_percent':(471/339-1)*100,'isolated_160mg_per_kg_dry_ug_per_g':160,'BCmean_to_historical_constitutive_20ngg':339*1000/20,'RDmean_to_historical_constitutive_20ngg':471*1000/20,'RDprimary_estimate_to_historical_inducible_600ngg':395*1000/600,'process_recovery_rate_calculated':False,'DW_FW_conversion_performed':False,'Figure3_error_type_unreported':True,'exact_P_unreported':True})
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
