import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'M4QLM7A9';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[36,467,562,748]),('Figure 2',4,[36,568,562,748]),('Figure 3',5,[36,50,562,348]),('Figure 4',5,[36,591,562,748]),('Figure 5',6,[36,438,562,748]),('Table 1',3,[305,600,562,746]),('Table 2',6,[36,50,562,126])]
gaps=['Eightmainpagesreadalloriginalsviewed5Figures2Tables7complete300dpicrops6authorsJianHeXuECUSTProcessBiochem122129to136 DOIprintedacceptedSep4onlineSep7ZoteroNov2022', 'NoSIlocalTablesS1S2seqprimerspromoterstrengthFigS1to14rawMSNMRcalibrationbioreactorunread GenBankAF081514U48796authorreportednotdownloaded refs40notindependentlyread', 'BL21DE3TaxuscanadensisGGPPSbrevifoliaTS codonoptimized upstreamDXSIDIispDFreducedtoDXSIDI initial4.6simplified5.7stronger11mgL72h notfullTaxol', 'FusionorientationTSGGPPSsameupstreampromoter16vs22conditionaladvantage Figure3SDSsolubleinsolublequalitativebandsnotkcatdirectchannelingGGPPmeasurement', 'Table1ECU5008duplicatedGSGGSGGSGrowlikely5006butnotverified secondECU5008GSTGS2 preserved no silentfix rigidlinkerseqAEAAAKEAAAKAtablevsAEAAAAKEAAAKAbody', 'ECU5004GSTGS32.1 ECU5008GSTGS2 37.8mgL reported2.7/3.6fold requireconditionmatched16Cbaseline not11mgL22C automatic exactratio no irreversibleTSactivityclaim', 'IPTGlower51.7glycerol3percent93.5mgL7.7mgpergDCW SIrawunread brothTBglycerol15gLrepeatedwording ambiguous firststudyoverall93.5/4.620.33foldnotonefactor', '5Lreactor71mgL48hinduction20C lowerthanflask93.5 baseline72h16C notsimpleoveralldecreaseisolateeffect proteinpoorFigS14authorreportednotread no industrialscalabilityproof', 'GCMSidentifyGC FIDcalibrationpuretaxadiene1H13CNMRmain20carbon4alkenecarbonvalues standardpuritySIunread noredoabsoluteconfig allprofileisomersnotdefined', 'Staticscreen0.90mgpergwetHz816 at100mgL1mL100mgwetmax1mgpergwet masslimited cannotintrinsiccapacityclaim Dynamic13.2mgpergdrybodyvsabstractwet conflict no wetdryconversion', 'Staticacetone86.8percentHz816vsdynamic29.1/31.692.1percent differentassays notsame recovery;resinadsorptionelutionactual84.5pure75.3 not95.5purityuntiladditionalpreparativeLC', 'Table2extraction73.9pure34.6silica67.3pure84.7 vsmethanolleach91pure19resin84.5pure75.3 recoverydenominatorsstepvsoverallunclear do notmultiply;supernatant92.1intracellular91weighted91.6 needsfractionsno inventmass', 'DataavailabilityabstractalldataarticleSIversusendNoDataused contradict no actualarchivefullrawverified;mainnerrorPundefined noinventedstats funding2019YFA0905000noconflictauthorhumanfalseclassificationdeferred']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注' if l!='Figure 5' else '原文未编号摘要图，Figure 5为笔记编号'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'8pages6authorsECUSTProcessBiochem2022DOIprintedtitlelive200122129to136 noSI','paper_type':'research','source_article_type':'Research Letter','title_zh':'TS与GGPPS融合生产紫杉二烯及树脂分离的证据边界','filename_title':'TS与GGPPS融合生产紫杉二烯及树脂分离的证据边界','journal_short':'Process Biochem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded8physicalpages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('M4QLM7A9-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
