import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'R8AD93HX';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[60,53,572,359]),('Figure 2',2,[60,527,572,741]),('Figure 3',4,[322,347,572,741]),('Figure 4',5,[60,53,310,349]),('Figure 5',5,[322,53,572,505])]
gaps=['Six pages PNAS99(20)12715-12720 October1 2002 fourauthors WalkerFujisaki equal Walker corresponding contributedAug2 notpublication liveZotero identity verified', 'BAPT TAX7 AY082804 paperonly sequenceversionunverified 1335bp445aa50546Da', 'Ninefamily five remainingcandidates not replicates cellfree BL21DE3 fedcomplexsubstrates notdenovoTaxol', 'Enzyme Ndebenzoyl2deoxytaxol chemicalNbz then2deoxytaxol notTaxol no omittedderivatization detected notnoenzymereaction', 'Five fulloriginalFigures allpagesread viewed300dpi crops complete figure3 upperreactionradio lowerstandardUV residual21.3 Figure5 upperLC loweritsMS different39.6and20.8methods', 'Single3primeepimer absoluteconfigurationunassigned partialNMRotherregionauthorreport only', 'Crudesolublekinetics protein1percent soluble activityrecovery15to20percent presumptiveinstability notproof Km2.4plusminus0.5 and4.9plusminus0.3microM R2.99 no nerrorCIrawrateskcat', 'Relativevelocity1versus.4 notkcatKm alphaandNbzdonorbelow.01 notzero donorchemicalyieldpuritiesdifferent noimpurityeffectproven', 'pH6.8 bufferchangesMESphosphateoverlap notcultureoptimal C13observedlimitedbaccatin notalltaxanes', 'G163XXXDA168 insteadHis motif mechanisticbetaamineprotonhypothesis no mutationstructure fiveacylases historicalscope nofullproduction naturalfinalorderunknown fundingnoCOIdeclaration']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'6pages4authorsPNAS99:1271512720October12002titleauthorsjournalDOIprintedvisualverifiedliveZotero','paper_type':'research','source_article_type':'Research article','title_zh':'紫杉醇侧链转移酶BAPT的功能鉴定与化学衍生化证据边界','filename_title':'紫杉醇侧链转移酶BAPT的功能鉴定与化学衍生化证据边界','journal_short':'PNAS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded6pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('R8AD93HX-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
