import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'TGJ6DZXZ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[316,180,559,522]),('Figure 2',2,[53,45,295,304]),('Scheme 1',2,[53,306,295,473]),('Table 1',2,[316,43,559,123])]
gaps=['Two main fullpages textoriginalimagesread fourcomplete300dpi crops Figure1ABmodelsequenceFigure2ABalltracesScheme1sixstructuresTable1fourcolumns; no rawchromatogramsPDBcoordinates or fullassaydetails cited14refsnotallread','LiveZotero200 threeauthorsTangTsaiKhosla Stanford JACS12542:12708-12709 DOIprinted webSeptember272003receivedAug12 ZoteroOct1 distinctdatefields','1QXG describedhomologymodel notnewcrystalstructure; PDBcurrentrecordnotqueried;18Angstrom1.8nm modelnotexperimentalchannelmeasure; template25-40identitynotaccuracy','Actresidues109112116133 vs tcmG116M120differentnumbering;sequencecorrelation acrossC16C20C24CLFsnotuniversalrules whiEchannelspeculative','ActF116Ain vivo6percentdec versusinvitro64;double66vs96 fromTable1 samevariantdifferentbackgroundnotintrinsicfixedspecificity no biologicalreplicateCI orP','Actdoubletotalyield30percentWTDMAC with66percentdec conditionalproductestimate19.8percent notabsolutefermentation orimprovementagainsttcm;ratio notproductivity','Acttriple notmorechainchange quadruplenoobservedproducts interfaceperturbation proposed no foldingbinding data no detectionlimit; tcmG116TM120Fno productalsohypothesis','tcmG116Tmore65percentoct totalcomparabletcmWT reported Figure2B2:1 notfullTable1tcmvalues;tcmminimalPKSvsacttailoringdifferentproducts backgrounds','Scheme1 octDMACSEK4SEK4b decRM20bSEK15SEK15b notallsameMScompound orcompletebiosyntheticproducts','Table1 actWT100/0vs99/1F116A94/6vs36/64double34/66vs4/96 exactcolumns; differences58/30percentagepoints nottotalyieldfoldincrease','FLAGpurity95percentproteinnotproductpurity;invivovitrodifference suggestsadditionalprotein effects butmultipleconditionchanges no uniquelyidentifiedcausalpartner','Chaincount C20minusC16fourcarbon twoextensions notdirecttimecourse;CLFimportantnotexcludeKSACPotherroles ordirectrefutationmalonyl-decarboxylation','NIHCA77248 Khosla TangNIHpostdocnoawardnumber noexplicitCOI nohumanreviewclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI three authors JACS125:12708-12709 two pages liveZotero200','paper_type':'research','source_article_type':'Communication','title_zh':'CLF链长门控的同源模型与体内外产物证据','filename_title':'CLF链长门控的同源模型与体内外产物证据','journal_short':'JACS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex two full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
