import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'4YPNMZFH';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Scheme 1',2,[45,57,551,734],[],'Scheme1.Taxadiene biosynthetic and variant-product mechanisms; GGPP carbon numbering, computedblueintermediateenergyblackbarrierredreactionfreeenergy kcal/mol. Alloriginalstructures andcaption.'),('Scheme 2',3,[48,57,295,310],[],'Scheme2. TxS products from10,11dihydro 6fluoro 7desmethylGGPP, prior-work context.'),('Scheme 3',4,[48,57,296,587],[],'Scheme3.EIMS fragmentation tobasepeakm/z122;blue13Ccarbonorigins computedenergies andlong-rangehydrogen migrations.'),('Figure 1',5,[47,57,297,487],list('AB'),'Figure1.TxS mutagenesis Aactive/inactiveresidues based3P5R Brelativeproduction WTsum100percent meansfromtriplicates SDinTableS8unavailable.'),('Scheme 4',6,[48,57,296,432],list('ABCD'),'Scheme4.Computed kineticisotope effects onlymigratingH/Dexchange: H→J7.2 C→D6.0 D→E4.4 C→E4.4 notexperimentallymeasuredrateconstants.'),('Scheme 5',7,[45,57,551,602],[],'Scheme5.isoGGPP I cyclisation taxaxenene12 andV610T products13-16. GGPPnumbering computedfreeenergies; body5.5versusgraphic5.4 barrier retained.')]
for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('4YPNMZFH-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'Printedtitle3authorsDOI AngewChemIntEd2025 64e202422788January10VOR matchliveZotero. All9originalpages textandvisualreviewed.','paper_type':'research','title_zh':'紫杉二烯体系的氢迁移与机制证据','filename_title':'紫杉二烯体系的氢迁移与机制证据','journal_short':'Angew Chem Int Ed','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['BodyR580MinactiveversusFigure1Agreenactiveconflict unresolved SIunavailable','NoSIattachment;maincitesTablesS1-S17 FiguresS1-S82 methodsNMRSDcomputedcoordinates notindependentlyreviewed','isoGGPP C10→C2 isotopepositionevidence isanalogspecific doesnotdirectlytrace naturalGGPPbothC10→C2→C6','ComputedKIE7.2/6/4.4/4.4 notmeasuredrates; lowlabel8andallDretained butexpectedC6couplingnotobserved','Compound5identityunresolved noNMR despiteGCMSmatch andCAS confusion; do notclaimdetermined','E583watergateI848LF834rotation hypothesesbasedstructure/model notexclusivecausalproof; V610Ttotalproductionnot1increase','AllenergiesDFTfreeenergy kcal/mol andGGPPnumbering notstandardtaxane orcellflux; EI70eVnotallinternalenergy','Scheme5body5.5 versusgraphic5.4 computedbarrier; minorpreserved discrepancy','Figure1Bmeansn3SDTableS8unavailable noallconditionnP CIs; priorSchemesubstratework notallnewexperiments','Absoluteconfigurationclaims mainreports12/15/16chemicalcorrelation SIunreviewed noECDcrystal claim forall13/14'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'truncation_Nterminal_aa':78,'prior_productcomposition1_2_percent':[87,13],'EIenergy_eV':70,'EIenergy_kcal_mol_conversion':70*23.060548,'EI_RDA_barrier_kcalmol':35.8,'EI_RDA_reactionfreeenergy':36.1,'cyclophomactene_highest_modelbarrier':13.9,'computedKIE_HJ_CD_DE_CE':[7.2,6.0,4.4,4.4],'KIE_experimentally_measured':False,'Figure1B_mean_triplicates':3,'SD_S8_unreviewed':True,'isoGGPP_C1_E_bodybarrier':5.5,'isoGGPP_C1_E_graphicbarrier':5.4,'isoGGPP_C2_D_barrier':21.1,'isoGGPP_cascade_deltaG':-49,'compound5_structure_unresolved':True,'natural_GGPP_full_two_step_not_directly_traced':True})
z=json.loads((d/'codex-live-zotero.json').read_text(encoding='utf8'));print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'live_title':z['data']['title'],'live_DOI':z['data']['DOI'],'images':[x['file'] for x in images]},ensure_ascii=False))
