import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'T83FD38L';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Scheme 1',1,[320,344,551,672]),('Scheme 2',2,[44,80,273,198]),('Scheme 3',2,[42,215,279,411]),('Table 1',2,[295,85,540,247]),('Table 2',2,[295,273,540,565])]
gaps=['Three fullmainpages text originalpagesread andviewed; threecompleteSchemes twoTables includingTablefootnotes; no originalrawNMRMSHPLC nor SI;refs19notallprimary independentlyread','TwoauthorsJohnElixJudithWardlaw ANU RapidCommunication57:681683 DOIprinted receivedJan4finalMar152004 ZoteroJuly7notprintedonline verifiedlive200','MaterialJ A Elix3643 Aug141977 CANB BlackMountainCanberra one sample not2004collection or specieswidequant','5.2gdryextract14.8mgpigmentosin5mgskyrin calculated.2846and.09615percent isolatedmass nottrueabundance or extractionrecovery;major/minor qualitative','Mass546.1534calculated546.1526C30H26O10 error1.46ppm reportednumbersnotremeasure;15carbon resonances support symmetry notaloneC6 linkage','Scheme3gHMBC methylC3two andC4threebond relations authoractualschematic notindependentrawcrosspeakresolutioncheck','Table1H6absentH8remaining andTable2C6type support6,6 linkage;comparative4onlysemivioxanthinhalfnotwholemolecule; differentCDCl3DMSOsolvents andfootnoteassignmentsreversed retained','Bodytenaromaticmethines wording overgeneralized Table2 hasquaternaryCO;H5upfield6.23vs6.83 versusdeshieldingwording notsilentlyassigndirectionmechanism','Rotationminus7.1 c.03EtOAc not absoluteR/S orenantiopurity; authorC3C6chiralityexplicitunknown aromaticC6 couplingsite not tetrahedralcentre no ECDXraychiralHPLC','ProposedsemivioxanthinphenolicradicalC6orC8coupling nottested enzymegeneticslabeling; lichenpartnercelloriginunknown; noPKSgeneassignment or bioactivity assays','KnownUVlibrarygreater99.9correlationnotpigmentosinpurity; newcompoundhomogeneityHPLC1HNMR author qualitative noquantpercentage','EIMSreported547Mplus1 59 vs5465 unusual intensity retained no reassignmentMplusH or inventedfragmentmechanism rawunavailable','ARC support no grantnumber noclearCOI nohumanreview classificationdeferred Csiropublisher2004']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI authors ANU57:681-683 three pages liveZotero200','paper_type':'research','source_article_type':'Rapid Communication','title_zh':'地衣pigmentosin A的双萘并吡喃酮连接证据与立体化学缺口','filename_title':'地衣pigmentosin A的双萘并吡喃酮连接证据与立体化学缺口','journal_short':'Aust J Chem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
