import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'K3AA2KIP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Scheme 1',2,[52,43,559,255]),('Scheme 2',2,[52,260,304,399])]
gaps=['All two main pages full text and original images read; two complete Schemes all compounds1-22 branches arrows reagents labels; SI notattached notread rawNMR plasmid or detailed culture notindependentlyverified;13numberedreferences notallread','LiveZotero200 sixauthors DOIprinted JACS12930:9304-9305 Communications receivedMay222007 webJuly112007 versusZoteroAugust1date preserveorigin','Actual CH999 engineered aromaticpolyketide system notdirectvalidationotherfungalproducts; previous WJ85 WJ35 citedworks notnew measurementsallScheme1 intermediates','WJ78compound15reported150mgL C19H12O7 m/z375.0462Na delta1.9mmu original; standardmonoisotopiccalc375.047523 delta1.323mmu notreplaceoriginal or remeasure','NMR C11delta151 standardester/pyridonecomparison author statement SIunread no independentHMBCreprocessing','OxyD omission no detectable15 underreportedconditions detectionlimit replicatesnotgiven notabsolutezero; function necessity notdirectC19carbon or nitrogen tracking','Protectionfromdecarboxylation proposed no labeledcarbon or timecourse; intermediate12dehydrationcompetition notquantkineticmeasurement','Model20 deprotection then21 inaqueouspH7.4 supportsamideelectrophilicfeasibility; RaneyNi duringdeprotection no proof allcatalytic contributions excluded; modelnotexact14','Scheme2 20to21 step91percent versusphenolamidedeplacementquant wording differentcounting;21to22quant notoverall yield','WJ1505reported50mgL TcmN driven differentregiochemistry not150to50sameproductoptimization; ratio3 notengineeringgain','Pannorin HMGCoAreductase activity priorreference notWJ150 bioactivityassay; OxyDlike otherclusters onlyhypothesis no universalbenzopyrone mechanism','No rawNMR no biologicalreplicateCI orP values; UC CRCC NSF CBET0545860 Syracuse Shimadzu funding noexplicitCOI humanreviewfalse classificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI six authors JACS129:9304-9305 two pages liveZotero200','paper_type':'research','source_article_type':'Communication','title_zh':'芳香聚酮中暂时酰胺化与苯并吡喃酮成环的证据','filename_title':'芳香聚酮中暂时酰胺化与苯并吡喃酮成环的证据','journal_short':'JACS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex two full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
