import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'NEFNRZLY';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',2,[42,382,551,740],'原文 Fig. 1：完整早晚期通路，全部结构、箭头、碳编号、a–g 功能图注'),('Figure 2',3,[42,620,551,740],'原文 Fig. 2：完整拟议氧杂环丁烷机制、三种结构、箭头和图注')]
gaps=['Historical2001narrative review notcompletecurrentminimalgenes/currentindustrialclinicalguidance','DOIfromZotero matchingprintedPIInotpublisherverified','ReadallsevenPDFpages andalltwoFigures; citedoriginalpapersrawdatastatscurrentaccessionsnotreviewed','Five specificclonedgenes plusGGPPsynthase; firstC5hydroxylasecDNAexplicitlynotisolated then','PDFvisualunits TS3microM TAT4.2/5.5microM DBAT10/8microM vsbenzoyl0.64/0.30mM; text extraction mM incorrect forfirstthree','ORFpredictedprecursorversusnativeenzyme massesdifferenttargetingcontext; pseudomature60notnaturalexactcleavage','GGPPRNAinductionnotprotein/fluxorTaxolyield proof','Tenbetahydroxylaseinitialspecificitynotallsubstratesabsolute;microsomalcompetingP450','Taxane2benzoylsemisyntheticsubstrate notuniquelyprovennaturalintermediate;acetylCoAlowernotzeroactivity','HXXXDG catalyticHis crosssystemcitations Carbini/Hershcholineacetyltransferase Brownratcarnitine notdirectTaxusallthree mutagenesis evidence','Fig2postulatedoxetane notreconstitutedcompletepath','Oxygenorderabundanceinferred C2/C9 orderuncertain;dozengenesapproxnotfixedcompletecount','PDF4one4(5)acetatewordingversusFig1/other4(20) retainedinconsistency','Referencebibliographydatesandclinicalclaimsnotindependentlychecked; noAIauthorclaim']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':c,'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,c in spec]
draft={'identity_matches':True,'identity_reason':'PDFtitleauthorsPhytochemistry5820011–7verified;PIImatchesDOIsuffix but DOI notindependentverified','paper_type':'review','title_zh':'紫杉醇已克隆基因与反应功能的2001年证据边界','filename_title':'紫杉醇已克隆基因与反应功能的2001年证据边界','journal_short':'Phytochemistry','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex direct original text and page reading'})
images=[]
for l,p,b,c in spec:
    out=d/('NEFNRZLY-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':images},ensure_ascii=False))
