import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'DUAG3WN5';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[49,56,545,321]),('Figure 2',4,[49,55,545,650]),('Figure 3',5,[49,56,545,677])]
gaps=['Nine main pages read and viewed, three complete original figures, no main table; cited primary studies and their SI not independently read','Single-author narrative Review; no search strategy, inclusion criteria, new datasets or meta-analysis','2024 online May26 versus Zotero September retained; historical claims not verified as current2026','Nine and thirteen enzyme baccatin III sets versus seventeen enzyme complete paclitaxel distinct studies and count definitions; do not sum schematic names to invent universal set','TOT CYP725, CYP725A55, bifunctional CYP725A4 and dioxygenase routes not presumed universally interchangeable','CYP725A22-1 and CYP725A37 author aliases from different primary studies; sequence identity not independently verified','Taxadiene103mgL yeast1gL Ecoli100ugpergFW plants crossstudy not matched; plant FW cannot convert to volume','BaccatinIII50 and155ngperg plantmaterial normalized basis not independently checked; ratio3.1 arithmetic only not causal superiority','Structure figures schematic not substitutes for independent NMR standard chromatography confirmation','Green production aspiration no life cycle or technoeconomic assessment; cell factory pathway proof not industrial readiness','Tissue expression supports network interpretation not same-cell simultaneous flux; promiscuity not quantitative branch loss','CCBY4 NIH5R01AT010593-03 NSF2312181 no competing interests human review false classification deferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图及图注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI single Philipp Zerbe UC Davis review aBIOTECH5:394-402 nine pages live Zotero200','paper_type':'review','source_article_type':'Review','title_zh':'紫杉醇通路新酶发现与动态代谢网络的生产边界','filename_title':'紫杉醇通路新酶发现与动态代谢网络的生产边界','journal_short':'aBIOTECH','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex full nine pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
