import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'FZARD87N';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[314,255,557,367],[]),('Figure 1',2,[49,58,559,437],[]),('Figure 2',3,[49,58,559,562],[]),('Figure 3',4,[314,156,559,545],list('AB')),('Table 1',4,[314,550,559,673],[]),('Figure 4',5,[49,58,295,249],[]),('Figure 5',6,[49,58,559,613],list('AB')),('Figure 6',7,[49,58,559,540],list('AB'))]
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':next((x['caption'] for x in rec['figure_candidates'] if x['label']==l),'原文摘要图'),'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a in spec]
gaps=['Readall9formalmainpages notSI despitepreparedsupplementflag; SI/HRMSraw/genes/citedfunctionalpapers/calculationinputs notread','PDFPublishedAug15 vsZoteroAug26; OUCT/OUTCTtypo andS samsunensisFigure6 notspeciesverification','Isolation38Lmethods vs20Lresults unresolved','SMARTtop25similaritynotidentity; HSQCdoesnotdirectlyobserveunprotonatedketalC needHMBC; actualrawspectraunread','Compound1printedobserved808.4933calculated808.4636 gap36.7363ppm notsilentlycorrected','5/6neutralprintedC41H62NO10 [M-H]727.430096 not713.4265; formulawithoutN713.427022 masscompatible butrawnotverified','Compound4C23ketoversustext4/5methylketal contradiction actualFigure2ketofor4','JBCArelative17RversusKR17S; auxiliaryenzymeexplanationunvalidated','FullmirrorcandidateconfigurationsinTable1 ordinaryachiralNMRcannotindependentlyselectenantiomer;DP4differencecouldsampling/reportingnotresolved','DP4energywindow10kcal/molmethod vs<10kJ/moltablefactor4.184; conditionalprobabilitynotglobaltruth','NOEusedpreconstructionandassessment notwhollyindependent; absolute2–6partlybiosyntheticanchor;NMR/ECDnotrerun','hexcandidate/previousheterologousexpressionnotcurrentwholepathconfirmation; enzymeversusspontaneousDAhypothesisnotdirectlyproven','Methanol/wateracetalization/proposedisomerization artifactoriginnotallroutesexcluded','MIC3.1threeGpositive1;vancomycin1.6–6.2range noindividualassignmentwithoutSI;notallbetter','Antibacterialn/errors/CI/statisticaltests/mainMICthreshold notclearlyreported; nocytotox/invivo','Gnegativeinactive25ugmLonlytestedstrainsnotallbacteria;missing3/4/6activitiesnotfilledzero']
draft={'identity_matches':True,'identity_reason':'Formal9pageAnalChem97 18075–18083 titleDOIauthorsmatch','paper_type':'research','title_zh':'Samsumycins发现策略与构型证据边界','filename_title':'Samsumycins发现策略与构型证据边界','journal_short':'Anal Chem','category':None,'related_categories':[],'classification_reason':'全部笔记完成后归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex directsource reading without externalmodel'})
images=w.crops(rec,draft,d)
with fitz.open(rec['main_pdf']) as doc:
    for i,(l,p,b,a) in enumerate(spec):
        out=d/('FZARD87N-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images[i].update(file=str(target),sha256=sha,bbox=b)
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
