import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'JH9J9NXX';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[54,20,555,353],[]),('Table I',5,[298,552,556,714],[]),('Figure 2',6,[310,20,556,232],[]),('Figure 3',7,[40,20,285,389],['A','B','C','D']),('Figure 4',7,[298,166,556,710],['A','B']),('Figure 5',8,[54,294,300,709],['A','B']),('Table II',8,[310,484,556,715],[])]
gaps=['All11mainpages textread originalpagevisuallychecked;all5Figures2RomanTables covered; noSI used','AY571340 accession sourcequoted notlive database checked;singlecopySouthern data notshown notallTaxusgenomes proof','Identity andsimilarity percentagesdistinct;717aa2154ntORF vs2941cDNA','NADPHKm17.8+/-2.9uM oncytc surrogate nottaxoidKm nor measured electroncouplingpercent','TableIh-1 perP450mol versusTableII nmol/h/mgtotalprotein no conversion without data','Ratb5 Sf9reconstitution notTaxusb5 yeast production;plantCPRsourcecomparisons rawdata notshown','Figure2 12hexposure10minutes later30seconds cannotcrosscompareintensity;Figure2 *2HA versusFigure4 *2noHA labelcontext retained','Figure4A1aa41HA vsA2aa56noHA confounded;B1B2samelength cleaner tagcomparison','CPR truncationmembraneassociation notproven directP450 recruitment noabsenceP450solublesearch','TableII10beta7fold notTaxoltitre;13alpha16.1/18.4/17.7 no reported gain no exactP independentbiolnCI','13alpha instability andendogenousCPRsaturation hypotheses notdirectmeasurement;P450immunodetection notallfunctionalprotein','Allmainfigures complete no fullpathproduction NADPHstoich ROS leakcoupling measured; futurewholecellfeed notcompleted']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表、图注与脚注','panels':a,'pages':[{'page':p,'bbox':[b[0]/594,b[1]/787,b[2]/594,b[3]/787],'dpi':300}]} for l,p,b,a in spec]
draft={'identity_matches':True,'identity_reason':'Main11pagePDF title authors journal89(5)588-598 DOI10.1002/bit.20390 matched original pages','paper_type':'research','title_zh':'红豆杉CPR与紫杉醇途径P450在酵母共表达的功能证据','filename_title':'红豆杉CPR与紫杉醇途径P450在酵母共表达的功能证据','journal_short':'Biotechnol Bioeng','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexdirectmaintextandoriginalpageinspection'})
images=[]
for l,p,b,a in spec:
 out=d/('JH9J9NXX-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':'原文 '+l+'：完整图表、图注与脚注','page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'TableI_CPR':210/65,'TableI_b5_withCPR':340/210,'TableI_both':340/65,'TableII_10beta_full':164/23.4,'TableII_10beta_trunc':158/23.4,'TableII_13alpha_full':18.4/16.1,'TableII_13alpha_trunc':17.7/16.1,'note':'Ratios of reported means; not Pvalues or confidence intervals'})
print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
