import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'N4BF65W4';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',2,[52,89,511,271],[],'Figure 1. Outline of the Early Steps of Taxol Biosynthesis. GGPP cyclization to taxa-4(5),11(12)-diene followed by P450-mediated formation of taxa-4(20),11(12)-dien-5α-ol.'),('Figure 2',3,[73,89,533,423],[],'Figure 2. Deduced Amino Acid Sequence Alignment of Taxoid Hydroxylases. T10H, T13H and S1/T5H; black boxes identical in all three sequences, gray in two.'),('Figure 3',4,[52,89,271,524],list('AB'),'Figure 3. Substrate Binding of Taxadiene Isomers. A: 4(20) isomer Ks 4±1 μM; B: 4(5) isomer Ks 6.5±1.5 μM. Recombinant S1-enriched microsomes, 200 pmol P450. Complete original two plots and caption.'),('Figure 4',4,[291,89,511,543],list('AB'),'Figure 4. Kinetic Evaluation of Taxadiene Isomers. Filled circles 4(20), open circles 4(5). A recombinant S1 50 pmol; B total native P450 about 50 pmol. Original caption averages 21.5 μM/135 and 36 μM/100 differ from body system-specific parameters; preserved and explicitly distinguished.'),('Figure 5',5,[73,89,534,378],[],'Figure 5. Proposed Mechanism for Cytochrome P450 Taxadiene 5α-Hydroxylase. Proposed C20 or C5 hydrogen abstraction converges on allylic radical 8 and 5α oxygenation. No direct intermediate detection; original complete structures and caption.')]
for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('N4BF65W4-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'Original printed title, four authors, Chemistry & Biology 11 379-387 2004 and DOI match live Zotero; all nine original pages visually reviewed.','paper_type':'research','title_zh':'紫杉二烯5α羟化酶克隆与双键迁移机制','filename_title':'紫杉二烯5α羟化酶克隆与双键迁移机制','journal_short':'Chem Biol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['Figure4 caption averages21.5/36μM correspond arithmetically to recombinant/native parameter means; average definition inadequately explained, body system-specific values retained','Results induced nativeTaxus cells versus methods unelicited T.media hicksii conflict unresolved; clone source T.cuspidata distinct','Minor yeast diol position and structure unknown noNMR; original raw chromatograms GCMS notallshown','± uncertainty definition and complete raw rates notprovided; three pooled catalytic experiments do not establish allfigure culturebatchn','Native totalP450 and downstream polyols not isolatedT5H turnover; Vrel notkcat Ks notKm','Proposed radical intermediate notdirectlyobserved; prior isotope evidence cited rather thannewKIE; nooverexpressionPTXincrease measured','No separate SI available; referenced papers notindependently read in this note'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'ORF_bp':1509,'protein_aa':502,'ORF_codons_including_stop':1509/3,'Ks_4_20_uM':4,'Ks_4_5_uM':6.5,'Ks_center_ratio':6.5/4,'recombinant_Km_4_20_uM':16,'recombinant_Vrel_4_20':120,'recombinant_Km_4_5_uM':24,'recombinant_Vrel_4_5':100,'recombinant_relative_efficiency_ratio':(120/16)/(100/24),'native_Km_4_20_uM':27,'native_Vrel_4_20':150,'native_Km_4_5_uM':48,'native_Vrel_4_5':100,'native_relative_efficiency_ratio':(150/27)/(100/48),'caption_mean_Km_4_20':(16+27)/2,'caption_mean_Vrel_4_20':(120+150)/2,'caption_mean_Km_4_5':(24+48)/2,'native_targetenzyme_quantity_unknown':True,'minor_diol_structure_unknown':True,'no_direct_radical_detection':True,'no_PTXYield_perturbation':True})
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
