import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'UZJ6VLEJ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[332,250,558,390],[],'原文摘要图：完整受体供体数量、结合口袋与右侧糖苷结构'),('Figure 1',2,[50,58,558,624],['A','B'],'原文 Figure 1：完整 78 底物柱形图、全部结构编号、鉴定符号与图注'),('Figure 2',4,[50,58,558,381],['A','B','C'],'原文 Figure 2：全部糖供体和四受体结构、完整配对数据与图注'),('Figure 3',5,[50,58,558,526],['A','B','C','D','E','F','G','H','I'],'原文 Figure 3：完整 A–I 结构、供体模型、功能、色谱、MD 和全部图注'),('Figure 4',6,[50,58,558,558],list('ABCDEFGHIJKLMNOPQRS'),'原文 Figure 4：修正版完整 A–S，包含此前首发缺失的 N 子图、动力学、门控与长图注'),('Figure 5',7,[50,58,558,635],list('ABCDEFGHIJ'),'原文 Figure 5：完整 A–J 晶体取向、三轨迹、全部 MM/GBSA、能量面和五亚稳态、长图注'),('Figure 6',9,[50,58,558,343],['A','B','C'],'原文 Figure 6：完整循环示意、四优化曲线、五色谱及全部图注')]
gaps=['All14mainphysicalpagesreadandvisualQA correctedJan52024version containsFigure4N;publishedfirstDec212023notZoterodate','Englishnaturalproductglycosylationnotusersugarimmuneexcludedcategory;main6figures+abstractgraphic no maintables/schemes','SIcomplete92substrates14negativecontrolsNMRHMBCCOSY spectra/TableS1–S7andcrystalstatsnotread;noindependentallproductassignments','78/92acceptednot78pureOlinkages or78x6fullytestedmatrix;48above80reportednotpeakheightestimate','Figure1starNMR andtrianglestandardidentitynotPsignificance;50structurecharacterizednotequalallNMR','Methods4.13conversionHPLCproductarea/(product+substratearea) notresponsecorrectedmolarconversion orisolatedyield','Methodsalltriplicate n3 independence/errorSDSE/exacttestPnotreported;noinventedbarspercent','Text35flavonoids1–35vsFigure1through34/steroid35 countoverlap retained','DonorlistGDPXylvsUDPXyl methodsfigure andUDPManlabelvsGDPManmethods unresolvednoninterchangeable','Figure3C/Dtextswapped relativeactualCUDPXyl/DUDPGalcaption;modelsdonorsnotfullsugarcrystal','UDPbinary1.86 andtruncated11–474fullactivityclaimSIunread;truefullsugardonormodelsnotcrystal','SugarpreferenceT145V8substrate71.6to93.2 contextnotintrinsicallsubstraterate;glcdrop/regiochange retained','Figure4KMfigure19.4±2.7/29.2±5.3/78.4±9.9µMvsroundedtextmMconsistent;KMnotKD;nativesubstratehypothesisonly','Figure4A–E4Dimage39vsbody/caption40;4OcaptionF139vsstructureF193 retained','Pocket1176Å3 widths12.4depth17.9experimentalstructuralgeometrynotproofuniversalrecognition;gatekineticsinferrednotdirectrate','H25/D123functionalimportance andSN2likelikelynotdirectcapturedtransitionstate','NoTris sameposeauthorSIcontrol claimnotallcrystalconditionsruledout','MD1000ns3systems plus200nssugardonor differentanalyses;Nacmanuallyadjusted/docked;noindependentreplicate/convergenceverified','MMGBSA200frames400–500ns notmeasuredKD;RMSDnotfullsamplingproof;4.8Åpose notcompletedchemistry','MetaMDstateI-10.6V-2.1difference+8.5versusauthorbarrier-8.5;stateenergychange notvalidatedTSbarrier;allbiasreweightconvergenceunread','Figure6Babcaptionorderreversedtoaxes;Figure6C36/36avsbody35 preservednotinventobject','UDPGlcfree=noexternallyfedUDPGlcnotabsentsystem/noUDP;donorpoolcyclingcountnotquantified','Economicdesignnotmatchedcost/fullscale/isolationyield;noimprovedglycosidepharmacologyproved']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'Directreadall14ACSResearchArticle title11authors475–488DOI Jan5correctedversion containsFigure4N','paper_type':'research','title_zh':'UGT74AN3广谱糖基化与底物翻转模型的证据边界','filename_title':'UGT74AN3广谱糖基化与底物翻转模型的证据边界','journal_short':'ACS Catal','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft)
draft['source_gaps']=[x.replace('DonorlistGDPXylvsUDPXyl methodsfigure andUDPManlabelvsGDPManmethods unresolvednoninterchangeable','DonorlistGDPXylvsUDPXylmethodsfigure unresolvednoninterchangeable;300dpifigureManactuallyGDPManconsistentmethods') for x in draft['source_gaps']]
w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Direct Codex fullmaintextreading14pages and sourceconflictchecks'})
images=[]
for l,p,b,a,c in spec:
 out=d/('UZJ6VLEJ-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-metamd-arithmetic.json',{'state_I_kcal_mol':-10.6,'state_V_kcal_mol':-2.1,'V_minus_I_kcal_mol':-2.1-(-10.6),'author_text_barrier_kcal_mol':-8.5,'boundary':'StateenergyarithmeticonlynotTSactivationbarrierindependentlyverified'})
print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images)},ensure_ascii=False))
