import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'UABT8U4R';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',2,[47,85,268,412],list('AB'),'Figure 1. Taxol and an Example of a Second-Generation Taxol Analog. A Taxol; B C10 propanoyl and sidechain furanoyl substitutions. Prior-study analog, notnewbioactivity data.'),('Figure 2',2,[47,528,507,759],[],'Figure 2. Biosynthetic and Synthetic Routes to Taxol Analog Precursors. DBAT route a and chemical route b, complete original structures and caption.'),('Figure 3',3,[105,85,327,330],[],'Figure 3. Radio-HPLC Analysis of Products Catalyzed by the 10β Acetyltransferase. DAB, Bacc, PDAB, BDAB. Original caption8.53min differsbody/methods8.63min; preserved.'),('Table 1',3,[105,516,566,755],[],'Table 1. 1H-NMR data for authentic10-DAB and enzyme-derived baccatinIII and10-PDAB. Complete allrowsfootnotes300MHz300KCDCl3; noenzymaticBDABNMR.'),('Figure 4',4,[47,85,268,388],[],'Figure 4. Comparison of Biosynthetically Derived Butyryl-10-Deacetylbaccatin III to Authentic Standards. 13-BDAB6.35,10-BDAB6.51,7-BDAB8.56min;60:40acetonitrile/water.'),('Figure 5',5,[344,85,566,330],[],'Figure 5. HPLC Analysis of In Vivo Production of Baccatin III from10-DAB. TAX06 solid versusTAX02dashed;7.69min30:70acetonitrile/water. FeedingconversionnotdenovoPTX.')]
for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('UABT8U4R-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'PrintedDOI,titlethreeauthors Chemistry&Biology13 309-3172006 matchliveZotero despitepreparedautomatic titlefalse dueβ/layout. All9originalpagesreadandvisuallyverified.','paper_type':'research','title_zh':'DBAT供体特异性与整细胞乙酰化','filename_title':'DBAT供体特异性与整细胞乙酰化','journal_short':'Chem Biol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['Reported100ml250μM20percent50nmol16hr inconsistent;methods100μMfeed18hrexpression; preserve notsilentlycorrected','Figure3captionBDAB8.53±.01min versusbodyandmethods8.63min; differentFigures use40:60 60:40 30:70HPLCconditions','EnzymaticbutyrylproductnoNMR <.1mg; syntheticstandardsNMR notenzymaticproduct NMR','Nativeprinted Vmax/Km units s-1 nM-1 andenzymenormalization inadequate; alternateconstantsinferredfromcompetition andUVresponseassumption notindependentkcatKm','Partialpurification nofullhomogeneity;independentrepeatsCI P detectionlimitsnotdefined percondition','IntracellularacetylCoA estimatedviaextractactivity ratherdirectmetabolomics;90percentmediumfractionnotmassrecoveryoractiveexportproof','Methodfragmentneutral-lossnotation notfullyconsistent withMHpositiveiondifferences; ionsretained notfullmechanismassignment','NoSI/rawdatasets orfullreferenced-paperverification; nontestedinvitroantitumorpotency noindustrialdenovoPTX ornonacetylwholecellproduction'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'reported_culture_volume_ml':100,'results_feed_uM':250,'results_totalfeed_umol':100/1000*250,'methods_feed_uM':100,'methods_totalfeed_umol':100/1000*100,'reported_product_nmol':50,'reported_conversion_percent':20,'conversion_from_resultsfeed_percent':50/(25*1000)*100,'conversion_from_methodsfeed_percent':50/(10*1000)*100,'results_time_hr':16,'methods_expression_time_hr':18,'printed_acetyl_specificity':3,'printed_propionyl_specificity':1.6,'printed_butyryl_specificity':.16,'printed_unit':'s^-1 nM^-1','propionyl_to_acetyl_percent':1.6/3*100,'butyryl_to_acetyl_percent':.16/3*100,'acetyl_to_butyryl_ratio':3/.16,'propionyl_to_butyryl_ratio':1.6/.16,'butyryl_Fig3caption_Rt_min':8.53,'butyryl_body_method_Rt_min':8.63,'butyryl_standard_match_other_HPLC_Rt_min':6.51,'enzymatic_butyryl_NMR_unavailable':True,'wholecell_nonacetyl_production_unproven':True})
live=json.loads((d/'codex-live-zotero.json').read_text(encoding='utf8')); print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'live_title':live.get('data',{}).get('title'),'live_DOI':live.get('data',{}).get('DOI'),'images':[x['file'] for x in images]},ensure_ascii=False))
