import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'R2HHGNNE';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',2,[13,38,534,318],[]),('Figure 2',5,[13,38,534,594],list('ABCD')),('Table I',6,[13,38,270,226],[]),('Table II',6,[277,539,533,686],[]),('Figure 3',7,[13,38,270,592],[]),('Figure 4',8,[13,38,534,646],list('ABCDEFG')),('Figure 5',9,[13,38,534,669],[])]
extra={'Table I':'TABLE I. Purification of Taxadien-5α-ol-O-Acetyl Transferase from Induced Taxus Cells','Table II':'TABLE II. Peptide Sequences Generated from the Purified Taxadienol Acetyl Transferase. a By proteolysis with trypsin. b By proteolysis with endolysC.'}
for label,page,bbox,panels in specs:
 pg=doc[page-1];file=d/('R2HHGNNE-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file));caption=extra[label] if label in extra else next(x['caption'] for x in rec['figure_candidates'] if x['label']==label)
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'OriginalPDF title3authorsDOI10.1006/abbi.1999.1609 ArchBiochemBiophys374(2)371-380Feb15 2000 matchesliveZotero;automatic titlefalsemanuallyresolved DOI1999suffixnotpublicationyear.','paper_type':'research','title_zh':'TAT克隆与紫杉二烯醇乙酰化功能验证','filename_title':'TAT克隆与紫杉二烯醇乙酰化功能验证','journal_short':'Arch Biochem Biophys','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['NativeTcanadensis protein andTcuspidata cDNA peptides91percentidentity notfullproteinidentity;causeofdifferences inferred','Method approx100pmol and50ug mismatch10fold using50kDa;originalpreservednotresolved','20percentconversion independentn errorbars P CI rawintegration notreported;noinplantaoverexpressionPTXtiter','H164mechanism inferredfromotherenzymes mutagenesisnotperformedonTAThere;noexperimentallocalization','Original2tables omittedbyautomaticfigurecandidate discovery manuallyaddedcomplete;GenBankversionnotdownloaded'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'initial_total_activity_pkat':302,'final_total_activity_pkat':10,'activity_recovery_percent':10/302*100,'initial_protein_mg':1230,'final_protein_mg':.05,'protein_remaining_percent':.05/1230*100,'protein_removed_percent':(1-.05/1230)*100,'reported_fold_purification':800,'reported_purity_approx_percent':95,'ORF_nt':1317,'reported_aa':439,'ORF_codons':1317/3,'reported_100pmol_protein_mass_ug_at_50kDa':100e-12*50000*1e6,'reported_mass_ug':50,'mass_inconsistency_factor':50/(100e-12*50000*1e6),'native_peptide_identity_percent':91,'native_peptide_identity_not_fullproteinidentity':True,'genetic_PT X_increase_measured':False});print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
