import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'V6YKJJBL';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[43,86,552,274]),('Figure 2',2,[43,525,552,741]),('Figure 3',3,[43,566,552,740]),('Figure 4',4,[43,86,552,546]),('Figure 5',5,[43,319,552,740]),('Figure 6',6,[43,86,552,307]),('Figure 7',6,[43,450,552,740])]
gaps=['All9originalmainpagesreadviewed Figures1-7 complete inclsidelongcaptions fullspectraaxes modelingandlabeledsubstratescheme noTable SI rawFIDMSmodels unavailable', 'Identity title9authors7issue12pp969-977 printedPIIS1074-5521(00)00046-6 matchesliveZoteroDOI autoDOIfalse notprintedDOI; publishedOct302000 vsZoteroDecissue', 'M60truncatedenzyme as cited nofullsequence independentlyverified notassumed60removed nor78deletion; proteinpurityover96percent', 'C4Rsubstrate84molpercentD vsC10over99molpercent chemicalpuritychirality distinct finalR:S91:9 assumptionepoxidation earlierD95:5 notidentical finalenantiopurity', 'GGPP C10 intermediateC11 productC7 numberedmapping; GGPP C4 productC5 terminatingbetaHloss notsamecarbonnumber', 'Unlabeledmajor94minor4(20)~5negligible3(4) labeled77.6 11.1 9.2sum97.9notnormalized missing2.1unexplained;overallrate~half relative4(20)increase notabsoluteyielddoubling', 'ApparentKIE2.1termination2.0migration notintrinsicmicroconstants no independentrepeatnSDCI P rawGC integration unavailable84percentDmixedinputnotcorrected', 'MSp272top273Cfragment122to123 labelretentionover99 author no rawMSrecalc; ~100microgGCestimate vs10microgpurifiedNMR notexact10percentyield', 'Figure4aunlabeledbmarkedH7alpha1.76lost H7beta1.19collapseJ6 H5excitation5.38 65ms DPFGSE; Figure5NOESY400ms unlabelstandardnotlabeled10microg2D', 'AM1MacSpartan+1C12cationminimized~2.2Angstromdistance notenzymeenvironmenttransitionstatebarriercomputed nofullcompetitivefreeenergy or directallenzymesidechainmediation exclusion', 'Fig7andmethodlabelC4substrate8 whileFig2substrate7 andFig2isomer8 conflict preserved Fig7ref37notinreference list notpatchedoriginal', 'Fiveprocesssummary firstC1andC15stereodata unpublished notall independentlyverified noallTaxolproduction complete humanreviewfalse classificationdeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original title nineauthorsvolumepagesandPII matchesliveZoteroDOI despite unprintedDOI','paper_type':'research','source_article_type':'Original research','title_zh':'TS环化中的氢迁移立体化学与同位素敏感分支','filename_title':'TS环化中的氢迁移立体化学与同位素敏感分支','journal_short':'Chem Biol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex all9originalpagesreadviewed atommappingalphabetaresolvedfromoriginal isotopebranchrelativevsabsolute andAM1evidenceboundary preserved'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
