import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'DEPIFGZ4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Scheme 1',1,[355,354,522,505]),('Table 1',2,[53,45,295,323]),('Figure 1',2,[53,603,557,761])]
gaps=['All3mainfullpages textoriginalimagesread threecomplete300dpicrops including firstpageunnumbered1RMe2RHstructures designatedScheme1noteonly fullTable1all21rowsfootnotes fullFigure1bothasymmetricmoleculeslabels;no CCDCcoordinateSI rawNMRbioassays12referencesnotallread','LiveZotero200 sixauthorsCuetoJensenKauffmanFenicalLobkovskyClardy UCSDCornell DOIprinted JNP6411:1444-1446ReceivedMay302001 webOct192001 versusZoteroNov1','FungusCNL3651996RosenvingeaBahamas morphPestalotiaundescribedspecies bacteriumCNJ328gramnegative FAMEunidentified notMRSA/VREwhichareassaytargets','Mixedculturepositive standardindividualcontrolsnotdetected plusfunguspureexternaltriggerlowyield qualifiesabstractonlymixed notabsolute dependence;funguscapability notruleout allbacterialcontributions inmixture','Bacterialextractcellfreebrothnegative notexcludeallchemicalsignallabilitycontactlowlevels;competitiveinductionhypothesis no identifiedBGCregulatormolecule receptors;background400foldotherliterature notthisdata','C21H20O6Cl2EI438440442 isotopepattern HRFAB439.0731calc439.0715delta1.6mmu3.64ppm DBE11 notalonepositionproof','NMRfirst-ringisopentenyl aldehyde supported secondringHMBCinsufficient authorXrayresolves;Table1C13202.4versusbody204.4 methoxy61.9versus61.6 C21HMBC145.9vsC10145.5 preserveconflicts','Bodytwoolefinic103.2/123 plus12quaternaryaromatic terminology doesnotmatchTableH4on103.2 sidechainC17132.1 no reviseddata invented','Figure1crystalP21c173KtwoasymmetricmoleculesR6percent intensity2sigma;Hbond2.622.522.78A crystalcontacts no solutionoccupancyrotationalenergyorstableatropisomer evidence;lowchemicalshifts wordingvsOH10-13ppm preserveactualdownfield','60mgfrom20nominalL gives3mgL recoverednotmeasuredtiter extra bacterialvolumeandlossunknown no productionoptimization','MRSA37ngmL.037ugmL VRE78ngmL.078ugmL specifictests strainsdetail nCI currentstandardsnotreported noMBCmechanism clinicalanimal data','NCI60meanGI506uM notcell50death ornormalcelltoxicity;HCT116guidedisolation notallfractionsMRSAguided;GI50dividedMICnottherapeuticindex','Analogue2patenttestosterone5alphareductase notcompound1assay orsecondnewisolate;NIHCA44848CA55060CA24487 NATOSpainfellowship noexplicitCOI humanfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI sixauthors JNP64:1444-1446 three pages liveZotero200','paper_type':'research','source_article_type':'Note','title_zh':'Pestalone共培养发现与晶体结构和体外活性证据','filename_title':'Pestalone共培养发现与晶体结构和体外活性证据','journal_short':'J Nat Prod','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
draft['figures'][0]['caption']='首页未编号结构图：pestalone 1与专利类似物2；Scheme 1仅为本笔记编号'
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
