import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'GSGUZKME';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[48,64,552,518]),('Figure 2',4,[60,65,564,629]),('Figure 3',5,[48,64,552,570]),('Figure 4',7,[48,64,552,701]),('Figure 5',8,[60,64,564,669]),('Figure 6',10,[60,64,564,605]),('Figure 7',11,[48,64,552,732])]
gaps=['17mainpagesreadandviewed7complete300dpiFigures SI figures tables1to10actualunread rawMSscRNAmatrixPRJNA909435notdownloaded nohumanreview referencesnotindependentlyread','SpatialMS20umpositive150to1200twobiorepsmasserror10ppmLibraryannotationnotallstandardsstructuresconfirmed3510pixels3506featuresdifferentobjects','DiscussionPM947ResultsFigure974conflict;Fig2selected4taxoidsnotpaclitaxelabsoluteconcentrationtransportnotruledout','8846cellsnotindependentplants35874meanreads2352mediangenesResultsmeanwordconflict36808genes15552cluster-enriched15clusters11Arabidopsismarkersseveralunannotated','Figure3HcaptiontSNEaxisUMAPCellRanger6.1.1vs3.0Monocle3vs2functions mitochondrial5vs20percentdoubletlogicunresolved noanalysisrerun','Leafmesophyllsubclasses16810910379total459CD182pseudotimenotrealageflux;Figure4geneclasscountsResultsconflictsnoenzymeassayforallels','CYP487CYP72574candidatecoexpressionnotreactionidentityFigure5EactualheatmapcaptionKEGGenrichmentconflict','27TF54promotersnetworkpredictednotallvalidatedfiveWRKYonly4IDslistconflict','SixTFEMSAreporterMYB17TSandbHLH46GGPPSrepressWRKY12DBATWRKY31SQEERF13C3HGT2CHSactivateGT2CHSEMSApanelEproteinGSTGT2butarrowbHLH68conflict','GSTpGEXresultsversusHisNimethodproteinidentityconflictEMSA3technicalreporter3biologicalnoTaxusnativeChIPmetabolicinterventionyieldnoKd;deferclassification']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'17pages title16authorsPlantCommun4:100630DOI liveZotero verified','paper_type':'research','title_zh':'红豆杉叶片空间代谢与单细胞图谱及六组转录调控候选的证据','filename_title':'红豆杉叶片空间代谢与单细胞图谱及六组转录调控候选的证据','journal_short':'Plant Commun','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded17pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('GSGUZKME-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
