import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'XPQ84JII';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[40,60,559,248]),('Figure 2',2,[40,358,559,754]),('Figure 3',3,[34,54,560,294]),('Figure 4',3,[34,535,560,754])]
gaps=['Readviewedall7physicalpages includes5mainpages2fullMethodspages allFigures1-4complete captionsbothcolumns panels3ab4abc; no mainTable SIunavailable', 'Title5authorsNature469116-120 firstpageDOI10.1038/nature09628 verifiedliveZotero issueJan62011 onlineDec152010 receivedAug6acceptedOct292010', 'ActualM107-TXS-CHT crystallizationconstructno measurabletaxadieneGCMS;priorM60M79active prior93 113126inactive cited notcurrentparallelassays', 'ConstructboundaryMethodsSummary107deleted vsdetailedR107startM107plusM79degradation29 residues originalnumberingkept notfixed byinventedsequence; native862roughly80transitnotidenticalM107', 'ACP1.82A FGP2.25A RRfree.167/.205and.187/.250;PDBACP3P5P FGP3P5R depositedcoordinatesstructurefactorsreported notindependentlydownloaded rerefined', 'Threealphadomains CterminalS553V862 NterminalM107I135plusS349Q552 insertionS136Y348;classIIvestigialnoDXDDoractivecavity notbifunctionalTXS', 'FGPsubstrateanalogue ACPnotTXSreactionintermediate despitebinding no ligandturnoverproof;omit3sigma notactualcarbocationtransitionstate', 'MgA/C D613D617 MgB N757T761E765 localgeometrynotallmutationalcausalityverified', 'ACP745/764 FGPmonomers746/764736/764 disorderedNterminaltagloops notallnativeatomsobserved;openTXSstructureunavailable', 'Figure4closedmodelgraftedBPPSNterminusJKloop usingNAMDCHARMM22gasphasemin10000steps mostheavyatomsfixed notlongMDorQM/MM reactionfreeenergyproof; VOIDOO1.4Amesh vs0Avolumes dummyboundaryapproximation', 'Taxadiene20percent4(20)historicalactiveenzyme cited notinactivecrystalconstructproductratio; exactvolumesinunavailableSITable2 notdigitized fakecorrelation', 'PPiH5betaalignment oneof2productorientations Y688andotherpolarbasealternatives remain finalbasehypothesis notproven nofullcausalancestorresurrection', 'NIHGM56838GM13956CA55254 andscholarshipfinancialCOInoneexplicitreported;humanreviewfalse classificationdeferred rawdiffractionSIunavailable']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original title fiveauthorsNature469116-120 and firstpageprintedDOI verifiedliveZotero','paper_type':'research','source_article_type':'Original research','title_zh':'TXS三域结构与催化闭合模型','filename_title':'TXS三域结构与催化闭合模型','journal_short':'Nature','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex all7mainPDFpagesincludingMethodsreadviewed fourcompletefigures confirmed experimentalstructure versusgraftedclosedmodel andinactivecrystalconstruct versushistoricalactivity'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
