import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'YLHKWJ9W';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',2,[33,481,562,724],'原文 Fig. 1：完整双模块及所有结构、下游背景和两栏完整图注'),('Figure 2',3,[211,145,562,723],'原文 Fig. 2：完整 A–E 响应曲面、32 菌株构型与图注'),('Figure 3',4,[211,391,562,725],'原文 Fig. 3：完整 A–D 产物、生长、乙酸、累计甘油图例与图注'),('Figure 4',5,[33,369,383,725],'原文 Fig. 4：完整 A–C 融合示意、筛选、时间响应、当量坐标和图注')]
gaps=['PDF1downloadcover PDF2–5main PDF6topreferences DOI; PDF6bottomdifferentAu/waterpaperexcluded','AllfourFiguresandallmaintextread SOMmethodsS1–11TablesS1–4/rawdata/citedstudiesnotread','MEP8genecontext only4modulated; strengthcalculatedarbitraryunitnotabsoluteproteinflux qPCRSIauthorreport','Fig2A/Bsame16constructtwoanglesnotindependentreplicates;total32 finitecombinatorialmaxnotuniversalglobal','Geneorder2–3foldand2000/15000foldspecifichistoricalcomparisons notallconditionsmatched universal','Lowerburdeninterpretation confoundedvector/promoter/integrationdifferences notdirectresourceproof','Indoleexternalintervention supportsproductioninhibition beyondcorrelation; dose>100contextbound rawcurvesSOMunread mechanismunknown synergyhypothesis','Figure3reactorsn2 meansSD endpoint174/210/1020mg/L concentrationsnotvolumetricproductivity noP CI','Netglyceroladdednotresidualconsumptioncarbonbalance;yeastextractcarbon overlayandworkingvolumeunresolved','98percentconversion bothalcoholandOCT not98percenttargetselectivity;21vs24smallscale products','58plusminus3 peakalcoholFigure4Ctaxadieneequivalentaxis notindependentpureproductresponsecalibrated; near80hpeak thenlower n2','ExtraP450additionloweroutputindoleincreased balanceexplanationnotsoleprovenburden','EqualOCTatreactor notpaclitaxel/fullyprecisecalibratedtotalproductsum;2400foldyeastcrossstudynotmatched','P450TMregionspredictednotallactualmembranemaps;fusionnotuniversalrequirement','AllremainingTaxolstepsnotcomplete;2010pathwaycounts/genehomologysuggestnotallfunctionalengineered;patentapplicationdisclosed']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':c,'panels':({'Figure 2':['A','B','C','D','E'],'Figure 3':['A','B','C','D'],'Figure 4':['A','B','C']}.get(l,[])),'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,c in spec]
draft={'identity_matches':True,'identity_reason':'PDFcoverandmainDOIauthorsScience330201070–74 matched excludingneighboringarticleonPDF6','paper_type':'research','title_zh':'双模块平衡与紫杉二烯首次氧化的证据边界','filename_title':'双模块平衡与紫杉二烯首次氧化的证据边界','journal_short':'Science','category':None,'related_categories':[],'classification_reason':'全部文献笔记完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex direct original-source reading'})
images=[]
for l,p,b,c in spec:
    out=d/('YLHKWJ9W-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':next(x['panels'] for x in figs if x['label']==l),'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':images},ensure_ascii=False))
