import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'EMJYQLMR';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[51,550,293,744]),('Figure 2',2,[51,251,293,574]),('Figure 3',2,[315,197,557,446]),('Figure 4',3,[51,53,557,373]),('Figure 5',1,[333,249,558,387])]
gaps=['ActualmainpaperfivepagesnotSI althoughattachmentautoisSupplementTrue fulltitleDOI authors9 first3equal Dongcorrespondence CPU OrgLett2024 acceptedFeb19ZoteroFeb21 originalXXXXvolpagesnotinvented', 'Fiveoriginalpagesallread4formalfiguresplusabstractgraphic Figure5notebooklabel originalunnumbered allcomplete300dpi crops', 'NoSIlocal FiguresS1to78 TablesS4to35 originalspectraFIDcalculationsunread authorFAIRPDFZIPavailabilityclaimnotverified', 'Taxadieneplatform20.3plusminus.3mgL nerrornotgiven externallyfedprenylalcohol truncatedpathnotallfromsimplecarbon previous100mgLotherditerpenesnotTaxadiene', 'DL10107controlDL10108CYP701A8 fromrice alteredNterminuscodonoptimized modelnotnativeTaxuspath GCMSnew288288286 products isolated45L12mg7mg5mg nottrueculturedtitersconversionrecoverynotreported', '1C20H32O311.2344Na theoretical311.2345 1S3S8S11S ROESYNMRcalcECD authorreported 2found311.2356Na11RnoessentialROESY reliesNMRcalcECD 3C20H30O287.2361H theoretical287.2369 1R3S8S fullSIunread', 'Naming1structure15hydroxyabeotaxadiene versusmechanism15hydroxytaxadiene 3structure11ketosecotaxadiene vsmechanism11ketosecotaxatriene retaincompoundnumsnotnew4th HMBC H2-10toC10possibletextissueunresolved', 'In vitroentkaurenepositive3alphaOH RhfRedNADPH buttaxadiene2negative withpartnersperoxide solubilityredoxauthorhypothesisnotmeasuredcause', 'Feedingtaxadiene1and2detected 3notdetectedwithtaxadieneor2 no direct2to3proof no purifiedtaxadienereactionreconstituted', 'Dock C18hemewithin5A notactualsite alternativeC13initial authorhypothesis waterquench notisotopeoxygenproof BtoG nottrapped', 'Figure4computedspecificCtoD cationdeltaGbarrier7.2 productminus6.3 radical54.1minus2.3 parenthesesdeltaE56.6product1.2 notdeltaG nocompletemechanismproof no computereexecution', 'AuthornofinancialCOI declared NSFC82073746 others no actualnewdrugactivity noTaxolcompleteproduction humanfalseclassificationdeferred']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注' if l!='Figure 5' else '原文未编号摘要图，Figure 5为笔记编号'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'5pages9authorsOrgLett2024titleauthorsDOIprinted mainpapernotSI verifiedlive200 volumeandpagesXXXX','paper_type':'research','source_article_type':'Research Letter','title_zh':'CYP701A8介导紫杉二烯重排的整细胞证据与计算机制边界','filename_title':'CYP701A8介导紫杉二烯重排的整细胞证据与计算机制边界','journal_short':'Org Lett','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded6pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('EMJYQLMR-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
