import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'4MEWB9MD';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[44,60,552,365]),('Figure 2',6,[44,355,552,713]),('Figure 3',7,[44,60,552,371]),('Figure 4',7,[44,493,291,713]),('Figure 5',8,[44,60,552,694]),('Figure 6',9,[44,60,552,388]),('Figure 7',10,[44,60,552,514]),('Figure 8',11,[44,60,552,491]),('Figure 9',12,[44,60,552,535]),('Figure 10',13,[44,60,552,547]),('Figure 11',14,[302,60,552,352])]
gaps=['All16mainpagesreadandviewed11mainFigurescomplete;actualSIFig1to4Table1unreadrawchromatogramsnotverifiedreferencesnotindependentlyread','10DAB.06to.1432.383fold138.3percentincrease baccatin.04to.164fold300percentincrease taxol.313to1.314.185fold318.5percentincrease authors238400419endpercentnotincrement','10DABOEplusminus.31inbodyincompatibleploterror retainunresolvednotrepairto.031;rawreplicatesnoexactPnoCI','RNAiauthorreportnonsignificantmetaboliteSIunreadnotnecessity;BAPTChIP14.41Y1Hnegative andqPCRnonsignificant preserveconflict TSTFbindingnotshown','Y1HpABAiABAabbreviationmisuseAbAselectionnotabscisichormone;Fig10OElegendversushormonetextconflict;NtabacumlocalizationNbenthamianareportermethodsdistinct','EMSAFigure7lane2labeledWTplusunlabeledmutantcompetitor retainedshift supportsselectivitynotmutantbinding doseunclear reporterCCGTTAtoTACCdeletionnotEMSAidenticalmutant B1affinitynotmeasured','ABREAERBpredictionminus313to319SIunreadnonecessityexperiment;ABA6h8.75MeJA12h8.97downnotcompletepathwayorthogonality','ChIP3.23relativeCDSnotactivationoverexpressedGFPnativebindingnecessitynotproved;noinventedfigurenumerics','TrolliusyunnanensisbodyTaxusyunnanensisreferenceconflict;LgMYB3bodyLgMYB7figureconflictTcMYB29a98.87identitynotnewgenelocusproof','UnitugpergDWnotmgLproductionratebatches;fungal3.26foldfrompriorworknotthisOE']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'16pages title5authorsFrontPlantSci13article804593DOI verified','paper_type':'research','title_zh':'TcMYB29a响应ABA并结合T5OH启动子促进紫杉烷积累的证据','filename_title':'TcMYB29a响应ABA并结合T5OH启动子促进紫杉烷积累的证据','journal_short':'Front Plant Sci','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded16pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('4MEWB9MD-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
