import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'7VG6VM6Z';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Scheme I',2,[38,48,297,285],[],'SCHEME I. Cyclization of geranylgeranyl pyrophosphate to taxa-4(5),11(12)-diene and elaboration of the olefin intermediate to taxol. Original structure and complete caption.'),('Table I',4,[305,48,561,250],[],'TABLE I. Diterpene Cyclase Activity in Stems of Several Gymnosperms. Specific activity in nmol/h/mg protein and (nmol/h/g tissue).'),('Table II',5,[37,48,294,195],[],'TABLE II. Partial Purification of Taxadiene Synthase from Pacific Yew Saplings. Numbers are means of twelve preparations, each roughly 30 g stem tissue.'),('Figure 1',5,[301,229,558,690],list('AB'),'FIG. 1. A Taxadiene synthase activity in native gel slices. B SDS-PAGE of slices 6,7,8,9 with silver staining. Direct loading impaired stacking and broadened bands.'),('Figure 2',6,[36,53,291,248],[],'FIG. 2. Effect of Mg2+ concentration on taxadiene synthase activity. Rates ±SE under standard assay conditions.')]
for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('7VG6VM6Z-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'Scannedoriginaltitle3authors ArchBiochemBiophys322(2)437-444October1 1995 matchesliveZotero. OriginalnoDOIprinted;recordDOI10.1006/abbi.1995.1486 notexternallyregistrychecked. All8scannedpagesvisuallyverifiedbeyondOCR.','paper_type':'research','title_zh':'紫杉二烯合酶原生蛋白与生化证据','filename_title':'紫杉二烯合酶原生蛋白与生化证据','journal_short':'Arch Biochem Biophys','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['ScannedoriginalnoDOIprinted liveZoteroDOI metadataregistry notexternallyqueried;identitytitleauthorsvolpages verified','TableII displayedmeanprotein*specificactivity yields7.83percentfinal versusreported16;12prepmeanproducts androundingmaydiffer rawperprepneeded notsilentlycorrected','Nativeprotein<=5percentafter600fold purification nosequence recombinantgene experimental localization orspecificresiduemutants','Woundingelicitors data notshown oneweekyewsaplingstem notallTaxus MeJAcellcultures','Fig2SE nundefined;12preparationsspecifictoTableII;I50curvesrawnotprovided noexactP CI;methodsnonlinear/resultsLineweaverBurk discrepancy','Product~3nmol and~4percent reported withoutrawscaleaccounting;nofullnewNMR/GCMSmainfigure;priorstructuralstudy cited'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'specificactivity_start':.04,'specificactivity_end':24.1,'fold_from_displayed_values':24.1/.04,'reported_final_recovery_percent':16,'recovery_from_product_of_displayed_means_percent':.02*24.1/(153.9*.04)*100,'per_preparation_raw_values_unavailable':True,'reported_targetprotein_fraction_percent_max':5,'TableII_preparations':12,'pine_to_yew_baseline_proteinactivity_ratio':4.4/.02,'woundedfir_to_yew_ratio':5.5/.02,'fir_wounded_to_constitutive_ratio':5.5/.11,'GGPP_Km_uM':3,'Mg_apparent_Km_mM':.16,'Mg_saturation_mM':1,'Mn_relative_percent_at1mM':13,'I50_DEPC_mM':.75,'I50_NEM_uM':2,'I50_phenylglyoxal_mM':10,'native_gelfiltration_kDa':75,'SDS_band_kDa':79,'no_gene_identified':True});print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
