import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'57AZ6R62';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[59,64,564,593]),('Figure 2',5,[48,65,553,705]),('Figure 3',7,[48,65,553,718]),('Figure 4',9,[48,65,553,608])]
gaps=['18pagesallreadoriginalsviewed4figurescomplete300dpiALLpanelscaptionssourceRevieworiginalreferencesSIunreadSupplementalTables1to3missingnotread','Online20250721issue20251013Zotero202510bothretainMcClune2024bioRxivpreprintnot2025Natureversion','Nearly500versusover21000reportedstructuresinternalconflict353126sum479notallcategoriesFigure2actual56vsbody35definitionsunclearenumerationrulesnotprovidednotmillionsactuallysynthesized','TXSopenstructversusAF3predictedclosednotbothcrystals4(20)vs4(5)positionsnotinterchangeableEriGStlTCsourcefunctionalparenthesesincoherentoriginalunverified','BAHDacylationOglucopyranosylsourceclassificationunverified13vs8geneGGPPstartTXSomitted8listnotcomparable100foldsourceclaimnotmatchingbaseline','MetabolonphysicalinteractioninsufficientfunctionalchannelingnotnewTaxolevidenceOCTtoxicitydegradationhypothesisnotconfirmed nohazardousexampleoperationalexpansion','184.2yeast101.4Yarrowia390Bsubtaxadiene7Ecoli4.32cyanoT5olnotfinalPTXhundredfoldchemicalcomparisonundefinedinputs20foldsmallchloroplastset3foldfusionnotmultipliable','AIfig4conceptualnottrainedtaxanemodel90percentknownpathrecoverynotunknownenzymeaccuracyRives2021abduplicateJiang2024bref2025Khan2024online2025issueLin2023bphotosynthesisvsyeasttriterpenetitlemismatch','NoLCAnoTEAnoindustrialproofnohumanreviewclassificationdeferred']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'18pages6authorsPlantCommun6:101460DOI liveZotero titlevisualverifiedTYPEReview','paper_type':'review','source_article_type':'Review','title_zh':'紫杉烷多样性综述的结构空间与合成策略证据边界','filename_title':'紫杉烷多样性综述的结构空间与合成策略证据边界','journal_short':'Plant Commun','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded18pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('57AZ6R62-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
