import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'GTJYULK2';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Scheme I',2,[54,57,303,240]),('Figure 1',3,[54,59,302,373]),('Figure 2',3,[311,59,558,393])]
gaps=['OriginalCommunication4pages2authors JBC27116:92019204April191996 pdfoldnoDOI printed liveZoteroDOI metadata titleauthorpagesverified automatedfalse not actualwrongPDF','GenBank U48796 paper accession only liveversion notdownloaded','Actual SchemeI plusFigures1and2 complete all3 originalviews prepared missedScheme','pTb42 repairedreadingframe pTb42.1 LE392library versusXL1Bluefunctionalextract externalGGPP no fullcell de novo production','6sequences11regions20primers83bp probe300000plaques102positive50rescreen38excised12large4full clones notn replicates','Figure1standard12.72product12.73radioGC19.40plusminus0.13 vsGCMS12.72plusminus0.01 different methods errorstatistic undefined standardracemate absoluteconfigurationnot measured','About1nmol assay product not mgLtiter conversion percent no recoveryreactionvolume nP CI reported','2700ntcDNA2586ORF862aa98.303kDa transit137pred72582.5kDa vsnative79 notexactcut unknownNtermblocked noactuallocalization','Abstract46vsbody45percentidentity67similarity grandfirunpublishedmanuscriptsequence noindependentdbverification motifsHisCysnotmutationallyvalidated','10ugprotein5ugRNA200uMinduction15uMGGPP visual micro units text extraction mgmM notcopiedrecipe','Likelyratelimiting futureTSincreaseTaxol not actualfluxcontrolorproduction validation no humanreview deferclassification']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'4pages2authorsJBC271:92019204titleauthorsjournalpagesvisualverifiedDOIliveZoteroonly','paper_type':'research','source_article_type':'Communication','title_zh':'紫杉二烯合酶克隆的功能证据与转运肽预测边界','filename_title':'紫杉二烯合酶克隆的功能证据与转运肽预测边界','journal_short':'JBC','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded4pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('GTJYULK2-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
