import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'D4TSYPV4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[41,318,293,577]),('Figure 2',2,[41,596,554,722])]
gaps=['All3mainfullpagestextoriginalsread twocomplete300dpi crops allthreeFig1traces chemicalstructurescaptionEICwindows Fig2allsubstratedomainbranchlabels;ESIrecord UV642375 directoryexists noPDF thusNMRTableS1FigS1S2unread34refsnotallread','LiveZotero200 fourauthorsXiangLudwigRadtkeYinLi MarburgCAS titleprintedmanualmatch automatictitlefalse DOIprinted OBC1826:4946-4948 receivedMay13acceptedJun22publishedJun222020 notdownload2024','Pcr93042147aa SATKSATPTACPACPTE twoACPs domainpredictionnotallenzymaticvalidation;6921bpfragment633bpterminator wording nosequenceboundaryreconstruction SIpending','NativePRB2deltapcr9304 no detectablemetabolitechanges unpublishedLiKindinger result nottranscriptmeasurementorproofzeroexpression;4of56clusters priorcontext notuniversalactivefraction','A nidulansLO8030pPX001vs emptypYHwApyrG tenintegrants similarrepresentativePX001 nottenfeedingbioreplicates;proteinsnotpurifiedPKS directmechanismnotcomplete','1 6,8dihydroxy3methylisocoumarin2hydroxymethyl3 6methoxy8hydroxy3methyl namesreported1HNMRTableS1notindependentlyrechecked;alreadyknown compoundsnotnewstructures','MplusH193.0493209.0451207.0663 diff15.9958and14.0170 supportOandnetCH2 notaloneposition proof;Fig1UV254 vsmax245325 distinct; EIC originalcaptionwindow.050Da text extraction .005 correctedbyoriginalimage notinstrumentaccuracyorCI','Feedsynthetic1 noforeignPKS yields2and3 afterday1 data notshown andfollowing7daysincrease nofullplottedtimecourse;RtUVMSMS2matched supportsconversion notidentifiedenzymenames orpureenzymes','Fig2branch1to2 C3methylhydroxylation1to3C6O methylation not2to3;acetylstarter4malonyl schematicnotisotopetracing endogenousenzymesunnamed','NoKRdomain notaloneexcludeoxidativehydroxylation;feedingstrongerevidencethanlackdomain;hostidentityresponsible genes notpredicted;abioticcontrolsnotshownmaintext','IcmM19 ATEG0014541percentidentity targetedcomparison notabsoluteabsencehomology; nativeproducerpathwayproductratio unknown','Noabsoluteproducttiterstandardresponseconversionratio isotopebalanceCIorPvalues peakheightnotmolarquantity noactivitytested','COI no competingfinancialinterest DFG Li84411-1 INST160620-1 NSFC31861133004 CSC201708530222 allreported humanreviewfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI four authors OBC18:4946-4948 three pages liveZotero200','paper_type':'research','source_article_type':'Communication','title_zh':'Pcr9304异香豆素合成与异源宿主二次修饰的证据','filename_title':'Pcr9304异香豆素合成与异源宿主二次修饰的证据','journal_short':'Org Biomol Chem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
