import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'WFQ9NBJX';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',3,[40,48,555,348],[],0,'Figure1.GGPP TS GGOH and finalengineeringoverview not3foldflux.'),('Table 1',4,[121,45,474,722],[],90,'Table1.Allstrains andhostgenotypes plasmidbackgrounds integrationstages. Originaltable rotated90degreesclockwise forreadability.'),('Figure 2',7,[40,48,555,437],list('ABCDE'),0,'Figure2.GCMSstandardcomparison andEcoli/yeastTS SDS Westernintact andfragments GAPDH.'),('Figure 3',8,[40,48,555,724],list('ABCDEF'),0,'Figure3.Singleproteasedeletions low/multicopyproductandGGOH, WesternGAPDH;Fcaptionaction10.3→48.6percentnormalizationtypo andunexplainedtriplestar preserved.'),('Figure 4',10,[40,48,555,690],list('ABC'),0,'Figure4.GO counts centralmetabolicproteinheatmap andLFQintensity notabsolutemetaboliteconcentrations.'),('Figure 5',11,[40,48,555,421],list('ABCD'),0,'Figure5.Ty1screening TS genomeintegration andGGPPmoduleaddition Delta22 HO TKL2, productGGOHcurves graphic/bodydiscrepanciespreserved.'),('Figure 6',11,[40,472,555,724],[],0,'Figure6.Fedbatch5Lreactor2Linitialworkingvolume, OD600glucoseethanoltaxadiene meansSD3bioreplicates endpoints878.5mgL180h.')]
for label,page,bbox,panels,rotation,caption in specs:
 pg=doc[page-1];file=d/('WFQ9NBJX-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72).prerotate(rotation),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'rotation_degrees':rotation,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'Printedtitleall10authorsDOI GreenChem20242610604-10616September132024matchesliveZotero all13originalpagestextvisualread.','paper_type':'research','title_zh':'酵母中紫杉二烯合酶的完整表达与降解','filename_title':'酵母紫杉二烯合酶的完整表达与降解','journal_short':'Green Chem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['ESIabsentnoindependentprimersequenceNMRcurvesrawomicsverification','131.97versus78.4increase68.33percent notbody93percentbaselineunclear','878.5versus282.4ratio3.111 notbody5.7initialshakeflaskbaselineunclear','Fig3FcaptionintactTSaction vsGAPDHmethods/E notsameasFig2intactoverTS13.7percent','Fig3Ftriplestar notdefinedbycaptiononly1/2star noexactP orallpaneln','Fig4Ccaptionabsolutemetabolites butmethodMaxQuantLFQandaxisLFQintensity proteinabundance notmetaboliteorabsoluteconcentration','GGOHbody76.9→110.4mgL Fig5Dpinkbarslower unresolvedrawdata','Figure6galactosecaptionvsbodyglucosetoethanol and25ml20percent10mlvolumebasis unclear','BST1/BTS1sourcevariants nomenclaturenotindependentsequenceverified','NotdirectPRB1TSproteolysis halftimecleavage-site oractualmeasuredgenomiccopynumbers','Historical2024highestclaimnotverifiedascurrentrecord; taxadienenotPTX 57.3recovery notcarbonconversion 98.45GCareanotabsolutemasspurity'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'singlecopy19_8_to39_2_increase_percent':(39.2/19.8-1)*100,'intact10_3_to48_6_ratio':48.6/10.3,'intact_increase_percent':(48.6/10.3-1)*100,'131_97_over78_4_ratio':131.97/78.4,'131_97_increase_percent':(131.97/78.4-1)*100,'body_claim93_percent_unresolved':True,'282_4_over131_97_ratio':282.4/131.97,'282_4_increase_percent':(282.4/131.97-1)*100,'878_5_over282_4_ratio':878.5/282.4,'body5_7_baseline_unresolved':True,'simpleendpoint_over180h_mgLh':878.5/180,'reactor_nominal_L':5,'initial_working_L':2,'product_taxadiene_notPTX':True})
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
