import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'BJCHTQFG';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',4,[49,56,521,435],[],'原文 Fig. 1：完整 cDNA、推导氨基酸、起止密码子、HXXXDG 及左侧图注'),('Figure 2',5,[49,56,548,318],list('ABC'),'原文 Fig. 2：完整组织条带、三种处理所有时间、灰度与误差、Southern 及图注'),('Figure 3',5,[49,330,521,718],list('AB'),'原文 Fig. 3：完整 SDS-PAGE 所有泳道与上下质量谱、m/z 和图注')]
gaps=['All7mainPDFpagesread;original1/3/4/5/6visuallychecked; noSI/accessiondatabase/references/rawnumbersread','Formal2007vol34pages89–95 online2006Nov9 preserveboth','Automaticfigureinventoryempty manuallyall3figuresincluded','AY452666authorreported notliveaccessionversionverified','ORF1323bp440aa mass48978pI6.05 predicted notmeasured;H162D166G167notmutatedhere','SemiquantendpointRTPCRnotqPCR;actincontrolstabilityandgraynormalizationdetailsunknown','Methods3repeatscaptionmeanSDn3 biologicalindependenceunclear noP CI/multiplecomparisons','Authorsallpeaks24h butSN12/24close;graph graydensityrange different notfoldcopyunits','Untreatedmentioned butfullparalleluntreatedtimecurvenotshown; transcriptionnotproteinenzyme/metaboliteyield','FruitTaxolnotdetect data-not-shown notindependentlychecked; tissuelimited3organs','Southernmultiplebands suggestsmallfamily notexactfunctionalcopycount;hybridalleles/crosshybridizationunresolved','Figure3A65kDa49plus16tag notnativeprecisemass; noproteomicidentityindependent','Figure3BactualMSnotretentionchromatograms;587.2609.2625.2 molecularadducts notdiagnosticMSMSfragments','Standardsmatchandtwo-substrate dependenceauthorfunction; productNMRcoelution/noenzymeemptyvectorcontrolsnotfullyshown','No Km kcat specificactivity conversionyieldsubstratepanel;conditionnotoptimum andnotwholeEcolipaclitaxelproduction']
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'Original7pageEnglishpaper DOIauthorsformal2007online2006verified','paper_type':'research','title_zh':'TmDBAT克隆功能验证与诱导转录的证据边界','filename_title':'TmDBAT克隆功能验证与诱导转录的证据边界','journal_short':'Mol Biol Rep','category':None,'related_categories':[],'classification_reason':'全部笔记完成后统一归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex direct mainreading'})
images=[]
with fitz.open(rec['main_pdf']) as doc:
    for l,p,b,a,c in spec:
        out=d/('BJCHTQFG-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
