import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'A2J2FZZU';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[54,110,552,705],['A','B','C']),('Figure 1',3,[54,634,550,714],['legend'])]
gaps=['Source verified visually titlepage1 DOIpage4 despite automaticfalse; fourmainpages readviewed; Spotlight commentary not original research or systematicreview; reviewtemplate used explicitly','SingleFigure1 fullABC onphysical2 with complete legendphysical3 two crops noGA noTable','Primaryrefs not independently reread in this interpretation; all experimental claims attributed commentary not own newexperiments','Mainendpoint baccatinIII or oxygenatedtetracycliccore not wholepaclitaxel industrial production sustainability proven; Figure1B T1betaH?T9O? hypothetical intermediates','CYP725A55 TOT1 ctg447gene1 vs CYP725A37 ctg2120gene5 vs CYP725A22 ctg2120gene4 preserveidentities sequencecurrentversionunverified','TOTAF2structure DFTmechanism notmeasuredcrystal fullkineticsbarriers supplied','Nineforeignenzymes vs thirteen genes different systems no automatic dispensablefour orstepcount','Bodyrepeat eitherT1betaH orT1betaH no guess which second; bodyT10alpha vsFigure/legendT10beta retained','Figure1A1dehydroxybaccatinIV versus yeast1betadehydroxybaccatinVI distinctnames not merged','Yeast reported startingtaxadienol tocore not glucose-to-baccatinIII or paclitaxel; chloroplastsignal modification future not wholepathvalidation','DBATsixfoldefficiency cited otherstudy notpaclitaxelyield; no rawratio/CI reanalysis','No currentmarket/medicalrecommendation orlivePSBD validation performed; sustainability noLCA energy solventcost data']
figs=[{'label':'Figure 1','caption':'原文 Figure 1：第 2 页完整 A–C 图版及第 3 页完整图注连续展示','panels':['A','B','C'],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300} for l,p,b,a in spec]}]
draft={'identity_matches':True,'identity_reason':'Direct visual titlepage1 DOIpage4 XueZhangYao Spotlight TPS29(9)948-951','paper_type':'review','title_zh':'紫杉醇通路补缺评述中baccatinIII重构与完整生产的区别','filename_title':'紫杉醇通路补缺评述中baccatinIII重构与完整生产的区别','journal_short':'Trends Plant Sci','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'DirectCodexallfourSpotlightpagesread originalQA reviewtemplate'})
images=[]
for l,p,b,a in spec:
 out=d/('A2J2FZZU-Figure-1-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':'原文 Figure 1：完整 A–C 图版及完整图注','page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
