import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'LDMEJZHN';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[389,255,557,394],[]),('Figure 1',2,[51,59,557,359],[]),('Figure 2',4,[51,58,295,425],list('AB')),('Figure 3',4,[314,58,557,584],list('ABCDE')),('Figure 4',5,[51,58,557,423],list('AB')),('Figure 5',6,[51,199,295,365],[]),('Figure 6',6,[51,513,557,758],[])]
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':next((x['caption'] for x in rec['figure_candidates'] if x['label']==l),'原文摘要图'),'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a in spec]
gaps=['Main8pages formalAnalChem96 16621–16628 notsupplement despitepreparedflag; SI/rawspectra/genedatabase/citedprimarypapers notread','PDFPublished2024-10-11 vsZoterodate2024-10-22 retained noedit','PCA3components57.7percent; nofeature/normalizationcausality; filteringrules/batches/n/errorbar meanings notclear main','Crudeextractbioactivity notcompound1causality;1inactive25ugmL','Absolute3R14S anchorsbiosynthetic/KRhomology notallindependentdirectmeasurement; NOEusedconstructionandassessment notwhollyindependent','DP4 100percent conditionalfourcandidates notunconditionalcertainty; SIcalculationsnotrerun','Lowenergywindowmethod10kcal/mol vsresults10kJ/mol unresolved4.184difference','NMRcalculationschloroform versusexperimentalCD3OD/DMSO inputsnotverified; DMSO1Hprinted3.50 questionableactualrawreferenceunknown','20conformersunder1minute authorreportnotindependentlytimed/fullhardwarebenchmark;200conformersRMSD.687SIunread','SanTTEpathproposed notknockoutcomplementationenzymereconstitution; lowhomology<30percent notmechanismproof','Mixed2/4negativeconversion limitsonlytestedconditions notproofSanTTE/noallartifactroutes','Dehydrataseabsentincluster notproofallnonenzymatic;1a–1dproposed notisolatedverified','2naturalfirstauthorclaim notindependentlyprioritychecked','2–4activityranges individualallocationTableS11unread;1synergynegativeTableS12notrawverified','L02/293Tlowercytotoxauthorreport noTableS13dose/stat independentlyread;notnontoxic/drugwindow']
draft={'identity_matches':True,'identity_reason':'Formal8pageAnalChem titleDOIauthorsmatch','paper_type':'research','title_zh':'Sanyensin柔性构型判定与生物合成假说','filename_title':'Sanyensin柔性构型判定与生物合成假说','journal_short':'Anal Chem','category':None,'related_categories':[],'classification_reason':'全部文献笔记完成后归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex directsource reading without externalmodel'})
images=w.crops(rec,draft,d)
with fitz.open(rec['main_pdf']) as doc:
    for i,(l,p,b,a) in enumerate(spec):
        out=d/('LDMEJZHN-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images[i].update(file=str(target),sha256=sha,bbox=b)
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
