import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'XJBC6G8N';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[60,53,572,472]),('Figure 2',3,[322,53,572,436]),('Figure 3',4,[60,53,310,271]),('Figure 4',4,[60,530,310,741]),('Figure 5',5,[60,53,572,673])]
gaps=['SixpagesPNAS99(14)9166to9171July92002threeauthorsWalkercorrespondingContributedFeb27notpubliveZotero200 verified alloriginalpages5fullfigures', 'SurrogateNdebenzoyl3RS2deoxytaxol enzymeNbzproduces2deoxytaxolnotTaxol standardchemicalNbznotpostenzymeBAPTderivatization Figure1hTaxolhistoricalnotactualenzymefullTaxol', 'NinefamilythreeassignedsixremainingnotreplicatesBL21DE3pSBETaT7argU cellfreefedcomplexsubstrates nofactory', 'EmptyvectorTAX1TAX2TAX6 boiled without either cosubstrate controls negative no detectionlimit', 'Figure2sampleradioandUV39.6plusminus.1 standardcoelution cannotresolvediastereomers Figure3upperstandardlowerproduct 40percentexcess originalnotconvertedtoeeor70to30 absoluteconfigurationunknown fullotherNMRonlyauthorreport', 'Figure4directinfusionAPCI notLCMS 855authorPpluswaternotTaxol 838820778760569509270 standardmatchauthorreport', 'Partialpurification50percent pure target50kDa Kmabstract.42/.40mM versusbody.45/.41mM unexplained kcat1.5plusminus.3persec enzymequantitynormalizationnotfullyreported', 'DuplicateassaymeanSElessthan15percent notbiologicaln2 R2.99LB no rawpointsCI pH8half7and9 highCapso bufferconfound', 'Donorsacetylphenylacetylnotdetected limiteddonors alphaattachedfreebetaandSalphaunproductive limitedacceptorsnotalltaxanes', '1323nt441aa49040DaAF466397paperonly H163D167G168possible notmechanisticallyvalidated noNtargetingnotlocalization identitysimDianthus53/64TaxusTBT60/69', 'Fouracylases8cDNAs20step historicalnotcurrentorcomplete naturalfinalordernotdirectlytested fundingnoexplicitCOI humanfalseclassificationdeferred']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'6pages3authorsPNAS99:91669171July92002titleauthorsjournalDOIprintedvisualverifiedliveZotero','paper_type':'research','source_article_type':'Research article','title_zh':'DBTNBT克隆与脱氧替代底物的N苯甲酰化证据','filename_title':'DBTNBT克隆与脱氧替代底物的N苯甲酰化证据','journal_short':'PNAS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded6pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('XJBC6G8N-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
