import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'QNCWGCR2';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',2,[67,49,555,554],[]),('Table 1',3,[303,47,555,374],[]),('Figure 2',4,[303,48,555,320],list('AB'))]
for label,page,bbox,panels in specs:
 pg=doc[page-1];file=d/('QNCWGCR2-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file));caption=next(x['caption'] for x in rec['figure_candidates'] if x['label']==label)
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'Original PDF title authors PNAS101(24)9149-9154 and printedfooter DOI10.1073/pnas.0403009101 matchliveZotero; automaticDOIfalse manuallyresolved. June15issue distinctJune3Zotero date.','paper_type':'research','title_zh':'诱导红豆杉cDNA文库与紫杉醇候选酶鉴定','filename_title':'诱导红豆杉cDNA文库与紫杉醇候选酶鉴定','journal_short':'PNAS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['Table1 abundance header percent has approximate tenfold mismatch against count/8424; authors intended unit unverified, original preserved','Single induced16h library no matched uninduced biological replicates; EST abundance not differential expression or cellular flux','1054 conversion>50percent no exact biologicaln CI P or full raw NMR locally; GCMS purity not qNMR','Other candidate genes and C9 oxetane ligase functions unresolved; C2alpha functional work referenced elsewhere','GenBank accession versions not downloaded; ZoteroJune3 date meaning not independently established'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'clones':10176,'usable_EST':8424,'unique_transcripts':3563,'usable_percent':8424/10176*100,'unusable':10176-8424,'unusable_percent':(10176-8424)/10176*100,'TS_hits':41,'TS_percent_computed':41/8424*100,'TS_per_mille_computed':41/8424*1000,'TS_table_value_with_percent_header':4.9,'DXR_hits':14,'DXR_percent_computed':14/8424*100,'DXR_per_mille_computed':14/8424*1000,'DXR_table_value_with_percent_header':1.7,'original_unit_suspected_not_silently_corrected':True});print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
