import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'RZNZCQRY';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',4,[41,46,554,605],list('abcde'),'原文 Fig. 1：GC-FID 空白与产物、两相照片、细胞计数、Fv/Fm 及不同产物株色谱；完整 a–e 及图注'),('Figure 2',5,[41,46,554,275],list('ab'),'原文 Fig. 2：摇动/静置照片与 patchoulol 滴度；μg/L culture，mean±SD，n=5，P 阈值完整'),('Figure 3',5,[41,466,554,726],list('ab'),'原文 Fig. 3：FC-3283/乙醇两相及转移前后 GC-FID 色谱，完整图注'),('Figure 4',6,[41,46,554,303],[],'原文 Fig. 4：全部液体结构、密度、温度物性及四种产物 GC-FID 峰面积，mean±SD，n=5，完整图注')]
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
gaps=['All8mainpages read; ESI rawGC/calibration andcitedsources/suppliercurrent specs notread','Automaticidentitytitleflagfalse actualPDFtitleDOIauthorsverified; automaticFig.candidateinventoryempty manuallyall4figuresincluded','Extractedtextmu→m fontissue; actualPDFpatchoulol ug/L notmg/L;500uL not500mL etc','Method500uLto4.5mLtotal10percent versusFigure1caption5percent unresolved','Generalbiologicaln3technicaln2 andFigure2/4n5 separatelyreported no poolingtechnicalreplicates','Figure2t/P thresholds authors;noexactP CI/rawtests verified; multiplepointt notreportedadjustment','FCphaseaccumulationnotcelltotalbiosynthesis; nofullmassbalance extractionkinetics/partitioncoefficients','Figure4area*1000notug/L orrates; no crossproductcalibration orgroupstat significance inferred','Figure1dFv/FmmaximumPSIIefficiency notdirectlinearelectronflow; dodecanelysisexplicitlyuntested','Figure3>99patch95–98others authorsSI2claimnotindependentlyquantified;2hdata notshownmethod16h','Transferrecoverynotwholepureproductyield; recyclemulticycles purity/cost/lifecycle/scale nottested','Density/materialstructuresreportedfromliterature notallnewmeasurements; UVM4parentcalledwildtype notnaturalstrain','ModelC reinhardtii4engineeredstrains notallmicrobes orcompletepaclitaxelproduction']
draft={'identity_matches':True,'identity_reason':'Readoriginaltitle/DOIauthors all8pages RSCAdv12 16632–16639','paper_type':'research','title_zh':'氟碳下层萃取的回收量与生产证据边界','filename_title':'氟碳下层萃取的回收量与生产证据边界','journal_short':'RSC Adv','category':None,'related_categories':[],'classification_reason':'全部笔记完成后归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex directsource reading without externalmodel'})
images=w.crops(rec,draft,d)
with fitz.open(rec['main_pdf']) as doc:
    for i,(l,p,b,a,c) in enumerate(spec):
        out=d/('RZNZCQRY-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images[i].update(file=str(target),sha256=sha,bbox=b)
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
