import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'K4UYREEP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[315,250,557,377],[],'原文摘要图：完整天然与人工路线、侧链结构及供体示意'),('Figure 1',2,[50,59,557,578],['a','b'],'原文 Figure 1：完整天然与人工侧链装配、AAE4 支路和图注'),('Table 1',3,[314,58,557,717],[],'原文 Table 1：完整菌株、基因型和来源；保留原文位点编号矛盾'),('Figure 2',4,[50,59,557,355],['a','b'],'原文 Figure 2：完整 PAM 和 PCL 比较、断轴、色谱和图注'),('Figure 3',5,[50,59,557,459],['a','b','c','d'],'原文 Figure 3：完整模型、单点及组合变化、统计标注和长图注'),('Figure 4',6,[50,59,557,473],['a','b','c','d'],'原文 Figure 4：全部色谱、ng/L 定量、酶组合矩阵及图注')]
gaps=['All11physicalmainpagesreadandviewed ACSResearchArticleearlyonlineA–K XXXXvolume/pagesnotinvented','Attachedmainmisflaggedsupplementheuristicactualmain;noSIprovidedreadFiguresS1–11TablesS1–3notindependentverified','WholecellfeedbaccatinIII50uMsidechain500uMDMSO3percent48h extraBAconcentrationnotreported;notdenovofromsugar','Threecoreassemblyreactions excludeadditionalAAE4donorgeneration;not3genesonly','PAMnegativewholecellapparentactivity notpureenzymeinactiveknowncause','PCL8.1and134.8foldintermediateaccumulationnotkcatKM isolatedactivity downstreamBAPTconfounds','CommercialbaccatinIIItraceTaxol authorspurificationcontrolSIunread residualLODLOQrecoverymatrixcalibrationnotshownmain','PrPCLA312GTable1Methodsactual300dpiFigure2versusA321GResultsunresolved;Figure4matrixTchDBTNBTvsbodyTableTcaDBTNBT;BTP1aM4Q376EtablevsQ387Efigureunresolved','ResultsPCLactivationinpresenceacetylCoA vsCoAschematic ambiguousnotverifiedchemicalrequirement','BAPTmodelAF3pTM.9qvinasequentialdockingnotcrystalorexperimentalhydrogenbondtransitionstate','Q386E4.31foldwholecellintermediateaccumulationnotpurekcat expressionstabilitylocalizationnotmatchedmeasured','Figure3ANOVATukeymeanSDn3biologicalvsMethodsmeanSEatleasttriplicateconflict;Q386EPless.001notexactP','PriorKMcalledaffinity kcatcalledefficiencybothnotdirectKDorkcatKM;TableS1unread','MainTaxol1.47ngLbodyFigure4bunitconsistentNOTugormg;18.7percentofbetaphenylalaninenativeroute notmolarconversionyield','ArtificialvsLphenylalaninenativeadvantage notversusbetaphenylalaninesupply;noindustrialcost/scale/wholemassbalance','Nbenzoyltransferasesdifferentwholecellsubstratepreference notexclusiveallconditionsornativeplantfunctionproof','PeroxisomelocalizationandOGDePTS1noimprovementauthorSIreport notintrinsicincompatibilityprooffluxchannelingCoApoolunmeasured','LCQQQMRMparametersSI;Methodsresolution100000settingreportedunverifiedinstrumentconfiguration','Noanaloguepharmacologyimprovementtested;nohumanfullpaperreview']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'Directread11physicalmainpages title10authorsDOI2026ResearchArticleearlyonline','paper_type':'research','title_zh':'酵母人工装配紫杉醇与补料转化的证据边界','filename_title':'酵母人工装配紫杉醇与补料转化的证据边界','journal_short':'ACS Synth Biol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'DirectCodexall11mainpagesfullreadoriginalpageQA'})
images=[]
for l,p,b,a,c in spec:
 out=d/('K4UYREEP-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
