import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'FBCVZJMP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[57,554,260,637]),('Figure 2',1,[264,229,473,332]),('Figure 3',2,[53,68,257,141])]
gaps=['Both2mainfullpages text originalimagesread threecomplete300dpi figurecrops allfragmentnumbersresiduenames finalpostulatedlactonebond; no fullrawMSEIIRaminoacidchromatograms noSI all3numberedreferences subitemsnotindependentlyread','Manualprintedtitle3authorsNakagawaNakazawaShoji Shionogi journal2812:1004-1005Dec1975 receivedApr11 liveZotero200; automatic titleDOIfalse DOIonlymetadata notprinted;thirdcreatorShojJunquote metadatawrong preservePDFname noteditZotero','PreviouslyreportedBsubtilispeptideformularesiduesfromreference1 no newMICtargetclinicalorBGC NRPS validation','Hydrogenatedhydrolysatealphaaminobutyrate vsintactacidmethylalphaketobutyrate supportDhb one residue notbothsaturatedunsaturatednaturalresidues; UVendabsorptionnotcompletegeometry','Figure1AcPheLeuPheThrValAlaDhb43 190303450533632703803;Thrfragmentdehydrationassumed533relative27percent notpurityorconversion;last100gapnotfreeresiduemass','Figure2AcMePheMeLeuMePheDiMeThrMeValMeAla43 204331492621734819 derivatizationnotnaturalN/O methylgroups;authornoCterminalinformation','Nacetylcompatible neutralityninhydrinnegative butnotaloneuniqueproof;Fig3CterminalDhbesterThrsidechainnotheadtotailamideall7residues','IRintact1723generalpeptidelactone1740conjugationexplanation nonunique;acid1695Mminuswater803 computedneutral821notobservedM; methylester1728M835+14netCH2 acidopening+18','OxidationTL119acidThr destroyed versusintactnotaffect supportsOHprotected no rawoxidationproductindependentreplicate; exactconnectivity combinedevidence','EmpiricalC42H57N7O9 nominal803 sevenresidues composition sum minus6waters NacetylnetC2H2O lactoneminuswater countconsistentnotuniqueisomerproof','Explicit stereochemistryaminoacidsnotdetermined no fillD/L Thrconfiguration norDhbEZ;postulatedplane structure notmodernfullNMRHRMSsolved','HitachiRMU6directinlet250C70eV mass803notMplusH;27relativeabundance no statsCI samplecount;noexplicitfundCOI nohumanreview deferredclassification']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title authors Shionogi J Antibiot28:1004-1005 two pages liveZotero200 DOI metadata notprinted','paper_type':'research','source_article_type':'Communication to the editor','title_zh':'TL-119肽内酯的质谱连接证据与未定立体化学','filename_title':'TL-119肽内酯的质谱连接证据与未定立体化学','journal_short':'J Antibiot','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex two full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
