import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'JJ77V5A7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Figure 1',2,[49,64,553,424],[]),('Table 1',5,[42,325,548,411],[]),('Table 2',5,[305,173,548,309],[]),('Figure 2',5,[42,424,548,740],['A','B']),('Figure 3',7,[42,69,548,703],[]),('Table 3',8,[49,68,552,243],[]),('Figure 4',8,[49,257,291,565],[]),('Figure 5',9,[42,69,284,570],['1','2','3','3A','3B','4','4A','4B'])]
gaps=['All ten mainphysicalpages read and viewed DOI title manually verified originalpage font extraction purification/first malformed; five Figures three Tables eight fullcrops noGA','AY724735 sequence accession quoted source no live current database fetch or raw sequence reanalysis','Table1 crude64.6/123.61=0.522611439 vs printed1.44;82.6/.523 about158 alignsfold157.9 but no silent correction','Source unit literally mu m/min/mg110.1 no invented umol/U/kcat conversion','Nativeprotein80kDa SDS162gel suggests dimer not full crystallographic interface; predicted687aa75.3kDa pI5.63','Km1.1mM pH7.5to8 Vmax110.1 source units; no fitdata nerrorCI exactP;18hour assay24linearity report not detailed raw timecourse','PLPSAM addition independence not all internal catalytic groups absent; Mg inReactiveGreen19 affects PALbindingnotPAMmetalrequirement','Substrate onlyalphaL amongtested notallpotentialaminoacids fullpanelnoLOD given; productinhibition notobserved noallconditions proof','RecombinantPAM EcoliXL1Blue pBMS2000 vectorcontrol activityLCMSMS betaPhe confirmed; bacterialunknownpeaksnotallPAMproducts','Figure5 alpha/beta same166mass needretentionanddaughters notmassalone; no chiral separation/ee absolutebetaPhe assignment supplied','Table3 common360to380aa partialGinkgo candidate79percent not fullseq functional validation;tenrandomizationsnotbioln10','Table2PALKm0.29to0.04mM versusbody29to260mu m retainedrange difference','GinkgoAY578145Methods vs A578145discussion discrepancy retained;AY231176PAMprediction not enzymatically verified','ASGbody174to176 vsFigure3175to177 MIO predictionHAL/PAL analogy notPAMstructure chemical confirmation;11residuesunmutated','HigherKm does not prove Taxolpathrate limitation; no overexpressionTaxoltitre industrialyield measured; phylogenetic timinghypothesisnotmolecularclock']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':'原文 '+l+'：完整数据、图注、序列行及表格脚注','panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a in spec]
report=(d/'codex-report.md').read_text(encoding='utf-8').replace('通过首页原图和 DOI 人工式逐项核对','通过首页原图和 DOI 逐项核对');(d/'codex-report.md').write_text(report,encoding='utf-8')
draft={'identity_matches':True,'identity_reason':'Directtenpagefullread titleverifiedonoriginal8authors ABB4381-10DOI10.1016/j.abb.2005.04.012','paper_type':'research','title_zh':'紫杉醇侧链PAM天然蛋白与克隆基因的功能证据','filename_title':'紫杉醇侧链PAM天然蛋白与克隆基因的功能证据','journal_short':'Arch Biochem Biophys','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':report}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'DirectCodexalltenmainpagesreadoriginalQA'})
images=[]
for l,p,b,a in spec:
 out=d/('JJ77V5A7-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':'原文 '+l+'：完整数据、图注、序列行及表格脚注','page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
