import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'GCY6UZB8';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',4,[49,48,556,549],list('AB'),'Figure1.Allnatural/semisyntheticrouteandproposedMIOmechanism panels;historicalputativestepsnotnewcompletepathway.'),('Figure 2',5,[49,48,556,580],[],'Figure2.Wholealignmentallresiduestermini/legend;ASG175-177 Ala notAsptexttypo;threePALrowsshownnotsevensaidincaption;sitefunctionspositionalnotmutagenesis.'),('Figure 3',6,[49,48,556,412],list('AB'),'Figure3.Completestructuralfragmentandfourisotopomerdiagram;notrawGCMSspectra orKIE;relativefragmentabundance notdirectmolecularfraction.')]
for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('GCY6UZB8-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file));figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
gaps=['All9physicalpagesread 8paperpagespluswebappendix noGA ortables noSI/rawGCMS','MethodfullcloneTaxuscanadensistranscriptpoolvsabstract/resultcuspidatasourceconflict','OneResultsAspSerGlyversusFigure2/discussionAlaSerGlyASG175-177sourceconflict','Figure2captionsevenPALsactual3PALrowssourceconflict','Noalln/SDSEM/CI/P rawinitialratedata Km45±8errornatureunspecified','SubstratesnondetectnoLOD nontestedallsubstrates 24hRonlycouldmaskrapidSreverse','FragmentP184100/P18550relativeabundance notnaivefraction isotopecorrection/rawabsent authored50percentpartialmigration C2stereochemistryunresolved noKIE','MIOsupportednotdirectPAMcrystal/covalentmoietydetermination orresiduemutagenesis tightlyboundPLPnotfullyexcluded','3Svs3RreverseVrel100vs5ratio20 notseparatekcat transCA10percentrate notfinal90percentselectivity','20mgLsolubleproteinnotbetaPheorPTXyield nofullpathway/physiologicalflux proof','Tchinensisnativekineticsfrompatentunread mixedspecies/preparation C11truncationcausalityunproven','2004pathwayhistoricalunresolvedstepsnotcurrentvalidatedmap','Noexplicitmodernconflictdeclaration advertisementpagefeefootnotenotCOI']
draft={'identity_matches':True,'identity_reason':'TitleDOIfourauthorsprinted2004JBC279(52)53947-53954matchesliveZotero;9physicalpagesviewedincludingwebappendixnotGA.','paper_type':'research','title_zh':'紫杉醇侧链PAM的立体选择性与氢迁移','filename_title':'紫杉醇侧链PAM的立体选择性与氢迁移','journal_short':'J Biol Chem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'kcat_perminute':.015*60,'kcat_overKm_M_inverse_s':.015/(45e-6),'kcat_overKm_mM_inverse_s':.015/.045,'reverseVrel_ratio':100/5,'reportednative_efficiency_ratio':2.1/(.015/.045),'reportednative_efficiency_fromconstants':2.3/1.1,'Cterminal_length_difference':698-687,'migration50_is_authored_interpretation_not_naive_P185fraction':True})
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'crops':[x['file'] for x in images]},ensure_ascii=False))
