import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'DW2KXVKT';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[36,464,562,748]),('Figure 2',4,[36,50,562,201]),('Figure 3',4,[36,208,294,700]),('Figure 4',5,[36,50,294,674]),('Figure 5',5,[304,50,562,666]),('Figure 6',6,[36,50,295,246]),('Table 1',3,[36,627,562,745])]
gaps=['Eightmainpages6formalFigures1Tableallreadoriginalsviewed7complete300dpicrops title6authorscorrespondJianheXuECUST8:331to338 DOIprinted onlineApr26acceptedApr11ZoteroJune2023', 'NoSIlocal TableS1strainsS2primersS3optimizedseqFigureS1conditionoptimizationnotread refs48notindependentlyread', 'Po1fATCCMYA2613TaxuscuspidataTASY codonoptimized YP11.02YP12.07YP21.13YP22.15YP23.27YP24.31YP25.68YP26.70YP27.80mgL terminalTaxadienenotTaxol', 'Abstractpushpull234percent vsYP27YP12ratio11.4 no reconciliation;fusion296percent not reproducedfrom.80versus.31or.27or.13 fusionlineageYP21bodyversuscumulativeFigure3 unresolved', 'YP27GGOH115WT.40 notdirectGGPPpoolorflux measurement no phosphatasesourcevalidation', 'SUMO3.55MBP3.45YP51alone2.01mgL body calculated76.62percentvsabstract62.3discussion60.6 unresolved YP51extraTASY173percent vs2.01/.8increase151.25 no correctingrawnotavailable', 'FiveNterminaltagsSUMOGSTMBPNusATrxA noactualsolubleinsolubleproteinmeasure no purekinetics tagsproductphenotypenotsolubilityproof', 'ThreeiterationsrDNACreloxPselecthighproducer23.7mgL GGOH115to31.4 copycorrelationnotsolecausepositionselectioneffects no eachroundexactfunctionalcopyassumption', 'CopyqPCRgenomicDNAgapdhvswordtranscriptionRTqPCRkit ambiguous nocopyequalsRNA no efficiencycalculationmain', 'M23conditionoptimizationM33plusLeuM4fedbatch5Linitial2L144h101.4OD210 Figure6M4/M6batch/fedbatchlabelsconflict noM6invented', 'FeedglucoseResultsversus10xYPDMethods dodecane10percentanalysisvs20percent36hbioreactor YNBglucose20percentvs20gLothercontexts preserveversions', 'Figures2to5triplicateSD noexplicitbiologicalindependencenoexactP CI Figure5bnoobviouserrors no totalreplicateNinvented;GCMSoctadecaneinternalstandard buttaxadiene calibrationresponsefactorrecoverynotfullyreported', 'Table1mixescellfree94percentproductfractionmgLgLmicroggFW notoneunifiedyieldranking no historicalGRASclinical firstpriorityclaimsverified nofinalP450orTaxoltest humanfalseclassificationdeferred']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注' if l!='Figure 5' else '原文未编号摘要图，Figure 5为笔记编号'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'8pages6authorsECUSTSynthSystBiotechnol2023DOIprintedtitleverifiedlive200331to338 noSI','paper_type':'research','source_article_type':'Research Letter','title_zh':'解脂耶氏酵母紫杉二烯生产中的融合标签与多拷贝整合','filename_title':'解脂耶氏酵母紫杉二烯生产中的融合标签与多拷贝整合','journal_short':'Synth Syst Biotechnol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded8physicalpages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('DW2KXVKT-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
