import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'NW57HMK4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[33,282,562,687]),('Figure 2',6,[43,149,563,738]),('Table 1',8,[33,70,563,612]),('Table 2',12,[32,70,810,456])]
gaps=['16pagesallreadoriginalsviewed2figures2tablescomplete300dpicropsTable2landscapereviewnarrativenotsystematic67originalreferencesSIrawdataunread','Figure1characterizedandproposedmixedTXSclassIIIfunctionclassificationunverifiedFoTO1physicalcomplexclaimstrongerthanCommentaryneedprimaryproof','Reference25ASRsentencebutplantminimalsettitle29minimalsetbutyeastfusiontitle53yeastfusionbutASRtitlemismatchnotautomaticallyrepaired','SpatialtransportessentialoverstatesstemoriginalcandidateABCG2localizationnoATPsubstratefluxlossrescueproofTcJAV3degradationFigure2modelnotnewdirectevidence','Leafreference35article100561versuspreviouslyreadGSGUZKME100630conflict56.6NtabacumFu58versusotherreviewNbenthamianaLi33conflictoriginalsunverified','Tmyb29aABAresponsiveearlierJAresponsive laterunresolvedTableTOT T9sevenknownlistnoDBATnotcompleteexecutablereconstruction','FoTO1early10to17foldnotfinalTaxol50nggunknownmassbasisversus10to30ugpergdrycannotcomputecrossstudyfold','Table1oxygenatedtotal570and78notfinalTaxol129and215184taxadieneplusminusundefinedSDSEM61.9ugLnotmgLcyanobacterial4.32hydroxyproducttableapproachonlyTXSGGPPSincomplete','Taxus310vs71.01ratio4.37BAPT135ratio1.90notbothfourfoldjointelicitationnotgeneticsoleeffect','SustainabilityplatformframeworknotLCAorTEAhybridforecastnotmeasuredindustrialproofclassificationdeferredhumanreviewfalse']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'16pages3authorsPlants15:1741DOI liveZotero titlevisualverifiedTYPEReview','paper_type':'review','source_article_type':'Review','title_zh':'紫杉醇可持续生产综述的平台框架与引用证据边界','filename_title':'紫杉醇可持续生产综述的平台框架与引用证据边界','journal_short':'Plants','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded16pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('NW57HMK4-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
