import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'ZKKMRAA9';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[263,523,472,672]),('Figure 2',2,[98,74,419,185]),('Table 1',2,[51,202,251,384])]
gaps=['Allthree mainpages fulltextoriginalimagesread threecomplete300dpicrops UVIRallaxesTable1alltenrowsagarfootnote noAArawchromatograms originalbioassayrecords replicates statistics all3refsnotindependentlyread','PrintedtitlefiveauthorsShojiHinooWakisakaKoizumiMayama Shionogi JAntibiot282:126-128Feb1975 receivedJuly291974 liveZotero200 DOIonlymetadata notprinted','StrainTL119Thailandsoil resemblesBsubtilis authorsidentificationinsufficient notmolecularlyconfirmed;strainnamevscompoundnamesame separate','5Lculture250mgcrude170mgpowder equals50and34mgL recoveredmaterials not truebrothtiter;massretention68percent nottargetchemicalrecovery noquantpurity','C42H57N7O9 nominalM803 notHRorMplusH elementalobserved62.37 7.11 17.68 12.09 vscalc62.76 7.10 17.93 12.20 differencesnotpurity inferred','Opticalrotation24Dminus8.7plusminus1 c.482DMSO notDLorCI noabsoluteconfiguration;above250decompositionnotsharpmpstoragestability;UVweak252258264268endabsorption nofullsequence;IRpossiblylactonenotcompleteconnectivity','AAumolmgThr1.09Ala1.19Val1.19Leu1.20Phe2.54 measuredhydrolysate hypothetical1.245moleculesumolmg803 notnewrawrecovery;count1eachPhe2 six knownN7 missingabnormalresidue deferredstructurepaper','NacetylDhbterminalCOOHlactone sequence preannounced laterpaper notfullstructuredatahere noDL absolutegeometry','Table1MICugmL12.5BsubtilisPCI219 1.56SaureusFDA209PJC1 3.13Smith other7 greater50 includingtwoGrampositive;notallGrampositive sensitive notclinicalbreakpointsorMBC','Agarusualdilution no fullinoculum replicatesCIP currentstandardassumed;greater50censorednotexact50 or noactivityallconcentrations','MouseIP50mgkg no observedtoxicsymptoms noanimalsnumberduration fullorganstudy safetywindowLD50unproven;curativeIPnotSC reportedwithoutfullefficacydose cannotborrowtoxicitydose;PKexplanationuntested','No drugtargetNRPSgenes clinicalefficacy or broadstraincoverage no fundingCOI statement thanksSMatsuura humanreviewfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title five authors J Antibiot28:126-128 three pages liveZotero200 DOI metadata notprinted','paper_type':'research','source_article_type':'Research Article','title_zh':'TL-119原始分离与初步组成和抗菌谱证据','filename_title':'TL-119原始分离与初步组成和抗菌谱证据','journal_short':'J Antibiot','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
