import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'RJH4IGK7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[44,47,553,448]),('Figure 2',4,[40,47,552,466]),('Figure 3',5,[44,47,553,480]),('Figure 4',6,[40,47,552,431]),('Figure 5',7,[44,47,553,544]),('Figure 6',8,[40,47,552,503]),('Figure 7',10,[40,47,552,388])]
gaps=['13mainpagesreadandviewed7completeFigures300dpiSIactualunreadrawGSE175645metabolomicnetdisknotdownloadedreferencesnotindependentlyread','NaturalbranchesassociationnotrandomsexnoTaxusOEknockdownrescuemetabolitecausalitynativeChIPorCoIP;2factorinteractionheterologousY2HBiFC','PTXfemale.07male.04mgpergDW1.75fold75percentincrease roundedmeansnotexactCI noindustrialmgLyield;targetedn6untargetedn10RNAn3independenttreemappingnotfullyclear','7taxoidsnotallfemalehigh10DABBAC10DAPnonsignificantCEPgraphsignificant targetedBAC/DABversusuntargetedionfeaturesdifferentretain','9445ions4479annotations1116DAM623plus4933054DEG1256plus1798 noallstructuresverified52putativepathwayunigenesnot52verifiedgeneloci','EMSA4targetsGGPPS/T13OH/T10OH/TBT notallactivation;DualLUCcombinationGGPPS/T10OHonly notT13OHTBT;BHLHbindingabsenceclassicmotifpredictionnotDNAprooftested','GST/GSHresultsversusHis/Nimethodconflict;TSGGPPSsameDN26572c0g1sourceconflict;methodT10OHomittedlist;4promoters3genesdiscussiontypo','femaleSpecificexpressionnotsexspecificgenomeabsenceWD40notvalidatedflavonoidstressresistanceunproved;complexenhancementnotformalinteractionsynergystat','RPKMRtypoDESeqcountinputunspecifieddoNotassumeTPMinput;Figure7enzymeproductschematicnotnewfunctionproof','Figure2Dflavonoidsnear5/8text23/3labelsambiguousactualSIunread;Allnotesclassificationdeferred nohumanfullpaperreview']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'13pages title11authorsHorticRes9uhac062DOI verified','paper_type':'research','title_zh':'雌性偏高TmMYB39与TmbHLH13互作及紫杉醇积累差异的证据','filename_title':'雌性偏高TmMYB39与TmbHLH13互作及紫杉醇积累差异的证据','journal_short':'Hortic Res','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded13pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('RJH4IGK7-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
