import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'BEFAAGRE';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[9,27,530,276]),('Figure 2',4,[272,25,530,301]),('Table 1',5,[272,27,530,153])]
gaps=['Allsevenoriginalpagesreadviewed Figure1 Figure2 Table1 complete originalcandidate missedFig2andTable1 manually included', 'Identity titlefiveauthors13pp90-96 ARTICLEPT980870 matchesliveZotero DOI10.1006/prep.1998.0870 automaticDOIfalse notprintedDOI', 'Figure2allfivegel lanes preserved lane2refoldedinactive lane4activefusion lane5enterokinaseremoved lostactivity datanotshown; isotopeproduct massspectraGCnotshown notfabricated', 'Originalmicro units kineticGGPP.5to15microM Km3.1microM native2.9microM microLassay antibioticsmicrogmL verified;37vs20C actualtemp', '15to20percent totalsoluble target70percenttargetsoluble greater95percentpurity distinctdenominators; hepta-histidylleader notassumed6His', 'Table1crude246mg1304nmolh5.3nmolhmg affinity12mg978nmolh81.5nmolhmg75percent versusbody13mg80percent unresolved notsilentlycorrected', 'BodyVmax.9plusminus.03micromolminmg versusTable81.5nmolhmg factor662.58 difference unresolved notexplainedbysourceraw; lowerkcatnotvaluereported error.03definitionunspecified', 'Kineticsduplicateexperiments pointaverages substrateblanks less20percentconsumption nonlinearMM no rawFIDfitresidualsbioculturenCI Pprovided', 'FullORF expression truncationstart138 testedfailed notnaturalcleavageknown andnot78residuedeletion; NterminalAQLSFNA frominactivepET3d minusMet notmatureplantboundary', 'Masssequencepredicted98.3kDa versusSDS80native79fusion12extra notinferexactcleavage; foldedmechanismandhostgrowthdatannotshown no generaltoxicclaims', 'TaxadienefunctionnotcompleteTaxol protein24or26mgLnotproducttiter casbeneinpreparation notvalidated; allreferencesnotchecked humanreviewfalse classificationdeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original title fiveauthors volume13pp90-96 ARTICLEPT980870 matches liveZotero DOI','paper_type':'research','source_article_type':'Original research','title_zh':'TS融合表达的可溶活性蛋白获取与原文数值矛盾','filename_title':'TS融合表达的可溶活性蛋白获取与原文数值矛盾','journal_short':'Protein Expr Purif','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex allsevenoriginalpagesreadviewed andmicroUnits checked; originalpurificationbodytable inconsistencies andVmaxspecificactivity differences preserved'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
