import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'5NZ2V9DS';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[315,261,563,404]),('Figure 2',2,[53,45,300,136]),('Figure 3',2,[53,141,300,253]),('Table 1',2,[315,45,563,172]),('Chart 1',3,[53,46,563,350])]
gaps=['All four originalmainpagesreadviewed Figures1-3 Table1 plus omittedautomatedChart1 allcompletecrops300dpi; existingPDFhighlightsretainedread-only rawNMRMSunavailable refsnotallindependentlyread','ElevenauthorsHoshiPernambucoChiba correspondingNozawa67issue9pp1580-1583 DOIprinted webJuly242004 volumeSep2004 receivedFeb24 downloaded2021notpub liveZotero200','ReadableattachmentG93YATLV used otherZNR88ZMXmissingfile nottreatedasnoPDF; sourceidentitymatches true','IFM52670ten150gmoistrice1.5kg isolates1 9mg2 12mg8 7mg3 300mg equals6 8 4.667 200mgkg recoverednottrueabundanceorfermentationtiter','1C14H20O4DBE5 EI252.1372calc252.1361plus4.36ppm 2C14H22O3DBE4 protonatedCI239.1642calc239.1647minus2.09ppm noformulaionconfusion','COSYHMBCtopology carboxyC11 linkedC10 ketoneC3adjacentC2 notC2carbonyl; 1CDCl3 vs2acetoned6 no directshiftpurestructureeffect','NOESYrelative ringorientation vs MosherC6S both; methylesters10 11 beforeMTPA deltaSminusR inHz500MHz notppm; printedroundingcannotrebuildallintegerHz; no rawreprocessing','Chart1 compoundA lactoneB sodiumcarboxylateC2methylbutanoyloxy; chemical derivatives10to17notallnaturalisolates no biosynthpathdirection inferred','6MnO2to7chemidentity 8heatingto3 9comparedpreparedethylester chemicalcorrelation notenzymes pathway; 12fromhydrogenation 13to17salts acidformnotnecessarilyprotonatedCOOH','Original1to7and9 inactive100microgdisk noMIC; active8textAfum18mm1microgdiskCandida17mm5microgdisk no new1or2activityassignment','Table1printedmgdisk vsbodymicrogdisk1000foldunresolved preserveoriginalcaptionheadernoquantdoseunification;8at.5 (16)slightgrowth +slightinhibition -none; AMPB13at10vs14at5 nonmonotonic nofitreplicatesstatisticalratio','8protonlisted1H forsome methyls vs13CCH3 notsilentlycorrected; Methodsborrowrefs strainNnotreported no targetcytotoxicityin vivo; grantChiba200322 FNGRPF2003 noCOIrepositoryexplicit humanreviewfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI elevenauthors67issue9pp1580-1583 Notes2004 fourpages liveZotero200','paper_type':'research','source_article_type':'Original research Note','title_zh':'Eujavanoic acids的立体化学与Compactin酸形式构效证据','filename_title':'Eujavanoic acids的立体化学与Compactin酸形式构效证据','journal_short':'J Nat Prod','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex four full original pages read and viewed; structural NOESY and Mosher evidence separated from paper-disk SAR and unresolved mg versus microgram unit conflict'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
