import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'KCRKWWRP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Scheme 1',2,[315,450,564,604]),('Figure 1',3,[52,53,565,495]),('Figure 2',4,[315,212,563,527]),('Chart 1',6,[0,0,doc[5].rect.width,doc[5].rect.height])]
gaps=['JustAcceptedpeerreviewednotversionofrecord coverOct302016 ZoteroNov4 nofinalvolume printed DOIfromZoteronotPDFstring title5authors6pagesincludingcoverandTOCidentitymatcheslive200', 'All6physicalpagesmaintextreadoriginalsviewed Scheme1Figure1Figure2andunnumberedTOCChart1 crops300dpi; TOCartworkalreadyclippedbyoriginalPDFpageedges entireavailableframepreserved missingedgecontentnotrecoverable', 'NoSIlocal detailedprotocolsfullsequencesstructurecharacterizationFiguresS1toS17notread mainreference22notindependentlyverified', 'Native92percent1and8percent5quotedpriorresearch Figure1CDbluegreenlegendinconsistentwithbody noexactbarquantification no nerrorP kcat turnover attribution', 'Y688Lreported2.4fold5anddownstream2 notTaxol finalyield increase140percent not240percent', 'TXSdeprotonationH20textcompound2butFigure1Bhydrocarbon5 Scheme1OCTcaption11vsgraphic10 Figure2A9Diolvsbody11 Figure2Bepoxide2vscentral3 retaincontexts', 'Q609Gsole9text versusFigure1DEandcoexpressionY609G cannotresolvewithoutSIseq do notinventcorrectconstruct', 'S587Ausualproductsabsent maycatalysisorprotein stability S587Gunknownless.5mgL notallcatalysisabsent 9Verticilla3712trienealreadyknown notnewchemical', 'DockingalternativeposeschainA/BPPipresence inconsistent PPiorY688basehypothesis notcatalyticbaseroleproven', 'T380Snew5(12)oxa3(11)cyclotaxan10ol11cyclicetheralcoholnotordinarytaxadiene5alpha10betadiol despiteinitialRTMSsimilarity twooxygenatomsnot2OH no desiredTaxolfluxproof', '23TaxustranscriptsRACEcandidateexpressionnegative notallnaturalhydrolasesabsent noindividualproteinexpressionpositiveactivityqualitycontrolsvisible inmain', 'NIHPewSearleNSFauthorfunding nofinancialCOIdeclared noSIreproduction no humanscientificclearance classificationdeferred']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注' if l!='Chart 1' else '原文未编号摘要图，Chart 1为笔记编号；原附件页边已截断，仅保留全部可见范围'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'6pagesJustAcceptedACS2016title5authorslive200 DOImetadataPDFstringabsentOct30vsNov4 datespreserved','paper_type':'research','source_article_type':'Research Letter','title_zh':'TXS上游异构体工程与CYP725A4产物选择性的证据边界','filename_title':'TXS上游异构体工程与CYP725A4产物选择性的证据边界','journal_short':'ACS Synth Biol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded6physicalpages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('KCRKWWRP-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
