import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'9BYJS95S';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Chart 1',2,[41,64,285,343]),('Chart 2',2,[297,64,543,454]),('Figure 1',3,[48,64,546,277]),('Figure 2',3,[48,303,289,664]),('Table 1',3,[303,304,547,440]),('Figure 3',4,[41,531,544,728])]
gaps=['Review historical firsthand narrative6pages2authors no new experiment no clinical guidance cited19papers unread independently','Visual PDF25(5)4824872014 ZoteroJune2014month not inferred exact day','Preparedfigureindex empty actual Chart1Chart2Figure1Figure2Table1Figure3 all6 manually identified','12kg air dried stem bark 0.5g recovered0.004167percent41.667ugg not absolute tissuecontent mass loss not analyterecovery','Table1visible ED503.5e-5ugml extractedmgml1000fold difference preservevisible historicalvalue original unverified','T/C Walkerweight ratio lowerbetter versus survival higherbetter Table1negative77 notordinarymassratio definitionunclear notinvent responseformula pluslevelsnotPvalues','Figure3A549ControlTaxol not adjacentHeLa orrefmousefibroblast no scale dose time n quantifiederror','Compound2to6historicalderivatives structuresXraypluschemical evidence original1971unread UV272IR1680delta6.46oxidationderivative notTaxol itself','Photoaffinity threecontacts not3independentpockets drugnormalnoncovalent versusmodifiedcrosslinks electroncrystal3.7A distinctevidence','Clinicaldatesregimensonlyhistorical no currentmedicaladvice justthisyear2013received2014pub not2026 no updatedFDA verification','No clinicalcostLCA TEA nP CI humanreviewfalseclassificationdeferred']
figs=[{'label':l,'caption':('原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'6pages2authorsAntiCancerDrugs25:482487DOI liveZotero verified Review','paper_type':'review','source_article_type':'Review article','title_zh':'紫杉醇发现开发史的结构证据与药理模型边界','filename_title':'紫杉醇发现开发史的结构证据与药理模型边界','journal_short':'Anti Cancer Drugs','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded6pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('9BYJS95S-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
