import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'WI8WUXWN';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',2,[31,63,556,727],[]),('Figure 2',4,[31,66,286,253],list('AB')),('Figure 3',5,[40,66,296,237],[]),('Figure 4',6,[31,65,556,543],[])]
for label,page,bbox,panels in specs:
 pg=doc[page-1];file=d/('WI8WUXWN-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file));caption=next(x['caption'] for x in rec['figure_candidates'] if x['label']==label)
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
draft={'identity_matches':True,'identity_reason':'OriginalPDFtitle 3authors DOI volume48791-97 matchliveZotero; automaticfalse title manuallyresolved; online6June2009 distinctJulyrecord.','paper_type':'research','title_zh':'TAX9与TAX14乙酰化及紫杉烷旁支证据','filename_title':'TAX9与TAX14乙酰化及紫杉烷旁支证据','journal_short':'Arch Biochem Biophys','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':['抑制表达仍在进行，无本文体内通量或敲低增产证据','TAX9>95% vsTAX14约25%纯度，未充分展示活性酶量校准与全部动力学原始拟合','B三种微量单乙酰化产物仅LCMS加位置推断，未逐一NMR确证','全部原始NMR谱图未本地提供，主文只部分数据；精确P/CI/独立酶批次未报告','初筛clone计数及C13绝对否定与少量taxusin检出有措辞边界，参考15/28卷年未经外部核查'],'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'KM_TAX9_A_uM':400,'KM_TAX14_A_uM':19.5,'KM_TAX9_to_TAX14_ratio':400/19.5,'KM_TAX9_B_uM':180,'Km_ratio_not_flux_or_binding_ratio':True,'rate_reported_range_per_s':[.9,1.5],'TAX14_purity_approx_percent':25,'TAX9_purity_greater_than_percent':95,'rates_not_reestimated_for_purity':True,'in_vivo_flux_measured':False,'knockdown_increase_observed':False});print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
