import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'WPSKKB3W';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[304,463,425,633]),('Table 1',2,[99,601,425,715])]
gaps=['Four full pages text and original pages read viewed; original unnumbered chemical structure assignedFigure1 note-only and complete Table1; no raw spectra or SI;20references notindependentlyread','PrintedPIIS0031-9422(96)00384-6 matches Zotero DOI suffix no literalcompleteDOI printed automaticDOIfalse overridden titleauthorsPhytochem44(2)271274; liveZotero200','ReceivedMay131996 copyright1996 volume1997 ZoteroJan1 not independentlyverifiedonline date; twoauthorsPeterCohen GHN Towers noexplicitCOI NSERCno grantnumber','Lichen Nlaevigatum semipurifiedactive tissue fraction notsinglepureprotein or sequencecofactor identity; commercialCfumagoCPO differentmaterials than citedXparietina vanadiumbromoperoxidase','Lichen1to2 1mg30percent20h firstdetection; no reported4/5; substrate2 no further5 nondetectnotabsolutezero noLOD','Fungal1to2/4/5 masses1mgeach yields30/30/27 first20/20/68h; same totalmass not100percentmolar conversion; secondsubstrate2to5 3mg90percent first40h endpoint68h','Nonenzymeperoxidechloridecontrol gives1to2/4/5 first40/40/68h; no further2 chlorination; earlierTLC notinitialrate no proven directactive-sitechlorine transfer or diffusiblechlorine exclusion','Table1control4 1mg30percent vs productparagraph.5mg30percent unresolved; DMF20buffer14 means41.2buffer58.8DMF versustext6:4bufferDMF conflict no silentrecipecorrection','Triplicateinitialsolutions then sixmixtures two substrates threeconditions notthree independentreplicates percondition;twoenzymeisolationbatches notallconditionn2;noSDexactP CItests','Dimedonactivity30nkatmg and equal100nkat notequal targetsubstrateproteinmolaractivity; noemodinkcatKm','UV EIMS 1HNMR author productidentity matches priorreports puritiesverifiedRPHPLC no rawplots or numericpurity; blanktablefieldsnotzeros','Naturaltissue prioracetate C5 chlorinatedobservations versuscurrentC7 selection notresolved;chlorideinhibition enzymeextractionlossdenaturation hypotheses not measured;originoflichenproteinunknown','Allrightsreserved originalfigurepreserved humanfalse classificationdeferred']
figs=[{'label':l,'caption':('原文未编号结构图，Figure 1 为笔记编号' if l=='Figure 1' else '原文 Table 1：完整反应产物及检测时间表'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'PrintedPII title authors journal44:271-274 match source despite no literal DOI','paper_type':'research','source_article_type':'Research Article','title_zh':'地衣与真菌酶制剂对emodin的氯化选择性及背景反应','filename_title':'地衣与真菌酶制剂对emodin的氯化选择性及背景反应','journal_short':'Phytochemistry','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex four pages fully read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
