import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'W9Z8EZLL';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Scheme 1',2,[51,32,297,451]),('Scheme 2',3,[51,32,559,277]),('Scheme 3',4,[51,32,559,186]),('Scheme 4',4,[51,190,559,396]),('Scheme 5',5,[51,32,559,267]),('Scheme 6',5,[51,271,559,523]),('Scheme 7',6,[315,32,559,131]),('Scheme 8',7,[51,32,297,410]),('Scheme 9',9,[315,32,559,214]),('Table 1',7,[315,35,559,214])]
gaps=['Readviewedall10mainpages originalScheme1-9allstructures titlesreactionconditionlines andTable1allrowsfootnotes; noFigure SIrawionfiles unavailable', 'Title5authorsBiochemistry35(9)2968-2977 originalBI9526239matchesZoteroDOI10.1021/bi9526239 thoughfullDOInotprinted;ZoteroJan11996notverifieddate abstractFeb151996notjournaldate', 'NaturalTaxusbrevifoliastems partialpurifiedenzyme notM60recombinant; tissue2yearsaplings saturating15microMGGPP1mMMg nohomogeneousenzymekcat', 'Normalconversion4to5percent prep~1nmol absenceotherolefins<.05percentsubstrate<7pmolh distinctdirectexogenous<.1percent<5pmolh notzero', 'Scheme2to6organiclabelchemicalpreparation notbiosyntheticroutes substrateDatompercent separatefromreactionyields;C4D2notlater4RsingleD stereospecassignments', 'Table1backgroundcorrected P272Pminus15257Cring122 fiveD277262127 threeD275260125 C4D2oneD273258123 andC2D1273258123;blanknotzero', 'TableD2O8plusminus2 C10D85plusminus5 uncertaintytypenandCI unreported notassertSDSEM independentculturen', 'FiveD3.6threeD4.0versus4.2tritiumparallel andC4D24.1vs4.3parallel notcombinecontrolsorcomputeintrinsicKIE', 'C20Dretentionopposespreliminary4(20)isomerization C1Dretentionopposesparticularcasbenemodel C4GGPPmappedC5product lostoneD notproductC4', 'Exogenous15microMolefins9to14percentapparentinhib inclunrelatedsandaracopimaradienenonspecific; noincorporation<.05percent direct5microMno<.1percent notallboundintermediateexcluded', 'Trappingrecovery~85 verticillene6vs210dpmpermicrog ratio2.857percent specificactivitynottotaltrappedflux percentage', 'D2Ototalrateattenuated~60percent productD8plusminus2 notzero norintrinsicsingledeprotonationKIE', 'C10GGPP toproposedC11 intermediate thenCringfragment122to123 supported actualpositionmostlikelyC7 asauthorsdiscussion notdirectNMRalphaassignment;85plusminus5vsinput>95notexactfullretention', 'Unknownolefin~10percenttaxadienelevelretentionverticillene parent272noD SIMpartialinsufficientID notconfirmedverticillene orwholeproductfraction', 'Scheme9enzymebasemediated1Sverticillenehistoricalmodel notidentifiedbase capturedintermediates norcurrentdirecttransferproof; slowperhapsratelimitingnotfullpathcontrolmeasured', 'NIHCA55254CA64483McIntireStennis0967AmericanCancerSociety explicitmodernCOIrepo unavailable allcitedrefsnotread humanreviewfalse classifylater']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original title fiveauthors35(9)2968-2977 and BI9526239code corresponds liveDOI; completeDOInotprinted','paper_type':'research','source_article_type':'Original research','title_zh':'天然TS同位素证据与酶内氢转移模型','filename_title':'天然TS同位素证据与酶内氢转移模型','journal_short':'Biochemistry','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex all10mainpagesreadviewed9completeSchemesandTable1 originalatomnumbering fragmentmappingexogenousnegativeboundcaveat and1996baseassistedmodelscopechecked'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
