import json,re,fitz,hashlib
from pathlib import Path
import worker as w
w.GRAPHIC_PATTERN=r'(?:(?:Extended Data )?(?:Figure|Table|Scheme|Chart) (?:S?\d+|[IVXLCDM]+)|Graphical Abstract|Unnumbered Structure Graphic(?: \d+)?)'
d=w.ROOT/'sources'/'U7HI9RTR';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
si=Path(r'C:\Software\Data\02-Zotero\storage\BY4L2FWE\ja1c07182_si_001.pdf')
paths={'main':Path(rec['main_pdf']),'SI':si};docs={k:fitz.open(p) for k,p in paths.items()};hashes={k:hashlib.sha256(p.read_bytes()).hexdigest() for k,p in paths.items()}
spec=[('Scheme 1','main',2,[59,65,568,282]),('Figure 1','main',2,[59,288,302,684]),('Figure 2','main',3,[59,335,302,601]),('Scheme 2','main',3,[323,200,568,480]),('Figure 3','main',4,[59,65,568,404]),('Table S3','SI',18,[88,77,510,675]),('Figure S10','SI',28,[75,80,510,496]),('Figure S12','SI',30,[75,80,515,496]),('Figure S17','SI',35,[87,70,510,453]),('Figure S18','SI',36,[87,70,511,714]),('Figure S22','SI',41,[87,70,512,356])]
gaps=['All six main pages read and viewed; selected SI methods and evidence pages checked, not all 44 SI pages independently reviewed; no raw NMR/MS files and not all references independently read','Corrected GedF ORF experimentally used, not original N-terminally truncated database annotation; identity JACS2021 Communication143(40)16326-16331 seven authors DOI matches live Zotero200','Intermediate4 unstable mixed with questin1 before NMR; TableS3 C10 66.8/H5.48 CH(OH), C9 no signal and some carbons inferred from HSQC/HMBC; H4 7.03 table versus7.04 figure rounding/overlap retained','GedE deletion no obvious profile change under tested conditions only; questinol5 sidechain oxidase not identified here','No added FAD required; S17 denatured protein supernatants no detectable FAD/FMN; not a universal proof absence of all metal/cofactor types; GedF NADPH requirement distinct from GedK','S22 NADPH preferred but small NADH product signal not zero; no kinetic cofactor affinity ratio reported','18O2 doublelabel delta4.0086Da, mixed gas only unlabelled/doublelabel, H218O S18 no shift; oxygen exchange universally absent not proved','Scheme2 transient radical/peroxide steps proposed, not individually isolated or verified by EPR/structure/energy measurements','Figure3 nine substrates different incubation times 6min 90min 8h 13h; no uniform initial-rate ranking; analogous products HRMS not every full NMR stereo/regiochemical proof','SI phylogeny uses16 conserved amino-acid sites and neighbor joining; no formal coevolution proof or all homolog functional validation','Figure3 error-bar replication definition not established in checked text; no invented n SD P value; no bioactivity assays here','All five complete main schemes/figures plus six selected complete SI figures/table at300dpi; SI S18 physical36 single page not S19 physical37; SI provenance stored independently','No raw production efficiency or Michaelis constants inferred from3min disappearance; human_full_paper_review false and classification deferred']
figs=[];images=[]
for label,kind,p,b in spec:
 doc=docs[kind];page=doc[p-1];cap=('正文' if kind=='main' else 'Supporting Information')+f' {label}（该文件物理第 {p} 页）：完整图表及图注、脚注'
 figs.append({'label':label,'caption':cap,'panels':[],'source_kind':kind,'source_path':str(paths[kind]),'source_sha256':hashes[kind],'pages':[{'page':p,'bbox':[b[0]/page.rect.width,b[1]/page.rect.height,b[2]/page.rect.width,b[3]/page.rect.height],'dpi':300}]})
 out=d/(rec['key']+'-'+label.replace(' ','-')+'-p'+str(p)+'-complete.png');page.get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target)
 images.append({'label':label,'caption':cap,'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha,'source_kind':kind,'source_path':str(paths[kind]),'source_sha256':hashes[kind]})
draft={'identity_matches':True,'identity_reason':'Main printed title DOI authors and pages match Zotero; supplemental DOI matches main','paper_type':'research','source_article_type':'Communication','title_zh':'GedF与GedK蒽醌开环的双酶与同位素证据','filename_title':'GedF与GedK蒽醌开环的双酶与同位素证据','journal_short':'J Am Chem Soc','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex six main pages read/viewed and selected SI evidence independently checked; overall dioxygenation separated from proposed microsteps'})
w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-supplement-provenance.json',{'path':str(si),'sha256':hashes['SI'],'pages':len(docs['SI']),'review_scope':'Selected methods and evidence, not all44pages','original_main_sha256':hashes['main']})
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
