import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'6VFAN6L4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[265,72,464,460]),('Figure 2',2,[55,72,255,372]),('Figure 3',2,[257,72,470,156]),('Table 1',2,[264,176,466,556]),('Table 2',3,[54,73,251,240])]
gaps=['All three main scanned PDF pages read and viewed Figures1-3 Tables1-2 complete300dpi crops; originalMSNMR spectra unavailable no SI','Live Zotero200 titlethreeauthors matches; source1979November32issue11pp1210-1212 Crossref200DOIverified cachedidentity; sourcePDFnotprintsDOI automatedidentityfalsesupersededmanualcheck','MalbrancheapulchellavarsulfureaNo26compost historicaltaxonomy no DNAphylogeny currentnameunverified; growthyeastglucoseagar vs SEMcaptionyeastmaltextractagar distinguished','37Crough50CsmoothSEM no morphologyquantificationrepeatsscalebar; growth45to50optimal notproductiontemperatureoptimum','Mainlymycelial association no extracellularmassbalance; isolationprocedure no isolatedmass totalculturesize recoverytiter; ethylacetateinsolubilityversuspartition step retainednotinventedsolubilitymechanism','C30H26O10nominalMW546DBE18 no exactmassppm; UV273385nm CHCl3; NMRexternalTMS notinternal no full13C2DNMR','ProposedFigure3samehistoricvioxanthinstructure notstandardcoinjectionorfullmodernstructuralidentity;332decompvs190to195explicit unresolved; rotationplus3.46c.95CHCl3notabsoluteconfigpurity','Table1 25strainrows11positive14negative notreplicates; fourpositiveMICle.045 three.095 two.19 one.39one1.56 all14negativegt100; limitsnotexactvalues','Table2 threeBfragilislt.39 Fglutinosumgt200 Fnecroforum12.5to25rangeasprintednotmeanSD; originalstrainspellingsretainednotmoderntaxonomyasserted','Bodyagarplatediffusionversustablefootnoteagardilution methodologicalwordinginconsistency explicit; differentmediaandduration acrossgroups no anaerobiosiscauseclaim','No independentrepeatcountQCpositivecomparatorstatistics no Pvalue; no measuredmoleculartarget invivoefficacytoxicity;otheractivitiespromisednotreported','SC30532weakerqualitativecrossliterature no sametimecontrolratio; threecitedsourcesnotindependentlyread; K Uenoacknowledgment no grantCOIdatarepositorydeclared;humanreviewfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title threeauthors JournalAntibiotics1979 32issue11pp1210-1212 CrossrefDOI200 liveZotero200','paper_type':'research','source_article_type':'Original research short article','title_zh':'嗜热真菌Tf-26Vx的历史结构比较与条件性抗菌谱','filename_title':'嗜热真菌Tf-26Vx的历史结构比较与条件性抗菌谱','journal_short':'J Antibiot','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full scanned pages read and viewed plus Crossref identity record; original research historical structural claim and censored MIC values distinguished'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
