import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'XUCXLM84';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[55,52,304,763]),('Table 1',3,[80,386,522,760]),('Figure 2',4,[55,54,304,467]),('Figure 3',4,[320,57,570,373]),('Figure 4',5,[46,53,294,686])]
gaps=['All six original mainpages read and viewed Figures1-4 Table1 complete including colored structural panels spectral axes and tablefootnotes; no originalFID rawNMR independentculture replicates SI available','Identity fiveauthors printedtitle PNAS93 pp6431-6436 liveZoteroDOI10.1073/pnas.93.13.6431 date1996Jun25 vs contributedMar4 notpublication; sourceTaxuschinensiscellculture taxuyunnanineC notTaxolitself','Acetatelowcarbonringlabel alone explicitly insufficienttoexcludeMVA becausecompartmentaccess; glucosepatterns andpreservedthreecarbon information maincomplementarydiscrimination','U13Cinput99percent stock diluted1to20 naturalaverage~5.76percent author~6;1position99percentstock1to1 nominal50.05percent author~50; originalsourceculture44days14plus30 notproductivitydirect','2.6percentdryweight vs2.2mgpergwet vs68mgL isolatedrecovery differentdenominators no pairedmassbalance moisturecarbonconversioninferred','Acetatering1.12plusminus.05percent near1.1natural; acetylcouplings internalpositivecontrol notallacetatezerolabel; Table1overlapaverages notindependent resolvedpeakvalues','Figure4C averaged IPPpositions2 4 5=1.33plusminus.07 2.38plusminus.15 8.69plusminus.32percent contradictequalMVA methylsources Figure4D; SDfourbiosyntheticallyequivalentmodules notn4 independentcultures','U13C ringmean4.22plusminus.18percent vs~40percent selectedtripleisotopomer authorsapproximation notsubstrateyield;Table1coupledfractions conditionalcarbon satellite share nottotalculture percent','LongrangeINADEQUATEsignals andpassivespins evidenceconnectivity changes notreactionenzymeidentified; rawpeakprocessingunavailable notclaimed reproducedNMR','UltimateIPPprecursors explicitlyunknown; specificRohmermodelnotallpredictionsmet no directDXP MEP DXS DXRcompletepath demonstrated; oldbiomassrecycling30percentacetyl dilution hypothesisonly','Othermonoterpenes higherplantsgeneralization citesunpublished data notdirectlyvalidated; MVA source conclusionstudiedtaxanering notallplantmetabolism orallconditions','All references notindependentlyverified historicalprioritynotchecked humanreviewfalse classificationdeferred noexplicitmodernCOI datarepo inferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original title fiveauthors volume93 pp6431-6436 matchesliveZoteroDOI; actualtracercompoundtaxuyunnanineC taxane skeleton context preserved','paper_type':'research','source_article_type':'Original research','title_zh':'紫杉烷骨架非MVA来源的同位素证据与替代路径边界','filename_title':'紫杉烷骨架非MVA来源的同位素证据与替代路径边界','journal_short':'PNAS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex all six original pages read viewed; atom positions abundance versus coupled fractions examined; MVA model rejection distinguished from incomplete alternative pathway identification'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
