import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'N5FYZAQ6';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[98,130,562,790]),('Figure 2',5,[87,95,562,731]),('Figure 3',6,[48,95,562,616]),('Figure 4',7,[88,175,562,640]),('Figure 5',9,[86,346,562,731])]
gaps=['14mainpagesreadandviewed5completeFigures300dpiSI S1toS5 TableS1 unread GenBankON759763notdownloaded referencesnotindependentlyread','TitleabstractTaxuschinensisMethodTaxusmediaunresolved;ResultsRi17complementMethodsCol0unresolved','TcJAV3MeJAexpressionFigure1noexactmeansfullqPCRparametersnotreportedmaintext nofoldinvented','Figure2body5dayscaptionmethod7days statisticslesiontsurvivalANOVAversusmethodsopposite starsconflict n12threerepeatsnotassumed36independent','Sequence10plus25equals34 sourceconflict95to128vs95to130;Figure3Cx2CcaptionCx4Ctextconflict noresiduemutagenesistest','Y2HBiFCLCIsupportinteractionnotTcJAV3inhibitionnoTaxusnativeCoIP noKdJAdependentdissociation','Y1HwaresponsehighernotKd threecopybaitsprogressivedeletionsnotcleanpointmutation noChIPEMSAnativewaessentiality','Figure5JAubiquitinationdegradationphosphorylationE3modeluntestedtwoalternativesnotindependentnonredundantequalimportanceproof','NoTaxusmetabolicinterventionpaclitaxelquantyield DBATtwofoldpriorreference27notnewresult;classificationdeferredhumanreviewfalse']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'14pages title8authorsIJMS23:13194DOI verified','paper_type':'research','title_zh':'TcJAV3与TcWRKY26互作及DBAT启动子调控的证据与JA模型边界','filename_title':'TcJAV3与TcWRKY26互作及DBAT启动子调控的证据与JA模型边界','journal_short':'Int J Mol Sci','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded14pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('N5FYZAQ6-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
