import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'FWQS6REW';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[316,184,559,342]),('Scheme 1',1,[315,348,559,560]),('Figure 2',2,[52,43,294,195])]
gaps=['Twofullmainpages text original imagesread; allFigures1/2Scheme1 complete300dpicrops alltracesstandardproteinlabels metabolites1-8; SIunavailable rawNMR constructboundaries radiometriccurvesnotindependentlyread cited15referencesnotallread','LiveZotero200 sixauthors Ma Zhan Xie Watanabe Tang Zhang UCLAUSC DOIprinted JACS1301:38-39 2008 webDecember122007 receivedOctober22 preserveonlinevsissueyears','Actual GfujikuroiPKS4 proteins Ecoli expression in vitro products;1SMA76abikaverinprecursornotbikaverin cellfactoryfermentation','S1830Aexpression8mgL vs2product1mg10mL distinctquantities; deletionexpression2mgL product.9mg10mL standaloneTEexpression5mgL no inventedgrowthproductivity','Figure1Awt1 Bmut2 Cdelete2 DEmut/delete plusstandaloneTE partiallyrestore1 notcomplete; lowermutrescue competitivebinding hypothesisnotKd','2MminusH341 UVNMR benzopyrone author SI notindependentallHMBC; O9C1esterthenC12C17 aldol proposedsequence notallintermediatesobserved','Scheme1 GrisCYC1 OxyCYC2 labels correspondbodyGrisARO/CYC OxyN notadditionalinventedenzymes; ACPbound intermediates7/8schematic notatomstructures','Figure2C actKR NADPH3mutactinMminusH301 standardRfLCUVmassmatching notdenovoNMRall; omitNADPHabolishes3 supportsKRcatalysis','Figure2DgraphActKR GrisCYC OxyCYC captionDlistsPKS4GrisOxyNomitsKR bodyC9reducedcontext; preserveoriginaldiscrepancy exactrecipeSIpending','2carbon14malonylradioTLC KRatleast equimolar large3 higherKR saturates 10foldKR3:1ratio1:2.5; conditionalnormalized28.57percent oftworeadoutsnotyieldpuritycarbonbalance orKd','SEK34data notshown cannotindependentlyverify;DMAC5octaketideSEK266nonaketideeach.2mg10mL with1 standardmatches;inferredKRaccessfullchain no directtimecoursecapture','ACS320vs280nm plotsnotdirectcrossquant; no replicatesCIPvalue;PTproposedproteinchainshieldingKRcyclizationmodel noatomiccomplex','AHA0535069N NIGMS1R21GM077264 noexplicitCOI humanfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title DOI six authors JACS130:38-39 two pages liveZotero200','paper_type':'research','source_article_type':'Communication','title_zh':'真菌PKS4环化改道与细菌修饰酶的跨体系合作','filename_title':'真菌PKS4环化改道与细菌修饰酶的跨体系合作','journal_short':'JACS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex two full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
