import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'T653KQDL';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[200,238,415,300],[]),('Unnumbered Structure Graphic 1',2,[53,79,295,225],[]),('Scheme 1',2,[53,303,295,445],[]),('Scheme 2',3,[53,50,295,310],[]),('Scheme 3',4,[53,50,295,254],[]),('Table 1',5,[53,50,559,355],[]),('Table 2',5,[53,362,559,560],[]),('Figure 1',6,[53,50,295,412],['a','b','c']),('Figure 2',6,[317,50,559,340],['a','b']),('Unnumbered Structure Graphic 2',6,[53,590,295,656],[]),('Unnumbered Structure Graphic 3',6,[317,485,559,543],[]),('Unnumbered Structure Graphic 4',6,[317,618,559,683],[]),('Scheme 4',7,[53,50,295,197],[]),('Scheme 5',7,[317,50,559,225],[]),('Unnumbered Structure Graphic 5',7,[53,382,295,502],[]),('Scheme 6',8,[53,50,295,281],[])]
gaps=['All9physicalmainpagesfullreadviewed5authorsJOC704667–4675DOI;GA2Figures2Tables6Schemes5unnumberedstructuregroups16crops','SIotherNMRGCMSrawtracescompletecharacterizationnotreadindependentreanalysisnotclaimed','C1GGPPenantio98–99assumedanalogygeranylPPnotdirecteachGGPP;C4precursor95to5late91to9inferredcorrected8to1epoxideratio','Table1H2alpha1.62H2beta1.72bodycallinghigherfield1.72conflictingdescriptor retained','ReferenceTablesracemictaxadienenotcrystalofTSorreactivecarbocation;Karplusanglemodelnotfixedenzymeconformation','Figure1StoCSYabsenceofbothsignals nottwoDs isotopecount1blockedspintransfer pathway modelplusNOE','RlabelC1to2alpha Slabelto2beta supportsinversionnotdirecttimesresolvedconcertedness','TransmethylC16D3label1.09disappears1.32remainsFigure2extra1.36impuritynotnewproduct','Oppositefaces14re15siantiaddition requiresknownH1beta+priorpeakassignments;H11transadditionalfluoroprobestudynotsolecurrentisotopeproof','C4productGC10to10to80MS273273272;firsttaxa34isomer24TENTATIVE basedMSfragmentnotfullNMR','Unlabeled24about1exoisomer25about4–5 vslabel10each;isotopeeffectinterpretation noexactkHkDcalculated','H5betaeliminationbodypredominantlyvsexclusively;91to9substratepuritylimiteddetectionnotuniversalabsoluteexclusivity','Preparatives5to10percenttypical6notpurekcatindustrialTaxolpathconversion;nerrorPnotreported','DirectC11toC7protontransferoractive-siteindirectnonexchangingrelayexplicitbothretained','EnzBschematicunspecifiedbase notconfirmedTSresidue;twistboatenergeticfavorabilitymodelnotmeasuredbarrier']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':'原文 '+l+'：完整结构、数据与图注；保留所有氘位置和编号','panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a in spec]
draft={'identity_matches':True,'identity_reason':'Directreadall9physicalpages5authorsJOC704667–4675DOI2005May12','paper_type':'research','title_zh':'氘标记约束紫杉二烯大环化与消除立体化学的证据边界','filename_title':'氘标记约束紫杉二烯大环化与消除立体化学的证据边界','journal_short':'J Org Chem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'DirectCodex9mainpagesreadoriginalpageQA'})
images=[]
for l,p,b,a in spec:
 out=d/('T653KQDL-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':'原文 '+l+'：完整结构、数据与图注；保留所有氘位置和编号','page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
