import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'8EX6AA7K';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',3,[66,86,549,583]),('Figure 2',4,[47,86,530,731]),('Figure 3',6,[47,86,530,715]),('Figure 4',8,[47,86,550,636]),('Figure 5',9,[66,86,549,630]),('Figure 6',10,[47,86,530,665]),('Figure 7',12,[47,86,530,398])]
gaps=['18mainpagesreadandviewed7complete300dpiFigures SI S1to6 Tables1to18 DatasetS1unreadrawMSRNAunreadrefsnotindependentlyreadhumanreviewfalse','ThreeindependentstemMSandRNA3yearmaireiMethodsprotoplast15to20stemsperreplicatemappingplantindependenceunclear','MSaverage6476pixels6354featuresdifferentobjects3replicates20um10ppmlibraryannotationnotallconfirmedstandardsabsoluteconcentration','Figure2TaxolCephalomanninemainlyredPC3buttextPC3endodermisPC5epidermisandclaimepidermisconflictdoNotrelabel','21233cells766084115162median2996bodyindividual228829813718Fig3notmeanpooledreplicate1530enriched14788input18clusters13markersfourunannotatedgroups','CellRanger6.1.1Seurat3.1.1Monocle2qualityUMIless500literalunresolvedWilcoxonbimodmethodconflictseveralUMAPcaptiontSNEaxis','ctg5026gene32DBATthispaperT10OHleafpaperCYP725thispaperconflictDatasetunreadctg8816gene2T14OHdiscussionTSconflictT10OHincompletectggene32actualfigurectg2120gene10','487CYPpriorgenomebulk42bark114strob130leaf90rootnotall487subtypes36candidateTF20+5+5+6coexpressionmotifnotallbound','WRKY31TATnegativeEMSA MYB47TSbindreporterunchangedMYB47T5activatebHLH68TATT10activateNAC2DBTNBTDBATrepress;captionallactivateoverstates','GSTresultsHisPET30NiMethodsconflictFigure6bTATctg2120gene5isT10OHelsewhere reporterlistT10OHomittedGAL4BDVP16controldescriptionunclear3biorepSDnoexactPCI','235ABCsum7+66+25+3+1+10+73+3+30+17humanABCGhomolognotplantsubstrateproofctg5370gene6membraneheterologousprediction7CtermTMnottransportATPdirectionturnovernativecausality','PRJNA730337genomeandRNAreuseunverifiedmarkerOsMCA1methodOsMAC1captionconflictWRKY33backgroundrepressorversuspositivecitedtitle;classificationdeferred']
figs=[{'label':l,'caption':('原文 Movie 1 静态海报及图注（内部索引 Chart 1，视频未读取）' if l=='Chart 1' else '原文 '+l+'：完整图表及图注'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'18pages title17authorsPlantJ1151243to1260DOI liveZotero verified','paper_type':'research','title_zh':'红豆杉茎单细胞调控证据与ABCG2紫杉烷运输候选的边界','filename_title':'红豆杉茎单细胞调控证据与ABCG2紫杉烷运输候选的边界','journal_short':'Plant J','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded18pages'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/('8EX6AA7K-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images)
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
