import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'JNTM74E7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',1,[130,513,468,651]),('Table 1',2,[44,39,559,247]),('Table 2',2,[44,259,559,389])]
gaps=['All three Englishmainpagesreadviewed Figure1Tables1-2 completeoriginalcrops; raw2DNMR unavailable noSIfiles referencesnotallindependentlyread','LiveZotero200 andprintedtitlefiveauthorsFoshanHainan47issue5pp767-7692011November matching; DOIregisterednotprintedCrossrefrecordcached; RussianoriginaldifferentpagesnotEnglishcitation','TwoAspergillussp FSY01FSW02 rottenAvicenniamarinafruitZhanjiang depositedFoshan no speciesDNA no singleculturematchedcontrols no inductionorproducerassigned','50L mixedmycelia25mg pure1 equals.5mgL isolatedrecovery notanalyticaltiter noextractionrecoveryreplicates; no brothvsmyceliumquantitation','C20H17N3O4nominalEIMS363DBE14 nohighresolutionppm; experimental.4H2Ocomposition notcovalenthydration ion; fragment29555percentnopathassigned','Table1DMSOd6H400C100TMS HMBCwrittenCtoH associationnotatomtransfer;20C sixaromaticCH ninequaternarysp2 oneCH threeCH2 oneOMe;C23NHnotextraC','C13H24HMBCsupportsOMe13 C18151.3C=Nauthorsproposal notcarbonyl; H5H6H7strongcoupleoverlapfootnote preservedweakHMBC notrawrechecked','Lprolineanthranilate structuraloriginhypothesis notfeedinggenesenzymes; minus96c.12MeOHrotationnotabsoluteconfiguration proof noRSECDXray','Table2compound1sixMIC62.5 31.25 15.62 15.62 62.5 31.25 compound2 .98 .49 1.95 7.8 7.8 15.62alllower MICratiocalculatednotstatisticaleffect','GatifloxacinBsubtilisNot tested notzero; norfloxacinEcoli gt125 notexact125; compound1notgloballysuperiortocomparator; significantwordingnotreportedPvalue','OriginalBacillusdysenteriaeBacillusproteusclassifiednegative keptasprintedtaxonomyunverified strainsunnumbered; selfreportedfinal1to2e8inoculum notsilentlychanged claimedCLSIolderstandardnotindependentlychecked','No replicatevariancePvaluesMBCtargetcytotoxicityselectivityin vivo; no fundingCOIrepositoryexplicit notinventedabsence;humanreviewfalseclassificationdeferred']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title fiveauthors47issue5pp767-769 English2011 CrossrefDOIregistration liveZotero200','paper_type':'research','source_article_type':'Original research article','title_zh':'Aspergicin的结构证据与混合培养抗菌比较','filename_title':'Aspergicin的结构证据与混合培养抗菌比较','journal_short':'Chem Nat Compd','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex three full original pages read and viewed; structural and MIC evidence separated from untested coculture induction and precursor assumptions'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
