import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'IDRG7GFP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[57,55,311,577]),('Figure 2',4,[57,58,311,295]),('Figure 3',4,[320,58,574,282]),('Figure 4',4,[320,532,574,742]),('Figure 5',5,[57,58,311,244]),('Figure 6',5,[57,413,575,742])]
gaps=['All6mainpagesreadviewed allFigures1-6complete captions axes spectra chemicalstructures andfullsequencealignment; noTable', 'Printed firstpageDOI10.1073/pnas.251539398 verified title4authors98(24)13595-13600; autoDOIfalse from fragmentedextraction; contributedOct112001 vsissuedateNov202001', 'F16GenBankAY056019 deposited asreported notindependentlydownloaded sequence; ORF1458bp485aa MW54652 identity63similarity72vsF14', 'MicrosomalHisimmunoblotlocalization datanotshown rawblot unavailable CO450peakvanishes3to5minutes notabsenceoffunction', 'NADPHreductase approx12 toover240mUpermg lowerboundratioapprox20 notTaxolproduction;positiveF14P450240pmolpermg differentunit', 'HPLCsubstrate43.4product25.6min plusMS304vs288delta16 tentative diol thenNMRsupports5alpha13alpha; 600microgforNMR >99percentGCpurity nottiter', 'CorrelationNMRcitedanddescribed notallraw2Ddisplayed noindependentrawspectrumintegration orlimitofdetection', 'Km24plusminus9alcohol14plusminus4acetate micromolar;triplicateanalysesmeanSD independentbiologicalculturenunknown; acetateconversion~6percent notzero notKmimpliespreferred noKd kcatinvented', 'Reciprocalcrosssubstratesnegativeunderreportedconditions do notexcludeallotherintermediates norlatermerging; alternativeadventitioussubstratevs2pathways unresolvedinvivo', 'Prioroxygenationorderfromtaxoidstructuresandabundancemayincludeoffpathdeadends historicalmodel notcurrentclosedTaxolproductionroute;Figure1dashedstepsundefinedXnegativeverifiedlabels', 'FundingNIH CA55254 CA70375 Cytoclonal McIntireStennis0967; modernCOInotreported notassertnone; allcitedpapersnotread', 'ReadbenignplantP450functionalbiochemistry expressedhostplatform highlevel no virusconstructionpropagationinfectionoperationalinstructionsadded; humanreviewfalse categorydeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original title fourauthorsvolumepp13595-13600 and printed firstpageDOI verified againstliveZotero','paper_type':'research','source_article_type':'Original research','title_zh':'Taxane13α羟化酶鉴定与早期路径分支','filename_title':'Taxane13α羟化酶鉴定与早期路径分支','journal_short':'PNAS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex all6mainpagesreadviewed fullFigures1-6 source biochemicalproductstructure kineticdenominators andinvivopathuncertaintychecked'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
