import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'9IDKAPJ8';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[13,40,534,256]),('Figure 2',3,[46,38,500,365]),('Figure 3',7,[13,39,534,685]),('Figure 4',8,[13,39,270,405]),('Table 1',6,[13,39,270,243])]
gaps=['All10mainpagesreadviewed originalFigures1-4 plusTableI fullpanels3ABCD4AB captions Figure3rightcolumncontinuationpreserved withoriginalpagecontext noSIrawavailable', 'Title7authors379(1)137-146 July12000 DOI10.1006/abbi.2000.1865firstpageverifiedliveZotero receivedFeb23revisedApr4notpublicationdates', 'M60M79pseudomature notactualnativeprocessingboundarydetermined; M1M60M79active M93M113M126proteinpresencebutnegligiblefunction data notshown noinventedexactsequence', 'TableI Km microM notOCRmM kcat secondsinverse native3/.0106fusion3.1/.0025M110.5/.0024M6015.9/.0102M7914/.0080; nativefusionpreviousrefs notsamebatchtriplicatebioculture', 'TableIkcatinactive<.00001 vsbodyrough<.0001 factor10 retained notpatched; blankKmnotzero triplicateaverages SE<10percent noexactSECI P or independentexpressionn', 'YieldM6030to40mgL M7910to20mgL purifiedprotein nottaxadienetiter; expression30to40percentsoluble vsM110percent purity>99vsM1~50 separatedenominators SDSnotshown', 'M60stability10days<30percentloss withsubstrateMghexaneproductremoval versusM792days70loss notsameendpoint cannotinferuniquehalf-life;M60solubilityatleast20mgml M79aggregatesabove5', 'Normalproducts94.0 4.8 1.2=100; majorand4(20)authenticstandards verticillene tentative;marked77.6 11.1 9.2 1.1sum99.0missing1.0notrenormalized', '4R[4D1]GGPP84molpercentD correspondingproductC5betaHre eliminated;3(4)10.29min m/z273 tentative noNMRconfirmed allminor; isotopeeffectrough2 notintrinsiccorrected mixedlabelk', '4(20)relative11.1/4.8 notabsoluteformationgain noaddotherpaperhalf-totalrate tothisexperiment; verticillenepriorbranchinterpretationnotdirectcarbocationcapture', 'Candidate3racemiccyclogeranylgeranylD2 noolefin versusGGPP>100pmol arguesexternalintermediate but authorsretain boundunexchangeabletransientcaveat', 'Inhibitor4and7notime-dependentinactivation Methods50microM results100microM discrepancy;4olefin~30percentrate parent270base122consistentcyclotaxadiene notfullyNMRproved7notconvertedbutweakinhibitor', 'I50at30microMGGPP90candidate3 120candidate4 100candidate7microM notKi andnotprovedcovalentmechanism orfulldiagnosticcompetitivekinetics', 'NIHCA55254GM13956GM31354CytoclonalMcIntireStennis0967 explicitmodernCOInotavailable rawGCblots labeledsubstratesynthesiscitedelsewhere nohumanreview allrefsnotread categoriesdeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original fulltitle sevenauthors379(1)137-146 and firstpageprintedDOI verifiedliveZotero','paper_type':'research','source_article_type':'Original research','title_zh':'TS拟成熟截短体与环化分支机制','filename_title':'TS拟成熟截短体与环化分支机制','journal_short':'Arch Biochem Biophys','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex all10mainpagesreadviewed fourcompletefiguresandTableI originalmicroMunits andcrosscolumncaption checked; nativeboundarytentativestructuresandoriginalparameterconflicts preserved'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
