import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'8ZTA7F52';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Scheme 1',3,[44,59,543,267],[],'Scheme1.Forwardexternal10DABacetylationandreverseunderalkalineconditions;notdenovotaxanecore/PTX.'),('Table 1',3,[44,282,543,564],[],'Table1.AllM0-M12modulesandplasmids;R0/R7/R8/R10areDBATaddedcounterparts notallMstrainsequivalent.'),('Figure 1',5,[44,59,543,296],list('ABC'),'Figure1.ModulesupplyrelativeAcCoApoolAU notmeasuredflux;M10bestnotmonotonicgenecount.'),('Figure 2',7,[44,423,543,742],list('ABCD'),'Figure2.BiomassAcCoAmgpergDCW baccatinugpergDCW DBATgelgrayAU;R10notmaxAcCoAat8h growthburden n3biorepsSD.'),('Figure 3',8,[52,419,552,742],list('ABCD'),'Figure3.Substrateaxis mgmL caption gmL1000xconflict;aceticacid changesbothsupplyandpH;1.14/1.3/1.57differentendpoints n3biorepsSD.'),('Figure 4',9,[44,59,288,552],list('ABCD'),'Figure4.AllfourconditionspH6/9bufferM0/R10;nonenzymaticandDBATlinkedreversenotallwaterhydrolysis.'),('Figure 5',10,[52,59,552,355],list('ABC'),'Figure5.PureDBATplusM0homogenate chromatograms structuresMS reverseacetyltransferorhydrolysis proposedbranches.'),('Figure 6',11,[44,250,543,742],list('ABCDEFG'),'Figure6.Allsevenpanelsgel included sourcebodymisrefsFig5;initialvsmaintainedpHdiffer;2/3/4.6gLnot98/97/78percentmolyield;3Lreactorinitial1L.')]
for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('8ZTA7F52-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file))
 figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
gaps=['PDFtextlayer mapsmu tom visuallyFigure2C/body101.6ugpergDCW Figure3CugmL Figure2BmgpergDCW','MainPDFarticleinpress final11(10)3322-3334fromliveZotero notprintedreadversion','SIabsent NMR spectraassignmentsCoASHwaterfractionC7epimersS1-7 notindependentlyreviewed','Figure3captionandmethod2.5 gmLvsaxisbodymgmL1000xunitconflict','Results3.4refFig5 actualfermentationFigure6 sourceconflict','MseriesmodulesversusRDBATstrains notinterchangeable','AcCoApoolAU/mgperDCW/mgLnotflux andDBATgelgraynotactivity','Eq1conversionis10DABpeakareadisappearance nottargetmolaryieldselectivity massconcentrationrationotmolconversion','R10notmax8hAcCoA highratiooutputgrowthconfounding','AceticacidbothpHandsupply cannotassignindependentcausalcontributions','CoASH20K6combined50fromunavailableSI notformalstatisticalsynergy potassiumphosphatesnotfullyionmatched','ReverseCoASHacetylacceptor notexclusivelywaterhydrolysis proposedbranchesremain','InitialacidpHgroupsdifferentfrommaintainedpHgroups 55htotal24hproduction','3Lreactorinitial1L finalvolumeafterfeedingnotfullyreconstructed','86percent2.59over3not7.5 crudeextract HPLCpuritynotgravimetricpurity','Figure2/3n3biorepsSD Figure1/6n3SDnotallsamereplicatedefinition allP/CI/rawpointsabsent','External10DABnotdenovobaccatin/PTX historicalhighestnotcurrentverifiedrecord industrialcostnotshown']
draft={'identity_matches':True,'identity_reason':'All13mainpagesreadtextvisual;titleDOIauthoridentitymatchesliveZotero;readPDFinpress finalmetadatafromcatalogexplicit.','paper_type':'research','title_zh':'乙酰供体与DBAT逆向反应的耦合','filename_title':'乙酰供体与DBAT逆向反应的耦合','journal_short':'Acta Pharm Sin B','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'isolation_recovery_percent':2.59/3*100,'isolated_over_crude_percent_not_recovery':2.59/7.5*100,'unit_typo_factor':1000,'conversion_rates_source_definition':'10DABHPLCpeakareadisappearance','external10DAB_gL':[2,3,6],'baccatin_gL':[2,3,4.6],'conversion_disappearance_percent':[98,97,78],'nottargetmolaryield':True,'culture_total_h':55,'production_h':24})
print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
