import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'LJCIHKC9';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[44,665,290,789]),('Figure 2',2,[310,79,555,639]),('Table 1',3,[50,82,558,251]),('Figure 3',3,[44,591,553,789]),('Figure 4',4,[44,79,291,611]),('Figure 5',4,[310,79,553,483]),('Figure 6',5,[50,88,291,499]),('Figure 7',5,[44,618,292,794])]
gaps=['All five main PDF pages text and original images read; seven Figures and one Table including footnotes; no raw NMR or full sequential assignment; cited primary papers not all independently read','Live Zotero200 title authors PNAS87:2077-2081March1990 matches PDF; DOI metadata not printed; communicated December26 1989 not publication date','Actual recombinant GAL4(62*) terminal Leu-Glu replaced Leu-Asp E62D not unaltered full881aa protein; scholarly article not degree thesis despite funding degree acknowledgement','112Cd I0 vs113Cd Ihalf isotope control not different elements; direct coupling evidence primarily Cd substituted not atomic coordinate determination of native Zn','Six spin systems Cys1-6 are arbitrary spectral labels not residue positions; Cys5/6 preliminary assigned Cys38/21 bridge positions not completed sequential assignment','Table1 Zn35C pH5.4 versus Cd35C pH8 not matched pH; missing values not zero; spin3 isotope Ha chemical shift unexplained footnote','Cys5 Cd2 beta5 and3Hz Cys6 Cd2 beta2 and3Hz weak couplings support bridges; overlap raw noise independent reprocessing unavailable','Two fourS coordination contacts need8 edges with6 Cys two shared arithmetic consistency not independent unique geometry proof','Figure7 cloverleaf model assumed Cys21/38 bridges not solved atom coordinates; helical NOESY cited unpublished not fully documented fold','Figure6 metal vsapo spectral effects not cellular transcription or DNA affinity assay;63 and other length constructs prior works not62star','Family LAC9 PPR1 sequence similarity not metal measurement each; DNA contact and downstream specificity interpretation; cellular Zn regulation hypothesis not measured','Transients signal accumulation not biological replicates; no statistical tests CI Pvalues; funding NIH DK09070 GM21919 RR03475 NSF DMB8610557 ACS RD259 no explicitCOI']

figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed title authors PNAS87:2077-2081 five pages liveZotero200','paper_type':'research','source_article_type':'Research Article','title_zh':'GAL4双核锌簇的核磁配位证据与结构模型','filename_title':'GAL4双核锌簇的核磁配位证据与结构模型','journal_short':'PNAS','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex five full pages read and viewed'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
