import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'VEHEPT5K';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[31,67,554,442]),('Table 1',3,[301,540,577,760]),('Figure 2',4,[31,557,286,759]),('Figure 3',4,[301,550,560,759]),('Figure 4',5,[41,68,563,490])]
gaps=['Allsixmainpagesreadviewed Figures1-4andTable1complete300dpi; no rawGCMSindividualfermentfilesconstructsequencesunshownblots allrefsnotindependentlyread','Manualidentity titlethreeauthorsEngelsDahmequalJenneweincorresponding DOI10.1016/j.ymben.2008.03.001 10issue3-4pp201-206 liveZotero200 auto titlefalse causedligatureformatting notwrongPDF','Originalprintedmicrogramunits204plusminus1 306plusminus3 306plusminus1 320plusminus3 228plusminus15 allmicrogL OCRmgincorrect resolvedfromoriginal; highest8.7plusminus.85mgL GGOH33.1plusminus5.6mgL','TargettaxadienenotTaxol firststepnotfullproduction historical2008knowledge notrecentcompletepath; onlineMar262008vsZoteroMayissue','CEN1to10compositiontable verified TDS74residueNterminaldeletion sameoriginalbackground codonoptimizedSynTDS notnovelcatalyticmutants; allfactorialorvectorburdencontrolsnotprovided','tHMG1CEN3to5.204to.306mgL50percent UPC2CEN5to7same.306 noobviousimprovementno directsteroluptakeorfluxproof explicitexogenoussterolsnotlistedinproductionmedium','SaGGPPSCEN7to8GGOH.283to27.6mgL97.5265fold taxadiene.306to.3204.575percent nothundredfoldtarget; tHMG1CEN4to6GGOH6.9to27.4mgL3.971fold','CodonoptimizedplantbackgroundCEN9.228mgLnotimprovedvsCEN7.306 whilearchaealCEN10 8.7mgL vsCEN8.32027.1875fold vsCEN3.20442.647fold vsCEN9.22838.158fold no unqualified40fold singlecomponentclaim','Figure2brokenaxis retained bodyhighest8.7 vsbarappearsaround8 no precisionbarredigitization; independentfermentn3SD no namedhypothesistestexactP CI invented','GGOHendpointsnotintracellularGGPPconcentrationnorinstantflux; biomassandRP18combinedrecoverynotfreeextracellularonly; alkalineprocessingrecoverycalibrationdetailsnotindependentlyverified','Figure4TICret8.2taxadiene10.5GGOH fragments272122107 withstandard supportsidentity no purifiedNMRrawfileverification','GGPPsaavoidingFPPcompetitivefluxauthorrationalenotdirectcompletecarbontracing DMAPPbuildingblockwordingnotextendedintoallDMAPPstoichrecipe','Culture48h28C100mL500mLbaffled2percentglucoseRP18.5percent totalreportedbiomass21.6plusminus2.5gL notperstrainDCW independentplantGGPPSwesternnotshownTDSblotsnotprovided','DFGJE418/3-2 noexplicitmodernCOIdatarepo humanreviewfalseclassificationdeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Printed titleDOIauthorsvolume201-206 matches liveZotero despiteautomaticligaturetitlemismatch','paper_type':'research','source_article_type':'Original research','title_zh':'酵母Taxadiene生产的前体供给与密码子优化协同证据','filename_title':'酵母Taxadiene生产的前体供给与密码子优化协同证据','journal_short':'Metab Eng','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex allsixoriginalpagesreadviewed; OCRmicrogramunitsresolvedfromoriginal; UPC2effectseparatedfromtHMG1 andGGOHproxy distinguished from GGPPflux'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
