import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'R4FKC62M';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[42,335,563,731],[]),('Figure 2',4,[162,94,563,684],['A','B']),('Figure 3',6,[162,190,563,548],[]),('Figure 4',7,[162,485,563,777],[]),('Figure 5',8,[162,94,563,403],['A','B']),('Table 1',8,[162,414,563,747],[]),('Figure 6',9,[162,390,563,765],[])]
gaps=['All15mainpages read and viewed; sixFiguresoneTable complete crops; SIunavailableS1S2TableS1notread','Finalendpointtaxadiene notfullpaclitaxel; Article202111147March3authors5identitymatched','MainfigsamplereplicatenerrortypeSDSEtestdetailsunreported no guessedn orpreciseP','BTS1inhostrankingnotpurifiedenzymekinetics FPPDMAPPpoolunmeasured','Figure3starmeansnonsignificantP>.05;body80foldBTS1vsmERG20 conflicts plottedmERG20similarCrSa no exactnewbarvalue','Report2.02plusminus.40vsconclusion2.05 preserved;TXD6/TXD1fromroundedmeans1836vs1900 source','TXD7 1.18/2.02 retention58.42% loss41.58% vsbodyreduced57%','MVAqPCRnotdirectflux;MBPsolubilitystabilitynotdirectmainexperiment;genomecopydoseproposalnot measured','TXD9usesrichmediumcomparedotherSC;originalrecipe20gLdextroseplus.2glucose1.8galactose retainednotfixed;GCcolumn.25uminnerdiameterunresolved','AllintegratedonlyTXD9TXD7TXD8stillTSBTSplasmid;TSMBPfusionnotTSBTSfusion','4independentcolonies4daysstabilityS2unread48generationsliteraturedoublinginference notmeasured;SIlistS1TableS1omitsS2','GCMSstandard13.1minsamefragmentstrongidentitynotindependentNMRisomersabsoluteconfiguration;calibrationrecoveryLODLOQrawdataunprovided','PlatformfutureP450testnotimplemented;priorhighest57mgLauthorbackgroundnotcurrentrecordverified']
figs=[]
for l,p,b,a in spec:
 rect=doc[p-1].rect;figs.append({'label':l,'caption':'原文 '+l+'：完整图表及图注','panels':a,'pages':[{'page':p,'bbox':[b[0]/rect.width,b[1]/rect.height,b[2]/rect.width,b[3]/rect.height],'dpi':300}]})
draft={'identity_matches':True,'identity_reason':'All15mainpages sourceidentity title5authors2021Metabolites11147 DOI10.3390/metabo11030147 verified','paper_type':'research','title_zh':'CRISPR整合酵母紫杉二烯平台的产量与表达剂量证据','filename_title':'CRISPR整合酵母紫杉二烯平台的产量与表达剂量证据','journal_short':'Metabolites','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexdirectmain15pages SIunread'})
images=[]
for l,p,b,a in spec:
 out=d/('R4FKC62M-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':'原文 '+l+'：完整图表及图注','page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'TXD2_TXD1':10.2/1.1,'TXD3_TXD1':50.2/1.1,'TXD4_TXD1':782/1.1,'BTS1_noGGPPS':782/10.2,'TXD5_TXD4':1.07/.782,'TXD6_TXD5':2.02/1.07,'TXD6_TXD1':2020/1.1,'TXD7_retention_percent':1.18/2.02*100,'TXD7_loss_percent':(1-1.18/2.02)*100,'TXD9_TXD6_percent':.41/2.02*100,'note':'Actually computed reportedmeanratios, notrawreplicate statistics'})
print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[x['file'] for x in images]},ensure_ascii=False))
