import json,hashlib,re,fitz
import worker as w
d=w.ROOT/'sources'/'UIJLVFTZ';rec=json.loads((d/'prepared.json').read_text(encoding='utf8'));doc=fitz.open(rec['main_pdf']);images=[];figures=[]
specs=[('Figure 1',2,[60,275,551,765],[],'Figure1.Historicalpostulatedpathway redunknownsteps notfullfunctionalreconstruction.'),('Figure 2',4,[60,82,551,680],list('AB'),'Figure2.Fullheatmapalltimepointsandpie/table;standardizednotabsoluteexpression;181/66727.1pieversustable21.1sourceconflict.'),('Table 1',5,[44,82,536,381],[],'Table1.All15tentativecandidates accessionannotationEvalues;onlyTB768functiontestedhere othersnotvalidated.'),('Figure 3',5,[44,628,536,765],list('AB'),'Figure3.Phyre2predictedstructureanddomains notnewcrystal activepositionsnotmutagenesis.'),('Figure 4',6,[60,82,551,481],[],'Figure4.CompletealignmentN/Cterminiandalllegend marks sitefunctionsassignedbyhomology.'),('Figure 5',7,[44,82,536,611],list('ABCD'),'Figure5.Bothsubstratesenzyme/noenzymeEICMRMandspecificactivity;RTbody3.93/3.95 vsfigure3.89/3.87 plusone3.83;differentpH/concentrations ratio6.04notcatalyticefficiency.'),('Figure 6',8,[60,442,551,765],list('ABCDE'),'Figure6.AllSignalPconfocalPIandFRAPpanels;BcontrolimageYFPcaptionGFP;D57slabelversuscaption40s;heterologousfusionnotnativeTaxus.')]

for label,page,bbox,panels,caption in specs:
 pg=doc[page-1];file=d/('UIJLVFTZ-'+label.replace(' ','-')+'-complete.png');pg.get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(bbox),alpha=False).save(str(file));figures.append({'label':label,'caption':caption,'panels':panels,'pages':[{'page':page,'bbox':[bbox[0]/pg.rect.width,bbox[1]/pg.rect.height,bbox[2]/pg.rect.width,bbox[3]/pg.rect.height],'dpi':300}]});images.append({'label':label,'caption':caption,'page':page,'bbox':bbox,'panels':panels,'file':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
gaps=['All12mainpagesreadtextvisual sevencompletegraphics noGA SIabsentS1-8TableS1DataS1 rawLCMS/UV/qPCR/FRAPunread','Titleautomaticfalsebeta/bencoding visuallyidentityDOIverified','Figure2B181Metabolismtags denominator66727.14pie vs21.1table matches858 mixeddenominator','HeatmaprowstandardizednotabsoluteorPsignificance PMswitchconfounding broadMeJAresponse','15tentativecandidates onlyTB768functionalvalidated notalltaxolsteps','Phyre2confidence100notactivityprobability/crystalstructure sitehomologynotcausal','RTbodybeta3.93coumaroyl3.95 vsFig5beta3.89coumaroyl3.87 betaoneMRM3.83 conflict','Figure5specificactivity102.309/617.760umolminmg conditionsbeta10mMpH8 versuscoumarate1mMpH8.5 ratio6.04notkcat/Km','Extinctioncoefficientsprinted3421/3885mMpercm missinginverseunitclarity nofixwithoutrawcalibration','AcCoAsubstrateCoA0.6umol andprotein0.008mg finiteCoA meanscannotmultiplyactivityby45/60min asyield rawinitialrateabsent notdeclareimpossibleinitialrate','NoKm/kcat/allnP/CI/SD rawinitialrates orproteinactivefraction;ATP/Mgconcentrationsnotfullymainprovided','Noenzymepuritymatchedemptyexpressioncontrolshown MRMstandarddetailsSIunread notallbackgroundionsenzymeproducts','Nofullenantiosubstrateselectivity actualbetaPhechiralitynotshownbeyondpathwaydiagram','Fig6BimageYFPcaptionGFP FRAPGFPdifferentlabels;photo57s vs40scaption/curve 6sbleachseparate','LocalizationheterologousCterminalfusionnotnativeTaxus endogenousgeneticnecessity/controlcoefficientnotshown','MeJABIII20.5taxol19foldauthorreportedSI notTB768singlegeneeffect/actualabsoluteyield','MethodWesternS8directoryS6 S8fragments sourcecrossrefconflict','2016journalyear2015acceptedcopyright notsameyear']

draft={'identity_matches':True,'identity_reason':'PrintedbetaTitle10authorsDOI2016PBJ14pp85-96matchesliveZotero;automatictitlefalsecharacterencoding manuallyresolved all12pagesreadvisual.','paper_type':'research','title_zh':'TB768侧链前体活化的功能证据','filename_title':'TB768侧链前体活化的功能证据','journal_short':'Plant Biotechnol J','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'report':(d/'codex-report.md').read_text(encoding='utf8'),'figures':figures}

w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft});w.write_json(d/'codex-crops.json',images);w.write_json(d/'codex-arithmetic.json',{'sequence_success_percent':667/858*100,'homology_percent':369/667*100,'nohits_percent':298/667*100,'metabolism_oversequenced_percent':181/667*100,'metabolism_overdifferential_percent':181/858*100,'specificactivity_ratio_differentconditions':617.760/102.309,'CoA_umol':1.5*.4,'protein_mg':.020*.4,'beta_rate_iflinear_umolmin':102.309*.008,'coumarate_rate_iflinear_umolmin':617.760*.008,'constanttimeextrapolation_notyield':True})

print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'crops':[x['file'] for x in images]},ensure_ascii=False))
