from pathlib import Path
import json,re,fitz,hashlib,sys
root=Path(r'C:\Software\Data\05-Obsidian\SynBioPath\.maintenance\literature-reading-20261006');sys.path.insert(0,str(root));import worker as w
d=root/'sources'/'YVBR4AY7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Table 1',2,[36,66,558,714]),('Table 1',3,[47,66,558,309]),('Figure 1',4,[36,513,545,739]),('Figure 2',6,[36,65,545,684])]
gaps=['Review8pages201063460467onlineJuly14fourauthorsLBFloreCoteraCinvestavIPN liveZotero200 identityverified','Table1twofullpages461462 allrowsheadersmethodcodesfootnotes retained plusFigure1fouralignmentsFigure2allabcd standardnotfungalsample','All88referencesnotindependentlyread patents45and46notpeerreviewfuturepapers authorunpublishedFigure2data notindependentfungusvalidation','Tablemainngml bnanogramsperdryweightnoexplicitgram cannotunify NDnotdetectednotzero NRundefined bodylow.024table.01.014 no cleanmetaanalysis','AntibodycrossreactivityUVTLCretentionmassalone insufficient completecompoundidentity Figure2cephalomannineNa854.6 vsTaxolH854 adductconfound pacliNa876.6epiNa876.6 exactsameformulaHRMSnotchiralselective','PartialPCR ts38screen12positive3detected dbatbapt90screen15then6threeboth notn completefungalgenesunproven nearplant97to99identity nogenomecontext horizontaltransfercontaminationhypothesesnotdetermined accessionsversionnotdownloaded','TandreanaereanalysisPCRpositive metabolitenegative mediaexpressionorpassagelosspossible notprovedcausality','Cultivation reportedfungalNe32 immunoassay valuesnotindependentpurechemicalflux nerrorCIunreported yeastandbacteriahistoricnotmatchedcomparison','NCEU314.1F4487.9516.4496.7 reported31.564.444.7percent versuscalculated55.3364.4158.13 discrepancyfirstthirdunexplained preserveboth MS855.2 reportednotchangedto854adductunverified','Yeasttaxadiene1000ngml1mgL5OH25ngml.025mgL not40foldconversion improved8700ngml8.7mgL GGol33100ngml33.1mgL notTaxol nofinalfactory2010stateonly','2010commercialabsencenotcurrentstate noTEALCAphysicalorigincompletefungalgenesunvalidated no systematicsearchprotocol nohumanreview classdeferred noexplicitCOI']
figs=[]
for l,p,b in spec:
 entry=next((f for f in figs if f['label']==l),None)
 if entry is None:entry={'label':l,'caption':'原文 '+l+'完整图表及图注（跨页表保留续表脚注）','panels':[],'pages':[]};figs.append(entry)
 entry['pages'].append({'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300})
draft={'identity_matches':True,'identity_reason':'8pages4authorsJAntibiot201063460467July14titleDOIprintedliveZotero200verified','paper_type':'review','source_article_type':'Review article','title_zh':'微生物紫杉醇报道的分析鉴定、遗传线索与产业化边界','filename_title':'微生物紫杉醇报道的分析鉴定与遗传线索','journal_short':'J Antibiot','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded8pages'})
images=[]
for l,p,b in spec:
 out=d/('YVBR4AY7-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':next(f['caption'] for f in figs if f['label']==l),'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':len(images),'files':[x['file'] for x in images]},ensure_ascii=False))
