import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'5LCZ6Y94';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',[(1,[386,263,557,404])]),('Unnumbered Structure Graphic',[(2,[51,207,294,467])]),('Figure 1',[(2,[51,468,557,758])]),('Table 1',[(3,[51,54,557,749]),(4,[51,54,557,339])]),('Table 2',[(5,[51,54,557,749]),(6,[51,54,557,359])]),('Figure 2',[(6,[51,361,297,504])]),('Figure 3',[(6,[51,604,557,758])]),('Table 3',[(7,[51,321,297,455])]),('Table 4',[(7,[315,192,557,330])])]
with fitz.open(rec['main_pdf']) as doc:
    figs=[{'label':l,'caption':next((x['caption'] for x in rec['figure_candidates'] if x['label']==l),'原文摘要图' if l=='Graphical Abstract' else '原文未编号结构图：glycinocins 1–8'),'panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300} for p,b in parts]} for l,parts in spec]
gaps=['Only local11pageASAPmain A–K; volume/pageunknown; SI/rawNP-MRD/database/citedpapers notread','Researchmainmisflaggedsupplement inpreparedmetadata','Table3 MIC versus methods IC50 and SI descriptionIC50 unresolved','Figure3 module10predictedVal versus chemicallyL-Ile; module2Dap notallDabexplained; candidateBGC notfunctionalvalidated','Dab is2,3diaminobutanoicacid; alphaabsoluteassumedbiosyntheticrelationship betaassignedconditionally','Marfey D-Valstandard31.03 hydrolysate32.23min unclarified; SI notread','Text compound4Dap conflictingDabactualstructure; saturatedchaincomparisons notcurrentmatchedseries','Text500/150MHz versusTables/experimental500/125','Textsp2methylene20.7–47.5ppm inconsistent; Table1IleCO170.7CH3; Table2branchedmethinetypesCH2','Compound4cytotoxupper5ugmL approx3.9uM belowfungal9.5/7.2andMRSA5.2; notfullsafetywindow','Triplicatefungal/cells notconfirmedindependent; antibacterials n notclear; noCI/P statistics','NoaddedCa notzerocalcium; noionicbackground exclusion/target/ecology/invivo causalproof','Strongestcompounddependsendpoint; MRSA+Ca2lowest2.5 not4; VRE3/4difference withouterror','Table1PDF3/4 andTable2PDF5/6continuations included']
draft={'identity_matches':True,'identity_reason':'Local11pageASAPmain titleDOIauthorsmatch','paper_type':'research','title_zh':'Glycinocins E–H结构构型与钙依赖活性证据','filename_title':'Glycinocins E–H结构构型与钙依赖活性证据','journal_short':'J Nat Prod','category':None,'related_categories':[],'classification_reason':'全部文献笔记完成后归类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodex directsource reading without externalmodel'})
images=w.crops(rec,draft,d);i=0
with fitz.open(rec['main_pdf']) as doc:
    for l,parts in spec:
        for p,b in parts:
            out=d/('5LCZ6Y94-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images[i].update(file=str(target),sha256=sha,bbox=b);i+=1
w.write_json(d/'codex-crops.json',images);print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'images':[{'label':x['label'],'file':x['file']} for x in images]},ensure_ascii=False))
