import json,re,fitz,hashlib,datetime,requests
import worker as w
d=w.ROOT/'sources'/'QWTYVVCT';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
spec=[('Graphical Abstract',1,[314,249,558,377],[],'原文摘要图：完整两底物、酶结构、两性离子和三产物模型'),('Scheme 1',2,[50,58,558,309],[],'原文 Scheme 1：GGPP、两底物分配、T5OH/OCT、OPP 脚注'),('Scheme 2',2,[50,317,558,524],[],'原文 Scheme 2：历史 C20 抽氢和双键环氧化竞争机制'),('Scheme 3',3,[50,59,558,299],[],'原文 Scheme 3：历史 OCT 反应模型、完整六结构及箭头'),('Figure 1',5,[50,58,558,402],['a','b','c'],'原文 Figure 1：完整 a–c 电子密度、口袋结构、所有突变色谱和长图注'),('Figure 2',5,[314,572,558,757],[],'原文 Figure 2：完整优化反应物、水分子、关键距离与图注'),('Figure 3',6,[50,58,558,344],[],'原文 Figure 3：全部能量分支、各中间体及三幅优化结构和图注'),('Scheme 4',6,[50,350,558,518],[],'原文 Scheme 4：环氧开环后的全部双色分支、局部能垒和脚注'),('Figure 4',7,[50,58,558,399],[],'原文 Figure 4：完整蓝红能量分支、全部七结构和图注'),('Figure 5',8,[50,58,558,317],[],'原文 Figure 5：iso-taxadiene 抽氢回弹能量、三结构、三优化模型、全部图注'),('Scheme 5',8,[50,324,558,566],[],'原文 Scheme 5：全部总结路径、环境标记，保留 iso 分支原文 epoxidation 标签')]
gaps=['All14mainPDFpagesreadandvisuallyinspected;prepheuristicSIflagfalse actualACSResearchArticle3912–3925 titleDOImatch','NoSI TableS1/S3 FigureS1–S8 Cartesiancoordinates/trajectoriesrawspectraread;referencesnottreatedasnewexperiments','Taxadienefromcrystal isotaxadienedocking;CpdIoxomanuallyaddednotcrystalobserved','CrystalproteinandfunctionalCYP725A4CPRfusiondifferentconstructs;alaninescanwholecellsnotpurifiedkinetics','MutantGCMSn/error/exactareas/testnotreported;noexpressionhemeelectroncontrolinreadmain;lossnotdirectchemicalrole','MainPDF5complex1.68Angstrom vs currentRCSB8X3E2.50;8X1Wapo2.10 externalchecked20261008 unresolvedcause noSI/rawdiffractionread','PDF4names8X3ECYP76AH1 whereasRCSBandpaperCYP725A4 conflictretained','Main100nsplusresultsreporttwo400nsreplicates;SIdistributions/convergenceunread noindependentsimulation','QM/MMUB3LYPB2electronicplusB1ZPEnotexperimentalactivationfreeenergy;singleinitiatingrepresentativesnapshot','Taxadiene12.2vs18.7computedunderselectedmodelnotallconditionspathimpossibility ormeasuredselectivityratio','EpoxideScheme4UB3LYPaceticacidmodelnotactualuniquebuffer;finiteOCTrouteinfigure despiteexclusiveauthorword','LongwaterprotonrelaynotexplicitQM/MMsolved;noidentifiednearbydonor Oprotonationexothermnotwholetransferbarrier','Figure4standalonePBE0differentfrominitialUB3LYPQMMM cannotspliceenergies/commonrateyield','PDF7IC3aC4centeredtextvsstructure/hydridemigration possiblelabelconflict noimplicitcorrection','Scheme5isotaxadienearrowepoxidationvsFig5textHAAOHrebound retainedoriginal','iso21.1barrierand2.3reboundnotproofhigherwholepathflux;TS92/8backgroundnotuniversal','OCTpathT5OHchemistrycomputationalmodel intermediatesnotnewexperimentcapture','Oxetaneenzymeassignment137/138conflictreferences discussednotresolvedhere nofullpaclitaxelproduction']
doc=fitz.open(rec['main_pdf']);figs=[{'label':l,'caption':c,'panels':a,'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b,a,c in spec]
draft={'identity_matches':True,'identity_reason':'All14mainpages ACSResearchArticle title9authors journal14 3912–3925DOIverified. Prepared is_supplement heuristic false positive','paper_type':'research','title_zh':'CYP725A4结构约束与质子化分支机制的证据边界','filename_title':'CYP725A4结构约束与质子化分支机制的证据边界','journal_short':'ACS Catal','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft)
draft['source_gaps']=[x.replace('Scheme5isotaxadienearrowepoxidationvsFig5textHAAOHrebound retainedoriginal','Scheme5detachedepoxidationarrowlabelnearbottomisopath attributionunclear notassigntoisopath;Fig5textHAAOHrebound retainedoriginal') for x in draft['source_gaps']]
w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Direct Codex read original14pages allmain11graphics and RCSBentrycheck'})
images=[]
for l,p,b,a,c in spec:
 out=d/('QWTYVVCT-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(matrix=fitz.Matrix(300/72,300/72),clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':c,'page':p,'file':str(target),'bbox':b,'panels':a,'sha256':sha})
doc.close();w.write_json(d/'codex-crops.json',images)
snap=[]
for code in ['8X1W','8X3E']:
 url='https://data.rcsb.org/rest/v1/core/entry/'+code;r=requests.get(url,timeout=30);r.raise_for_status();obj=r.json();w.write_json(d/('rcsb-'+code+'-20261008.json'),obj);snap.append({'code':code,'url':'https://www.rcsb.org/structure/'+code,'retrieved':datetime.datetime.now().isoformat(),'title':obj['struct']['title'],'resolution':obj['rcsb_entry_info']['resolution_combined']})
w.write_json(d/'codex-pdb-check.json',{'database':snap,'paper_complex_resolution':1.68,'unresolved':True,'boundary':'Currententrysnapshotonly;rawdiffraction/SITableS1 and depositrevision causalreasonnotverified'})
print(json.dumps({'chinese_characters':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'image_files':[x['file'] for x in images],'pdb_check':snap},ensure_ascii=False))
