import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'3J66M8TZ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[49,428,546,715]),('Table 1',3,[49,600,546,714]),('Table 2',4,[49,56,546,150]),('Figure 2',5,[304,329,546,716]),('Figure 3',6,[304,55,546,572]),('Figure 4',7,[49,55,546,428]),('Figure 5',8,[49,55,291,451]),('Figure 6',9,[49,50,546,317])]
gaps=['All11mainpagesreadandviewed sixfigures twofulltables300dpi no rawGCMSCELgrowthfilesrefsnotallindependentlyread','Journalissue2012 vs onlineAug182011 Zotero2011 date preserved; filenameuses2012volume93issue4pp1651-1661 fiveauthorsPfeifer corresponding liveZotero200 DOI identitymatches','ProductiontaxadienenotTaxol gLfedbatchhistoricalAjikumar2010notthispaper; .502mggDCWnotmgL','YW22JM109DE3YW23BL21DE3nonisogenic backgrounds downstreamT7pACYCp15a vsT5pQEandTrcpTrcpBR322plasmidmarkerpromoterconfounded no universalKbetterB','Figure2SDn3to6 Figure3SDn3 Figure4SDn4 Figure5SDn3 recorded asreported no fabricatedprecisePvaluesorunreportedCIs','348of4070DE genes243YW22higher105YW23higher absolute log2difference>2correspondsfourfold vsFigure3captiontwofold unresolved rawCELnotobtained noFDRreported K12referenceprobecomparabilitylimit','MEPdxsispEispFispAhigherinYW23p<.05 ispUhigherYW22p<.01 transcriptnotflux SDSsolubleproteinnotquantactivity','Figure4actualabcd dTaxadiene captiondethanoletaxadieneincorrect sourcepreserved; 22observedbestbut12to27notstatisticallydifferent noethanolpanelinvented','Residuallactatesuccinateformatepyruvate<.5mMnotintracellularabsenceorzeroflux; richmediumcarbonnotglycerolonly','Indole30C16hplategrowthnot22C5dayproduction directtaxadieneindolehistoricalnotcurrent; 300mgLrelativegrowth65.3and78.5percent; lowdoseuninhibitedtextp<.05inconsistentnotcorrected','DiscussionpykFreversephysiologicaldirectioncontradictedbyUniProtP0AD61live200 physiologicalPEPtoPyruvate; PEPactivatespfkAclaimcontradictsP0A796inhibition; glyceraldehyde3Pvs glycerol3Pnamesconfused no silentoriginalPDFediting','OfficialUniProtP0AD61andP0A796JSONcached provenancecrosscheck notnewexperimentaldata; Figure6modelnotdirectflux','NIHGM085323Milheim2006-17 noexplicitmodernCOIdatarepo statement seen nohumanreviewclassificationdeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Fiveauthors titleDOI93pp1651-1661mainmatches liveZotero200 online2011issue2012','paper_type':'research','source_article_type':'Original research','title_zh':'K系与B系大肠杆菌Taxadiene生产的宿主与中心代谢比较','filename_title':'K系与B系大肠杆菌Taxadiene生产的宿主与中心代谢比较','journal_short':'Appl Microbiol Biotechnol','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex all11pagesreadviewed fullfigures/tableschecked and two official UniProt records independently crosschecked for biochemical direction and regulation errors'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
