import json,re,fitz,hashlib
import worker as w
d=w.ROOT/'sources'/'T6ZTH9UD';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));doc=fitz.open(rec['main_pdf'])
spec=[('Figure 1',2,[40,48,550,464]),('Table 1',3,[40,52,550,418]),('Figure 2',4,[41,263,287,747]),('Figure 3',5,[41,49,550,339]),('Figure 4',6,[41,49,287,476])]
gaps=['All six main pages read and visually checked; Figures1-4 andTable1 complete including all gel panels captions and tablefootnotes; no raw spectra culture repeats SI or notshown results available','Identity manually confirmed by title fourauthors volume9 pp2237-2242 PII S0968-0896(01)00072-4 andliveZotero DOI; automatic DOI_match false because printedPII notDOI; Zoteroonly QHuang author incomplete notmodified','TS Nterminal78 residues removed pTS79H name not79removed; gene origins verified originalTable1; threeexpressionproducts fourenzymefunctions fusionnotproofchanneling','Original micro units visually verified muLextracts andACN smallscale vsactualmL largescale andantibioticmicrogmL; IPTG50mgL roomtempunspecified','Figure3 carbonpeakassignments taxadiene121.9 42.0 31.1 30.4 GGDP40.2 25.8 ACN118.8 glycerol63.9 73.3 authors70percentGGDPconversion estimate notisolatedyield','2Lcellfree10mgpurifiedtaxoidmixture main4(5)minor4(20) GCMS13percent notnecessarilymassratio minorfullNMRnotshown; equilibriumvsdeprotonationselectivity unresolved','Invivoisolated .5mg1L versus1.3mg1L 2.6fold withoutnSDP CI wholeproductmassbalancerecovery; finaldesignDXPS plusplysSregulationchange thirdvector confounded noDXPSexclusivecausality','Figure4 time0 3 16h37C pyruvate25.8 DXP26.3 deoxyxylulose25.2 longdephosphorylation; Figure3same25.8differentmolecule context','DXPotherbranches acknowledged DXRfuture nottested; no intracellularGGDPfluxpoolquant; TSonlynondetectnotzeroGGDP','Taxadiene notcompleteTaxol historical2001 no modernpriority verification allcitedpapersnotindependentlyread; humanreviewfalse classificationdeferred']
figs=[{'label':l,'caption':'原文 '+l+'：完整图表及图注、脚注','panels':[],'pages':[{'page':p,'bbox':[b[0]/doc[p-1].rect.width,b[1]/doc[p-1].rect.height,b[2]/doc[p-1].rect.width,b[3]/doc[p-1].rect.height],'dpi':300}]} for l,p,b in spec]
draft={'identity_matches':True,'identity_reason':'Original printedPII titlefourauthorsvolumepages matches liveZotero DOI despiteautomatic DOI-match false and incompleteZoteroauthorlist','paper_type':'research','source_article_type':'Original research','title_zh':'大肠杆菌Taxadiene体内外合成的早期证据与前体供给局限','filename_title':'大肠杆菌Taxadiene体内外合成的早期证据与前体供给局限','journal_short':'Bioorg Med Chem','category':None,'related_categories':[],'classification_reason':'全部文献解读完成后统一分类','source_gaps':gaps,'figures':figs,'report':(d/'codex-report.md').read_text(encoding='utf-8')}
w.normalize_format(draft);w.validate_structure(draft);w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex full original six pages read and visually checked; PII identity and original micro-units verified; isolated product mass and DXPS confounding explicitly distinguished'})
images=[]
for fig,(l,p,b) in zip(figs,spec):
 out=d/(rec['key']+'-'+l.replace(' ','-')+'-p'+str(p)+'-complete.png');doc[p-1].get_pixmap(dpi=300,clip=fitz.Rect(b),alpha=False).save(out);sha=hashlib.sha256(out.read_bytes()).hexdigest();target=out.with_name(out.stem+'-'+sha[:16]+'.png');out.replace(target);images.append({'label':l,'caption':fig['caption'],'page':p,'file':str(target),'bbox':b,'panels':[],'sha256':sha})
w.write_json(d/'codex-crops.json',images);print(json.dumps({'CJK':len(re.findall(r'[\u4e00-\u9fff]',draft['report'])),'files':[x['file'] for x in images]},ensure_ascii=False))
