import json,time
import worker as w
d=w.ROOT/'sources'/'TGJ6DZXZ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'model_channel_Angstrom':18,'model_channel_nm':18*.1,'F116A_dec_in_vivo_percent':6,'F116A_dec_in_vitro_percent':64,'F116A_difference_percentage_points':64-6,'double_dec_in_vivo_percent':66,'double_dec_in_vitro_percent':96,'double_difference_percentage_points':96-66,'double_total_relative_to_WT_DMAC_percent':30,'conditional_dec_relative_to_WT_DMAC_percent':.30*.66*100,'oct_to_dec_backbone_carbon_difference':20-16,'added_extensions':(20-16)/2,'absolute_productivity_gain_proven':False,'mutant_structure_solved':False,'binding_constants_measured':False,'PDB_current_record_checked':False})
claims=[('Identity','PDF1/2','TangTsaiKhosla Stanford JACS12542:12708-12709 DOIprinted webSeptember272003 receivedAugust12 versusZoteroOct1 live200'),('Coverage','PDF1/2 Figures1/2 Scheme1 Table1','Alltwofullpagestextoriginalsread fourcomplete300dpi cropsviewed Figure1ABmodelsequenceFigure2ABalltraces sixstructures tableall3rows4columns no rawchromatogramscoords14refsnotallread'),('Model','PDF1 Figure1','Homologymodel Swissmodel templates1E5M1KAS1F91 identity25-40percent notaccuracy18Angstrom1.8nm notexperimentalmeasuredchannel;1QXGdepositreported currentPDBnotqueried'),('Sequence','PDF1 Figure1B','Act109112116133 numbering separate tcmG116M120; familysequenceassociationnotuniversalrule whiEC24othergatekeepershypothesis'),('Act in vivo','PDF1 Figure2A Table1','F116Adec6 doubledec66 andRM20bDMAC2:1;doubletotalyield30percentWTDMAC notproductivitygain conditional19.8percentWTreported'),('Multimutant','PDF1/2','acttriple nofurtherspecificitychange fourAlanineno product interfaceperturbationproposednotdirectfold orbindingexperiment'),('Reverse','PDF1/2 Figure2B','tcmG116Tmore65percentoct comparabletotalyieldtoWT report2:1;doubleG116TM120Fno detectedproduct structuralroleshypothesis notdirectstability'),('Products','PDF2 Scheme1','OctDMACSEK4SEK4b andDecRM20bSEK15SEK15b distinctdownstreambackgrounds no exactsamecompoundassumption'),('Table','PDF2 Table1','WT invivo1000 invitro991 F116A946vs3664 double3466vs496 exactcolumns;58and30percentagepoints nottotalyieldfoldincrease'),('Assay','PDF2','FLAGpurification95proteinnotproductpurity minimalPKSwithouttailoring andcellproteins;conditiondifference suggestscontextbias no uniquelycausalpartneridentified noCIorP'),('Scope','PDF2','CLFimportantchainlengthnotexcludeKSACPotherroles no directdisproofmalonyldecarboxylation;2extraextensioncount consistent nottimecourseobservation'),('Declarations','PDF2','NIHCA77248 Khosla NIHpostdocTang noawardnumber noexplicitCOI humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex both full original pages read and viewed; two figures one Scheme one Table complete original crops visually checked; homology channel versus mutant phenotype and in vivo versus in vitro proportions distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
