import json,time
import worker as w
d=w.ROOT/'sources'/'E4HTE8GN';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Seven reported new HPPO meroterpenoids and two known analogues','PDF1 structures','1–7 new,8/9 known; no demonstrated biosynthetic genes'),('Penicillium sp.SCSIO41691 ITS PP112158','PDF6 fungal material','99percent similarity retained at genus level'),('1/2 methyl at C1 and different oxygen bridges','PDF2–4 Table1 Figure1','COSY H1/H3-16 and HMBC to C1 C2 C12b; structure comparison not traced migration'),('1 absolute1R3R4aR6aR12aR12bS','PDF3/7 Figure3','CuKalpha Flack0.18(7),CCDC2301023 plus Figure4 ECD'),('3 absolute2R3S4aS6aR12aR12bR','PDF4/7 Figure5','Flack0.03(5),CCDC2300687'),('4 ECD similarity to3 and presumed shared biogenesis','PDF4–5 Figure6','Not independent Xray for4'),('6 ECD FigureS60 not read','PDF5','SI absent; main-text comparison recorded'),('7 C1 epimer relative NOE evidence','PDF5 Figure2','Not all7 compounds have single crystal data'),('5 NOIC50 21±1 versusindomethacin24±2uM','PDF6 Table4','RAW264.7 CC50both>50; statistical superiority not established'),('H1975 IC50 9=15uM,2=67uM','PDF6 originalTable4','Conflicts with allnoobviouscytotoxicity prose'),('Slash indicates not tested','PDF6 Table4 footnote','Not zeroactivity or established lack of toxicity')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read all8 mainPDFpages, originalpages1–7 and all12 actual300dpi cropped figures/tables visually checked. Structure graphic adjusted to include all labels without adjacent text. SI,CCDC,NP-MRD and cited papers not independently read; ECD not rerun. No external model review.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
