import json,time
import worker as w
d=w.ROOT/'sources'/'R8AD93HX';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'ORF_triplets':1335/3,'Km_ratio_not_affinity':4.9/2.4,'relative_velocity_ratio_not_catalytic_efficiency':1/.4,'baccatin_Km_microM':2.4,'beta_donor_Km_microM':4.9})
claims=[('Identity', 'PDF12715footer', 'Sixpages fourauthors WalkerFujisaki equal Walker corresponding October1 2002 contributedAug2 DOI192463699'), ('Coverage', 'PDF12715to12720 Figures1to5', 'Fulltext sixoriginalpages viewed fivecomplete300dpi crops viewed everypanelcaption Figure2 priorsemisynthesis notnewenzymecompleteproduction'), ('ScreenControls', 'PDF12718to12719', 'Ninefamily five remaining notreplicates TAX7hit withoutcosubstrate emptyvector negative omittedchemicalderivatization negative analyticaldependence notnoenzymereaction'), ('Product', 'PDF12715 Figures3and5', 'Enzyme Ndebenzoyl2deoxytaxol chemicalNbz2deoxytaxol notTaxol Figure3 upperradioreaction lowerUVstandard residual21.3 target39.6 Figure5 LC20.8 anditsMS838820778760569509270 differentmethods'), ('Stereo', 'PDF12719 Figure4', 'PartialNMR single3primeepimer absoluteconfigurationunassigned likelyTaxol onlyhypothesis otherNMRregionauthorreportedno fullrawspectrum'), ('Kinetics', 'PDF12718to12719', 'Crudesolubleprotein target1percent total protein inclusionbodies 15to20activityrecovery unstablepresumed Km2.4plusminus.5and4.9plusminus.3microM pH6.8 bufferconfoundoverlap R2.99 nerrorCIunreported'), ('Donors', 'PDF12716to12719', 'Fourdonors chemicalyields40 26 30 10 purity95 90 95 80 different no enzymeyield Vrel1 and.4 2.5ratio notefficiency alphaNbzbelow.01notzero regioC13limitedbaccatin'), ('SequenceMechanism', 'PDF12719to12720', '1335bp445aa50546Da AY082804 paperonly similarity71to74 notidentity58to69 G163XXXDA168 betaaminegeneralacidbase hypothesis no mutationalstructuralproof'), ('Boundary', 'PDF12720', 'NaturalhydroxylationNbzorderunknown fiveacylaseshistoricalnotallpathwayclosure NIH eXegenics McIntireStennis Toho noexplicitCOI humanreviewfalse deferclassification')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex6pagesfulltextread6originalsviewed5complete300dpicropsviewedResearchBAPTchemicalderivatizationanalyticaldependenceabsoluteconfigurationunassignedcrudeextractmicroMkineticsrelativevelocitynotcatalyticefficiencymotifhypothesisPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
