import json,time
import worker as w
d=w.ROOT/'sources'/'3J66M8TZ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
# Use the printed volume year for this new note only, preserving Zotero online date.
rec['date']='2012'
w.write_json(d/'codex-arithmetic.json',{'volume_year':2012,'online_publication_date':'2011-08-18','Zotero_date_unchanged':'2011-08-18','DE_total':348,'all_genes':4070,'DE_percent':348/4070*100,'YW22_higher':243,'YW23_higher':105,'DE_sum_check':243+105==348,'YW22_fraction_DE_percent':243/348*100,'YW23_fraction_DE_percent':105/348*100,'log2_2_fold':2**2,'relative_growth_300mgL_percent':{'YW22':65.3,'YW23':78.5},'growth_reduction_percent':{'YW22':100-65.3,'YW23':100-78.5},'relative_growth_difference_percentage_points':78.5-65.3,'best_Figure2_specific_titer_mg_per_gDCW':.502,'converted_to_mgL':False,'Fig4_actual_panels':4,'Fig4_caption_panel_mismatch':True,'raw_CEL_reprocessed':False,'differential_expression_FDR_reported':False})
claims=[('Identity','PDF1-11/liveZotero','FiveauthorsPfeifercorresponding AMB93issue4pp1651-1661printed2012 onlineAug182011 Zotero2011 preserved filename2012 nooriginalrecordsmodified'),('Scope and coverage','PDF1-11Figures1-6Tables1-2','All11pagesreadviewed eightcomplete300dpicropswithcaptionfootnotes verified sixfigures twotables; noallrawfileorrefsverificationclaim'),('Product distinction','PDF1/2Figure1','TaxadieneproducednotTaxol fullpathdiagrambackground gLfedbatchAjikumar2010notcurrent smallscale'),('Constructs','PDF3/4Tables1/2','YW22JM109DE3 YW23BL21DE3 nonisogenic upstreamchromosomal dxsidiispDF downstreamT7pACYCp15a T5pQETrcpTrcpBR322 differpromoterbackbonemarker noonefactorcleancomparison'),('Specific production','PDF5/6Figure2','YW22roughly2.5fold YW23 allthreedesigns .502mggDCW notmgL SDSsolublefractionnotquantactivity SDn3to6 ANOVAp.585limitedupstreamcomparison'),('Transcript evidence','PDF4/6Figure3','sixCELtriplicate22C48h RMAK12probes 348of4070 243K105B p<.01 absoluteLog2>2vscaptiontwofold unresolved noFDR rawnotavailable'),('MEP gene differences','PDF6Figure3B','dxsispEispFispAhigherB p<.05 ispUhigherKp<.01 n3SD highertranscriptsnotproofharmorflux'),('Temperature','PDF6/7Figure4','actualabcd dTaxadienecaptiondethanoletaxadieneerror preserved22observedbest12to27notstatisticallydifferent37notobserved n4SD lowercarbonuptakeratebettergrowthnotcompleteyieldcarbonbalance'),('Residual organics','PDF7','Lactatesuccinateformatepyruvate residual<.5mM nointracellularabsenceorzeroflux richmediumextracarbon'),('Indole','PDF5/7/8Figure5','30C16hplate growthn3SD highdoseinhibits300mgL65.3vs78.5relative lowdoseuninhibitedp<.05sourceissue notsilentlyedited prior8folddropnotcurrentmeasure'),('Central model','PDF8/9Figure6','Modelnotflux orcandidateinterventionproof PykFpyruvatetoPEPdirectionwrong glycerol3PvsGAPnamesmixed PEPpfkactivationcontradictsothertext'),('External crosscheck','OfficialUniProtP0AD61P0A796 JSON200 currentturn','P0AD61physiological righttoleftRhea reaction meansPEPtoPyruvate P0A796PEPallostericallyinhibits cachedofficialJSON citedinreport notnewexperiment'),('Declarations','PDF10','NIHGM085323Milheim2006-17 noexplicitmodernCOIrepository seen noinventedabsenceconflict humanreviewfalseclassificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all11mainpagesreadviewed plus official UniProt direction/regulation crosschecks; measured host phenotype separated from proposed flux mechanism and explicit source inconsistencies','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
