import json,time
import worker as w
d=w.ROOT/'sources'/'5NZ2V9DS';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'wet_rice_kg':10*150/1000,'isolated_mg_per_kg_wet_rice':{'compound1':9/1.5,'compound2':12/1.5,'compound8':7/1.5,'compound3':300/1.5},'formula_DBE_compound1':(2*14+2-20)/2,'formula_DBE_compound2':(2*14+2-22)/2,'reported_mass_error_ppm_compound1':(252.1372-252.1361)/252.1361*1e6,'reported_mass_error_ppm_compound2':(239.1642-239.1647)/239.1647*1e6,'reported_mass_error_ppm_compound7':(306.1809-306.1831)/306.1831*1e6,'ppm_to_Hz_factor_at500MHz':500,'mg_vs_microgram_unit_factor':1000,'Table1_dose_unit_conflict_resolved':False,'Table1_dose_rows_as_printed':[10,5,1,.5],'compound8_zone_mm_as_printed':[30,27,18,'(16)'],'compound13_zone_mm_as_printed':[32,21,16,'-'],'compound17_zone_mm_as_printed':[22,18,'+','-'],'compound9_zone_as_printed':['-','-','-','-'],'true_titer_verified':False,'paper_disk_is_not_MIC':True,'raw_Mosher_data_reprocessed':False,'biosynthetic_pathway_demonstrated':False})
claims=[('Identity','PDF1-4','ElevenauthorsHoshiPernambucoChiba Nozawa Notes67issue9pp1580-1583 DOIprinted webJuly242004 volume2004 downloaded2021notpub liveZotero200 actualG93YATLV otherattachmentmissingnotnoPDF'),('Coverage','PDF1-4 Figures1-3Table1Chart1','Allfourpagesreadviewed fivecomplete300dpicrops Chart1notautocandidate included all1to17substituentmaps ABC Tableallfootnotes parenthesesplusminus; originalPDFhighlight preserved'),('Recovery','PDF2','IFM52670ten150gmoistrice1.5kg1 9mg2 12mg8 7mg3 300mg equals6 8 4.67 200mgkg finalrecovery notyieldabundance'),('Compound1','PDF1/2Figure1','C14H20O4DBE5 EI252.1372calc252.1361plus4.36ppm C11177.7carboxylC3203.1ketone adjacentC2 notC2carbonyl COSYHMBCconnectivity reportno raw'),('Compound2','PDF1/3Figure1','C14H22O3DBE4 MplusH239.1642calc239.1647C14H23O3minus2.09ppm H3H45.60 5.33J9.7 correlationsH2C8aH3C4aH4C5H6C4a 2acetonevs1CDCl3'),('Relative stereo','PDF1/2Figure2','NOESY2Me9H8aH6OHsameface axialequatorial model relative notaloneRS'),('Absolute stereo','PDF1-4Figure3','Methylesters10and11 MTPA deltaSminusRHz500MHz C6Sbothauthors assignment actualderivatization no independentrawrepick printed2decimalroundingnotintegerHzexact'),('Chemical series','PDF2-4Chart1','A lactoneB sodiumacidC2methylbutanoyloxy1to9isolates10to17chemicalderivatives notnaturalpath map 6oxidation7 8heat3 9preparedethylester supportsstructureonly'),('Activity source','PDF2/4','8activeAfum18mm1microgdiskCandida17mm5microgdisk body1to7and9inactive100microg new1and2notextractactivityassigned'),('Critical units','PDF2Table1','Headermgdisk bodymicrogdisk1000fold discrepancy unresolved notsilentlycorrected no unifieddoseratiofit; AMPB13at10vs14at5nonmonotone noerrorreports'),('Table endpoints','PDF2Table1','8 30 27 18 (16) residualgrowth 13 32 21 16minus 17 22 18plusminus9allminus plus slightnotinventedmm noMIC'),('SAR limits','PDF2-4','Acidandsalt+acyloxy conditionaltestedseries notuniversalnecessity no directtargetdiffusion uptakeproof highlysaturated17active noallolefinrequirement'),('Source issues','PDF4','8some methylproton1HvsCH3carbon mismatch preservedrawunavailable assaymethodborrowedrefs specifictestedstrainreplicatesnotreported no statisticaltargetcytotoxefficacy'),('Declarations','PDF4','Chiba200322 FNGRPF2003 funded no modernCOIdatarepository explicit noall7refsread humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all four original pages read and viewed; Figures1-3 Table1 and Chart1 complete crops checked; NOESY and actual Mosher evidence separated from paper-disk SAR with explicit unresolved mg versus microgram unit discrepancy','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
