import json,time
import worker as w
d=w.ROOT/'sources'/'Z6YUHKGS';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('TOT1 Chr9_74725878 oxidizes1 tooxetane2 andepoxide3','PDF1–3 Figure1ABCDE','groupII singlecandidate insectcells EV T5alphaH controls'),('Km14.14±3.15 micromolar notmillimolar','PDF3 originalimage','text extractor losesGreekmu; S6 notindependentlychecked'),('Substrates4/5 noexpectedoxidation andepoxide3notconverted2','PDF3 Figure2ABC','50uM1/2/4/5 4.5uM3; doesnotexcludealltransientboundintermediates'),('DFTtruncatedmodel bothspin,25.1first6.8oxetane10.7epoxide','PDF4 Figure3','25.4-.3; -8.5-(-15.3); -4.6-(-15.3) locallycalculated'),('T9alphaH1 Chr9_26460669 taxusinreporter','PDF4–5 Figure4ABC','17candidates multienzymebackground notfulldirectsubstratespectrum'),('Ninegene tobacco combinationbaccatinIII notpaclitaxel','PDF4,6 Figure5AB','609Naadduct RT/MSMS standard; omissionnotnativeKO'),('C1C10functions/order remainnetwork hypotheses','PDF7discussion','promiscuity and low~50ng/gdryweight'),('Figure5Dn3biologicalSEtwo-sidedt100uMMeJA','PDF6 Figure5D','0 1 2 4 8 16 24 48 72,exactPcorrectionnotreported'),('GeneexpressioncorrelationERlocalizationnotchanneling','PDF5–7 Figure5C–H','Pearsonnotcausal GFPmarker5microns,plastidERtransportprobably')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read eight originalPDFpages maintext and references; viewed original figures1–5 and all five actual300dpi crops; checked Greekmu units visually and relativeenergy arithmetic. SI absent; no independentmodel or human review.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d);w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
