import json,time,re
import worker as w
d=w.ROOT/'sources'/'V7XAHPMQ';rec=json.loads((d/'codex-prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
draft['report']=re.sub(r'\{\{FIGURE:([^}]+)\}\}',r'<!--FIGURE:\1-->',(d/'codex-report.md').read_text(encoding='utf-8'));w.normalize_format(draft);w.validate_structure(draft)
w.write_json(d/'codex-draft.json',{'draft':draft,'method':'Current Codex source reading formal PDF and preview'})
claims=[('Formal17pageversion vs33pagepreview same DOI','formal1–17 preview1–33','Nature647639–647 five figures two extended reporting summary'),('323783 total36258positive287525negative','formal3 Figure2b Methods10','initialcategorysequence matching and synthetic negatives, not all experimentally tested'),('Complexes predicted docking not experimental structures','formal2–3,10 Figure1–2','AlphaFoldAlphaFillAutoDock'),('Bothunknown AUROC.7198vsESP.6523','formal4 Figure3a','random .8927; ESPfinalmodel differenttraining'),('Ablation singlecomponents .7036/.7021 vs.7198','formal4–5 Figure3b','dataset advantage distinguished architecture'),('Sixfamilies nitrilase excludedbothunknown','formal6 Figure4d','insufficient positives; thiolasefinetune.8230 vs.8247'),('8flavindepenzymes78substrates624pairs55substratesnohits','formal6–7 Figure5','onlyflavinfamily newmatrix'),('91.7Top1 twelve noveltysubstrates not624accuracy','formal6 Figure5e','11/12consistent rounded7/12ESP; TopkdefinitionsSIpending'),('34metabolites860enzymes29240pairs','formal7–8 extended1','10/34withinTop5percent17/34Top20percent'),('BGC ranks not newenzymatic pathwayvalidation','formal14 extended2','CEAS twoinputsTop5/4 BLS5 CAR4; AlbC1/1 AlbAB3'),('Reporting summary replicationno not sufficient perassaystatistics','formal15–17','samplesize323783 no no no; no inferredmodelreplicates')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read original main preview text and formalPDF1–14 text, viewed formal main/extended graphics and reporting summary15–17, inspected all seven actual300dpi crops. SI absent. No code run, external model or human review.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked)
note=w.publish(rec,draft,images,checked,d);w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
