import json,time
import worker as w
d=w.ROOT/'sources'/'D4TSYPV4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'reported_MplusH':[193.0493,209.0451,207.0663],'hydroxylated_vs_initial_mass_difference':209.0451-193.0493,'methylated_vs_initial_mass_difference':207.0663-193.0493,'methylation_net_formula':'CH2','EIC_original_caption_half_window_Da':.050,'EIC_automated_text_half_window_Da':.005,'window_is_accuracy_or_CI':False,'predicted_protein_aa':2147,'adjacent_ACP_domains':2,'integration_transformants':10,'feeding_biological_replicates_assumed_from_transformants':False,'host_tailoring_genes_identified':False,'absolute_conversion_measured':False,'raw_ESI_read':False})
claims=[('Identity','PDF1/3','XiangLudwigRadtkeYinLi MarburgCAS OBC1826:4946-4948 DOIprinted manualtitlematch despiteautomatictitlefalse live200 receivedMay13acceptedpublishedJune222020'),('Coverage','PDF1-3 Figures1/2','All3mainpagestextoriginalsread bothcomplete300dpicrops viewed threetraces structurescaption Figure2allseven domains twoACPs substratebranch;SIrecorddirectoryUV642375existsnoPDF noNMRTableS1S1S2 independentlyread34refsnotallread'),('Native deletion','PDF2','UnpublishedLiKindinger deltapcr9304no detectedmetabolitechanges no RNA orproofzeroexpression'),('Domains','PDF1/2 Figure2','2147aa SATKSATPTACPACPTE predictednotallfunctionvalidated genomic6921and633description exactsequenceboundaryunverifiedSIpending'),('Expression','PDF2 Figure1','LO8030pPX001PX001 vs emptypYHwApyrG tenintegrationtransformants similarprofiles nottenfeedreplicates;systemfunctionnotpurePKSreconstitution'),('Identity products','PDF2 Figure1','1dihydroxy3methyl2hydroxymethyl3C6methoxyC8hydroxy reported1HNMRTableS1 knownstructures notdenovo novelcompounds;completeSIunread'),('Mass','PDF2','193.0493209.0451207.0663 difference15.9958Oand14.017netCH2 not15CH3 notalonepositionproof'),('EIC correction','PDF2 Figure1caption original300dpicrop','Originalimage prints plusminus0.050Da all3ions whereasmaintext extractionmisreads0.005 originalprevails;UV254detection vsmax245325 notsameparameter windownotaccuracyCI'),('Feed','PDF2/3 Figure1','Synthetic1feedingLO8030 forms2/3 day1data notshown following7daysincrease notfullquanttimecourse;RtUVmassMS2matched notidentifiedhostenzyme'),('Branches','PDF2 Figure2','1to2C3methylhydroxylation1to3C6Omethylation notsequential2to3;acetylfourmalonylmodel notisotopetraced no P450geneinvented'),('Domain logic','PDF2','NoKRnotaloneexcludeoxidativehydroxylation feedingstrongerevidence hostenzymesunidentified directpureenzymesabioticcontrolsmaintextnotshown'),('Comparison','PDF2','IcmM19percentATEG0014541percentidentity targetedcomparisons notnohomologyabsolute;nativeproductratio unknown'),('Quant limits','PDF2/3','Noabsolute titerstandardresponseconversioncarbonbalanceCIorP peakheightnotmolaramount noactivityassay'),('Declarations','PDF3','No competingfinancialinterest DFG Li84411-1INST160620-1 NSFC31861133004 CSC201708530222 humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three original pages read and viewed; two complete original figures visually checked including EIC caption window correction; heterologous product association versus host feeding conversion and unidentified enzymes distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
