import json,time
import worker as w
d=w.ROOT/'sources'/'3DVJBS6C';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('One new1 andtwo known2/3','PDF1–3 Figure1','stephaochratidinA stephacidinA notoamideE'),('C35H39N3O7 DBE18 sodium636.2671calc636.2686','PDF1 Table1PDF2','notprotonatedion'),('HMBCconnectionsandNOESYrelativestereochemistry','PDF2 Figure2 Table1','C9fragment andhybridlinks, noabsolutealone'),('Absolute10S11R17S21S1primeS5primeS8primeS9primeS','PDF2 Figure3/4','CuKalphaFlack0.04(7) ECDsupport, CCDC2226694unretrieved'),('C7primeNOEtextversusCH3Table1and5primelist','PDF2 actualpage','potentialnumberingtyponotsilentlyfixed'),('Scheme1proposednotvalidatedgenecluster','PDF2–3 Scheme1','PKSNRPSmalicacid analogical i–iv noisotope/enzymetests'),('EC5015.4uM A375RSL3rescue notenzymeIC50','PDF3 Figure5ABCD','786O H1299othercells noEC50reported'),('Erastin FINO2 A375 rescue scopes','PDF3 Figure5EF','limitedtestedmodelsnotallferroptosis'),('DPPHironnegativeassays andlipid26.4to12.2vsFer12.67percent','PDF4 Figure6ABC','directlyviewedratios; limitedassaynegative'),('HMOX1protein/mRNAdecrease andZnPPpartialrescue notdirecttarget','PDF4 Figure6DEF','2/4/6/8hIB panel;P<.01exacttestnunknown; nocausalgeneticrescue')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read all5originalPDFpages includingreferences; viewed originalpages1–4 and all9actual300dpi graphic/table/schemecrops. SI and crystaldata notretrieved, no independentECD recalculation. No externalmodel or humanreview.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
