import json,time
import worker as w
d=w.ROOT/'sources'/'IZ54BKA3'
rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft']
images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'TF_activators':22,'TF_repressors':10,'TF_total':32,'elicitors':9,'enzyme_table_entries':21,'online_year':2024,'volume_year':2025,'FW_DW_conversion_performed':False,'fold_changes_multiplied':False,'PAL_methylation_equals_TET1_demethylation':False})
claims=[('Identity','PDF1-2/liveZotero','Repository cover plus Expert View four authors DOI erae240 online23May2024 volume76(1)124-1332025; correspondence Coombe-Tennant Loake deceased'),('Coverage','PDF1-11','All eleven original pages read and viewed including repository cover and ten article pages; four complete final300dpi crops viewed'),('Candidate evidence','PDF3-4','Genomic proximity and coexpression select candidates;13 bait genes expression correlations not enzyme causality'),('Reconstruction','PDF4-5/Table1','21 table entries include distinct PCL sources and nomenclature not21 uniformly essential reactions; fed second module not full carbon deNovo'),('Quantities','PDF4-5','64.29 and29.39nggFW different acylactivases versus941.40Taxusleaf;50ngg baccatin massbasis unspecified noFW/DW imputation'),('Path uncertainty','PDF6/Figure1','ABCDE includes hypothetical intermediates grey unassigned T1betaH/T9alphaO probable TOT1 multifunction; not all reactions independently established'),('Diagram conflict','PDF6/Figure1D','CoA bearing structure labelled beta phenylalanine and acid structure labelled beta phenylalanoylCoA retained original labels with conflict noted'),('Regulators','PDF7/Table2','Nine elicitors32TF22activators10repressors not common dose/titer comparison'),('ERF conflict','PDF7/Table2/PDF11references','TcERF12 activator TcERF15 repressor opposite Zhang2015 reference title; original full experiment not newly checked'),('bHLH conflict','PDF7-8','Body bHLH46 vs table TmbHLH14 not silently unified'),('Cross species','PDF8','2039TF974PSM933central carbon promoter binding Arabidopsis not Taxus census or causal production'),('Methylation','PDF8-9','Ten/fourteenyear lines promoter region specific correlations DBTNBT upstream high both old/new GGPPS undetected not whole genome generalization'),('Intervention boundary','PDF8-9','Taxus5aza2deoxycytidine distinct other species5azacytidine PTX recovery with biomass decrease parameters not invented'),('Editing direction','PDF9','Arabidopsis TET1 demethylation and tobacco DRM methylation different directions; proposed Taxus DBTNBT recovery not demonstrated'),('Fold boundary','PDF9','3.5fold chemical conditions and25fold methylated PALg1 associated combination comparison not multiplied nor sole methylation causal attribution'),('Publication evidence','PDF9-11','Fal2024 bioRxiv development evidence not TaxusPTX histone experiment; no assertion about current2026publication state'),('Transparency','PDF9','No conflicts IBioIC BBSRC listed funding; not all cited full studies or raw datasets independently reviewed')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Read and visually inspected all eleven physical PDF pages and all four complete final original crops, including Box1 and Figure1ABCDE. Preserved source contradictions and feeding, species, methylation direction, units and publication date boundaries.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review)
w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
