import json,time
import worker as w
d=w.ROOT/'sources'/'U7JJFWV8';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'taxol_fold1_20_increase_percent':(1.20-1)*100,'10DAB_abstract_body_difference':2.16-2.09,'RNAi_taxol_relative_decrease_percent':(1-.89)*100,'RNAi_DAB_relative_decrease_percent':(1-.49)*100})
claims=[('Identity','PDF1/9/11','11pages9authorsfirst2equalChunfangZhaocorrespondFrontPlantSci12article697476DOI20210809fund2019ABA091COIread'),('Coverage','PDF1to11Figures1to5','All11mainpagesread11originalsviewed5final300dpicropsallpanelscaptionsunitschecked SI Table1actualunreadMW928850notdownloadedreferencesfullpapersunread'),('Hormone','PDF2/4/5Figure1','Cells#48SA2.5mMMeJA.1mM0to6hWRKY33SA6h3.24 noMeJAinductionnotnochangestarsdeclineorJAexclusivity;ERF15SA3h2.66other7gene6hvaluesfrombody'),('Features','PDF3/4/5Figure2','TwoWRKYdomainC2H2GroupIphyloAtWRKY20notAtWRKY33identity LSPLLspeculative nofunctionmutation;GFPonionnuclearnotallnativecells2daysvs2plus2methods'),('Intervention','PDF3to6Figure3','10yearleavesLBA4404OE5.72RNAi.47matchingemptyvectorsn3biologicaltechnicalnotn9 sevenupBAPT.57downRNAiT10H2.00upretainheterogeneity'),('Metabolites','PDF1/5/6/8Figure3DE','Taxolrelative1.20not2.20RNAi.89DAB.49 DABabstract2.16body2.09notaveraged graphnounitsnoexactP invented notmgL;DBAT10DABsubstratenotproductsourceerror'),('DBAT','PDF6/7Figure3FGH','Y1Hquadruple6bpmotifsY187reportnotnativeChIP noEMSA;383bpfullvsprogressiveWa/Wbdeletionnotcleanmutations Wbcontributioninferencearchitectureconfounds'),('ERF15','PDF7/8Figure4','ERF15OE1.24RNAi.47 GUSactivitynotTFbinding715promoterY1Hbinding W1deletereducesW2furtherdeletepartlyrecoversfull>double>single notbothpositiveroles nojointERFblockrescue'),('Errors','PDF2/3/6/8/9','MethodgeographyHUSTVilniusconflict;Duncanp>.05significantsymbolconflict;Figure5DBATandTASYbothtaxadienesynthasewrong DBATacetyltransferase'),('Limits','PDF1to11','noexactPstatsCIrawdatasequenceonlyaccessionnotallrawdata;noSAreceptornoSAexclusiveallconditionsindustrialproduction noERF15proteincomplexclaim')]
labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex11mainpagesread11originalsviewed5complete300dpicropsallpanelscaptioncheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
