import json,time
import worker as w
d=w.ROOT/'sources'/'JNTM74E7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
m1=[62.5,31.25,15.62,15.62,62.5,31.25];m2=[.98,.49,1.95,7.8,7.8,15.62]
w.write_json(d/'codex-arithmetic.json',{'isolated_mass_mg':25,'mixed_culture_volume_L':50,'isolated_recovered_mg_per_L':25/50,'formula_DBE':(2*20+2+3-17)/2,'MIC_compound1_over_compound2':[a/b for a,b in zip(m1,m2)],'compound2_lower_MIC_all_six':all(b<a for a,b in zip(m1,m2)),'norfloxacin_Ecoli_MIC_is_gt125':True,'gatifloxacin_Bsubtilis_is_not_tested':True,'analytical_titer_measured':False,'single_culture_matched_control_reported':False,'absolute_stereochemistry_verified':False,'biosynthetic_precursor_labeling_done':False,'statistical_significance_reported':False})
claims=[('Identity','PDF1-3 Crossref','FiveauthorsFoshanHainan English47issue5pp767-7692011Nov DOI10.1007s1060001100538registerednotprinted Crossref200allmatch liveZotero200 Russianoriginalpp674676different'),('Coverage','PDF1-3 Figure1Tables1-2','All3pagesreadviewed threecomplete300dpicrops includingallHMBCarrows allTable1weakoverlapfootnotes andfull24MICcellsnot testedgt125 preserved'),('Source','PDF1/2/3','TwoAspergillusspFSY01FSW02 rottingAvicenniamarinafruitZhanjiang depositedFoshan no speciesDNA no producerassignment singleculturematchedcontrolinductionproof'),('Recovery','PDF3','50L mixedmycelia25mg1 .5mgL isolatedrecovery notbrothtiter extractionyield no pairedmycelialextracellularmassbalance'),('Formula','PDF2/3','C20H17N3O4EInominal363DBE14 sample.4H2Onotcovalenthydratedstructure exactmassunmeasured fragment29555notpathassigned'),('NMR','PDF2Table1','DMSOd6H400C100TMS20C sixaromaticCH ninequaternarysp2 oneCH threeCH2oneOMe C23NHnoextraC; strongcoupleoverlap weakHMBCnotrawrechecked'),('Connectivity','PDF1/2Figure1Table1','HMBCwrittenCtoH associationnotreaction C13H24supportsOMe13C18151.3imineauthor; C2164C10161.6 othercarbonyls notalllowfieldcarbonyl'),('Stereo and origin','PDF2/3','Lprolineanthranilate structuralproposal nofeedinggenesenzymes; minus96rotationc.12MeOH notRS orpureenantiomer proof'),('Comparative MIC','PDF2Table2','m1six62.5 31.25 15.62 15.62 62.5 31.25 vs m2 .98 .49 1.95 7.8 7.8 15.62allm2lower ratio63.8 63.8 8 2 8 2 notstatisticalexacteffect'),('Comparator limits','PDF2Table2','Gatifloxacin Bsubtilis Not tested nozeroinactive NorfloxacinEcoli gt125censored not125 m1betteronlySaurEcoliandothersworse nogeneraldrugadvantage'),('Method limits','PDF2/3','Bacillusdysenteriaeproteusnegativeasprintedmodernnameunverified strainsunnumbered final1to2e8CFUmlselfreport no rewrite standardscorrespondenceunverified noNvariancePvalueMBCtargetcytotoxefficacy'),('Declarations','PDF1-3','No explicitgrantCOIrepository fields notnegativeassertions citedrefsnotallread humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three original pages read and viewed; full Figure1 and Tables1-2 checked; Crossref identity verified; mixture origin separated from unproven induction, structural precursor assumptions and comparative censored MIC','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
