import json,time
import worker as w
d=w.ROOT/'sources'/'N6EIP5DM';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Narrative review2026formal44(7)1939–1959, copyright2025','PDF1,19–21','DOI10.1016/j.tibtech.2025.11.013 authorsandaffiliations checked'),('Figure1hostarrows distinguishintermediatesfromfulldeNovo','PDF2 Figure1caption','heterologouskeyprecursorsrelatedtaxanes'),('Figure2twospeculativebaccatinroutesandsidechain','PDF5 Figure2, Box2and3','greenandpinkalternative,grayPAM/PCL/BAPT/hydroxylation/DBTNBT'),('IUP147foldprecursorpool notTaxolyield','PDF7,12–13','differentendpoint and exogenoussubstrate/cofactorneeds'),('Totaloxygenated570±45 and361.4±52.4mgL not5alphaol','PDF8–9 Table1','actualrotatedtable visuallyread'),('Yeast0.97ugL paclitaxelfrombaccatinIII','PDF9 Table1','explicitstrategystartfrombaccatinIII'),('Tobacco64.29nggFWstartingmaterialnotindependentlyresolved','PDF10 Table1ref18','sidechaingeneslisted,originalMolPlantnotread'),('Baccatin50ngg tableunitincomplete,Science2024DW','PDF10Table1; separatelyreadZ6YUHKGSPDF7','preserveoriginaldryweightwhiletable10–30uggDW'),('EngineeredAlternaria61.9±6.3ugLtaxadienenotnativeTaxol','PDF11Table1;Box1','differentclaimscope'),('ABCG2candidateinvitrotransportnotvalidated','PDF19','singlecellandMSI notfunctionaltransportproof'),('Figure4ABCfutureAIframeworknotfullTaxolvalidation','PDF17–18 Figure4','sensor PLM and combinatorialpathway;EPA27.5gLdifferentproduct')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read original21page formalPDF maintext Boxes1–4 and references; viewed Figures1–4 and all4rotatedTable1pages; inspected eight actual300dpi crops. Reference Science2024 read separately in same task; other99referencepapers notall independentlyread. No externalmodel or human review.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':['Figure 1','Figure 2','Figure 3','Figure 4','Table 1'],'covered_labels':list(dict.fromkeys(x['label'] for x in images)),'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
