import json,time
import worker as w
d=w.ROOT/'sources'/'23NGHBLY'
rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft']
images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('113metagenomes14sites5types,101public12new','PDF1–3 Figure1A','66methane19oilgas15hydrate7asphalt6mud,unequal groups'),('MAG thresholds and quality not pathway completeness','PDF2–3Figure1B–C,PDF11','4335new plus1688public to3175 at99ANI;50completeness10contamination'),('Mapping improvement22.91percentagepoints,Welch notpaired','PDF2–3Figure1D','74.05vs51.14;Welcht208.68=9.48P6.02E-18;internalcatalog notexternaltest'),('1895OTUs at95ANI30coverage,contig taxonomy separate','PDF2,4Figure2,PDF11','1707one type166two24threeormore;contig counts notcellcounts'),('Figure3 counts inconsistent,metabolic function prediction only','PDF5–6Figure3','370archaea1527bacteria totals1897;30AOM1163potentialmixotrophs736aerobicgenes'),('17968BGC to9390GCF,novelty comparison notchemical verification','PDF5–7Figure4,PDF12','9278GCF98.81OMDnovelty;MIBiG2hits99.98novelty;80coverage75identity historicthresholds'),('BGC positivegenomes1458andbacteriaarchaeacomparison','PDF7–8Figure5','2.38±1.94vs1.28±0.62P<.001;perMb1.01±.70vs.78±.39P<.00001;238archaealBGC'),('Figure6 heatmap transformation conflicts','PDF9Figure6','captionLog10normalized versus zscore colorbar,not precise rawcounts'),('Depositedcontig size conflicts','PDF2 andPDF12dataavailability','56Gbbody54Gbdeposited;accessions notretrieved'),('Other taxonomy counts remain unresolved','PDF2,5–6','407genera vs960potentialnovelgenera;200OTU10.06percent not1895denominator;44vs55phyla')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read originalPDF maintext methods pages1–12, references13–14 andpublisher15; inspected originalgraphic pages3,4,6,7,8,9 plusall6actual300dpicrops. Local SI absent, no raw-data rerun, no external-model orhumanreview.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
