import json,time
import worker as w
d=w.ROOT/'sources'/'T83FD38L';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'isolated_pigmentosin_drymass_percent':14.8/5200*100,'isolated_skyrin_drymass_percent':5/5200*100,'reported_mass_error_ppm':(546.1534-546.1526)/546.1526*1e6,'H5_vs_monomer_shift_ppm':6.23-6.83,'carbon_formula_count':30,'reported_carbon_resonances':15,'true_tissue_abundance_verified':False,'absolute_stereochemistry_verified':False,'biological_activity_tested':False})
claims=[('Identity','PDF1','TwoauthorsElixWardlaw ANU57:681683 DOIprintedRapidCommunicationJan4finalMar152004 ZoteroJuly7notindependentlyonline verifiedlive200'),('Coverage','PDF1-3 Schemes1-3 Tables1-2','All3mainpagestextoriginalsviewed fivecomplete300dpicrops viewed fullTablefootnotesAD Scheme3allcorrelationfragments; no rawMSNMRHPLC refs19notindependentlyread'),('Source','PDF3','1977Aug14Elix3643CANB BlackMountainone sample5.2gdry14.8mgpigmentosin5mgskyrin isolatedmassnotabundancerecovery'),('Formula','PDF1/3','546.1534found546.1526calcC30H26O10 reportedmass1.46ppm notremeasured;15resonancessymmetrynotsolelinkageproof'),('Fragment','PDF2 Scheme3Table2','MethylC3two-bondC4three-bondgHMBCreported H1.45C20.7H34.66C76.3H42.74C34.9 lactone171.7; rawcrosspeaksnotrechecked'),('Linkage','PDF2 Table1/2','H6absentH8present6.78C6quaternary109.9supports6,6 connectivity withcomparisons andgHMBC;bodytenmethinesovergeneralizednonprotonatedcarbons'),('Tables','PDF2 Schemes1/2 Tables1/2','4data onlysemivioxanthinhalf CDCl3/DMSOcomparisons specified footnotea-c assignmentsreversed; no falsewholemoleculetable claim'),('Shift','PDF2','H56.23vs6.83upfield minus.60 versusdeshielding wordingconflict preservevalues no inventedanisotropymeasurement'),('Stereo','PDF1/2/3 Scheme1','Pigmentosin1wavybondscomp2/3wedges rotationminus7.1c.03EtOAc notRS orenantioselectivity;C3/C6chirality expresslyunknown aromaticC6 nottetrahedralcentre'),('Biosynthesis','PDF2','PhenolicradicalmonomerC6orC8coupling envisagednotmeasured enzymegeneisotope; no cellpartnerorigin orbioactivity'),('Analysis boundary','PDF3','KnownUVcorrelation99.9not newcompoundpurity;newhomogeneityHPLC1HNMR qualitative;EIMS547Mplus1relative59and5465reportednotreassigned'),('Declarations','PDF3','ARC no grantnumber no explicitCOI humanreviewfalseclassificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three original pages read and viewed; three schemes and two tables complete original crops visually checked; structural connectivity versus unknown stereo and proposed biosynthesis distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
