import json,time
import worker as w
d=w.ROOT/'sources'/'M4QLM7A9';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'upstream11_vs5_7_fold':11/5.7,'overall93_5_vs4_6_fold_multiple_conditions':93.5/4.6,'static_taxadiene_input_mg':100*.001,'static_resin_wet_g':.1,'static_supply_limit_mg_per_g_wet':100*.001/.1,'dynamic_elution_percent':29.1/31.6*100,'reactor_reported_mgL':71,'flask_reported_mgL':93.5,'wet_dry_capacity_comparison_allowed':False,'recovery_denominators_fully_defined':False,'biological_n':None,'exact_P':None})
claims=[('Identity','PDF1/7/8','8pages6authorsJianHeXuECUSTProcessBiochem122129to136DOIprintedacceptedSep4onlineSep7ZoteroNov2022fund2019YFA0905000noconflictauthor'),('Coverage','PDF1to8Figures1to5Tables1to2','All8mainpagesreadoriginalsviewed7finalcomplete300dpicropsviewed F3allABCDgelandrightcaption noSI seqprimersS1S2FigS1to14rawMSNMRcalibrationreactorunread refs40notindependentlyverified'),('IdentityGenes','PDF2Table1','BL21DE3GGPPSfromTaxuscanadensisAF081514TSbrevifoliaU48796codonoptimizedauthoraccessionsnotdownloaded Table1ECU5008duplicateoneGSGGSGGSGvsGSTGS2 no silent5006correction rigidlinkerseqextraAbodyconflict'),('Upstream','PDF3/4Figure2','ECU5000dxsidiispDF4.6mgL72h ECU5001dxsidi5.7stronger500311mgL measuredproductnotIPPDMAPPpoolorburden noallMEPstepsdiagramproved'),('Fusion','PDF4/5Figure3','TSGGPPSfusionconditional16vs22C qualitativeS/PbandslowerTsolubilitysupportnotdensityquantnotkcatnotdirectsubstratechannelingnoGGPPpool measured32.1GSTGS37.8GSTGS2 author2.7/3.6foldneedmatchedconditionsnotautomatic11higherTbaseline'),('Conditions','PDF5/7Figure4','lowerinduction51.7then3percentglycerol93.5mgL7.7mgpergDCWmainSIreferenceonly overall93.5/4.6about20.33multifactor notsingleconstructeffect TBglycerol15gLrepeatedwordingnotresolved'),('Reactor','PDF7','5L71mgL48h20C vsflask93.5 72h16C notmatchedonefactor lowerproductionauthorspoorproteinFigS14unread noindustrialprocessproof'),('Analysis','PDF3','GCMSidentifyFIDpuretaxadienecalibrationoctadecaneIS main1H13C20carbons4alkenic no rawSIcalibrationpurityfullstereo independentlyverified errorbarnstatPundefined'),('Static','PDF3/6Figure5AB','Hz816.90Hz818.89D4020.88mgpergwet static100mgL1mL100mgwet supplies.10mgmax1mgpergwet notactualintrinsiccapacity staticacetoneHz81686.8percent'),('Dynamic','PDF6/7Figure5CD','13.2mgpergdrybodyvswetabstract no wetdryconversion 31.6adsorb29.1elute92.09percentconsistent92.1 distinctstatic86.8 nooverallrecovery'),('Separation','PDF5/6Table2','directextract73.9pure34.6silica67.3pure84.7 versusintracellleach91pure19resin84.5pure75.3 needdenominatorstepvswholeunresolvednotmultiply extracellular92.1plusintracellular91weightedtotal91.6 needsmassweights no unweightedaverage'),('PurityLimits','PDF6/7/8','95.5purityafteradditionalprepLCFigS10unreadnotresin75.3 directchannelingnotproven terminaltaxadienenotTaxol dataavailabilityalldataarticleSIvsNoDataused sourceconflict classificationdeferredhumanfalse')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex8mainpagesreadalloriginalsviewed5Figures2Tables7complete300dpi finalcropsviewed qualitativegelnotdirectchanneling matchedconditions fractionswetdryandrecoverydenominatorspreserved originalduplicateconstruct notsilentlyfixed SIunread humanreviewfalse','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
