import json,time
import worker as w
d=w.ROOT/'sources'/'DEPIFGZ4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'formula':'C21H20O6Cl2','DBE':(2*21+2-20-2)/2,'reported_HRFAB_MplusH':439.0731,'reported_calculated_MplusH':439.0715,'reported_mass_difference_mmu':(439.0731-439.0715)*1000,'reported_mass_difference_ppm':(439.0731-439.0715)/439.0715*1e6,'MRSA_MIC_ng_mL':37,'VRE_MIC_ng_mL':78,'MRSA_MIC_ug_mL':37/1000,'VRE_MIC_ug_mL':78/1000,'NCI60_mean_GI50_uM':6,'isolated_mass_mg':60,'nominal_fungal_base_volume_L':20,'isolated_mass_per_nominal_L':60/20,'actual_total_volume_with_bacterial_addition_accounted':False,'measured_broth_titer':False,'therapeutic_index_determined':False,'animal_efficacy_reported':False,'inducer_identified':False,'absolute_coculture_dependence_proven':False,'NMR_table_ketone_ppm':202.4,'body_later_ketone_ppm':204.4,'table_methoxy_C_ppm':61.9,'body_methoxy_C_ppm':61.6})
claims=[('Identity','PDF1/3','SixauthorsCuetoJensenKauffmanFenicalLobkovskyClardy UCSDCornell JNP6411:1444-1446 DOIprinted receivedMay30webOct192001 ZoteroNov1 live200'),('Coverage','PDF1-3 Scheme1 Table1 Figure1','All3mainfullpages textoriginalsread threecomplete300dpi cropsviewed unnumberedstructures1RMe2RH designatedScheme1noteonly Table21rowscompletefootnotes Figure1bothasymmetricmolecules;noCCDCcoordsrawNMRbioassays12refsnotallread'),('Organisms','PDF1/3','CNL365Pestalotiamorph1996BahamasRosenvingea unknownspecies CNJ328gramnegativeFAMEunidentified notMRSAorVREtesttargets'),('Trigger','PDF1/2','Mixedpositive standardsingleculturesnotdetected butfungalpureexternaltriggerlowyield qualificationofabstractonly;fungalcapabilitynotexcludeeverybacterialcontribution'),('Signals','PDF2','Extractcellfreebrothnegative notallchemicalsruledout no BGCregulatorsensor identified competitonhypothesis background400foldotherstudy notpestalone'),('Composition','PDF1/3','C21H20O6Cl2EI438440442dualCl HRFAB439.0731calc439.0715delta1.6mmu3.64ppm DBE11 notpositionproof'),('NMR','PDF2 Table1','First-ringisopentenylaldehyde supports secondringHMBCinsufficientXrayneeded;Tableketone202.4latertext204.4 methoxy61.9text61.6 C21HMBC145.9C10145.5 preservedconflicts'),('Types','PDF2','103.2H4aromatic vsbodytwoolefinic103.2123 and12quaternaryaromatic problematic C17132.1notinventnewvalues;OH10-13lowchemicalshiftwording butactualdownfield'),('Xray','PDF2/3 Figure1','173K P21c2asymmetricmoleculesR6percentI2sigma contacts2.622.522.78A crystalnearorthogonalnotrotationalbarrierstableatropisomer orsolutionoccupancy'),('Isolation','PDF3','HCT116activityguidedisolationnotallMRSAguided60mg20nominalL3mgLrecoverednotrealbrothtiter additionalbacterialvolumeunknown'),('Antibacterial','PDF1/3','MRSA37ngmL=.037ugmL VRE78=.078 specifictests no fullstrainpanelMBCtargetCIstatistics currentstandardoranimalmodelcompleted'),('Cells','PDF1/2','NCI60meanGI506uM growthinhibitionnotcell50deathnormalcellthreshold;no therapeuticindexdirectGI50MICratio'),('Analogue','PDF1/2 structure2','Desmethyl2patentreported5alphareductase notpestaloneactivitytest no secondnewisolate'),('Declarations','PDF3','NIHCA44848CA55060CA24487 SpainNATOfellowship noexplicitCOI humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three full original pages read and viewed; complete original chemical structures NMR Table and both-molecule crystal figure visually checked; coculture induction versus pure fungal capability, NMR conflicts, crystal geometry and in vitro activity distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
