import json,time
import worker as w
d=w.ROOT/'sources'/'N5FYZAQ6';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Identity','PDF1/10/12','14pages8authorsIJMS23:13194DOI titleabstractTaxuschinensisMethodTaxusmediaunresolved GenBankON759763authorreportednotdownloaded'),('Coverage','PDF1to14Figure1to5','All14mainpagesreadandoriginalsviewed5complete300dpicropsviewed SI S1toS5 TableS1actualunread referencesnotindependentlyread'),('Candidate','PDF3/4/8Figure1','24TcVQcandidatepartialmotifconservationlowbranchconfidence notfullorthologfunctionalproof10plus25equals34lengthconflict95to128vs95to130'),('Expression','PDF3Figure1DE','DMSOvsMeJAaxis6h TcJAV3starP.05TcWRKY26twostarP.01 noexactmeansdoseqPCRdetailsmaintextnotprovided'),('Phenotype','PDF4/5/10/11Figure2','HeterologousfunctionalphenotypenotTaxusJAmetabolitecausality n12SEMthreerepeatsnot36independent body5dayscaptionmethod7days StatisticslesiontsurvivalANOVAversusmethodsopposite starsinconsistent ResultsRi17complementMethodCol0backgroundunresolved'),('Interaction','PDF6/11Figure3','Y2HBiFCLCIsupportTcJAV3TcWRKY26interactioncontrolsnegative noTaxusnativeCoIP noinhibitionactivityJAdependentdissociationproteinKd;Cx2CcaptionCx4Ctextandfigure noTcresiduemutagenesistest'),('Promoter','PDF7/8/12Figure4','Y1Hwaandwbthreecopyresponsewa stronger underselectionnotKd;DualLUCfullDBATrespondP.05wa-deletedandnoWboxnsprogressivedeletionsnotcleanpointmutations noChIPEMSAnativewaessentiality'),('Model','PDF9Figure5','JAubiquitinationdegradationphosphorylationE3modeltwoalternativesnotdirectexperiment noTcJAV3inhibitionreporter noindependentnonredundantequalimportanceproof'),('Output','PDF7/9/10','NoTaxusmetabolicinterventionnewpaclitaxelquantyieldDBATtwofoldpriorref27notnewresult DBATratecontrolbackgroundnotmetaboliccoefficient')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex14mainpagesread14originalsviewed5complete300dpicropsallpanelscaptioncheckednoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
