import json,time
import worker as w
d=w.ROOT/'sources'/'G27YIFKJ';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'printed_matrix_first_row_sum':.18-.16-.09+.07,'printed_matrix_row8_sum':-.44-.59+1.12-.08,'matrix_height_is_not_automatically_probability':True,'Figure1_panels_count':6,'actual_paper_authors_count':2,'editor_not_author':True,'original_figure_notebook_executed':False,'package_installed_or_current_compatibility_verified':False,'upstream_biological_models_reproduced':False,'quantitative_benchmark_reported':False,'historical_python_versions':['2.7','3.6']})
claims=[('Identity','PDF1','AmmarTareenJustinBKinneytwoauthorsCSHL AlfonsoValenciaAssociateEditor notauthor ApplicationsNote36issue7pp2272-2274DOIprinted liveZotero200 onlineDec102019 volume2020 downloaded2024notpublication'),('Coverage','PDF1-3 Figure1','All3pagesreadviewed onlyFigure1 completeAtoF structureallaxesgeneannotationgenomiccoordinate entirecaption expandedrightmargin300dpicropchecked'),('Interface','PDF1-2','DataFramerowspositionscolumnscharactersvaluesheights matrixsigned arbitrary suitabledata matplotlibAxesnativevectors noanalysisvalidityguarantee'),('Energy','PDF2Figure1AB','CRPnegativeDeltaDeltaGenergykcalmol priorKinney2010 PDB1CGP priorParkinson1996 notnewcrystalKDmeasure firstrowdisplaynumberssumzero includesnegative notprobability'),('Probability','PDF2Figure1C','Annotatedhuman5primesplices GENCODEprobability dashedexonintron no celltypespliceefficiencyproof or exactNreported'),('Information','PDF2Figure1D','WWdomainPFAMRP15 informationbits highlightednamedpositions notsameprobabilityunit nofunctioncausality orreportedexactalignmentcount'),('Enrichment','PDF2Figure1E','ARS1log2enrichment orangeWT threeAB1B2regions unpublishedJBK data analogousmutARSseq nofullsamepublishedexperiment noreplicationrateconversion'),('Attribution','PDF2Figure1F','U2SURPexon9 maskedDNNscores permissionadaptedJaganathan2019 notnewtrainingcausalwetassay chr3coordinatebuildunreported unshownalternativebasesnotzeromeasure'),('Conversion','PDF2','Matrixconversionprobabilitylogoddsinformationmasked described no complete pseudocountbackgroundgapdefaults here no inventedformulaimplementation'),('Evaluation','PDF2','Authorsthoroughlytested noquanttestcountscoverage runtimememorybenchmark; actualusagescitedpreprintspluspublications notindependentsoftwareverification'),('Availability','PDF1-2','OriginalPython2.7Python3.6historicalcompatibility docsGitHubfigureipynb cited no currentAPICLIinstalled testednotebookrun'),('Declarations','PDF2/3','NIH1R35GM1337775P30CA045508 CSHLNorthwell conflictno CC BY4 paper sourcecitationsnotallread humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three original pages read and viewed; complete Figure1 A-F and caption visually checked; software display functionality distinguished from upstream biology, historical compatibility and unperformed code reproduction','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
