import json,time
import worker as w
d=w.ROOT/'sources'/'T6ZTH9UD';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'invivo_isolated_mg_per_L':[.5,1.3],'fold_change':1.3/.5,'percent_increase':(1.3/.5-1)*100,'cellfree_taxoid_mixture_nominal_mg_per_L':10/2,'cellfree_not_culture_titer':True,'GCMS_minor_fraction':.13,'GCMS_fraction_mass_equivalent_verified':False,'pure_major_product_mass_derived':False,'independent_repeats_or_statistical_tests_reported':False,'DXPS_effect_isolated':False,'taxol_production':False})
claims=[('Identity','Main1/liveZotero200','Original PII matches DOI title fourauthors pp2237-2242; Zotero onlyoneauthor incomplete notmodified'),('Coverage','Main1-6 Figures1-4 Table1','Entire maintext read and allsixpages viewed; full300dpi crops allfigures captions Table1footnotes gelA-D spectra axes complete finalcropvisualchecks'),('TS truncation','Main2 Figure2A','First78 aminoacids removed pTS79H name not79deletion; solubleprotein90kDa notindependent quantitativefullTScomparison'),('Gene products','Main3 Table1 Figure2','Taxusbrevifolia TS Schizosaccharomycespombe idi1 Erwiniaherbicola crtE Ecolidxs; threeproteins fourfunctions fusionnotchannelingproof'),('Smallscale NMR','Main2/5 Figure3','Taxadiene121.9 42.0 31.1 30.4 GGDP40.2 25.8 ACN118.8 glycerol63.9 73.3;70percentauthorestimate notpureyield'),('Scaleup mixture','Main2/3/4','2Lcellfree10mgpurifiedtaxoidmixture minor4(20)13percentGCMS notmassfractionasserted; minorfullspectranotshown mechanismalternativeunresolved'),('In vivo design','Main3/4/5/6','TSonlynondetect; IDPI-GGDPS TS.5mg1L isolated;final DXPS plusplysS-IGS regulation1.3mg1L2.6fold confounded no exclusiveDXPScausality'),('DXPS activity','Main4/6 Figure4','0 3 16h37C carbonpyruvate25.8 DXP26.3 deoxyxylulose25.2; same25.8inFigure3differentmolecule context'),('Units and recovery','Main5/6','OriginalmuLsmallscale notmL antibioticsmicrogmL IPTG50mgL roomtempunspecified24hpostinduction; biomass extraction isolation weighing no totalproductmassbalance'),('Limits','Main4-6','No nSD exactP CI reconstruction DXRfuture nottested noGGDPpoolflux directmeasurement allreferencesnotindependentlyread humanreviewfalse classificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex full six-page original maintext read and visually checked; complete figure/table crops reviewed; identity via printedPII; isolated mass and multifactor DXPS comparison distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
