import json,time
import worker as w
d=w.ROOT/'sources'/'FBCVZJMP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'empirical_formula':'C42H57N7O9','nominal_formula_mass':42*12+57+7*14+9*16,'Figure1_nominal_fragments':[43,190,303,450,533,632,703,803],'Figure1_first_six_differences':[190-43,303-190,450-303,533-450,632-533,703-632],'Thr_nominal_residue_after_assumed_dehydration':101-18,'acid_nominal_mass_inferred_from_Mminuswater':803+18,'methylester_nominal_mass_reported':835,'methylester_minus_inferred_acid':835-(803+18),'free_residue_formula_sum':{'C':40,'H':69,'N':7,'O':15},'six_peptide_bonds_water_loss':6,'N_acetylation_net_formula':{'C':2,'H':2,'O':1},'lactone_additional_water_loss':1,'final_formula_from_count':{'C':40+2,'H':69-6*2+2-2,'N':7,'O':15-6+1-1},'acid_mass_is_direct_observed_M':False,'absolute_stereochemistry_determined':False,'Dhb_double_bond_geometry_determined_maintext':False,'biological_activity_tested_here':False})
claims=[('Identity','PDF1/2','NakagawaNakazawaJunichiShoji Shionogi JAntibiot2812:1004-1005Dec1975receivedApr11 live200 DOIonlymetadata automatedDOItitlefalse manuallycorrect;metadataShojmisspellnotPDF'),('Coverage','PDF1/2 Figures1-3','Bothfullpages text originalsread threecomplete300dpi figurecrops viewed including expandedFigure2leftAc fullformula finalesterbond; nofullrawIRMSAAchromatograms previouspapersnotallread'),('Composition','PDF1','Priorreference1Bsubtilis TL119 empiricalC42H57N7O9 ThrAlaValLeuonePhetwo notnewstrainengineering bioactivityorBGC'),('Dhb','PDF1','Hydrogenationhydrolysatealphaaminobutyrate plusintactacidhydrolysatemethylalphaketobutyrateGCMS supportoneDhb notbothnaturalresidues;UVnotsolegeometryproof'),('Sequence','PDF1 Figure1','AcPheLeuPheThrValAlaDhb43 190303450533632703803 intactnominalM notMplusH;Thrdehydrationassumed101minus1883 533relative27percent notpurityyield;last100gapnotfreeresidue'),('Methylation','PDF1 Figure2','AcMePheMeLeuMePheDiMeThrMeValMeAla43 204331492621734819derivative notnatural methylatedresidues;authornoCterminusinfo'),('Nterm','PDF1','Nacetylcompatible neutralninhydrinnegative jointsupportnotaloneuniqueassignment'),('IR','PDF1/2','Intact1723 acid1695 methylester1728cmminus1 conjugation explanation notuniqueconnectionproof general1740context'),('Mass','PDF1/2','AcidMminusH2O803 inferM821 notdirectacidM;esterM835 plus14netCH2 acidopeningplus18 consistentnotnewHRMS'),('Oxidation','PDF2','AcidThrdestroyed oxidation hydrolysateAA vsintactThrnotaffected supportsOHprotected nofulloxidizedproductrawreplicates'),('Closure','PDF2 Figure3','DhbCterminalesterThrsidechain NacetylPheLeuPhe tail notall7headtotailamidering'),('Formula','PDF2','Nominal803 empiricalformula andsevenresidue count minus6waters NacetylC2H2O minuslactonewaterconsistentnotallconnectivityisomersruledout'),('Stereo','PDF2 Figure3','Postulatedstructure expresslywithoutaminoacidstereochemistry do notfillDL Thr orDhbEZ'),('Method and limits','PDF1footnote/2','HitachiRMU6 directinlet250C70eV notmodernsoftionMS raw unavailable no independent nCI P MIC orfundCOI statement humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex both full original pages read and viewed; three complete original figures visually checked; intact and derivatized nominal fragments versus inferred acid mass, postulated connectivity and unresolved stereochemistry distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
