import json,time
import worker as w
d=w.ROOT/'sources'/'K3AA2KIP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
mz=19*12+12*1.00782503223+7*15.99491461957+22.9897692820-0.000548579909
w.write_json(d/'codex-arithmetic.json',{'formula':'C19H12O7','ion':'M+Na','reported_mz':375.0462,'calculated_monoisotopic_mz':mz,'absolute_difference_mmu':abs(375.0462-mz)*1000,'absolute_difference_ppm':abs(375.0462-mz)/mz*1e6,'paper_reported_difference_mmu':1.9,'WJ78_reported_mgL':150,'WJ150_reported_mgL':50,'same_product_improvement_comparison':False,'Scheme2_20_to_21_reported_step_percent':91,'intramolecular_displacement_reported_quantitative':True,'biological_replicates_reported_maintext':False,'raw_SI_read':False})
claims=[('Identity','PDF1/2','Sixauthors Zhang Wilke Zhan Watanabe Boddy Tang UCSyracuseUSC JACS12930:9304-9305 DOIprinted webJuly112007 receivedMay22 versusZoteroAugust1 live200'),('Coverage','PDF1-2 Schemes1/2','Bothmainpagestextoriginalsread bothcomplete300dpicrops viewed all1-22 structures branches arrows labels; no FiguresTables;SI experimental NMR plasmids unavailable notread'),('Product','PDF1 Scheme1','15WJ78 C19H12O7 reportedm/z375.0462Na delta1.9mmu150mgL; noN;formula notaloneesterconnectivity proof'),('Mass','PDF1','Independentreportednumbersarithmetic standardmonoisotopic375.047523 absolute1.323mmu vsoriginal1.9 preserved notrawremeasure'),('Structure','PDF1','NMR deltaC11 151 ester vs pyridone syntheticstandards SIauthor statement notindependentallHMBCverification'),('OxyD','PDF1','Omission OxyD retainPKSOxyJOxyK no detectable15 detectionlimitreplicatesnotprovided necessaryunderreportedconditionsnotabsolutezero'),('Protection','PDF1 Scheme1','AmideprotectterminalC19 preventdecarboxylation interpretation no directisotopeN orcarbontracking intermediatesnotallisolated'),('Branch','PDF1 Scheme1','12OxyKdehydration enablesphenol attackamide to15 vs slowdehydrationamideattackketone pyridone hypothesis noquantkineticseries'),('Model','PDF1/2 Scheme2','Acid19directamideactivation failedlactone21;amide20deprotection phenol displacesamide reportedpH7.4;modelchemicalfeasibility notexact14 orcompleteenzymefreecellularproof RaneyNi present'),('Yield','PDF2 Scheme2','20to21step91percent versusphenoldisplacementquant wording distinct;21to22quant nottotalsyntheticorbiologicalcarbonyield'),('Prediction','PDF2 Scheme1','TcmNregioselectivity prediction5WJ15050mgL consistentnot3foldsameproductoptimization; no sourceCIorPvalue'),('Activity','PDF2','5pannorinanalogue notWJ150HMGCoAreductaseassay;priorpannorin reference cannottransferactivity'),('Extension','PDF2','OxyDlikeotherclusters rubromycin mechanismhypothesis notdirectvalidationotherfungalproducts'),('Declarations','PDF2','UC CRCC NSF CBET0545860 Syracuse Shimadzu support noexplicitCOI humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex both original pages read and viewed; both complete original Schemes visually checked; observed product and omission control versus model chemistry and speculative intermediates distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
