import json,time
import worker as w
d=w.ROOT/'sources'/'YVBR4AY7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'baseline_ngml':314.1,'F4_reported_ngml':[487.9,516.4,496.7],'original_percent':[31.5,64.4,44.7],'calculated_percent':[(v/314.1-1)*100 for v in [487.9,516.4,496.7]],'yeast_taxadiene_mgL':[1000/1000,8700/1000],'yeast_5OH_mgL':25/1000,'yeast_GGol_mgL':33100/1000,'ratio_not_conversion':1000/25,'table_highest_ordinary_mgL':800/1000})
claims=[('Identity', 'PDF460titlefooter', 'Review8pages4authorsJAntibiot201063460467July14DOIja201083 liveZotero200 Englishnonthesisnonimmunitytopic'), ('Coverage', 'PDF460to467Table1Figure1Figure2', 'All8pagesmaintextreadoriginalsviewedTable1p461and462fullrowsfootnotes4complete300dpi crops plus2figuresviewed88referencesandpatentsunreadindependently'), ('TableUnits', 'PDF461462Table1footnotesPDF466', 'ngmlordinary bnanogramsperdryweightnoexplicitgram notcommensurate NDnotdetectzero NRundefined bodylow.024table.01.014 inconsistentrange exampleshighest800ngml.8mgL notcrossstudytruebest'), ('AssayIdentity', 'PDF464to466Figure2', 'Standardmixture13taxanes notfungalvalidation authorunpublisheddata cephalomannineNa854.6 mayconfoundpacliH854 pacliandepiNa876.6 identicalmolecularformulahighermassaccuracynotstereoseparation antibodycrossreactiveUVTLCpeaknotfullidentity'), ('Genes', 'PDF462to464Figure1', 'TS38screen12positive3detected DBATBAPT90screen15and6threeboth sequencesnearplant97to99identity genomiccontextfunctionmissing contamintransferalternativeinterpretationsnotdetermined EU375527EU883596notdownloaded'), ('Negative', 'PDF464Discussion', 'TandreanaetsbaptPCRpositive metaboliteprofilenegative mediaexpressionpassagedroppossible notprovedcausality allreportedproducersnotuniformaffirmedornotuniformdenied'), ('ProductionArithmetic', 'PDF464GenomeShuffling', 'NCEU314.1F4487.9516.4496.7 ngml original31.564.444.7percent calculated55.3364.4158.13 firstthird mismatchunexplained50F388F4screenednotn MS855.2 reportedadductunverifiednotcorrected'), ('Heterologous', 'PDF464', 'Yeast1000taxadienengml1mgL5OH25.025mgL 40ratio notconversion 8700taxadiene8.7mgL GGol3310033.1mgL notTaxol wholepathunclosed2010notcurrent'), ('Scope', 'PDF460463466467', 'NarrativereviewrepresentativeTable1nosystematicsearch nCIerrornotuniform patents45and46lowfollowup noallstrainvalidation noTEALCAcommercialabsence2010scope only fundingSEMARNATFOMIXICyTDFCONACYTnoexplicitCOI humanfalseclassificationdeferred')]

labels=list(dict.fromkeys(x['label']for x in images))
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex8pagesreviewmaintextread8originalpagesviewedTable1bothpagesFigure1Figure2abcd4complete300dpicropsviewedmixedunitsanalyticalambiguityPCRnotcompletepathnegativeprofilinghistoricalproductionarithmeticmismatchPythonverifiednoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
