import json,time
import worker as w
d=w.ROOT/'sources'/'KQEEHRUG';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
draft['source_gaps'].append('Figure3cchr12 164283692to800807320span636.523628Mb vsbody76.2Mb unresolved; exactSupplementaryDatacoordinatesunread')
w.write_json(d/'codex-draft.json',{'draft':draft,'method':'CurrentCodexsourcegrounded8pages'})
claims=[('Identity','PDF1/7/8','19authors5equal3correspondCommunBiol4 1203DOIpub20211020'),('Coverage','PDF1to8Table1Figures1to3','All8mainpagesread8originalpageimagesviewed4final300dpicropscompletepanelsaxeslegendscaptionschecked;SIanddatabasesactualunread'),('Assembly','PDF2/6Table1','kmer10.49Gbassembly10738316084bp scaffoldN50966801426contig2892145 34931genesBUSCO72.6/73.7 notcompletegeneproof98.95percentgenesnotbases'),('Repeats','PDF2/6Figure1','Annotated74.11percentvs77.74kmerdifferentmeasurement LTR40.95Gypsy35.95Copia4.77 rate7.34573e-10datesmodeldependent'),('Phylogeny','PDF2to4/6/7Figure2','14taxasampled T.yun closestS.gig withinset133.4to213MYA GnetalesASTRALDNAexception1KPdiscordance588vs575familiesunresolved'),('Duplication','PDF4/7Figure2','ResultsnoclearpeakvsMethodsKs0.1majorpeak no widespreadsynteny;no recentWGD evidence notexcludeancient; fourduppercent85.57restunresolved'),('CYP','PDF4/5/7Figure3','624CYP45068CYP72562CYP725A40chr12nestedsets notallvalidated;38knownpathhomologycandidates'),('Cluster','PDF5/7Figure3c','Body76.2MbvsFigure3chr12 164283692to800807320 Python636.523628Mb unresolved;3artificialsubregionsdistance<10interveninggenesnotbp'),('Expression','PDF5to7Figure3ad','5tissues3biology15independentsamplestreenumberunknown;stem1mmtwig0.5cmtrunk5cmconfounds;12plus15=27uncharacterizedCYP r>0.8P<0.05correlationnotfunctionmultiplicityCIexactPunreported'),('Limits','PDF1to8','No newenzymeproductstructurenativeperturbationorheterologousPTXgain;historicalC1C9status2021;PRJNA661543actualnotdownloaded; noCOIfundingp8read')]
labels=[x['label'] for x in images];review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex8mainpagesread8originalimagesviewed4complete300dpicropsvisuallychecked;sourceconflictsretainedPythonactualarithmeticSIunread;noexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review)
w.write_json(d/'codex-arithmetic.json',{'coordinate_endpoint_difference_Mb':(800807320-164283692)/1e6,'coordinate_source':'Figure3cheader','body_reported_Mb':76.2,'unresolved_scope_or_typo':True,'four_duplication_percent_sum':sum([60.07,.75,11.66,13.09]),'candidate_count':12+15,'not_raw_statistics':True})
w.validate_structure(draft);note=w.publish(rec,draft,images,review,d);w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'});print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
