import json,time,hashlib
from pathlib import Path
import worker as w
w.GRAPHIC_PATTERN=r'(?:(?:Extended Data )?(?:Figure|Table|Scheme|Chart) (?:S?\d+|[IVXLCDM]+)|Graphical Abstract|Unnumbered Structure Graphic(?: \d+)?)'
d=w.ROOT/'sources'/'U7HI9RTR';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'));si=json.loads((d/'codex-supplement-provenance.json').read_text(encoding='utf-8'))
assert hashlib.sha256(Path(si['path']).read_bytes()).hexdigest()==si['sha256']
w.write_json(d/'codex-arithmetic.json',{'observed_double18O_mass_shift_Da':323.0902-319.0816,'expected_two18O_minus_two16O_Da':2*(17.99915961286-15.99491461957),'unlabelled_protonated_product_main':319.0816,'double_label_protonated_product':323.0902,'mixed_gas_product_peaks':[319.0813,323.0902],'heavy_water_product_peaks':[319.0812,319.0812],'substrate_incubation_minutes':{'1':6,'5':6,'6':6,'13':6,'7':90,'16':480,'14':780,'15':780,'17':780},'substrates_tested':9,'positive_substrates':8,'initial_rate_ranking_valid':False,'phylogeny_conserved_amino_acid_positions':16,'kinetic_constants_verified':False,'radical_microsteps_directly_verified':False,'all_SI_pages_independently_reviewed':False})
claims=[('Identity','Main1/6 and liveZotero','Seven authors JACS14340pp16326-16331Communication DOIprintedSept292021 online notdownloaded2024; mainattachmentESA4KD2W supplementalBY4L2FWE'),('Main coverage','Main1-6 Scheme1-2 Figure1-3','Allsixpagesreadandviewed fivecomplete300dpimaincrops plus six selectedSI tablefigures; allfinalcrops visuallychecked captionsfootnotes present'),('Gene perturbation','Main2 Figure1A/B','DeltaFandK questin1questinol5accumulate DeltaE noobviouschange conditionalnotallGSTdispensable; questinoloxidaseunknown'),('Reconstitution','Main2 Figure1C SI9','GedFwithNADPHproduces4 noFblocks noNADPHblocks FplusK1min4and2 3minreportedcompletechromconversionnot100isolatedyield noexternalFADneeded'),('Annotation','Main2 SI7','GedF databaseNterminaltruncated correctedORF used homologguided nottestoforiginaltruncatedprotein'),('Structure','Main2 SI18TableS3 SI28S10 SI30S12','4unstablemixwith1 C10 66.8CH H5.48s C9nosignal partialcarbonHSQCHMBC H4table7.03figure7.04 overlap; HMBC H10C4C5 H4H5C10 no pureallatomsclaim'),('Cofactors','Main3 SI35S17 SI34S16','Denaturedprotein supernatants noFADFMNdetected withstandards; chemicallyreducedemodin withK workswithoutNADPHFAD distinguisheswholemoduleGedFdependency; noexhaustivemetalanalysis'),('NADPH preference','SI41S22','NADPHgreaterproductthanNADH butNADHsmallnonzeroproduct noabsoluteinability affinityratiounmeasured'),('Oxygen atoms','Main3 Figure2 SI36S18','normal319.0816 double18O323.0902 delta4.0086 mixed319.0813and323.0902no+2 H218O319.0812 no shift sameO2twoatoms supported notuniversaloxygenexchangenone'),('Mechanism','Main3 Scheme2','C10carbonhydrogen deprotonation conjugatedanion8 SETtripletO2 radical9 peroxide10 cycloperoxide11 rearrangement12 protonation2 proposednotallintermediatesisolatedEPRverified'),('Substrate time','Main4 Figure3A SI37-38S19','Nineentries8positive1negative17;1/5/6/13sixmin7ninetymin16eighthours14/15/17thirteenhours endpointbarsnotinitialrate commoncomparison; analoguesHRMSproposedstructuresnotallNMR'),('Phylogeny','Main4Figure3B/C SI13','NJ16conservedaminoacidpositions unrootedlimitedsupport notformalcoevolutionanalysisnotallhomologfunctionverified'),('Statistics and scope','Main1-6 SIselected','Noinventedreplicaten SD P values no kcatKm orbioactivity; naturalproductquestinemodin mechanismfocused otherpathwayinferencesnotexpanded'),('Declarations','Main5','NSFC31972855NationalKeyRD2021YFC2102600Taishansupport no competingfinancialinterest rawdataandallrefsnotindependentlyreviewed humanreviewfalseclassificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex six main pages read/viewed plus selected SI methods and structural isotope cofactor evidence; complete original crops reviewed; proposed radical microsteps separated from demonstrated overall conversion','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'supplement_provenance':si,'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
