import json,time
import worker as w
d=w.ROOT/'sources'/'W8HZP738';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
common=.98*.93*.63*.90
w.write_json(d/'codex-arithmetic.json',{'shown_step_yield_product_aldehyde4_percent':common*.87*100,'author_aldehyde4_percent':45,'shown_step_yield_product_endocrocin2_percent':common*.78*.78*100,'author_endocrocin2_percent':32,'shown_step_yield_product_cinnalutein3_percent':common*.78*.85*100,'author_cinnalutein3_percent':35,'calculated_only_dimethyl10_percent':common*.78*.72*100,'raw_yield_precision_verified':False,'all_endocrocin_carbons_observed':False,'hypericin_redshift_activity_tested':False})
claims=[('Identity','PDF1','Printed entiretitle DOI fiveauthors46:2377-2380 confirms identity automatic titlefalse not actualwrongPDF; JKUHeinzFalkcorr liveZotero200'),('Coverage','PDF1-4 Figure1Scheme1 Note18','All four pages and finaltwo300dpi originalcrops viewed; allbranchesa-i structurescaption intact; no main tables or rawspectra; referencesnotes18notallindependentstudies'),('Numbering','PDF1/3 Note1','Author arbitrary1,6,8 hydroxy3methyl anthraquinone nomenclature; naturalbiosynthetic relationships cited nottested'),('Protection','PDF2 Scheme1ab','98percent methylation then93percentselectivedeprotection minus5vsminus70 verifiedsourcepage negatives; noquantoldcontrol'),('Marschalk','PDF2/3 Scheme1c Note18compound7','63percent isolatedyield notregioisomerpercentage; CH2H4.60C53.1andOH4.92 selectednumbers quinonemethide mechanisticexplanation notdirectobserved'),('Oxidation','PDF2/3 Scheme1def Note18compound4','7directoxidationpoor unquantified; 8reprotect90 then4PCC87 versus9Jones78 differentproducts; aldehydeH10.65C192.9pos341'),('Branches','PDF2/3 Scheme1ghi','9to2full78 to3singleOMe85 to10doubleOMe72; decarboxylation/degradation conditional source no universalstability'),('Yields','PDF2/3 Scheme1','Reported4five-step45 2six-step32 3overall35 versus displayintegerproducts44.95831.44034.261; do not silentcorrection'),('Spectral gaps','PDF3/4 Note18','EndocrocinC9C10aCOOHnotobserved dueinsolubility OH3labelconflicts1,6,8;compound10duplicatedC10aC3assignments; no invented2DNMR crosspeaks'),('Prospective use','PDF1/3 Note18compound4','Aldehyde potentialsynthon hypericinderivatives nofinaldimer photodynamicassay actualUV405 notnewhypericinredshift'),('Limits declarations','PDF3','No scale fullworkup replicates or massbalance noindustrialTEA FWF16969and15380 noexplicitCOI humanfalseclassificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex four main pages read and original pages viewed; complete Figure1 and branched Scheme1 cropped and visually checked; yield arithmetic and spectral omissions retained','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
