import json,time
import worker as w
d=w.ROOT/'sources'/'V6YKJJBL';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'labeled_product_percent':[77.6,11.1,9.2],'reported_percent_sum':77.6+11.1+9.2,'unaccounted_percent':100-(77.6+11.1+9.2),'normalized_to100':False,'unlabeled_major_percent':94,'unlabeled_minor_4_20_approx_percent':5,'relative_4_20_proportion_ratio':11.1/5,'total_rate_approx_relative':.5,'nominal_4_20_absolute_rate_ratio_if_equal_responses':.5*11.1/5,'nominal_ratio_is_exact_rate':False,'KIE_termination_approx':2.1,'KIE_migration_reported':2.0,'NMR_mass_approx_microg':10,'GCMS_estimated_mass_approx_microg':100,'purified_recovery_fraction_exact_known':False,'model_distance_Angstrom_approx':2.2,'actual_transition_state_verified':False})
claims=[('Identity','Main1/liveZotero200','Nineauthors title7issue12pp969-977 PII matchesDOI printedpublicationOct302000 vsDecissue'),('Coverage','Main1-9Figures1-7','Entiremaintextread all9pagesviewed fullseven300dpicrops reviewed sidecaptions NMRaxesallpanels modelingandcompletechemicalscheme noTable'),('Atom mapping','Main2/3Figures2/3','GGPP C4 toproductC5 terminatingbetaHloss; GGPPC10 tointermediateC11 toproductC7 no numberconflation'),('Branch proportions','Main3Figure2','Unlabeled94~5negligible3(4) labeled77.6 11.1 9.2sum97.9notrenormalized totalrate~half relative4(20)rise notdoubleabsoluteyield'),('MS transfer','Main3Figure3','C10Dover99retained Cfragment122to123 parent272to273 supports C7 thenNMRdefinesalpha; no rawmassfilesindependentrecalc'),('NMR distinction','Main3-5 Figures4/5','~10microgmarked insufficient2D selected1D DPFGSEH5at5.3865ms; unlabelNOESY400ms forstereoassignment notmarked2D'),('Stereo signals','Main4/5 Figure4','H7alpha1.76 disappearsH7beta1.19collapseJ6 H6changes standardvsmarked; pentaneinterference .5to1.5 recognized'),('NOESY','Main4/5 Figure5','H19.93 toH7beta1.19 others noH7alpha1.76 relation plusalphaH3C18 supportsassignments notfreeenergy proof'),('Model boundary','Main6/7 Figure6','AM1minimized+1C12carbocation~2.2A distance notenzymeincluded actualtransitionstatebarriers no directallenzymemediationexclude'),('Purity and numbering','Main7Figure7','C4substrate84molD chemical93percent finalH91:9estimatedviaepoxidationassumption vsD95:5;Fig7substrate8 vsFig2substrate7isomer8 originalconflict'),('Unpublished evidence','Main7','C1C15stereochemicalsummary citesunpublishedresults notallfiveprocessesindependentlydemonstrated;M60asreportednotassumeddeletion60'),('Limits','Main8/9','NIHsupport noexplicitmodernCOIdatarepo rawkineticsnSDCI Pnotprovided allrefsnotread humanreviewfalse deferredclassification')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read and viewed all9originalpages andall7completefigurecrops; originalalphabetaatommapping verified relativebranchratio distinguished from absolute formation andAM1model from completeenzyme mechanismproof','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
