import json,time
import worker as w
d=w.ROOT/'sources'/'9BYJS95S';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'recovered_g':0.5,'air_dried_input_g':12000,'recovery_percent':0.5/12000*100,'recovered_ug_per_g':0.5*1e6/12000,'structure_publication_to_first_approval_years':1992-1971,'mass_unit_error_factor':1000,'methanolysis_atom_balance_C':47+2,'product_C':17+29+3,'methanolysis_atom_balance_H':51+8,'product_H':17+36+6,'methanolysis_atom_balance_O':14+2,'product_O':4+10+2})
claims=[('Identity','PDF482/487','Review2authors6pagesAntiCancerDrugs25(5)482487DOI liveZotero verified November82013received18accepted ZoteroJune2014monthretainnoexactday COInone'),('Coverage','PDF482to487','All6pagesfulltextread6originalsviewed manually6figures charts retrieved preparedindexempty Chart1Chart2p483Fig1Fig2Table1p484Fig3p485 final6complete300dpicropsallviewed captionfull originals19refs unreadindependently'),('History','PDF482/486','1960screen1962collect650samplesnot650species1964RTIsamples1971structure1992approval21years historical narrative notoriginal currentregistryverification'),('Yield','PDF482Chart1Chart2PDF483','12kgairdriedstem bark0.5grecovered0.004167percent41.667ugg notabsoluteplantcontent intermediatefractionmassnotanalyterecovery ChartWalkerT/Cmeanmassratio lowerbetter unequaldose notefficacyfold'),('Structure','PDF483Figure1Figure2PDF484','C47H51NO14 formula massesNMRchemical derivativesXrayjointconstraints originalcrystalsunread compounds2to6specifichistoricalindex UV272IR1680delta6.46oxidationderivative notTaxolphysicalconstants'),('Units','PDF484Table1','VisibleED503.5e-5ugml extractedmgml error1000 originalhistoricalvalueunverified notautofixsource repeatedn CIunreported'),('Models','PDF483Chart1PDF484Table1text','WalkerweightT/CvsP4survivaldifferentdirection tableSRCnegative77notordinaryweight ratio responseformulaundefined plusgradesnotPvalues nSDSEMP CIunreported'),('Mechanism','PDF485Figure3PDF486','Figure3A549ControlTaxol wholebothpanelsnotHeLaadjacentorrefmousefibroblast no scale dose time n quantification imageonlyrepresentative'),('Binding','PDF486','Photoaffinity3contactsnot3independentpockets derivativecovalentcrosslinknotnativeTaxolcovalent 3.7Aelectroniccrystalmodel distinct hydrogenexchange complement no originalrawdataread'),('ClinicalBoundary','PDF486/487','Historicalclinicalstoryregimensnotcurrentadvice1983to1988hiatusauthorclaimunverified 1992Dec29approval 1994and1999authorhistorical justthisyear2013received2014pubnotcurrent200yeartreeonepatientundefined regimen noindustrialeconomicproof humanreviewfalse deferclassification')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex6pagesfulltextread6originalsviewed6complete300dpicropsviewedReviewhistoricalclinicalversuscurrentguidancemassunitvisualcheckedT/CendpointboundariesPythonarithmeticverifiednoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
