import json,time
import worker as w
d=w.ROOT/'sources'/'V4DNVIRB';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Sevennew2–8 andknown1,ansaetheronebackgroundnotnew','PDF1–3 unnumberedstructuregraphic','C4substitution/C9sugarvariation'),('SP101promoter andSP102regulatorbackground,WTregulatorsnotproductive','PDF2 Figure1ab','structuralpromoterbackgroundmatters,SIcontrolstextonly'),('tpt14deletionsugarlossaglycones3/4retained','PDF2–3 Figure1b','geneticdependency notpureenzyme kinetics/donors'),('tpt12increased1/6 notattributabledeletionwhencomplementfails','PDF3','authorsexplicitlimitation; SIabsent'),('52kbminimizedcluster vs62402bpfullplasmid','PDF3,5 Figure2','differentlengthscopes'),('Heterologous4matchedretentiontimeUV,notfullspectra','PDF3 Figure2b','hostcontrolstandardtrace, no titer'),('Spontaneouscyclizationprobably notfullydemonstrated','PDF3–4 Figure3','hostenzyme/extractionnotexcluded; authorsrequireprecursor/biomimeticvalidation'),('Printedion1/6/7Hcounts inconsistentwithcalcmasses','PDF3,5 originalpages;codex-mass-check.json','actualarithmeticexampleC26H35NO7+473.2408paper472.2330'),('Absoluteconfiganalogicalbiosynthesis/ECD SIunread','PDF2–3','ROESY/NOESYrelative, methanolysissugarD, ECDsameclass'),('Antimicrobialdisk20ug notMIC,colon50uMneg','PDF3,5','noactivitytestedpanel, no soybeanlipoxygenaseassay'),('Isolatedmgnotcalibratedproductiontiter','PDF5','20Lsolidculture85/64/26/4mg and7/5/4/5.5mg')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read all6originalPDFpages includingexperimental and references; visually checked originalpages1–5 and all5actual300dpi crops; independentlycalculatedprintedionmassdiscrepancies. SupportingInformationmissing; no externalmodel or humanreview.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
