import json,time
import worker as w
d=w.ROOT/'sources'/'GSGUZKME';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'six_MS_feature_clusters_total':sum([974,717,485,411,636,283]),'mesophyll_subclasses_total':sum([168,109,103,79]),'mesophyll_CD':103+79,'mesophyll_CD_percent':(103+79)/sum([168,109,103,79])*100,'TF_candidates':6+5+4+5+7,'promoter_candidates':24+6+6+13+5,'TF_expression_screen_ratio':2**.26})
claims=[('Identity','PDF1/14','17pages16authorsPlantCommun4:100630DOIliveZoteroonline20230525issue20230911COInonegenomePRJNA730337RNA909435authorreportednotdownloaded'),('Coverage','PDF1to17Figure1to7','All17mainpagesreadoriginalsviewed7complete300dpicropsviewedSIfigstables1to10unreadrawmatricesMSnotreanalyzedreferencesnotindependentlyread'),('SpatialMS','PDF2/3/4/13/14Figure1/2','3510spatialpixels3506ionfeaturesnotconfirmedstructurespositive150to120020ummass10ppmLibraryannotationtwoMSbiorepsPM974versus947textconflict4selectedtaxoidsnotpaclitaxelquantconcentrationnoindustrialyield'),('Cells','PDF4/5/6/12/13Figure3','8846capturedcellsnotplants35874meanreads2352mediangenesResultsmeanconflict36808genes15552enriched15clusters11Arabidopsismarkers6/7mesophyll3BSvein8/12mixedepidermal9vascular13pavement14phloemsomeunannotatedHcaptiontSNEaxisUMAP'),('Trajectory','PDF6/7/13/14Figure4','459mesophyll16810910379CD18239.65percentnotrealtrackedage ormetabolicfluxcellcoverageispercentdetectednotenzymeactivity manyclasscountsFigure4AversusResultsconflict'),('CYP','PDF6/8Figure5','487CYP74CYP725candidatecoexpressionnotreactionassignment5EactualheatmapcaptionKEGGenrichmentconflict'),('Network','PDF9/10Figure6','27TF54promoterslog2ratio.26P.01twofilterscoexpressionmotifpredictnotallboundfiveWRKYonly4IDslistunresolved'),('EMSA','PDF9/11/14Figure7AF','SixauthorpairsMYB17TSWRKY12DBATWRKY31SQEERF13C3HGT2CHSbHLH46GGPPSWT20/200competitionmutantretained noKd EproteinGSTGT2arrowbHLH68conflictGSTpGEXversusHisNimethodunresolvedEMSAthreeTECHreps'),('Reporter','PDF9/11/14Figure7GH','MYB17TSbHLH46GGPPSrepressotherfouractivateLUCRENmethod3BIOrepsANOVADuncanP.05noexactPCI;noTaxusnativeChIPKOrescuemetaboliccausality'),('Limits','PDF11/12/13/14','Figure7ItoLintegrationschematicnotnewISHtransporttracer;mitochondrial5and20percentdoubletlogicCellRanger6.1.1and3.0Monocle3and2functionsconflict;downregulateterpenoidgeneralclaimnotvalidatedengineering;SIrawunread')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex17mainpagesread17originalsviewed7complete300dpicropsallpanelscaptioncheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
