import json,time
import worker as w
d=w.ROOT/'sources'/'BEFAAGRE';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'table_activity_recovery_percent':978/1304*100,'purification_fold':81.5/5.3,'table_protein_recovery_percent':12/246*100,'table_purified_protein_mg_L':12/.5,'body_max_purified_protein_mg_L':13/.5,'table_specific_activity_umol_min_mg':81.5/1000/60,'body_Vmax_umol_min_mg':.9,'body_Vmax_over_table_specific_activity':.9/(81.5/1000/60),'body_table_consistent':False,'protein_yield_not_taxadiene_titer':True,'kinetics_duplicate_not_proven_independent_cultures':True,'Km_microM':3.1,'native_reference_Km_microM':2.9})
claims=[('Identity','Main1/liveZotero200','Fiveauthors vol13pp90-96 articlePT980870 matchesDOI automaticprintedDOIfalse notwrongpaper'),('Coverage','Main1-7 Figures1/2 Table1','Fullsevenoriginalpagesreadviewed and3complete300dpicropsverified allgel lanes markers tablefootnote; automaticcandidatemissedFig2Table1 manuallyincluded'),('Construct and temperature','Main3/5/6','pET3dTX insolubleinactive; pET32TXfusion37Cinsoluble20Csolubleactive; vectorotherdifferences no uniquefoldingmechanismproof'),('Denominators','Main1/5/6','Target15-20percenttotal solubleprotein 70percent targetsoluble 95percentpurity distinct; heptahistidylleader originalnotassumed6His'),('Gel and sequence','Main4/5 Figure2','Lanes1vectorcontrol2refoldedpET3d inactive3solublefusion4purifiedfusion5releasedTS;AQLSFNAfrompET3dnotnativeboundary'),('Purification inconsistency','Main5Table1','24613045.3 crude12197881.5 affinity75percent vsbody13mg80percent unexplained no correction;15.38foldactivity notprotein recovery'),('Kinetic units and inconsistency','Main3/5','Km3.1microM native2.9microM bodyVmax.9plusminus.03micromolminmg vs81.5nmolhmg662.58fold unresolved rawnotavailable'),('Kinetic design','Main3','duplicateaverages eachsubstrateblank less20percentconsumption nonlinearMMfit no independentculture n CI exactP invented'),('Product evidence','Main4/5','TLC.91 MS272257229121122123107 authenticstandardcomparison spectraGCnotdisplayed notclaimedrawverification proteinmgnotproductmg'),('Tag removal and truncation','Main6','Enterokinase removal lostmostactivity lowyieldnotshown truncationstart138 failednotshown maturecleavageunknown not78residuedeletion'),('Limits and support','Main5-7','SDS80kDa native79 predicted98.3differentbasis no exactcleavageinference hostgrowthnotshown casbeneinpreparation notvalidated NIHandWelch no explicitCOIdatarepo classificationdeferredhumanreviewfalse')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex full sevenoriginalpages read viewed complete3graphiccrops; originalmicroUnits resolved body/table discrepancies preserved asunresolvedsourceissues','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
