import json,time
import worker as w
d=w.ROOT/'sources'/'WWVFPY84';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Single2014MuskegonmixedbloomMicrocystisdominance','PDF6','notallproductionstrainassigned'),('1LalloThr,2SerHtyr,3Dgln,4Dgln996','PDF2–3structures','2twocompositionchanges samemolecularformula'),('2massresult1005.700 vsmethods1005.4700','PDF2/6','printedconflict notOCR repaired silently'),('Figure1A NMRdifferences,1B FDVAstandardLallo','PDF3Figure1AB','FDAAinsufficientresolution p7'),('GlnhydrolysisGlu','PDF3','configurationreadconvertedresidue, intactGlnNMR'),('Table1onlyValNMePhePheAhpTyr','PDF4originalTable1','noThrGlnBTA rows ormaincontinuation'),('6threo2Sstar3Rstar','PDF4','3.6Hz andrelativeHMBCinferrednotabsolute'),('8/9artifactspeculation','PDF4–5structures','8methoxy,7to8formulaCH4O notonlymethyl;9Ser4plusringchanges'),('8result1806.8310 methodfound1806.8333','PDF4/6','calculatedvsfound discrepancy retained'),('Chymo1.85plusminus.04 vs3 2.5plusminus.6uM p≤.0001','PDF5Figure2A','ANOVATukeyHSD,2variableschanged'),('Chymo4 1.4 vs9961.5 p.4679','PDF5','notdetected difference notequivalence'),('Elastase1.12plusminus.002,996.83plusminus.02,3 1.4plusminus.15,4 .84plusminus.12uM','PDF5Figure2B','error/nnotfullyspecified'),('FerintoicDTrp inactive10uM textnumber4actually5','PDF5','4hasactivecurve,sourceindexconflict'),('Microviridin7/8/9 7.3/1.5/4.0uM','PDF5','SIunread,multiplechangesnoisolatehydrolysiscausation')]
checked={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex read all8PDFpages; originalpages1–5 and all5actual300dpi crops viewed including all9structures fullTable1andFigure2AB. Mass/indexdifferencesconfirmedinoriginaltext; SIandNP-MRDnotindependentlyread. Noexternalmodelreview.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
