import json,time
import worker as w
d=w.ROOT/'sources'/'GTJYULK2';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'reported_ORF_triplets':2586/3,'predicted_mature_aa':862-137,'library_positive_percent':102/300000*100,'gcms_figure_rt_difference_min':12.73-12.72,'abstract_identity':46,'body_identity':45,'identity_difference_percentpoints':46-45})
claims=[('Identity','PDF9201titleauthorsjournalbanner','Communication4pagesWildungCroteauJBC27116April1996:92019204titleauthorpagesvisualconfirm preparedfalse DOI notprinted onlyliveZotero10.1074/jbc.271.16.9201 sourceidentified'),('Coverage','PDF9201to9204','4pagesfulltextoriginalsreadviewed actualSchemeIplusFigure1and2complete300dpi3cropsallviewed 51refsnotindependentlyreadGenBankU48796paperonlyliveversionnotdownloaded'),('Probe','PDF9201/9202','Protein10ugmicrosequencingfailed6cyclasesequences11regions20primersonecombo83bp cyclasehomologynotfunctionalone'),('Library','PDF9202','300000plaques102positive50rescreen38excised12large4full notreplicaten 12samegene clonesreadingframeorfalseupstreamstop pTb42 repairedpTb42.1 double strand noPCRchanges againstsource'),('Function','PDF9202/9203','LE392libraryXL1BlueexpressioncellfreeextractfedGGPP about1nmolproductnotwholecellmgLproduction identicaloutofframeextractnondetect no absolutezero detectorlimitsunspecified'),('Product','PDF9203Figure1','GCMSstandard12.72product12.73m272257229121122123107match radioGC19.40plusminus0.13differentmethod GCMS12.72plusminus0.01errorstatundefined nnotreported racemicstandard no independentabsoluteconfigurationno newNMR noallbyproductquantification'),('Sequence','PDF9203Figure2','2700ntcDNA2586ORF862aa98.303kDa transit137predmature72582.5kDa native79 estimate unknownboundaryblockedNterminusnoactualplastidlocalization'),('Comparisons','PDF9201abstract9203body','grandfiridentity46abstract45body67similarityunresolvedunpublishedmanuscriptreference motifsDDMADDSYDDHis370415793Cys329650777 uncertainnotmutageneticproof'),('Units','PDF9201/9202visible','5ugRNA10ugprotein200uMinduction15uMGGPP textmicrotomillierrors verified not copiedoperativeprotocol'),('Boundary','PDF9201intro9204last','perhapsratelimiting strongpromoterTaxusincreaseTaxolfuture speculation no actualfinalPTXproduction nofluxcontrolcoefficients nSDSEMPCIundefined humanreviewfalseclassificationdefer')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex4pagesfulltextread4originalsviewed3complete300dpicropsviewedResearchfunctionproductcontrolsverifiedtransitpredictionversusmeasurementperhapsratelimitingversusfluxproofPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
