import json,time
import worker as w
d=w.ROOT/'sources'/'76I5KWYI';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('SynBNP chemicallysynthesized notnaturalisolate','PDF1–4 GraphicAbstract Scheme1','noculture/heterologous/KOidentitytest'),('192predictedCCPscreen,diagramapproximately200','PDF1Figure1abc','onecnnprioritized notallvalidated'),('Atmost3Adomains with>3mismatches','PDF2','twolevelsequencefilter notallcode≤3'),('A6A9LeuvsOrnpredictions resolvedbychargeinspection','PDF2–3Figure2a','SANDPUMAOrnnotpureenzymeverified'),('Figure2blue27/29/30 vsbodyCnn27–29','PDF2originalFigure2a','numberinggapnotresolvedwithoutSIsequence'),('atrhomology60–85percent motivates2methylcinnamoyl','PDF3Figure2b','sameproductunverified,ACP/CoAwording'),('10merdepsipeptidecyclizationdesign','PDF2–3Figure2c Scheme1','synthesisdoesnotverifybiosyntheticprediction'),('MICBAS8498 Bsub64ugmLmostothers>50/64','PDF3Table1','15microbialslisted notallnoactivity'),('HeLa7U2OS4LS/RKO6HT2915HCT11619HCC21uM','PDF3Table1','Vero4HEK6noshowtumorselectivity'),('Textadditional13microbes9cellsversustable15/9total','PDF3actualTable1','SIunreadnotinferredmissingrows'),('C6reducedactivityup to64ugmL','PDF3–4','nopublishedmaintextfullIC50folds ortargetmechanism')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read all5originalPDFpages includingreferences; viewed originalpages1–3 and all5actual300dpi crops; recheckedapproximate200sign, domainnumbersandtableunits/counts visually. SI and code notindependentlyretrieved, no externalmodel or humanreview.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
