import json,time
import worker as w
d=w.ROOT/'sources'/'VEHEPT5K';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'microgram_to_milligram_factor':.001,'taxadiene_mgL':{'CEN3':.204,'CEN5':.306,'CEN7':.306,'CEN8':.320,'CEN9':.228,'CEN10':8.7},'tHMG_CEN5_over3':.306/.204,'UPC_CEN7_over5':.306/.306,'GGOH_CEN8_over7':27.6/.283,'GGOH_CEN6_over4':27.4/6.9,'taxadiene_CEN8_over7_percent_increase':(.320/.306-1)*100,'taxadiene_CEN10_over8':8.7/.320,'taxadiene_CEN10_over3':8.7/.204,'taxadiene_CEN10_over9':8.7/.228,'nominal_48h_average_mgLh':8.7/48,'ratios_have_propagated_error':False,'statistical_tests_reconstructed':False,'GGOH_direct_GGPP_flux':False,'taxol_production_demonstrated':False,'free_extracellular_only_titer':False})
claims=[('Identity','Main1-6/liveZotero200','TitlethreeauthorsEngelsDahmequalJenneweincorresponding DOI10.1016/j.ymben.2008.03.001 pp201-206matches despiteauto titlefalse; onlineMar262008issueMay10issue3-4'),('Coverage','Main1-6Figures1-4Table1','Allsixpagesreadviewed fivefull300dpicrops tablefootnotesfigure2brokenaxisfigure4bothmassspectraTICcaptionscomplete finalcropvisualchecks'),('Strain designs','Main2/3Figure1Table1','CENPK2-1C commonbackground10strains TDSNterminal74removed plantsTaxuschinensis vsSaGGPPS codonoptimizednotactive-sitemutant allfullfactorialburdencontrolsnotshown'),('Cultivation','Main3','100mL500mLbaffled28C160rpm48h glucose2percent RPC18.5percent combinedbiomasssorbentrecovery biomass21.6plusminus2.5gLnotperstrainDCW n3SD'),('Units resolved','Main3/4originalpages','122plusminus3GGPPproxy 204plusminus1 CEN3 306plusminus3CEN5 306plusminus1CEN7 320plusminus3CEN8 228plusminus15CEN9 allmicrogL OCRmgresolved visual original highest8.7plusminus.85mgL'),('tHMG versus UPC','Main4Figure2','CEN3to5.204to.30650percent CEN5to7same.306 UPCnoobservedtargetincrease no directsterolfluxuptakeconfirmation exogenoussterolnotlisted'),('Precursor source','Main4Figure3','CEN7to8GGOH.283to27.6~97.5fold buttaxadiene.306to.320~4.6percent CEN4to6GGOH6.9to27.4~3.97fold sourceeffectnotcompletefluxtrace'),('Optimization background','Main4/5Figure2','CEN9plantGGPPSoptimizedTDS.228lowerthanCEN7.306 CEN10archaeal8.7vsCEN8.32027.1875fold vsCEN3.20442.647vsCEN9.22838.158 no singleunqualified40fold'),('Measurement interpretation','Main3/4','GGOH measuredalcoholnotdirectintracellularGGPPflux alkalineprocessingrawrecoverynotindependentlyverified nofreeextracellularonly claim proteinwesternnotshownTDSblotsunavailable'),('Product identity','Main5Figure4','Taxadiene8.2minGGOH10.5minTICspectra272122107standardsupportsidentity noindependentpureNMRinstrumentrawverify'),('Statistical limits','Main3-5Figures2/3','Independentfermentn3SD no explicittestpreciseP CI statementsinvented ratiosarithmeticnotstatproof endpoint48hdivide notinstantproductionrate'),('Pathway scope','Main1-5','TaxadienefirststepnotfullTaxol historicalknowledge notcurrentlatest priorityclaimauthoronly GGOHmasscannotdirectlyaddtotarget'),'']
claims=claims[:-1]+[('Declarations','Main5','DFGJE418/3-2toSJ noexplicitCOIdatarepository allrefsrawnotchecked humanreviewfalseclassificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all6mainpagesreadviewed originalmicrogramunitsresolved fullfigures/tablechecked; tHMG1effect separatedfromUPC2 andGGOHproxyfromdirectGGPPflux','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
