import json,time
import worker as w
d=w.ROOT/'sources'/'EMJYQLMR';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'isolated_mg_per45L':[12,7,5],'recovered_mg_perL_not_actual_titer':[12/45,7/45,5/45],'total_recovered_mg_perL_not_titer':24/45,'taxadiene_platform_reported_mg_perL':20.3,'C20H32O_DBE':(2*20+2-32)/2,'C20H30O_DBE':(2*20+2-30)/2,'cation_deltaG_barrier_kcalmol':7.2,'radical_deltaG_barrier_kcalmol':54.1,'barrier_difference_kcalmol':54.1-7.2})
claims=[('Identity', 'PDF A titleDOI datesPDFDauthors', 'FivepagesactualmainnotSIdespiteautoflag9authors3equalDongCPU2024letter DOI4c00103 acceptedFeb19ZoteroFeb21 nofinalvolumeprintedXXXX preserve'), ('Coverage', 'PDF AtoEFigures1to4abstract', 'Allfivepagesfulltextreadoriginalsviewedfourformalfiguresplusabstract5complete300dpicropsviewedFigure5notebooklabel abstractoriginalunnumbered noSI/FIDlocal read claimmainonly'), ('Platform', 'PDFB Figure2', 'PhoNIPK idiGGDPS TS BL21DE3 truncatedexogenousprenylalcohol20.3plusminus.3mgL taxadiene notTaxol nerrornotreported100mgLpriorotherditerpenes'), ('Products', 'PDFBtoC Figure3', 'DL10108CYP701A8vsDL10107new288288286 45Lisolated12 7 5mg nottruetiterorconversion 1abeotaxane2OH3seco 1and3namevariationnumbertracked'), ('Structure', 'PDFBtoC', '1C20H32ONa311.2344vs311.2345calc5DBE1S3S8S11S 2Na311.2356noessentialROESY11RcalcNMRandECD1S3S8S11R 3C20H30OH287.2361vs287.2369calc6DBE1R3S8S authorreportedfullSIunread H2-10toC10HMBCpossibletextissueunresolved'), ('FunctionalBoundary', 'PDFCtoD', 'ModifiedNterminalcodonoptimizedpureenzyme entkaurene3alphaOHpositive RhfRedNADPH taxadiene2negative withredoxpartnersperoxide solubilityunsuitablepartnerhypothesisnotmeasuredcause'), ('Feeding', 'PDFD', 'Feedtaxadiene1and2detected 3notdetectedwitheithertaxadieneor2 model2to3notdirectproof no taxadienepurifiedreconstitution'), ('Mechanism', 'PDFC Figure4 PDFD', 'DockC18within5Anotactualinitialsite alternativeC13 no intermediatestrapped noOisotopewaterquenchproof computationCtoDonly cationdeltaGbarrier7.2productminus6.3 radical54.1minus2.3 parenthesesdeltaE56.6/1.2notG nofullenzymecycleproof'), ('LimitsFunding', 'PDFDtoE', 'Authorno competingfinancialinterest declared NSFC82073746 andothers no newproductbioactivityTaxolproduction SIandFAIRZIPavailabilityauthorstatementunverified allclassificationdeferred humanfalse')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex5pagesmaintextread5originalpagesviewed4formalfiguresplusabstract5complete300dpicropsviewedCYP701A8wholecellproductsinvitrotaxadienenegativefeeding3absentcalculatedCtoDnotfullmechanismSIandFIDunreadsourceboundaryPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
