import json,time
import worker as w
d=w.ROOT/'sources'/'4MEWB9MD';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'10DAB_fold':.143/.06,'10DAB_increase_percent':(.143/.06-1)*100,'baccatin_fold':.16/.04,'baccatin_increase_percent':(.16/.04-1)*100,'taxol_fold':1.31/.313,'taxol_increase_percent':(1.31/.313-1)*100,'MeJA12h_relative_if8_97foldinverse':1/8.97,'MeJA12h_decrease_percent':(1-1/8.97)*100})
claims=[('Identity','PDF1/15/16','16pages5authorsfirst2equalFrontPlantSci13article804593DOI20220304fund31770613KC21028COIread'),('Coverage','PDF1to16Figure1to11','All16mainpagesread16originalsviewed11final300dpicropscompleteallpanelscaptionschecked SIFig1to4Table1unreadrawchromatogramsnotverifiedreferencesnotindependentlyread'),('Protein','PDF4/6/7Figure2/3/4','527aa60.18kDa7.95predicted98.87percentQHG11457.1notdistinctlocusproofR2R3nucleusGFPDAPIexpressionneedle/rootnottaxolconcentration LgMYB3body7figureconflict'),('ChIP','PDF7/8/9Figure5','GFPoverexpressedcellsantiGFP3.23T5OHR3CDS214.41BAPTR7CDS3notactivation nativeessentialitynotshown TSnotbindingregiontested'),('Y1H','PDF5/9Figure6','Y1B1and3B1positiveB2BAPTP5negative BAPTChIPconflict retain noalltargetspositive ABAtypoAbAselectionnotabscisichormone officialTakara20090512pdfverified'),('EMSA','PDF5/10Figure7','GSTfusionbindsWTB1WTcompetitor20/100reduces mutantcompetitorlane2ALSOlabeledWTretainedshift supportsselectivitynotmutantbinding noquantKd ormutantdosetitration'),('Reporter','PDF5/9/11Figure8','NbenthamianawtvsB1modifiedlowerbutresidual n3 tthresholdnotexactP CCGTTAtoTACCmutationdifferentEMSACCTA notsameconstruct nativepromoternecessitynotshown'),('Metabolite','PDF10/12Figure9','3independentlinespergroup ugpergDW.06to.1432.383fold .04to.164fold .313to1.314.185fold increment138.3300318.5notauthors238400419increments 10DABplusminus.31errorunresolvednotcorrected'),('RNAi','PDF10/12Figure9SI3authorreport','RNAinonsignificantmetabolitesnotnecessity efficiencySIunread OE7genesupBAPTnochange othersnotdirecttargets noindustrialmgLyieldbiomass'),('Hormone','PDF1/5/6/11/13/14Figure10/11','ABA20uM6h8.75 MeJA50uM12h8.97down timecoursesdifferent n3 Figure10OElegendconflict ABREAERBminus313319predictionSIunreadnonecessityfungal3.26priornoABAepistasisnoorthogonality'),('Errors','PDF6/10/11','TrolliusbodyTaxusreferenceconflict; B1reporter/EMSAdesigninconsistent; noexactPrawcountsCI noindependenthumanfullreview')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex16mainpagesread16originalsviewed11complete300dpicropsallpanelscaptioncheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
