import json,time
import worker as w
d=w.ROOT/'sources'/'LJCIHKC9';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'metal_count':2,'coordination_contacts':2*4,'unique_cysteine_ligands':6,'bridging_ligands':2,'contacts_with_bridges':6+2,'Cd2_couplings_Cys5_Hz':[5,3],'Cd2_couplings_Cys6_Hz':[2,3],'Zn_Table1_pH':5.4,'Cd_Table1_pH':8.0,'matched_pH':False,'sequential_assignment_complete':False,'atomic_coordinates_solved':False,'cellular_zinc_regulation_tested':False})
claims=[('Identity','PDF1/5','Pan Coleman Yale PNAS87:2077-2081March1990 communicatedDecember26 1989 notpublication scholarlyarticle notthesis; liveZotero200 DOI metadata notprinted'),('Coverage','PDF1-5 Figures1-7 Table1','All5pages text and original images read; eight complete300dpi original crops viewed including Table1 footnotes; no rawNMR and not all16 cited primarypapers read'),('Construct','PDF1/2','Actual62star Nterminal62 terminalLeuGlu replacedLeuAsp E62D notfull881aa; 63 andotherlengths discussion prior studies distinguished'),('Isotopes','PDF2 Figure1/2','112Cd I0 versus113Cd Ihalf sameelement isotope notdifferentmetal; HMQC2.6-3.8ppmCysbeta supportsS ligands; transients notreplicates'),('Assignment','PDF3 Table1 Figures2/3','Six spin systems arbitrarylabels notresidueindices; Table1degenerate spin2 missingnotzero;spin3Ha difference112Cd4.29vs113Cd4.33 reasonunclear'),('pH','PDF3 Table1','Zn35CpH5.4 Cd35CpH8.0 notmatched pH no identicalaffinity conclusion'),('Bridges','PDF3/4 Figures4/5 Table1','Spin5Cd2 beta5and3Hz spin6Cd2beta2and3Hz weakcouplings pluslargeCd1 supportsbridging; overlap phasecoding author analysis rawnoise notindependentlyprocessed'),('Count','PDF4/5 Figure7','Two4S sites8contacts sixCys two bridges arithmetic consistency notuniquegeometry proof'),('Model','PDF5 Figure7','Cloverleaf proposedmodel Cys21/38assumed bridge preliminary spin6/5assignment notcompletedsequence; noatomiccoordinatefile; helical NOESY unpublished'),('Conformation','PDF5 Figure6','apoZnCd spectra0.9mM16transients2.5s metalstabilization notcellulartranscriptionaffinity; Cdsubstitute notphysiologicalmetal'),('Family','PDF5 Figure7','LAC9 PPR1 sequence comparison notnew metalmeasurements eachprotein; specificityotherregion hypothesis noDNAcomplexbasecontacts'),('Scope','PDF5','CellularZn regulation and extensionstootherCysrich proteins hypotheses nottested; NIH DK09070 GM21919 RR03475 NSF DMB8610557 ACS RD259 noexplicitCOI')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all five original pages read and viewed; seven figures and one table complete original crops visually checked; direct Cd coupling versus proposed Zn geometry and cellular regulation distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
