import json,time
import worker as w
d=w.ROOT/'sources'/'XUCXLM84';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'nominal_U13C_glucose_atom_percent':(99+20*1.1)/21,'nominal_1_13C_glucose_C1_atom_percent':(99+1.1)/2,'culture_days':14+30,'IPP_C2_C4_C5_abundance_percent':[1.33,2.38,8.69],'dry_weight_fraction':.026,'wet_weight_mg_g':2.2,'culture_isolated_mg_L':68,'three_yield_bases_equated':False,'coupling_fraction_not_absolute_abundance':True,'raw_spectral_integrals_recomputed':False,'SD_in_Fig4_independent_culture_n4':False,'full_alternative_pathway_identified':False,'acetate_negative_alone_conclusive':False})
claims=[('Identity','Main1/liveZotero200','Fiveauthors PNAS93pp6431-6436 title matchesDOI10.1073/pnas.93.13.6431; contributedMar4 notpublicationJun25'),('Coverage','Main1-6 Figures1-4 Table1','Allsixmainpages read and viewed completefive300dpicrops withcoloredstructuralpanels spectraaxes captionsfootnotes finalcropsviewed'),('Actual compound','Main1/2 Figure1','Taxuschinensiscellculture taxuyunnanineC fouracetyl twentycarbon taxaneskeleton notdirectTaxolitself'),('Yield bases','Main1/2/3','2.6percentdryweight 2.2mgpergwetcellmass 68mgL cultureisolated differentdenominators no massbalanceequating'),('Input labeling','Main2','99percentstock Uglucose1to20unlabeled ~6percent;1position1to1~50percent; culture14plus30days no99percententireinputclaim'),('Acetate evidence','Main3 Figure1B Figure2B Table1','Ring1.12plusminus.05percent near1.1natural acetylsatellites demonstrateincorporation;explicitlyinsufficientalone becausecompartmentaccess hypothesis'),('Glucose topology','Main4 Figure1C/D Figure3','Twelveadjacentpairs fourwithlongrangeconnection thirdcarbon; triple2,3,5 author~40percent inferredrearrangement no directnamedenzymeidentified'),('Quantification','Main2/3 Table1','H10at6.01ppm satellites calibrate C10absoluteabundance; coupledpercentfraction relativecarbon signal; overlapped averagedfootnotes preserved no rawFID reanalysis'),('MVA comparison','Main5 Figure4C/D','IPP2,4,5=1.33plusminus.07 2.38plusminus.15 8.69plusminus.32 contradict equalMVA methylsources;SD ofequivalentmodules notfourculturebioreps'),('Alternative limits','Main5/6 Figure4E','SomeRohmerpredictionsnotmet ultimateprecursors explicitlyunknown no DXP MEP DXS DXRstepsidentified; loweracetyl30percent oldbiomassrecycling hypothesisnotmeasured'),('External scope','Main6','Othermonoterpene broaderplantsclaim unpublisheddata notverified MVAnotabsentallmetabolism allcitedsourcesnotindependentlyread'),('Declarations','Main6','DFGSFB369 FondsChemIndustrie noexplicitmodernCOIdatarepo humanreviewfalse classificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read and viewed fullsix originalpages and fullfive originalgraphic crops; carbon numbering abundance coupled fraction model predictions examined; fullalternative pathway notclaimed','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
