import json,time
import worker as w
d=w.ROOT/'sources'/'9HACLINL';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('JointfirstDiPengXiangchaoLuoRunweiZhu,QiWangcorrespond','PDF1/5','SchoolPharmacyQingdaoUniversity'),('1/2C16H17N5O4,3C12H15NO5','PDF1–3','HRMSprotonated344.1351/344.1353/254.1022'),('1Xray17R19R20SZ,CCDC2126704','PDF2Figure2','criticalHMBCmissingfirst, crystallographicconstraints'),('fourmethines listsfive andC20both65.5','PDF2–3originaltext','sourceambiguities retained SI needed'),('2C20epimer ECD17R19R20RZ','PDF3Figure3','notownXray'),('3DP4+100vs0candidate ECD8R10S11S','PDF3','SIunread calculationnotrerun'),('Scheme1biosynthetichypothesisnotverified','PDF3Scheme1','noisotopeenzymeintermediategene proof'),('1IC509.6plusminus1.04uM','PDF4Figure4A','error kindnotreported;2/3negativeinitial20uM'),('1SPR3.40uM,2reported43.16uM','PDF3–4Figure4B','2rawS7absent'),('C/DHepG2CETSAn3','PDF4Figure4CD','noexactstat orcellularTmestimated'),('CDTm53.9plusminus.6to57.6plusminus.4C','PDF4Figure4EFG','proteinthermalstabilitynotdiseasetherapy'),('H405nmblue,I50uMHepG2distribution','PDF4Figure4HI','HeLa colocalizationSIonly, excitationnotemissionmaximum')]
checked={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex read all5PDFpages, originalpages1–4 visuallyread and all6actual300dpi crops checked including Figure4A–I. NMR count/C20 discrepancy and IC50/Tm errors checked visually. NoSI/CIF independentanalysis or externalmodelreview.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
