import json,time
import worker as w
d=w.ROOT/'sources'/'W6R3DDNY';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'TXS_Table_percent_to_fold':[1+256/100,1+176/100],'body_3179_9_ug_per_g_to_mg_per_g':3179.9/1000,'568_2_ug_L_to_mg_L':568.2/1000,'cross_paper_1000_over_1_3_not_15000':1000/1.3,'T5Ac_21_over_3_7':21/3.7})
claims=[('Identity','PDF1/10','12pages7authorsReviewFrontPlantSci14:1100228date20230126DOI liveZotero titlevisualverifiednoCOISpanishfunding'),('Coverage','PDF1to12Table1/2Figure1/2','All12physicalpagesreadalloriginalsviewed4complete300dpicropsallviewedincludingtablesfootnotesFigure1ABCfullcaptionFigure2photoscaptionoriginalrefsSIunread'),('Taxus','PDF2/3/4Table1Figure1','DBAT1.7foldMeJaindependenceversusHo2.5MeJaNCED48percentABA2.7foldPTXreportersnotproductiontwentymonthculturefiveyearstability'),('Conflicts','PDF3/4/12Table1Figure1','TXS256176percenthigherPTXTableversus2.641.55foldtaxanesbodyZhang2011aDBATbody2011btablefigurebutref2011bfungus75percentmaintenanceversusTEdenominatorHoTmaireicellrootmixed'),('Units','PDF5/6/9Table2','Originalvisual210ugperg568.2ugL1440.81434.92473.29ugpergtextlayermgincorrectTable3179.9actualmgpergDWversusbodyugpergDWsourceconflictretainednotautomaticrepair52.610.78actualmgL27/50ugpergdry56.6/1.3ugpergfresh'),('Roots','PDF5/6Figure2','19weekrootformation1.5yearstableculture10monthotherlinecellulaseextracellularreleasehighernot totalproductionPALline-specific4C heating wordingcontradictionspectroscopicidentitylimited'),('Other','PDF6/7/11/12','BIS2TSAR2transcriptsnotfinalstableyieldDBTNBT7.4jointconditionendophytepositiveclaimsnegativeHeinigsourceconflictmarkertoolnotfullpathwayCRISPRfuture'),('Microbes','PDF7/8','1.3mgLtaxadieneversus1gL15000foldnotsharedbaselineexogenous10DABDBATbaccatinnotdenovoBsubtilis17.8mgL83foldtaxadieneDeJongendpointambiguous'),('Yeast','PDF8/9','taxadiene8.772.857plusminus3129unitsmgLvariedconditions78totaloxygenatedtaxanesnotfinalPTXpotentialisomer97plusminus2notconfirmedSDSEMunknownmaxdifferenttimessumnotvalidT5Ac21over3.7approx5.68'),('Plants','PDF9/10','plantgrowthtoxicityandGGPPcompetitioncompetinginterpretationschloroplasttargetingnotdirecttransportfluxrawdata2023pathwayincompletehistoricalnotcurrentstatusclassificationdeferredhumanreviewfalse')]
labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex12physicalpagesread12originalsviewed4complete300dpicropsFigures1ABC2photosTables12footnotesvisualmicrogramunitsandactualTable3179.9mgbodyugconflictcheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
