import json,time
import worker as w
d=w.ROOT/'sources'/'XPQ84JII';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'ACP_resolution_A':1.82,'FGP_resolution_A':2.25,'ACP_R':.167,'ACP_Rfree':.205,'FGP_R':.187,'FGP_Rfree':.250,'ACP_R_gap':.205-.167,'FGP_R_gap':.250-.187,'full_native_aa':862,'construct_reported_total':764,'ACP_modeled_aa':745,'FGP_A_modeled_aa':746,'FGP_B_modeled_aa':736,'ACP_unmodeled':764-745,'FGP_A_unmodeled':764-746,'FGP_B_unmodeled':764-736,'Nterminal_deletion_numbering_fully_resolved':False,'gasphase_minimization_steps':10000,'is_full_MD_QMMM':False,'VOIDOO_mesh_probe_A':1.4,'VOIDOO_volume_probe_A':0,'historical_minor_product_approx_percent':20,'historical_minor_fraction_is_inactive_construct_measurement':False,'PPi_terminal_base_directly_proven':False,'coordinate_SI_independent_validation_performed':False})
claims=[('Identity','Main1/4/5/liveZotero','TitlefiveauthorsDOI10.1038/nature09628Nature469116-120 issueJan62011 onlineDec152010'),('Coverage','Main1-7Figures1-4','All7physicalpagesreadviewed includesfullMethods all4final300dpicrops fullbothcolumncaptions Fig3ab Fig4abc noTable SI notavailable'),('Constructactivity','Main1/4/6','ActualM107-TXS-CHT99percentSDS purity but no measurabletaxadieneGCMS; M60M79previousactive notsameprotein'),('Numbering','Main4/6','MethodsSummary107deleted vsR107startM107 and29resdegradationM79 retained notpretendprecisesequencerebuilt'),('Structures','Main1/4/5/6','ACP1.82FGP2.25 RRfree.167/.205and.187/.250 PDB3P5PACP3P5RFGP coordinatesfactorsreported notdownloaded'),('Architecture','Main1/2Figure2','AlphaCterminalS553V862 betaM107I135andS349Q552 insertionS136Y348 vestigialclassII noDXDDnotbifunctional'),('Analogue','Main3/4Figures2/3','FGPsubstrateanalogue ACPnotanyTXSreactionintermediate bindingnotturnover;3sigmaomitmapnotcarbocationobservation'),('Metalcoordination','Main3Figure3','A/C D613D617 B N757T761E765 diphosphateHbondR754N757watermediatedothers notallsitemutantsvalidated'),('Missingregions','Main6','ACP745/764FGP746/764736/764 Nterminaltagandloopsdisordered notallclosednativeatomsobserved'),('Model','Main3/4/6/7Figure4','BPPSgraftedNterminalJKloops NAMDCHARMM22gasphase10000steps constrainedheavyatoms fullyclosedhypothesis notfullMDtransitionpath'),('Volumes','Main7Figure4','VOIDOO1.4A solventmesh vs0AvdWvolumes dummyboundarymethod preserved exactnumericsSITable2missing notfakecorrelation'),('Mechanisticboundary','Main4Figure4','Twofitproductorientations PPiH5betahypothesis polaralternativeY688otherres remains nofinalbaseproof noinvivotransition'),('Historicalpromiscuity','Main4','~20percent4(20) priorref21activeenzyme notinactivecrystalconstructproduct80:20'),('Transparency','Main5','Explicitnocompetingfinancialinterests NIHGM56838GM13956CA55254 fellowships PDBreported SIrawnotread humanreviewfalse classifylater')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex readviewedall7mainPDFpages includingfullMethods allfourcompletecrops inspected bothcolumncaptions; inactiveconstruct crystalgeometry versusgraftedclosedmodel andterminalbasehypothesis preserved','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
