import json,time
import worker as w
d=w.ROOT/'sources'/'57AZ6R62';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'Type_I_II_counts_only':353+126,'TXS_13_gene_components':1+2+3+7,'reported_8_components_no_TXS':2+6,'known_skeletons':11})
claims=[('Identity','PDF1/14','18pages6authorsfirst3equal2corrPlantCommun6:101460DOI liveZotero online20250721issue20251013bothretainCOInonefunding'),('Coverage','PDF1to18Figure1to4','All18pagesreadalloriginalsviewed4complete300dpicropsallviewedpanels1ring2ABC3ABC4ABcaptionsfullSupplementalTables1to3notattachedunreadreferencesnotindependentlyread'),('Counts','PDF1/3/4/5/14Figure1/2','11knownskeletonstheoreticalnewXIInotidentifiednear500versusover21000internalconflict353126sum479notalltypeactual56Fig2vs35precursorbodydefinitionsuncleartheoreticalmillionsnotcreatedlibrary'),('Structure','PDF4/5/6Figure2','TXSopenstructclosedAF3predictedlidsnotbothcrystalsTXStypeIionization4(20)versus4(5)notinterchangeableEriGStlTCsourceparenthesesfunctionalclassconflictsBAHDacylationglycosylgroupfamilyunsupportedSvsRpaclitaxelvaguechiralposition'),('Discovery','PDF6/8Figure3A','13genes1+2+3+7eight2BAHD6CYPnoTXSstartbasisunclear100foldcrossstudynotmatchedcausalcomparisonMcClune2024bioRxiv622305not2025NatureversionmultipleCYP2OGDmodelsnotsingleroute'),('Titers','PDF6/11','184.2yeast101.4Yarrowia390Bsubtaxadiene7Ecoli4.32cyanobacteriaT5olnotTaxolfinalhundredfoldchemicalproductionclaimnosameinputstimecost20foldchloroplastlimitedset3foldfusionnotmultiply'),('Metabolon','PDF9to12Figure3C','AuthorphysicalinteractioninsufficientfunctionalchannelingrequirednoactualtaxanemeasurementnewTCAexamplesconceptualsupportOCTtoxicitydegradationhypothesisnotconfirmedotherhazardousexamplehighlevelonlynotengineeringexpansion'),('Toolkits','PDF7/11/12Figure3B','CRISPRidCas9reversibleNORgenericplantplatformnotDNAcleavageorvalidatedtaxanecircuitcompartmentpromoterenhancersapplicationunverifiedMFAfuturestrategynotfluxactuallymeasured'),('AI','PDF8/9/13Figure4','NPClassifierclassificationversusroutepredictionBioNavi90percentknownroutesnotunknowntaxanefunctionprecisionmodelsconceptualnonewtrainedweightsbenchmarkdataTaxuslimitedstereoselectivityunverified'),('Citations','PDF11/13/15/16/17','Rives2021abandbsametitleDOIduplicateJiang2024bbody2025refKhan2024online2025issueMortimer2018body2019refLin2023bphotosynthesissentenceyeasttriterpenetitlemismatchunrepaired'),('Boundary','PDF13/14','NoLCAorTEAclinicalcurrentclaimsnotverifiedarbitrarydesignedtaxanefutureforecastnotdeliveredhumanreviewfalseclassificationdeferred')]
labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex18pagesfulltextread18originalsviewed4complete300dpicropsallviewedknownpredictedtheoreticalboundariesinternalcountcitationconflictscheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
