import json,time
import worker as w
d=w.ROOT/'sources'/'G9BV86WS';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'ORF_triplets':1320/3,'reported_Km_ratio_not_affinity':0.64/0.30,'benzoyl_Km_mM':0.30,'taxoid_Km_mM':0.64,'acetyl_donor_relative_percent':1.5,'chemical_step_a_caption_hours':18,'chemical_step_a_methods_hours':16,'library_plaques':60000,'candidate_genes_not_replicates':7})
claims=[('Identity','PDF13591titlefooter','Research6pagesWalkerCroteauPNAS9725:1359113596Dec52000contributedOct16notpublication DOIprintedliveZotero verified preparedautofalse sourceactualmatching'),('Coverage','PDF13591to13596Figure1to5','All6pagesfulltextoriginalsreadviewed5complete300dpicropseverypanelcaptionviewed25refsprimarynotindependentlyreadAF297618paperonlyliveversionunread'),('Surrogate','PDF13591/13592Figure2PDF13594','Semisynthetic2debenzoyl713diacetylbaccatinIII surrogate product713diacetylbaccatinIII not Taxol natural substrate andreactionorder unproven chemical91and42percent99purity notenzymeyields16hmethod18hcaptiondifference'),('Library','PDF13593/13594/13595','60000plaques7fullcandidategenes notn XL1BlueMRF libraryJM109expression pKW18TAX2cellfreefedacceptorbenCoAnotwholecellcarbonfactory'),('Controls','PDF13595bottom','Without either cosubstrate boiled protein or emptyvector controls no detectableproduct n detectionlimit unreported'),('Product','PDF13594Figures3/4PDF13596','RadioHPLC21.9plusminus0.1UVradiocoelution versusLCMS43.6plusminus0.1differentmethods MS688671652611593551489matchstandard plus authorreported1HNMRmatchnoenzymaticallygeneratedrawspectrumattached chemicalstandardshiftsnotrawenzymeproductread'),('Kinetics','PDF13593/13596','Partialpurification timeprotein linearity saturatedother2mM Km0.64and0.30mMactualvisual notmicro R2.99LB fit no kcatnCIPrawpoints pH8half6.5and9.9differentbufferconfounds'),('Specificity','PDF13596','No10DABnonC2modification C2alreadybenzoylatednotfreeC2competition early2a5adiolinactive notallrequiredsubstitutions mapped acetylCoAsaturatedVrel1.5notzero oraffinity no substitutedaroylCoAtestedfutureanalogproposal'),('Sequence','PDF13595Figure5PDF13596','1320ORF440aa50089Da68identity74simTAT64identity70simDBAT motif5of6H158D162G163potentialnotmutationalproof noNTermtargetingnotactualcytosollocalization'),('NamesBoundary','PDF13591/13595/13596','InitialDAT10acetylmeansDBATelsewhere versusCatharanthusDATFig5 distinct preservefullnames fundedCytoclonalnoexplicitCOI nofinalTaxolyieldorindustrialprovennPCIunreported humanreviewfalse deferclassification')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex6pagesfulltextread6originalsviewed5complete300dpicropsviewedResearchsurrogateproductidentificationcontrolsverifiedKmactualmMversusmicroextractionerrorsregioselectivitylimitedsubstratesnaturalorderhypothesisPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
