import json,time
import worker as w
d=w.ROOT/'sources'/'5F27T5Y6'
rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'SA_methods_results_ratio':2.5/.25,'paclitaxel_mg_g_DW':155.10/1000,'paclitaxel_percent_DW':155.10/1e6*100,'fold1_79_increase_percent':(1.79-1)*100})
claims=[('Identity','PDF1and14','15pages6authorsBMCPlantBiology25article723DOIverifiedpublished20250528received20241223accepted20250520fund82204344KC21028noCOI'),('Coverage','PDF1to15Figures1to5','15mainpagesread15originalsviewed5final300dpicropscompleteallpanelscaptionlegend units;Additionalfiles1to5rawdatasetsdatabaseaccessionsactualunread'),('Localization','PDF3/4/11/12Figure1','233aa702bpsoftware26.79kDapI7.69notexperimental S33SIunread tobaccoEGFPfusionnuclearnotallTaxuscells;MethodsTcMYB76stopcodonmicroscopeconflictsconstructunverified'),('SA','PDF4/11Figure1de','0.25mM8.83fold3h14.32foldresponse vsMethod2.5mMtenfoldconflict unresolved nonmonotonic noSAreceptorJAexclusiveproof'),('Intervention','PDF5/6/12Figure2','MYB73OE62.11fold10biosyntheticgenesexplicitvalues WRKY33OE2.09RNAi.18 MYB73RNAi.38wordingrelativecontrol;RNAi8genes9valuesnotforcedmapping matchingemptyvectorsdifferentCK'),('Metabolites','PDF5/6Figure2de','10DAB691.23SD68.68baccatin43.85SD4.18taxol155.10SD17.88ug/gDW folds2.382.871.79n3biologicaltteststars;RNAi.85.81.70none significantno179percentincrease unitPython'),('T10OH','PDF5/7/13Figure3','Y1HMRE1EMSA Nterminal1to384bpGSTnotfullproteinwild200:1coldcompetitionnotmut GSTcontrol ChIPGFPoverexpressionTaxusvsIgG DualLUCtobaccoGAL4activityvsownpromotermutationreducesnotallgone nofluxnecessitytest'),('WRKY33','PDF7/8/13Figure4','MRE2Y1HEMSAChIPDualLUC directpromoterbindingnotTFproteininteraction;DBATpriorcitationnotread nojointWRKY33blockrescueothermediatorsnotexcluded'),('Model','PDF10Figure5','DBATcaptionBAPTlikeerrornoenzymeidentityoverwrite;Figure5barreuseFigure2notindependent data;10beta14betaproductlabelnotproofsingleT10OHtwohydroxylations noenzymereactiondone'),('Limits','PDF9to15','noexactP/CImultiplecomparisonsreported noindustrialyieldhealthproof;Dataavailabilitynodatasetsgeneratedtensionwithactualreportedexperimentsnotallrawpublic;SA/JAintegrationhypotheses externalreferencesunread')]
labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex15mainpagesread15originalsviewed5complete300dpicropsallpanelscaptioncheckedPythonunitsnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']+['Figure5 10beta14beta productlabelnotproofT10OHsingleenzymebothhydroxylationsnoenzymeassaydone']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
