import json,time
import worker as w
d=w.ROOT/'sources'/'SUKVCHS8';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'sampling_instances':17*4*2*2,'enriched_modules_fraction':3/200,'new_members':7+1})
claims=[('Identity','PDF1/3/4','Research8:0965COMMENTARY3authorsDOIverified20251021PDFversusZotero202501conflict4physicalpages3articlepages'),('Coverage','PDF1to4Figure1','All4pagesreadoriginalsviewedonecomplete300dpiFigure1ABCDcaptionviewednoindependentprimaryarticleSIrawdata11refsnotread'),('Sampling','PDF1/2Figure1C','17treatments4times2maturities2replicates272samplespooled17143nucleartranscriptomes2901estimatedstatesnotcelltypesorbiologicalreplicates'),('Modules','PDF2Figure1C','cNMF200modules3enrichedknownpathwaygenes1.5percentnotprecisionrecall77clonedtestednotdefined8over77hitrate'),('Members','PDF2Figure1D','EightnewmemberssevenenzymesandnonenzymaticFoTO1sevennewmembersbaccatinPCLsidechaintransientacetylationsdeacetylationsnotindependentstructureproof'),('FoTO1','PDF2/3Figure1D','NTF2likeauxiliarypossible scaffoldpreciseroleunknown17foldearlyoutput10foldintermediate4notbaccatin17foldorf inalTaxolnoabsoluteunitsCI'),('Endpoint','PDF3Figure1D','BaccatinIIIand sidechainprogressnotcompleteindustrialTaxolproofnaturalneedleabundancecomparisonqualitativenounitnormalizationlasttwoenzymesauthorwritingtimeclaimnotcurrentglobalstatus'),('Boundary','PDF3references','Nature2025primarypaper6438071582to592notindependentlyreadfundingCOIretainedclassificationdeferredhumanreviewfalse')]
labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex4physicalpagesread4originalsviewed1complete300dpicropsABCDcaptioncheckedCommentarysecondaryevidencePythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
