import json,time
import worker as w
d=w.ROOT/'sources'/'DUAG3WN5';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'baccatin_III_reported_crossstudy_ratio_arithmetic_only':155/50,'Ecoli_taxadiene_reported_gL_to_mgL':1000,'plant_freshweight_to_volume_conversion_allowed':False,'causal_enzyme_set_superiority_verified':False,'new_experimental_data':False})
claims=[('Identity','PDF1/7','Single Philipp Zerbe UCDavis Review printed DOI5:394-402 receivedMar20 acceptedMay8 onlineMay26 ZoteroSeptember; no new datasets'),('Coverage','PDF1-9 Figures1-3','All nine original pages read/viewed; three full300dpi crops viewed all structures bothAB Figure3 and captions; no main table; primary cited papers not independently read'),('Production','PDF1/2/3 Figure1','Natural source versus cell culture semisynthesis and engineered hosts; commercial statement historical not2026market audit; green noLCA'),('Discovery','PDF3 Figure2','Jiang2024 TOT CYP725 microsomes and Taxusknockdown author review report; T9aH taxusin screening; nine enzymes to baccatinIII notcompleteTaxol'),('Other set','PDF4/6 Figure2','Zhang2023b T9aH CYP725A22-1 dioxygenases thirteen baccatinIII seventeen fullTaxol authorreported; no independent gene count reconstruction'),('Other oxetane','PDF6','Yang2024 CYP725A37 CYP725A55 1beta-dehydroxy-baccatinVI distinct endpoint; Zhao2024 CYP725A4bifunctional authorreported'),('Promiscuity','PDF5/6 Figure3A','TXS T5aH multiple substrates/products blackblue schematic not quantified flux; Liu2024 extra products cited not independent NMR confirmation'),('Network','PDF6','Different enzymatic routes tissue-expression and promiscuity support network interpretation not simultaneous same-cell flux'),('Numbers','PDF2/6','Taxadiene yeast103mgL Ecoli1gL plant100ugpergFW; baccatin50vs155ngperg plantmaterial crossstudy not matched or absolute base verified'),('Prospects','PDF6/7 Figure3B','Spatial organization protein function expression fermentation future direction; not industrial validation no statistical synthesis'),('Declarations','PDF7','NIH5R01AT010593-03 NSF2312181 no competing interests CCBY4 no new datasets humanfalse classificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex nine original pages read and visually checked; three complete original figure crops visually checked; review versus cited primary evidence and production endpoints retained','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
