import json,time
import worker as w
d=w.ROOT/'sources'/'98APV48H'
rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
wrapper=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'));draft=wrapper['draft']
draft['source_article_type']='Research Article'
images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
for row in images:row['caption']='原文 '+row['label']+'：完整图表及图注'
for row in draft['figures']:row['caption']='原文 '+row['label']+'：完整图表及图注'
w.write_json(d/'codex-draft.json',wrapper);w.write_json(d/'codex-crops.json',images)
w.write_json(d/'codex-arithmetic.json',{'dxs_vs_baseline':313.8/49,'combined_vs_dxs_volume':390/313.8,'combined_vs_dxs_per_OD':26/25.44,'historical_volume_fold':390/17.8,'historical_per_OD_fold':26/1.981,'all_product_values_beta_caryophyllene_equivalent':True,'absolute_taxadiene_response_factor_verified':False,'qPCR_biological_n':2,'qPCR_technical_replicates':4,'culture_n':3,'exact_P':None})
claims=[('Identity','PDF1/2/9','Repository cover plus 8 main pages; printed DOI, five authors, journal83 pages66-73; cover download date distinct from publication'),('Coverage','PDF1-9 Figures1-7 Table1','All source pages and eight complete original crops viewed; SI and independently cited papers unavailable'),('Quantification','PDF4/5/7 Figures2/3/7','SIM m122 with beta-caryophyllene standard and internal standard; plotted equivalents not verified absolute taxadiene concentration'),('Module identity','PDF3/4 Table1','Bsubtilis168; TXS chromosomal; fusion joins short-chain prenyltransferases, not TXS; eight means seven MEP genes plus ispA'),('Medium','PDF4/5 Figure2','2SR about49equivalentmgL48h; mixed K2HPO4 unit preserved; small culture not reactor validation'),('DXS','PDF5 Figure3','313.8equivalentmgL and25.44perOD; growth lowest; metabolites not directly measured'),('Transcript','PDF5 Figure4','Two biological and four technical replicates; rpoB normalization; approximate transcript change not protein or flux fold'),('Fusion expression','PDF5/6 Figures5/6','Four fusion directions soluble His bands qualitative; separate-RBS controls versus discussion without-linker wording; no direct substrate-channeling measurement'),('Combined','PDF6/7 Figure7','FLE320 versus combineddxs_FLE390equivalentmgL;26perOD; volume and OD-normalized changes different'),('Historical comparison','PDF2/7/8','390/17.8=21.91 versus26/1.981=13.12; source thirteen-fold follows normalized metric more closely'),('Source conflicts','PDF6/8','Discussion assigns390toFLE versus results320FLE; integration wording conflicting without SI; not silently corrected'),('Limits','PDF7-9','Intracellular less1percent author report only; fedbatch future; no final paclitaxel; human review false')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex full nine physical pages read and visually checked; seven figures and one table complete original crops visually checked; equivalent calibration and arithmetic boundaries retained','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
