import json,time
import worker as w
d=w.ROOT/'sources'/'WPSKKB3W';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'reported_fungal_products_nominal_molar_yield_sum_percent':30+30+27,'volume_from_text_buffer_fraction':14/34,'volume_from_text_DMF_fraction':20/34,'text_buffer_fraction_ratio_claim':.6,'control_product4_table_mass_mg':1,'control_product4_paragraph_mass_mg':.5,'control_product4_both_reported_percent':30,'independent_replicate_n_per_condition':None,'initial_rates_verified':False,'pure_lichen_protein_identified':False})
claims=[('Identity','PDF1','Title twoauthorsCohenTowers Phytochem44(2)271274 PII matches DOI suffix without literalDOI; copyright1996volume1997 receivedMay131996 ZoteroJan1notonlineverified'),('Coverage','PDF1-4','All4mainpagesreadoriginalsviewed2final300dpi originalcropsviewed full unnumberedstructure andTable1 not invented originalFig1number; refs20notindependentrawspectra'),('Lichen identity','PDF1/3','Nlaevigatum tissue semipurifiedactivefraction twoisolations6mgeach30nkatmg dimedon notsingleprotein sequenceorcofactor; otherXparietinaenzyme properties nottransferred'),('Design','PDF2/3 Table1','Two substrates three treatments sixmixtures pH3.4 endpoints68h; triplicatesolutions not established3replicatespercondition noSDtestsP'),('Lichen results','PDF2/3 Table1','Emodin to7chloro1mg30percentfirst20h no reported5chloroordichloro;7chloro furthernotreported noLODzero'),('Fungal results','PDF2/3 Table1','Emodin yieldsmono7mono5dichloro1mgeach30/30/27first20/20/68; secondsubstrate3mgproduct90first40endpoint68 conversiondistinctisolation'),('Control','PDF2/3 Table1','Nonenzyme chlorideperoxide emodin sameproductsfirst40/40/68 but7chloro nofurther; difference supports enzyme contribution not directactive-site transfer proof'),('Time','PDF2 Table1','FirstTLCdetection not initialrate; shared68h not equalkinetics verified no rateconstants'),('Source conflict','PDF3 Table1','Control5chloro table1mg30 versusparagraph.5mg30;DMF20buffer14 versuswritten6:4bufferDMF no silent correction'),('Characterization','PDF3','PuritiesRPHPLC author UV EIMS1HNMR identity match priorreports but rawspectra numericpurityunavailable'),('Mechanisms','PDF2','Chlorideinhibition lostextractenzyme anddenaturation are alternatives not tested concentrationresponse rescue; tissueoriginsproteinunknown'),('Declarations','PDF3/4','NSERC support no grantnumber explicitCOIabsent originals read nohumanreviewclassificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all four pages text and original pages read; unnumbered structure and Table1 complete original crops visually checked; control reaction source inconsistencies and crude enzyme identity boundaries retained','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
