import json,time
import worker as w
d=w.ROOT/'sources'/'XJBC6G8N';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'ORF_triplets':1323/3,'Km_abstract_acceptor_mM':.42,'Km_abstract_donor_mM':.40,'Km_body_acceptor_mM':.45,'Km_body_donor_mM':.41,'Km_acceptor_difference_mM':.45-.42,'Km_donor_difference_mM':.41-.40,'kcat_reported_persec':1.5,'product_excess_percent_original_no_conversion':40})
claims=[('Identity', 'PDF9166footer', 'Sixpages threeauthorsWalkerLongCroteau Walker corresponding July9 2002 contributedFeb27 DOI082115799 liveZotero200'), ('Coverage', 'PDF9166to9171Figures1to5', 'Allsixpagesfulltextreadoriginalsviewedfivefull300dpicropsviewedallpanelscaptions'), ('Surrogate', 'PDF9166Figure1PDF9168', 'SurrogateNdebenzoyl3RS2deoxytaxol enzymeNbz2deoxytaxolnotTaxol diagramhTaxolnotactualfullproduct chemicalNbzstandardnotpostreactionderivatization'), ('ScreenControls', 'PDF9167to9168', 'Ninefamilythreeassignedsixremainingnotn BL21DE3pSBETaT7argU emptyvectorTAX1TAX2TAX6 boiled without either substrate allnegative no detectionlimit no denovofactory'), ('ProductStereo', 'PDF9168to9169Figures2and3', 'Figure2sampleradioUVcoincident39.6plusminus.1 cannotdiastereoresolve Figure3 upperstandardlowerproduct standard1to1 product40percentexcessoriginal absoluteconfigurationunassigned no eeorconversionclaim fullrestNMRauthorreported'), ('MS', 'PDF9167/9169Figure4', 'DirectinfusionAPCI notLCMS 855authorPpluswaternotTaxol 838820778760569509270 stdsameauthorreportednotcomparativepanel'), ('Kinetics', 'PDF9166/9168/9169', 'Partialpurified50percent Kmabstract.42/.40mM body.45/.41mM unexplained retainboth kcat1.5plusminus.3snegative1 enzymequantitycorrectiondetailnotfullyreported duplicateassaymeanSElessthan15percentnotbiologicaln2 R2.99 no rawratesCI'), ('Specificity', 'PDF9169', 'pH8half7and9 phosphateCapsochanged donoracetylphenylacetylnotdetected limitedtest alphaattachedandfreebetaSalphaunproductive surrogateactive notnaturalorderproof'), ('Sequence', 'PDF9169Figure5', '1323nt441aa49040DaAF466397paperonly eightaligned blackfouridenticalgrayfoursimilar H163D167G168 possiblecatalysisnomutation noNTertargetingnotcelllocalization Dianthusidentity53similar64TaxusTBT60/69'), ('Boundary', 'PDF9169to9171', 'Fouracylases8functionalclones20stepshistorical incomplete naturalfinalordernotdirectlytested NIH eXegenicsMcIntireStennis noexplicitCOI humanfalseclassificationdeferred')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex6pagesfulltextread6originalsviewed5complete300dpicropsviewedResearchDBTNBTsurrogate2deoxytaxolenzymaticNbzstereoselective40percentexcessunassignedconfigurationKmabstractbodymismatchpartial50percentpurityduplicateassayreportedSEdirectinfusionAPCIPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
