import json,time
import worker as w
d=w.ROOT/'sources'/'S7AVSQZL';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'benzoyl_supply_enzyme_count':1+3,'BAHD_candidates':25,'P450_candidates':'more_than_40','reaction_efficiency_comparison':'about_280_metric_unreported','tobacco_feed_conversion':'more_than_60_percent_not_final_Taxol','yeast_titer':'not_reported'})
claims=[('Identity','PDF1/3','NewsViews2authors3pagesDOI801yversusprimaryLiang800z distinct liveZotero verified visiblepublished30April2025 extractedxxplaceholdernotactualmissingdate'),('Coverage','PDF1to3Figure1','Fulltext3originalpagesreadviewedcomplete300dpi Figure1 entiretwo metabolite rows feedarrows modules full two columncaption viewed citedprimaryunreadnoSI'),('Sidechain','PDF1left/right','PAMTbaccata TBPCCLTbaccata AAE16Tchinensis CoAL312GPchrysogenum BAPTTcuspidata morethan60percentfedbaccatinIIItoNdebenzoyl2deoxytaxoltobacconotfinalyeastyield'),('Oxidation','PDF1right','TB506 and morethan40P450 tested negative specifiedsystem not universal noactivity T2OGD author functional candidate not newcommentexperiment no kinetic details'),('Acylation','PDF1right','25BAHD candidates T3NBT last Nbenzoylation after T2OGD about280fold DBTNBT comparisonmetricundefined not totalpathyield nSDSEMP CIunreported'),('Grid','PDF2Figure1PDF3','10deacetyl and acetylated rows fourDBATarrows alternative modificationstages no measured flux equalbranches benzoylCoA distinct beta phenylalanoylCoA fourenzymePALCNLCHDKAT1module'),('Factory','PDF1lastPDF2bottomPDF3','FedbaccatinIIIbetaphenylalanine yeast production minuteamountnotquantified full de novo single strain future goal BAPTorthologues solubility MBP categories no effectsize'),('Boundary','PDF3','Gridcouldcontributelowtiter cautious notcausalproven futureconsortiumfromotherproductcases not Taxolconsortium noLCA TEA industrialverification humanreviewfalse classificationdefer')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex3pagesfulltextread3originalsviewed1complete300dpicropviewedNewsViewsprimarydistinctionfeedboundaryreactionefficiencyquantitiesversuswholepathcheckeddatevisualverifiednoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
