import json,time
import worker as w
d=w.ROOT/'sources'/'T653KQDL'
rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft']
images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Identity','PDF1/9','Five authors JOC2005 70 4667-4675 DOI10.1021/jo0502091; full nine physical pages read'),('Coverage','PDF1-8','GA two Figures two Tables six Schemes basic structures and four numbered reactions; sixteen final complete 300dpi crops each visually inspected'),('Purity','PDF2-4/9','C1 enantiopurity98-99 assumed analogous geranyl PP not directly measured; C4 precursor95:5 epoxide8:1 inferred final91:9'),('Assignments','PDF5 Tables1/2','C16 methyl1.09 C17 1.32; H2alpha1.62 H2beta1.72; body higher-field phrasing conflicts with numbers retained'),('C1','PDF6 Figure1 reactions1/2','R substrate maps D to product2alpha; S to2beta; both MS one D. Loss of two TOCSY responses for S reflects propagation not two deuteriums'),('Terminal','PDF6 Figure2 reaction3','Trans CD3 maps C16 missing1.09;1.36 extra peak impurity; known H1beta plus mapping supports anti overall addition'),('Elimination','PDF7 reaction4 PDF8 Scheme6','GC10:10:80 masses273273272; 24 tentative GCMS assignment not full NMR confirmed; main product D lost supports preferred H5beta elimination'),('KIE','PDF7/8','Branching shift interpreted primary isotope effect; no measured kH/kD no replicate count/error/P supplied'),('Mechanism','PDF7/8 Schemes4/5/6','Transient conformations models; trans bridgehead also depends parallel fluorinated probe paper; direct C11to7 versus non-exchanging enzyme relay unresolved; Enz-B not identified residue'),('Scope','PDF8/9','Preparation5-10percent typical6 not kcat Taxol titre; SI/raw spectra unread')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex directly read all nine main PDF pages, inspected all original page images and each of sixteen final 300dpi crops with full labels panels legends table rows and structures. No external LLM or human review. Original wording conflicts and tentative assignments retained.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked)
w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
