import json,time
import worker as w
d=w.ROOT/'sources'/'D5QBZ4FI';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'HK1_over_HK17':109.7/2.9,'HK5_over_HK1':277.8/109.7,'HK21_over_HK17':7.9/2.9,'HK22_over_HK21':11.4/7.9,'HK9_over_HK10':76/4.9,'HK12_over_HK9_multiple_changes':528.5/76,'HK12_over_HK16':528.5/445,'culture_figure_n':3,'construction_validation_n':5,'pure_taxadiene_response_verified':False,'volume_overlay_conversion_verified':False,'exact_P':None})
claims=[('Identity','PDF1/9','Eight authors Karaca corresponding printedDOI MicrobCellFact23:241 receivedMar29 acceptedAug19 onlineSep62024 liveZotero200'),('Coverage','PDF1-10 Figures1-3 Tables1-2','All10mainpagesreadviewed five complete300dpi original crops viewed all32strain design and bars preserved;4SI files notread refs31notindependentlychecked'),('Background','PDF2/3/4 Figures1/2 Table2','SCIGS22a already tHMG1ERG20 modified MVA sixextra genes; diagrammixedscope; X-2 versusXI-2 retained'),('Quantification','PDF5/6','72h20mL flask10percentdodecane SIM122 betaCary internalstandard and calibration; no verified puretaxadiene response or independently reconstructedoverlay correction'),('Replicates','PDF5/6 Figure3','Fivebiologicalreplicates construction versus productionfiguretriplicate meanSD; noexactP or tests reported'),('Basic','PDF6 Figure3','HK1 109.7 versusHK17 2.9 sixextraMEP not claimed actuallyMVA; lowoutput no directtoxiccause'),('Fusion','PDF7 Figure3','TS-GGPPS HK5277.8 HK217.9 reverseHK976 HK25notobserved orientation discussion conflict preserveconstruct'),('tHMG1','PDF7','HK212.6 HK18notdetected HK6notdetected HK2211.4 HK104.9 HK26notdetected; 1.44ratioHK22/HK21 15.51HK9/HK10 notuniversal'),('ERG20','PDF7/8','HK347 HK19.08 contradict universal MVA advantage HK2764 highestMVA; fusionHK29/HK132.6 HK31/HK152.2 authorreport no invent bars'),('Maximum','PDF8/9 Figure3','HK12 GGPPS-TS plusseparatetHMG1ERG20528.5 vs abstract528; HK16 GGPPS-ERG20 plustHMG1TS445 HK3224.4; nofinalTaxol notsinglefactor'),('Limit','PDF8','Authors explicitly no RNA/protein/intermediatepool analysis mRNA structures substratechanneling and toxicity hypotheses; no industrialscale'),('Metadata conflicts','PDF2/9/10 Table1','Malci215tablevs251body; refs16year2014 27year2013 31volume194 retainednotindependentcitationvalidation'),('Declarations','PDF1/9','TUBITAK117Z246 Anadolu2008S091 no competinginterests CCBYNCND4 originalfigs humanfalseclassificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex ten full original pages read and visually checked; three figures and two tables complete crops visually checked; source conflicts surrogate calibration and matched comparisons retained','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
