import json,time
import worker as w
d=w.ROOT/'sources'/'BALTX27W';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('C20H26O6 sodium385.1629 calculated385.1622 DBE8','PDF2Table1','threecarbonyl twoalkenes threerings'),('H7toC6 prose correlation missing table row','PDF2Table1Figure1','tableH7only9/14, originalNMRunavailable'),('DP4+100percent only1avs1b','PDF2–3','relativecandidatecomparison notabsoluteprobability'),('1S5R10R13R15R Flackminus.08(9)','PDF3–4Figure2','CuKalpha CCDC2160284, notindependentCIFrefinement'),('IC50 4.2plusminus.2 and3.0plusminus.4uM','PDF3Table2','CC50>30,SI>7>10,n3SD'),('MTT48h vsdifferentiation5days','PDF3–4Table2Methods','differenttimewindows'),('3unassayed because.3mgscarce','PDF3–4','notinactive'),('RAW264.7signal vsBMMphenotype','PDF3–4Figure3','differentcells,norescuebinding'),('p65captionpP65 vsbandsP65','PDF4Figure3','nuclearcytoplasmicdistribution, notphosphorylationproof'),('62m source genusidentification','PDF1/3','Chalinidaefamily andITS Pestalotiopsisgenus'),('isolation7.2/1.9/.3mg','PDF4','recovery nottiter, agitation120ppmprinted')]
checked={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex read all6PDFpages; actual originalpages1–4 and all7actual300dpi croppedgraphics visuallychecked, including both compoundpanels and fulltablesfootnotes. Noexternalmodelreview, SI orCIF unavailable.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
