import json,time
import worker as w
d=w.ROOT/'sources'/'9A5TMMLF';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'source_gene_set_size':18,'source_oxidation_product_classes':3,'independent_experimental_n':'not_reported'})
claims=[('Identity','PDF1/2','Spotlight not original experiment four authors two correspondents MolPlant17:370371March42024 DOI verified live Zotero'),('Coverage','PDF1/2Figure1','Both pages full text and originals viewed final complete300dpi Figure1 viewed structure arrows enzyme names full caption no SI attached cited primaries not independently read'),('GeneSet','PDF1left2ndpara right2ndpara','18 gene minimal set author summary baccatinIII then paclitaxel transformation but low yield prevents entire single module reconstruction no universal host minimum demonstrated'),('Oxidation','PDF1left3rdpara right3rdpara','2OGFeII C4betaC20 epoxidase versus CYP725A4 two sequential epoxidation competing explanations natural order not resolved no new kinetic or structural evidence'),('Figure','PDF2Figure1caption','Thick arrow multistep thin single dashed unknown order two taxadiene doublebond positions distinct sidechain T2primealpha not C20 extraction misread'),('Host','PDF1right3rdpara','Three oxidation products in tobacco epoxidase seems inactive microorganisms host n expression detection limits unspecified not universal noactivity'),('Channeling','PDF1right3rdpara','Enzyme assemblies substrate channeling proposed investigation not measured stablecomplex or functional channeling evidence'),('Boundaries','PDF1/2','No yield units n SD SEM P CI LCA TEA stableindustrial data sustainability future prospects cited primaries unread human review false defer classification')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex2pagesfulltextread2originalsviewed1complete300dpicropviewedCommentaryversusprimaryevidencegeneminimumversusfullmoduleresolvednoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
