import json,time
import worker as w
d=w.ROOT/'sources'/'ZKKMRAA9';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
aa={'Thr':1.09,'Ala':1.19,'Val':1.19,'Leu':1.20,'Phe':2.54}
w.write_json(d/'codex-arithmetic.json',{'source_volume_L_approx':5,'crude_mg':250,'isolated_material_mg':170,'crude_material_mg_per_source_L':250/5,'isolated_material_mg_per_source_L':170/5,'crude_to_final_mass_retention_percent':170/250*100,'retention_is_target_recovery':False,'measured_broth_titer':False,'empirical_formula':'C42H57N7O9','nominal_formula_mass':42*12+57+7*14+9*16,'observed_elemental_percent':{'C':62.37,'H':7.11,'O':17.68,'N':12.09},'calculated_elemental_percent_reported':{'C':62.76,'H':7.10,'O':17.93,'N':12.20},'observed_elemental_sum':62.37+7.11+17.68+12.09,'sum_is_purity':False,'reported_AA_umol_per_mg':aa,'inferred_molecules_umol_per_mg':1000/803,'conditional_residue_equivalents':{k:v*803/1000 for k,v in aa.items()},'MIC_table_numeric_ug_mL':[12.5,1.56,3.13],'MIC_table_greater50_count':7,'dose50_mgkg_is_efficacy_dose_reported':False,'species_confirmed_Bsubtilis':False,'absolute_stereochemistry_determined':False})
claims=[('Identity','PDF1/3','FiveauthorsShojiHinooWakisakaKoizumiMayama Shionogi JAntibiot282:126-128Feb1975 receivedJuly291974 live200 DOIonlymetadata notprinted'),('Coverage','PDF1-3 Figures1/2 Table1','All3fullpagestextoriginalsread threecomplete300dpicrops viewed UVIRbothaxes tablealltenMICrowsagarfootnote; no rawAAreplicatesfullanimalrecords3refsnotallread'),('Source','PDF1/2','ThailandsoilstrainTL119 resemblesBsubtilis authorsinsufficientidentification explicitlynotconfirmed; strainvscompoundlabeldistinct'),('Isolation','PDF2/3','5L250mgcrude170mgfinal powder normalized50and34mgL isolatednotbrothtiter;68percentmassretentionnottargetchemicalrecovery'),('Formula','PDF1/3','C42H57N7O9 observedC62.37H7.11O17.68N12.09 versuscalc62.767.1017.9312.20Mplus803 nominalnotHRMplusH;99.25sum notpurity'),('Properties','PDF1 Figures1/2','decompositionabove250notsharpmp rotation24Dminus8.7plusminus1c.482DMSO notDLorCI UV252258264268weakshouldersIRpossibleester notcompleteconnection'),('Analysis','PDF3','HitachiKLA5 hydrolysisinsolubleHCl issue Thr1.09Ala1.19Val1.19Leu1.20Phe2.54umolmg conditional1.245moleculesumolmg count1eachPhe2 approximate recoverynotnewmeasured'),('Structure scope','PDF1','sixknownresiduesvsN7 NacetylDhbCOOHlactonesequence announced succeedingpaper notactualfullstructuraldatahere noabsoluteconfig'),('MIC','PDF2 Table1','12.5BsubtilisPCI219 1.56SaureusFDA209PJC1 3.13Smith other7greater50 includespneumoniaetypeIpyogenes;notallGrampositive;traditionalnamesretained no clinicalbreakpoints'),('Assay limits','PDF2 Table1footnote','usualagardilution nofullinoculum nCI P greater50censorednotexact50 MBC mechanism or broadstrainproof'),('Animals','PDF2','IP50mgkg no observedtoxicsymptoms nfollowupnotgiven notLD50orfullsafety;curativeIPnotSC noeffectsizeorefficacydose cannottransfertoxicitydose PKexplanationunmeasured'),('Declarations','PDF3','SMatsuura thanked invivoassays no fundingnumberCOIstatement nohumanreviewclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three full original pages read and viewed; two spectra and complete ten-row MIC Table visually checked; strain identification versus resemblance, isolated mass versus broth titer, censored MIC and limited animal observations distinguished','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
