import json,time
import worker as w
d=w.ROOT/'sources'/'RQJU5L74';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'reported_isolation_percent':.02,'conditional_yield_mass_fraction':.02/100,'conditional_yield_microgram_pergram':.02/100*1e6,'ED50_parent_unit_unspecified':5.5e-5,'ED50_fragment2_unit_unspecified':1e2,'ED50_fragment3_unit_unspecified':2.2e-2,'conditional_ED50_ratio_fragment3_parent':2.2e-2/5.5e-5,'conditional_inverse_relative_activity':5.5e-5/2.2e-2,'body_relative_activity':.001,'crystal4_R':.125,'crystal5_R':.142})
claims=[('IdentityBoundary', 'PDF2325title2327signature2326footer', 'Threephysicalpages contain adjacentpapers ActualTaxol startsleftbottom2325 righttopstructuralplate belongs Taxol entire2326 endslefttop2327 WaniTaylorWallCoggonMcPhail May51971 notZoteroMay1 ReceivedFeb16 DOIfrommetadata notprinted liveZotero200 manualmatch'), ('Coverage', 'PDF2325structure2326TableIequation1foot17', 'Allthreeoriginalpagesviewed actualpapertextread fourcomplete300dpicropsviewed originalunnumberedstructuralplate Figure1notebooklabel equation1Scheme1notebooklabel TableIoriginal foot17Figure2notebooklabel adjacentphotochemistrytableexcluded'), ('Isolation', 'PDF2325right', 'Stem bark alcohol fractionationchromatographyTaxolyield.02percent rawmassfreshdryrecoverynotgiven notabsolutecontent C47H51NO14M853 no industrialorclinicalperformance'), ('Degradation', 'PDF2326left equation1foot14', 'Mildmethanolysis2C17H17NO4 3C29H36O10 methylacetatenotisolated 3NMRnotobtainedinsoluble norearrangementauthorassumption supportedtaxininepriornot direct'), ('Crystal', 'PDF2326left/rightfoot13', 'Directderivative4pBrC24H20BrNO5 C2Z4R.1251772 derivative5bisiodoC33H38O12I2 P212121Z4R.1422305 heavyatom anomaloushalogenabsoluteconfigauthorreported parentnotdirectXray fullcrystallelsewhere noCIF'), ('Position', 'PDF2326TableIrightfoot16', 'Historicalnumbering retained baccatinVreferenceC13from13alphaacetate TableJHzδnotstatistics MnO2neutralinactive6oxidized8C31H36O11m584.2266calc584.2257 UV272IR1680H10δ6.46 supportC13not9,10dioxo noHMBCinvented'), ('Activity', 'PDF2325foot5PDF2326foot17body', 'ED50Taxol5.5e-5notOCRminus6 compounds2and3 1e2and2.2e-2 unitsnotprinted nCIcurveunreported pureTaxolversusconcentratesdifferent systems'), ('DiscrepancyMechanism', 'PDF2326rightfoot17', 'Body3.001relativeactivity versus conditionalED50inverse1over400 unexplained retainboth inactivequalitativeC13leavinggrouphypothesisnotmicrotubulemechanism'), ('Funding', 'PDF2325foot2PDF2327lefttop', 'NCI SA43ph4322 DukeEndowment NIHPR330 noexplicitCOI metadataDOI notprimaryindependentlychecked classificationdeferred humanfalse')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodexactualresearchcommunicationtextread3originalpagesviewedpaperboundaryidentified4complete300dpicropsviewedoriginalunnumberedstructureequation1TableIfoot17derivativeXraynotparentED50exponentactualvisualunitunspecified1over400versusbody1over1000PythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
