import json,time
import worker as w
d=w.ROOT/'sources'/'YHD6KJUF';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('18tested14successful14newditerpenes,not14totaltested','PDF2,4','Taxadiene,variediene,casbene,collinodieneunsuccessful;noquantthresholdSI'),('Probe geometry2E6Z10E and12step5percentchemicalyield','PDF2–3Figure2','17Z/E2to1,42/22isolatedyields,notenzymaticconversion'),('25/26 and29 absoluteconfigbiosyntheticassignments','PDF4Figures3–4','25/26tentative;29sameinitialfoldassumption;GCMSnotchiralproof'),('SiCotB2 fourisolatedproducts31–34,DFT feasible notdirectintermediatecapture','PDF4–5Figure5','B6transitionstatenotminimum;blueblackredenergiesdistinct'),('8.2highestbody conflicts8.6blackFigure5','PDF4–5','E6F68.2;H6I68.6 no silentcorrection'),('MgMS32/39/40and40tenRviafoldhypothesis','PDF6Figure6','39/40matchedNtPSGCMS;CpTS1CjCSalso40'),('PmS purpleassignmentsconflictbody','PDF6–7Figure7','text45major46/47trace vsfigure45misscross40cross'),('DFTcorrectsH8I8notstable andhighest20.4','PDF7–8Figure7','J8K8L8 path;xxplaceholder45.2bluebox retained'),('48rejectedcandidate49supportedbydeuteriumC6','PDF6,8Figure8A','SvSfrom2Dprobe,isolated49NMR statedSIabsent'),('46retainsD27347losesD272,branchM8vsN8','PDF6–7','46M8deprotonation47afterM8N8shift;not46mustpassN8'),('50NtPSDFTbranchnotisotopicallyclosedallsteps','PDF6,8Figure8B','O8energybetweenfig7/8notmerged;noallcarbocationcapture')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read original10pagePDF maintext pages1–9 and references9–10; inspectedallgraphicpages1–8 plus9actual300dpicrops. LocalSI absent; no raw-NMR reanalysis, independent-modelreview orhumanreview.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
