import json,time
import worker as w
d=w.ROOT/'sources'/'RJH4IGK7';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'PTX_rounded_mean_fold':.07/.04,'PTX_rounded_mean_increase_percent':(.07/.04-1)*100,'PTX_female_ug_per_g_DW':.07*1000,'PTX_male_ug_per_g_DW':.04*1000,'DAM':623+493,'DEG':1256+1798,'PCA_first_two_percent':32.03+8.41,'candidate_pathway_unigenes':sum([3,1,6,4,7,19,6,3,1,2])})
claims=[('Identity','PDF1/12/13','13pages11authorsHorticRes9uhac062DOI20220314correctedtypeset20220623notscientificerratumproofCOInoneGSE175645authorreportnotdownloaded'),('Coverage','PDF1to13Figure1to7','All13mainpagesread13originalsviewed7complete300dpicropsallpanelsunitscaptionschecked SIfigS1to8tablesS1to7actualunreadrawMSRNAunreadreferencesnotindependentlyread'),('Material','PDF9/10Figure1/2','5yearTmediaCangqianfreshbranches targeted6independentrepeatsuntargeted10RNA3 treebranchgenotypemappingnotfullyclear nosexrandomization'),('Metabolites','PDF2/3Figure1','PTX.07vs.04mgpergDWfromaxis1.75fold75percentnotmgLCEP7EDAP7EPTXfemhigh10DABBAC10DAPnonsignificant starsP.001 noexactPerrorCI'),('Omics','PDF2to6Figure2/3/4','9445features4479annotationsnotallconfirmed1116DAM623+4933054DEG1256+1798PCA32.03+8.4140.44percent52pathwayunigenesnot52functionalgeneloci'),('Annotation','PDF2/4/6Figure2D/4C','Textflav23/3Figure2Dflavlabelnear5/8amino23/3conflict notresolved;targetedBACDABnonsignificantversusannotatedfeaturechange notallconsistent samecompoundmultipleions noNMRproof'),('TF','PDF5/6Figure5','59MYB32bHLH392aaMYB39687aabHLH13femalehighnotgenomicsexabsence MYB39tobacconucleus noTaxusOEKOrescueorChIP'),('EMSA','PDF5/7/11Figure5','FourGGPPS/T13OH/T10OH/TBTMBEsGST20/200WTcompetitordecreasemutantnoeffect supportsinvitroselectivitynoKd;GSTGSHresultsHisNimethodconflict'),('Interaction','PDF6/8Figure6AB','BiFCnGFP/cGFPnucleussinglehalvesnegative Y2HBDMYB39ADbHLH13singlecontrolsnegativep53Tpositive noTaxusnativeCoIPstoichiometryWD40proof'),('Reporter','PDF6/7/8Figure6DtoG','LUC/RENn3SDP.05 GGPPSMYBalonenonactivationcomboincreaseT10OHMYBslightcomboincreaseT13OHTBTnonsignificantnotallEMSAactivate noformalsynergyinteractionmodel'),('Errors','PDF4/9/11','TSandGGPPSsameDN26572c0g1promoterID unresolvedmethodT10OHomitted4promoters3genesdiscussiontypo RENreportertextvsratiofigure usefigure nofullconstructSIverification'),('Model','PDF9/10Figure7','HypotheticalsexassociationinvitroheterologoussupportnotcausalnecessarysexmediatornoTaxusmetabolicinterventionnoflavonoidstressphenotype GGPPS/MEPT10OHschematicnotnewenzymeactivity noindustrialadvantageproof')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex13mainpagesread13originalsviewed7complete300dpicropsallpanelscaptioncheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
