import json,time
import worker as w
d=w.ROOT/'sources'/'6VFAN6L4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
rec['date']='1979';rec['journal']='The Journal of Antibiotics'
w.write_json(d/'codex-arithmetic.json',{'formula_DBE':(2*30+2-26)/2,'Table1_total_strain_rows':25,'Table1_gram_positive_rows':11,'Table1_gram_negative_rows':14,'Table1_MIC_le_0045_rows':4,'Table1_MIC_0095_rows':3,'Table1_MIC_019_rows':2,'Table1_MIC_039_rows':1,'Table1_MIC_156_rows':1,'Table2_strain_rows':5,'Table2_Bfragilis_lt039_rows':3,'MIC_values_are_censored':True,'replicate_counts_reported':False,'modern_complete_structure_verified':False,'absolute_stereochemistry_verified':False,'fermentation_titer_reported':False,'molecular_target_measured':False,'in_vivo_efficacy_reported':False})
claims=[('Identity','PDF1-3 Crossrefidentity','SaitoMatsuuraOkazakiChugai1979November32issue11pp1210-1212 liveZotero200 Crossref200matchesDOI notprintedonscan sourceautomatedidentityfalse manuallyoverridden'),('Coverage','PDF1-3 Figures1-3Tables1-2','Allthreepages read viewed five300dpi originalcompletecrops Figure1bothABcaption Figure2entireflow Figure3bothterminalmethyl expandedcropchecked all25Table1rows all5Table2rows andfootnotes'),('Organism','PDF1Figure1','CompostNo26 historicallyMalbrancheapulchellavarsulfurea noDNAtaxonomy; yeastglucosegrowth28to55optimal45to50 vs SEMyeastmaltcaption37and50 distinct noquantmorphreplicates'),('Recovery','PDF1-2Figure2','Mainlymycelial extract crystal noisolatedmassculturevolumepercentpuritytiter; ethylacetateinsolubletext vs partitionprocedure bothretainednoinventedexplanation'),('Formula','PDF1/2Figure3','C30H26O10nominal546DBE18 noexactmassppm UV273385CHCl3NMRexternalTMS notfull2Dor13C'),('Comparison','PDF1/2Figure3','Authorssameproposedhistoricvioxanthinstructure notindependentlymodernconfirmed 332decomposition versus190to195 unresolved rotationplus3.46c.95CHCl3noabsoluteconfiguration'),('MICpositive','PDF2Table1','11positive strainrows fourle.045 three.095 two.19 one.39one1.56 notindependentrepeats or clinicalsusceptibilitybreakpoints'),('MICnegative','PDF2Table1','14gramnegativerowsallgt100 preservecensorbound notexact100orallconcentrationsinactive'),('Anaerobe','PDF3Table2','ThreeBfragilislt.39 strictlessthan notle; Fglutinosumgt200 Fnecroforum12.5to25range preserveasprintednoSD allanaerobesensitiveclaimunsupported'),('Methods','PDF2/3Tablefootnotes','Bodydiffusionwordingversusfootnotedilution explicitlyinconsistent differentmediaandduration cannotinfer anaerobiosiscause no reportedrepeatQCstatistic'),('Otheractivity','PDF2/3','SC30532qualitativeweakernotmatchedheadtoheadratio otherbiologicalactivitypromisedelsewhere noactualparameters targetefficacytoxicity'),('Declarations','PDF3','K Uenoacknowledgment no explicitgrantCOIdatarepository noall3referencesread humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three scanned original pages read and viewed; complete Figures1-3 and Tables1-2 checked; Crossref identity confirmed; historical structure comparison, unresolved decomposition discrepancy, censored MIC and method wording inconsistency preserved','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
