import json,time
import worker as w
d=w.ROOT/'sources'/'NW57HMK4';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'DBTNBT_vs_WT':310/71.01,'BAPT_vs_WT':135/71.01,'Alternaria_ug_L_to_mg_L':61.9/1000,'Table2_platforms':7})
claims=[('Identity','PDF1/13','16pages3authorsPlants15:1741ReviewDOI liveZotero published20260604nodatanewCOInonefundingAIpolishingBioRenderdisclosed'),('Coverage','PDF1to16Figure1/2Table1/2','All16pagesreadalloriginalsviewed4complete300dpicropsallviewedTable2landscapewide7platformsfootnotesallincluded67referenceoriginalsSIrawdataunread'),('Pathway','PDF1to5Figure1','19to23stepsversus19modelcharacterizedproposedmixedTXSclassIIIbifunctionalclassificationunverifiedoxetanekeyquestionsabstractresolvedspecificenzymaticbody50nggbaccatinbasisunknownnotcomparable10to30ugpergdry'),('FoTO1','PDF4/14Ref30','NTF2likephysicalTXST5complexscaffoldauthorclaimstrongerthanResearchCommentaryuncertainpreciseroleprimarynotread10to17foldearlynotfinalTaxolyieldterminalreference31completeproductionnotindustrial'),('Regulation','PDF5/6/10Figure2','MYB29aABAearlyJAlaterconflictTcJAV3ubiquitin26SschematicoriginalN5FYdegradationmodelnotnewdirectproofgenomespartslistoverstatement'),('Spatial','PDF7/14/15Ref34/35','intercellulartransportessentialauthorclaimstem8EXoriginalABCG2candidateheterologouslocalizationwithoutactualtransportnecessityleafRef35article100561priorGSGoriginal100630conflict'),('Microbes','PDF7to9Table1','Ecoli570plusminus45oxygenatedtotalyeast78oxygenatedacetylatednotPTXtaxadiene8.7129plusminus15215184.2Bsub17.8Yarrowia101.4Aalternata61.9ugLnotmgLnSDSEMPCIunreportedcyanobacteria4.32hydroxytableonlyTXSGGPPSinsufficientoxidationgene listRef63triterpenenottaxane'),('Plants','PDF8/10/14/15Table1','56.6freshNtabacumFu58thisreviewotherW6RreviewNbenthamianaLi33samevalueconflictoriginalsunreadDBATomittedbaccatinTablegene listnotexecutable310vs71.01ratio4.365135ratio1.90jointelicitationnotbothfourfold'),('Citations','PDF4/9/10/14/15Ref25/29/53','ASRsentence25minimalplanttitleminimalplant29yeastfusiontitleyeastfusion184.253ASRtitleinternalthematicmismatchretainednoinventedrepair'),('Sustainability','PDF2/10to13Table2','7platformqualitativecomparisonnoLCAnoTEAnocarbonnegativeproofhybridfutureforecastnotmeasuredfullindustrialperformanceclassificationdeferredhumanreviewfalse')]
labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex16pagesfulltextread16originalsviewed4complete300dpicropsallviewedTable2landscapeinternalcitationmismatchcheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
