import json,time
import worker as w
d=w.ROOT/'sources'/'9IDKAPJ8';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'normal_product_percent':[94,4.8,1.2],'normal_sum':94+4.8+1.2,'marked_product_percent':[77.6,11.1,9.2,1.1],'marked_sum':77.6+11.1+9.2+1.1,'unaccounted_marked_percent':100-(77.6+11.1+9.2+1.1),'renormalized':False,'M60_kcat_ratio_M1':.0102/.0024,'M79_kcat_ratio_M1':.0080/.0024,'M60_Km_ratio_native':15.9/3,'M60_kcat_Km_Minv_sinv':.0102/(15.9e-6),'native_kcat_Km_Minv_sinv':.0106/(3e-6),'relative_4_20_proportion_ratio':11.1/4.8,'absolute_4_20_rate_change_known':False,'inactive_table_kcat_upper_sinv':.00001,'inactive_body_kcat_upper_sinv':.0001,'upper_bound_discrepancy_factor':10,'preincubation_method_microM':50,'preincubation_results_microM':100,'I50_microM':[90,120,100],'I50_is_Ki':False,'substrate_for_I50_microM':30,'deuterium_mol_percent':84,'terminal_KIE_rough':2,'independent_biological_n_verified':False,'tentative_minor_products_retained':True})
claims=[('Identity','Main1/liveZotero200','Title7authors379(1)137-146July12000 printedDOI10.1006/abbi.2000.1865verified'),('Coverage','Main1-10Figures1-4TableI','All10textpagesreadalloriginalpagesviewed5completecropsreviewedFigure3ABCDcaptionrightcolumncontinuationpreservedFigure4ABTablefootnotes'),('Constructs','Main4/5/8','M1M60M79functional M93M113M126proteinpresent data notshown no maturecleavagesiteobserved pseudomaturedefinition retained'),('Expression','Main5','M60M7930to40percentsolubleM1~10 proteinpurity>99vsM1~50 notsamedenominator yields30to40/10to20mgLpurifiedproteinnotproduct'),('Kinetics','Main5/6TableI','Km microMnotOCRmM native3.0M6015.9M7914 kcat.0106/.0102/.008 SE<10percenttriplicateaverages nativefusionpriorrefs notsamebatch significantclaimabsent'),('Originalconflict','Main6TableI/Main6body','Inactivebounds<.00001table vs<.0001body tenfolddiscrepancy blankKm notzero'),('Samplequalities','Main6','M6010mgml10daysloss<30withsubstrateMghexane vsM792days70loss differentendpoints nothalf-life M60>=20mgmlM79>5aggregation'),('Normalproducts','Main6/7Figure3','94.0major4.8minorstandardcomparison1.2verticillenetentative noNMRconfirmedminor allactiveformsreportedsamesetnotallshown'),('Markedbranch','Main7/8Figure4','84molD input77.6 11.1 9.2 1.1sum99missing1notpatched3(4)10.29min273tentative sharedC4interpretationH5betaHre eliminatedKIErough2'),('Relativevsabsolute','Main7/8','4(20)11.1/4.8relativefractionratio notabsoluteformation2.31gain noexternalhalfratetransferred'),('Alternateintermediate','Main8/9Figure2','3noolefinsvsGGPP>100pmol authorsretain tightlyboundnonexchangeableintermediate caveat'),('Timeinactivationconflict','Main4/5/9','4and7noinactivation Method50microMresults100 retained notmechanismcovalentpositive'),('Analogueproducts','Main9Figure2','4~30percentrate m/z270base122 consistentderivative notfullyNMRproved7notconvertedbutweakbindinginhibitorypossible'),('Inhibitors','Main9','ApproxI5090120100microMfor347 at30microMGGPP notKi orirreversibleproof'),('Limits','Main1/7/9/10','Funding NIHCA55254GM13956GM31354CytoclonalMcIntireStennis0967 labeledsubstratesynthesiselsewhere rawblotsGC unavailable allrefsnotread humanreviewfalse classifylater')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex readviewedall10mainPDFpages fivecompleteoriginalfiguretablecrops reviewed includingcrosscolumncaption; originalmicroMunits parameterconflicts andtentativeproducts preserved; independentarithmeticderivednotclaimednewmeasurement','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
