import json,time
import worker as w
d=w.ROOT/'sources'/'XDR3W689';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Two new stereoisomers share planar scaffold with A3302B','PDF4 Figure2','same protonated ion804.4277; Phe positions differ'),('Candidate31kb fiveORF sevenmodules not causal proof','PDF2–3 Figure1','five plus two modules; no KO complement or enzyme reconstitution'),('Connectivity supported by COSY HMBC NOESY','PDF4–6 Figure3 Table1','Thr sidechain to Dhb carbonyl ester; NOESY proximity not covalent proof'),('Whole hydrolysis cannot independently locate two Phe stereoisomers','PDF6 Figure2','2 and3 L plus D Phe require positional evidence, SI absent'),('NH9.52 to9.32 upfield and Ala40.0 anomalous','PDF5–6 Table1','retain source inconsistency no correction'),('Figure4 proposed pathway for3 not validated enzyme sequence','PDF7 Figure4','M3 noE and dehydration unassigned; caption3 body1 conflict'),('MIC1/2/3 25/3.25/6.25 against S aureus3090','PDF8 Table2','Tet6.25; no replicate CI or superiority test'),('Compound1 Kp and Pa MIC25 not all Gramnegative inactive','PDF8 Table2','2/3>25; all other Gramnegative>25'),('MIC concentration and strain IDs internally conflict','PDF1,8–10','3.25 vs3.125; 6.5 vs6.25; Kp different source identifiers')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read original12page PDF maintext and references; inspected all original graphic pages and all six new300dpi crops. SI absent; no independent model or human review.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
