import json,time
import worker as w
d=w.ROOT/'sources'/'RWTI5U34';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'bark_mg_per_kg':40,'ug_per_g_same_mass_basis':40,'weight_percent_same_mass_basis':40/1000000*100,'functional_set_right':9-1+5,'functional_set_left':9,'65_percent_remainder_not_all_productive':'not_calculated_as_yield'})
claims=[('Identity','PDF1/3','Perspective4pages3authorsfirst2equal1corrBioDesRes6Article0035DOI liveZotero verified submittedMarch7acceptedApril9publishedMay92024 funding COInone'),('Coverage','PDF1to4Figure1ABC','All4pagesfulltextread4originalsviewed final300dpi fullABCfigureviewedcaptionwhole21refs primary papers not independently read noSI'),('Counts','PDF1Introduction','About20reactions notgenes 40mgkg barkequals40ugg0.004percent dryfresh undefined no n noerrors'),('Oxetane','PDF1lastPDF2Figure1B','TOT1highacetylatedsubstrateinsectandTaxusknockdownreportedsecondary epoxidase taxusindirectconversion oxidizedtaxadienedecrease not itselfdirectsubstrateproof CYP725A4differentexplanation alternative mechanisms hosts substrates differ'),('Figure','PDF2Figure1B','BranchTOT1product1dehydroxyIVoxetanebaccatinIepoxide crossedinterconversionnotrequiredsequential intermediates otherstudystructuresnotindependentlyverified'),('Sets','PDF2Figure1C','left9includingTXSright13 nine minus1TOT1 plus5 functional coexpression set not confirmed physicalchromosomecluster Fernie2023 versusYan2024 comparedcontents notliteralhistorical basedfollowup'),('FinalProduct','PDF2rightlast','benzoicacid Lphenylalanine baccatinIIIexternallysupplemented paclitaxeltobacco accumulation notsinglebackgroundfull de novo'),('ProductProfile','PDF3left','OCTisoOCTmore65percent accumulatedtaxanes specific systemnotcarbonflux residual35notallproductive nativeTaxusnotobservedaccumulationcited2011reviewnotuniversalabsence'),('Hypothesis','PDF3leftRef19','Taxuspartnerproteinsmicroenvironmentmetabolonhypothesis generalmembraneboundmetabolonsref not specificTaxolphysicalorfunctionalcomplex demonstrated'),('Boundary','PDF3Conclusions','No new n P CIindustrial LCA TEA titer derivativepharmacology result futureprospects human review falseclassificationdeferred')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex4pagesfulltextread4originalsviewed1complete300dpicropABCviewedPerspectiveprimarydistinctionfunctionalsetversusgenomicclusterhypothesisversusdirectevidencecountscheckednoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
