import json,time
import worker as w
d=w.ROOT/'sources'/'IDRG7GFP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'alcohol_Km_microM':24,'alcohol_Km_SD_microM':9,'acetate_Km_microM':14,'acetate_Km_SD_microM':4,'acetate_relative_conversion_approx':.06,'reductase_background_mU_mg_approx':12,'reductase_coexpression_mU_mg_lower_bound':240,'nominal_lower_bound_fold':240/12,'fold_is_exact':False,'NMR_product_microg_approx':600,'GC_purity_percent_lower_bound':99,'parent_mass_delta':304-288,'ORF_bp':1458,'aa_length':485,'ORF_stop_triplet_consistent':1458==485*3+3,'molecular_weight_calculated':54652,'sequence_identity_percent':63,'sequence_similarity_percent':72,'triplicate_analysis_n':3,'independent_biological_replicates_verified':False,'kcat_Kd_known':False,'invivo_two_pathways_proven':False})
claims=[('Identity','Main1/liveZotero200','Fourauthors title98(24)13595-13600 DOIprintedfirstpage matched;Nov202001 issue notOct11contribution'),('Coverage','Main1-6Figures1-6','Entiretextreadall6pagesviewed andall6finalcomplete300dpicrops reviewed structures captions spectra axesfullsequence noTable'),('COspectra','Main3/4Figure2','F16CO450peak unstable3to5minutes versusnegativeglucuronidase notabsenceofprotein;Hisimmunoblotlocalization data notshown'),('Electrontransfer','Main3/4','F14positive240pmolP450permg;reductase12toover240mUpermg differentmeasure fromTaxoltiter'),('Productscreen','Main4Figure3','substrate43.4minproduct25.6 morepolar notpositionstereoproofalone no rawintegrationconversionrecalc'),('Mass','Main4Figure4','304vs288plusO16 fragments286271253 supportsdiol tentative thenNMRconfirmation'),('Structure','Main4/5Figure5','~600microg isolated >99percentGCpurity forNMR deuterobenzene previouslyassignedprotons plusdescribedcorrelations notallraw2Dshown no fermentationtiter'),('Sequence','Main1/4/5Figure6','AY056019depositedreported ORF1458bp485aa54652MW63identity72similarity Cys431 PFG435to438 noindependentGenBanksequenceverification'),('Kinetics','Main3/5','pHnear7.5broad Km24plusminus9alcohol14plusminus4acetate micromolartriplicateanalysesmeanSD independentbiologicalrepeatunknown acetate~6percentnotzeroKmnotpreference'),('Crosssubstrate','Main5Figure1','13alphafails5alpha10betadiol5acetate and10betafails5alpha13alphadiol underconditions unknownLOD notprovenabsolutezero orallroutescannotmerge'),('Pathboundary','Main6','Adventitioussubstratealternative andtwoearlyrouteslatermerger alternative retained noinvivofluxnorpathclosure;priorstructureabundanceordercaution'),('Transparency','Main1/6','GenBankdepositionpresent NIH CA55254CA70375Cytoclonal McIntireStennis0967 noexplicitmodernCOI rawblotsorrawspectra unavailable allcitedreferencesnotread')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read all6mainpages andviewed6originalpages and6completefigurecrops; productstructure vs chromatographicpolarity vs kinetics andinvivopathalternatives preserved','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
