import json,time
import worker as w
d=w.ROOT/'sources'/'N5CFQ4FU';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
names=['miRN108','miR164a','miRN109','miR482g','miR164c','miR7762.1','miR482j','miR396d','miR159b','miRN187','miR396b','miRN209','miR482c','miR482l','miR159b']
w.write_json(d/'codex-arithmetic.json',{'Chr10_PHAS_percent':48/160*100,'chr9_region_bp':758158182-616470670,'chr9_region_Mb':(758158182-616470670)/1e6,'miRNA_category_entries':len(names),'miRNA_unique_names':len(set(names)),'families':92+219,'target_union_not_computable_without_overlap':True})
claims=[('Identity','PDF1/9','7authorsFrontPlantSci15article1403060DOI20240508 manuallytitlematches despiteautomatedfalse'),('Coverage','PDF1to11Figure1to5Table1','All11mainpagesread11originalsviewed6final300dpicropscompletecaptionsfootnoteschecked supplementaryfilesSRAreferencesactualunread'),('Materials','PDF2/3','2female2maleEnshileavesMay2021 plus42publicRNA3publicsRNA; differentialn6tissue1treatment3sex nofullmappingverified;coordinatesinvalidsourcepreserved'),('Methods','PDF3Figure2','STAR2.7.9RSEMTPMedgeRlogFC1FDR.05 countinputnotexplicit;ShortStackPatMaNmiRBase22.1Phasis3.3psRNATargetscore3TPTMnotTPM;correlationabsr.7WGCNAweight.3 noactivationproof'),('Enzymes','PDF3/4Figure1/2','71putativehomologygenes_like_specificityunverified chr9region616470670to758158182141.687512MbnotcompactBGCproof pathwaypriorbackground tissueRNAnoquantpaclitaxel MJn1 femaleeffectsdependtissuesnewEnshileafnosignificant'),('TF','PDF4/6Figure3','990TF60families29modulesfinal10enzyme28TF differentFigure560miRNA9PHAS14TF10enzyme coexpressionnotpromoterbindingdirectionunknown'),('RNA','PDF4/5/7Figure4','460miRNA311families92known219novelfamilies160PHAScandidates48Chr10equals30percent not160verifiedproducts49and18targetsoverlapunknownnot67unique280triggerpredictions'),('Table','PDF5/8Table1','6directmiRNAplusPhas2176viaTF3viaPHAS miR159bduplicateB/C15entries14unique miR482c3957410miR482j2172780TPTMnotactivitycopiesyield miRN1081649830miRN109667260TBT2'),('Network','PDF7/8Figure5Table1Discussion4.3','TableAenzymesBTFthenenzymesCPHASthenTFthenenzymes authordirect15overgeneralizationnoexperimentalcleavage;arrowstypeheterogeneous'),('Limits','PDF1to11','NoPARE5RACEfunctionalreportergeneticperturbationHPLCtaxolyieldproof spongeceRNAeditingfutureproposalnotimplemented accessionPRJNA1031429authorreportnotdownloaded noSIrawreanalyzed')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex11mainpagesread11originalsviewed6complete300dpicropsallpanelscaptioncheckedPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
