import json,time
import worker as w
d=w.ROOT/'sources'/'W9Z8EZLL';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'verticillene_specific_activity_dpm_microg':6,'taxadiene_specific_activity_dpm_microg':210,'specific_activity_ratio_percent':6/210*100,'ratio_is_total_flux_fraction':False,'D2O_product_single_D_percent':8,'D2O_error':2,'C10_product_single_D_percent':85,'C10_error':5,'error_type_verified':False,'D2O_rate_reduction_approx_percent':60,'intrinsic_KIE_calculated':False,'C20_three_D_retained':3,'C1_C20_five_D_retained':5,'C4_two_D_product_retained':1})
claims=[('Identity','Main1/10/liveZotero200','Title fiveauthors35(9)2968-2977 BI9526239 matched DOI bibliographicrecord; completeDOI notprinted; dateJan1notverified'),('Coverage','Main1-10','Allmainpages textread originalpagesviewed ninecompleteSchemes andTable1 finalcropsviewed withconditionlinesandfootnotes'),('Enzyme','MainMethods','NaturalTaxusbrevifolia partiallypurified preparation notrecombinantM60notuniformenzyme nohomogeneouskcat'),('Labels','MainMethods/Schemes2-6/Table1','C20threeC1C20five>95atomD C2single84 C4double91 C10single>95 exogenousracemicverticillene94; organic synthesesnotplantpath'),('Mass','Main6/7Scheme7Table1','Reference272257122 five277262127 three275260125 C4andC2 273258123; C-ringfragment supportedwithmultiplelabels'),('Statistics','Main7Table1','8plusminus2D2O and85plusminus5C10 backgroundcorrected noerror typenorindependentn verified blanknotzero'),('Ringformation','Main7/8Scheme8','C20andC1retention arguesagainstparticular4(20)isomerizationandcasbenemodel C4GGPPtoC5product lossof1D notlaterstereospecific4Rstudy'),('Conversions','Main7/8','3.6and4.0percent compared4.2parallelcontrol C4 4.1 compared4.3 differentparallelcontrols nointrinsicKIEcomputed'),('Externalolefins','Main6/8','9to14percentnonspecificinhibition15microM includesunrelatedcontrol direct5microMnone<.1percent<5pmolh cannotexcludeinternalnonexchangeableintermediate'),('Trapping','Main8','85percentrecovery6vs210dpmpermicrogram is2.86specificactivityratio nottotalfluxfraction'),('Hydrogen','Main8/9','D2O~60percentratedecrease8plusminus2D C10singleD85plusminus5 andC-ring122to123 directringlocalization C7 mostlikely notsiteNMR'),('Unknown','Main8','Unknownolefin~10percenttaxadienepeaklevel RtconsistentverticillenepartialSIMinsufficientidentification notconfirmednorcompleteproductfraction'),('Mechanism','Main9Scheme9','1996EnzBmediatedsamehydrogenreleaseandreturn tightlybound1Sverticillene hypotheticalbaseidentityuncapturedintermediates notlatermechanismoverwritten'),('Limits','Main1/10','Fundingretained noindependentCOIverified rawSIMmissing allreferencefulltextsnotread humanreviewfalse classificationdeferred')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read and viewed all ten original pages and ten complete Scheme/table crops including chemical condition lines and table footnote; mass fragment inference, unidentified olefin and historical mechanism boundaries retained','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
