import json,time
import worker as w
d=w.ROOT/'sources'/'5QMZSYED';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'isolated_mass_mg':2.1,'rice_mass_kg':1.2,'isolated_mass_per_kg_rice':2.1/1.2,'reported_mass_error_ppm':(181.0860-181.0859)/181.0859*1e6,'formula_DBE':(2*10+2-12)/2,'true_broth_titer_verified':False,'native_fungus_produces_compound1_verified':False,'intermediate2_directly_detected_here':False,'host_ethylating_enzyme_identified':False,'Rdomain_mutation_causality_tested':False,'compound1_bioactivity_tested':False})
claims=[('Identity','PDF1','Printed title DOI eightauthors TohokuQueenslandGriffith TetrahedronLetters1342024 154865 onlineDec32023 liveZotero200 manualtitle overridesautomatedfalse'),('Coverage','PDF1-3 Figures1-4Table1','All3mainpages read viewed five300dpi crops checked include clusterhomologytable allHPLCtraces bothstructures allCOSYHMBC arrows completeNMR OHlastrow fullFigure4domainpath caption'),('Candidate','PDF2 Figure1','PbpsA4170aa39identity55similarityFlvA genesBCD annotation notactivitytests; ERzeroMTzero domainstates authorproposal'),('Controls','PDF2 Figure2','HPLC210nm peak1 absentempty presentpbpsAandpbpsABCD noquantcalibrationreplicates; BCD nochange conditionalnegative withoutproteinvalidation'),('Recovery','PDF2','Rice1.2kg50gx24 isolated2.1mg equals1.75mgkg notliquidtiter biosynthesisyield ornativefungusproduction'),('Formula','PDF2/3 ref22','BodyC10H12O3MplusH181.0860calc181.0859C10H13O3 error.552ppmDBE5 ref22 printsC10H3O3missing1 explicittypo retained'),('Structure','PDF2 Figure3Table1','EthylH102.47qH111.12tJ7.8 H11C3HMBC; propenylH75.94H86.67H91.89 H8C6HMBC;J15.6supportsE notabsolutechirality'),('Assignment','PDF2 Table1Figure3','TenC numbered2to11 oxygen1 C4OHremainingcomposition OH6.27brs;bodyH5C5selfHMBCnotindependentlongrangeproof; SIrawunread'),('Pathway','PDF2/3Figure4','Three malonylextenders proposedtetraketide2 knownpriorshunt notisolatedfedhere; hostethylation analogy notenzyme donor isotopeKO evidence'),('NRPS','PDF3','CATAconservedRdomainLysAsn possibleimpairmentno mutationrestoreenzymetest no causalcertainty; LeuIle recognitioncodeanalogy cannotruleoutsubstrateavailability'),('Activity','PDF1-3','No compound1bioactivityassay backgroundotherproductactivitynottransferred'),('Declarations','PDF3','COInoneknown dataonrequestnotrawrepository JSPS22H02775AMEDCREST23gm1610007 BINDSNHMRCARC humanreviewfalseclassificationdeferred')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex all three original pages read and viewed; four complete figures and Table1 original crops checked; experimentally supported structure distinguished from untested host modification and NRPS mutation hypotheses','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
