import json,time
import worker as w
d=w.ROOT/'sources'/'2BXAQGNW'
rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft']
images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'14_of_27_percent':14/27*100,'UDP_to_emodin':2.5/25,'conditional_emodin_product_uM':25*.26,'conditional_UDP_cycles':25*.26/2.5,'conditional_baohuoside_uM':50*.24,'note':'Conditional on percent yields using corresponding initial substrates; not measured cycles or verified mass balance'})
claims=[('Identity','PDF4874to4877','4actualmainpages7authorsEnglishOrgLett16DOIol502380p autoSIflagincorrect actualmaintext completejournalpages verified;published20140905notZotero0919'),('Coverage','PDF4874to4877Figures1to3graphicalabstract','4pagesread4originalsviewed4final300dpicropscheckedallstructurespanelletterscaption;Chart1internalgraphicalabstractindexed embeddedimagebbox162.482239.188462.444344.523 fullycontained;SIactualunread'),('Candidate','PDF4874and4875','NineclonesCtGT6UGT73AE1His6Ecoli cDNA1476bp491aaKJ95678856percentVitisUGT73C2 authorinfo notdownloaded nativeflavonoidGTtentative'),('Controls','PDF4874and4875','NoenzymeornoUDPGcontrolsrequired;500ugcrudeproteinnotpureenzymeconcentrationrepeatnCIunreported'),('Library','PDF4875and4876Figure1','27members19types14over80percent16aglycons20isolated4authornovelnotindependentnovelty;9singleof19multiplenucleophiles;3blowyieldnotisolated starstructureconfirmedlimited'),('Positions','PDF4875and4876Figures1and2','Emodin8OnotRpUGT1emodin6O glycyrrhetiniccarboxyglucosylesternotC;S/O/N2a14a17aJ9.6/6.8/8.4 beta rawNMRunread noallsubstratesuniversality'),('Reversible','PDF4876Figure3','Icariin7OglucosedeletionbaohuosideI38percentHPLC 1to5UDP12hKeq7.5authorsdefinitionSIunread notnewcomputedthermodynamics'),('Coupled','PDF4876Figure3','50uMicariin25uMemodin2.5uMUDP1mgprotein12h24/26percentdifferentdenominators no50sum;conditional6.5uMproduct2.6UDPturnsand12uMbaohuosidePythonnotclosedmassbalance'),('Limits','PDF4874to4877','SI S1toS12proceduresrawspectraactualunread noproteinreactionvolinvented noexactPstats;pharmbenefitsreferencesnotdirectmeasured noindustrialcostenvironmentalvalidation noRugulosinAfunctiontested;fundingCOIverified')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex4mainpagesread4originalsviewed4complete300dpicropsfullstructurepanelscaptionscheckedgraphicalabstractbboxPythonarithmeticnoexternalLLMorhumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review)
w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
