import json,time
import worker as w
d=w.ROOT/'sources'/'AK9B4YFU';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
claims=[('Seven maydistacins plusfusaproliferin8 terpestacin9','PDF1–2 structures','Author novelty claim retained; no independent complete literature audit'),('JointfirstauthorsShiDuanWang','PDF8 author contributions','Z.S.X.D.F.W.equal'),('1S15R23S and2 1S8R11S15R23S','PDF2 Figure3AB','ECDcalculations,not singlecrystal'),('3 C8 relative8Rstar','PDF2 Figure4A','Two candidateDP4+100percent conditioned onmodels'),('3 totalDBE8 sameas2','PDF2 formulaC27H40O6','Ringopening and acetylcarbonyl offset; notonlyacetylation'),('4/5 solventfootnotes differTable1/2','PDF3–4 originaltables','4b5a protonversus4a5b carbon retained'),('3 H2a prose listedonbothfaces','PDF2 originalNOE paragraph','Internal wording inconsistency notsilentlycorrected'),('4 mass441.2599 vs441.2602','PDF5/8','Bothsourcevalues retained'),('Figure4C modelcontains11Sstar omittedfromcaption','PDF7 originalFigure4','Explicitcandidate scope retained'),('6 7Sstar8Sstar selected','PDF5–7 Figure4D','DP4+100percent; R2 alone not structureproof'),('7 C11acetate chemicalhydrolysisrelated9','PDF6/8','S68unread; sourcehydrolyzedrotationminus23.5 versusliteratureminus18'),('1NOIC5019±2uM','PDF1/6','Dexamethasone6.7±.6abstract versus6.9±.7body'),('RAW264.7MTTsurvival>90percentat50uM','PDF6','Limitedtestedrange,not general safety; othersNOinhibition<40percent')]
checked={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read all9 mainPDFpages, originalpages1–8 and all8 actual300dpi cropped graphics/tables visually checked. Rotated originalTable1 by90degrees for readability. SI,NP-MRD,citedpapers not independently read; calculations not rerun. No external model review.','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':[x['label'] for x in images],'covered_labels':[x['label'] for x in images],'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',checked);w.validate_structure(draft)
note=w.publish(rec,draft,images,checked,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
