import json,time
import worker as w
d=w.ROOT/'sources'/'FWQS6REW';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'mutant2_reported_mg_per10mL':1,'mutant2_equivalent_mg_perL_reaction':1/.01,'deletion2_reported_mg_per10mL':.9,'deletion2_equivalent_mg_perL_reaction':.9/.01,'mutactin3_reported_mg_per10mL':.2,'DMAC5_SEK266_each_reported_mg_per10mL':.2,'each_equivalent_mg_perL_reaction':.2/.01,'max_KR_to_PKS4_ratio':10,'reported_product3_to_product1_readout_ratio':[1,2.5],'conditional_two_readout_fraction_percent':1/(1+2.5)*100,'fraction_is_total_molar_conversion':False,'fermentation_titer_measured':False,'binding_constant_measured':False,'raw_SI_read':False})
claims=[('Identity','PDF1/2','SixauthorsMaZhanXieWatanabeTangZhang UCLAUSC JACS1301:38-392008 DOIprinted webDecember122007 receivedOctober22 liveZotero200'),('Coverage','PDF1/2 Figures1/2 Scheme1','Bothfullpagestextoriginalsread threecomplete300dpicrops viewed allABCDE Figure1 ABCD Figure2 standardsproteinlabels Scheme1products1-8branches;SIunavailable15refsnotallread'),('System','PDF1','GfujikuroiPKS4 purified Ecoli protein in vitro product1SMA76aprecursorbikaverin notwholebikaverin fermentation'),('Mutation','PDF1 Figure1B Scheme1','S1830A loses1 predominant2MminusH341 UVNMR authorSI notrawrechecked; O9C1 ester C12C17 aldol proposedsequence'),('Deletion','PDF1 Figure1C','PKS4-99 forms2.9mg10mL supportsretainedcatalysis notatomicfullfoldidentity; proteinexpression2mgL vsproductdistinct'),('Complement','PDF1/2 Figure1DE','StandaloneTEpartialrestore1 both mutants;S1830Alowerrelative1 competitionbindingauthorhypothesis noKd nofullrecovery'),('Reduction','PDF2 Figure2C','actKR NADPH3mutactinMminusH301RfLCUVMSmatched;removeNADPHabolishes3 supportscatalyticparticipation not directACPtrappingtimecourse'),('Labels','PDF1 Scheme1','GrisCYC1 OxyCYC2 diagramlabels versusbodyGrisARO/CYC OxyN;7/8ACPbound schematicnotstructureobserved'),('Figure2D discrepancy','PDF2 Figure2','ActualgraphDActKRGrisCYC OxyCYC captionDonlyPKS4GrisARO/CYCOxyN;bodyC9reducedcontext preserve discrepancy exactrecipeSIpending'),('Ratio','PDF2','14CmalonylradioTLC KRatleastequimolar large3 higherKR saturates10foldKR3:1approx1:2.5 normalized28.57percent two signalsnotmolarconversionpurity orKd'),('Further','PDF2 Figure2D','SEK344data notshown;DMAC5octaketideSEK266nonaketideeach.2mg10mL with1 standardmatched notalldenovoNMR; inferredfullchainKRaccess'),('Mechanism','PDF2','ChainperiodicexitKS shieldingACP/PT proposed noatomiccomplex;actKRpromotesC7C12 interpretation noquantaldolrate'),('Quant boundary','PDF1/2 Figures1/2','HPLC320nmvs280nmnotcrosspeakintegralquant;protein8mgL5mgL vsreactionproduct10090or20mgL distinct notfermentation noCIorPvalues'),('Declarations','PDF2','AHA0535069N NIGMS1R21GM077264 noexplicitCOI nohumanreviewdeferredclassification')]

labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex both full original pages read and viewed; two figures and one complete Scheme visually checked; in vitro function versus proposed competition and docking mechanisms distinguished, Figure2D graphic and caption mismatch preserved','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c} for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
