import json,time
import worker as w
d=w.ROOT/'sources'/'DW2KXVKT';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'YP12_vs11_fold':.07/.02,'YP12_vs11_increase_percent':(.07/.02-1)*100,'YP27_vs12_fold':.8/.07,'YP27_vs12_increase_percent':(.8/.07-1)*100,'fusion_vs24_increase_percent':(.8/.31-1)*100,'fusion_vs23_increase_percent':(.8/.27-1)*100,'fusion_vs21_increase_percent':(.8/.13-1)*100,'SUMO_vsYP51_increase_percent':(3.55/2.01-1)*100,'YP51_vs27_increase_percent':(2.01/.8-1)*100,'GGOH_decline_percent':(1-31.4/115)*100,'reactor_vs_best_flask_fold':101.4/23.7,'reactor_vs_initial_fold_crossconditions':101.4/.02,'original_biological_repeat_independence':None,'exact_P':None})
claims=[('Identity','PDF1/7','8pages6authorsJianheXuECUSTSynthSystBiotechnol8:331to338DOIprintedacceptApr11onlineApr26ZoteroJune2023 authorsnofinancialinterestfund2019YFA09050002187108531971380222201714026'),('Coverage','PDF1to8Figures1to6Table1','All8mainpagesreadoriginalsviewed6Figure1Table7complete300dpicropsviewed SIstrainsprimersoptimizedseqTablesS1to3FigS1unread refs48notindependentlyread'),('Baseline','PDF2Figure2','Po1fATCCMYA2613TaxuscuspidataTASYcodonoptimizedYP11.02YP12.07mgL120h 3.5fold250percentnotfinalTaxol noP450tested'),('PushPull','PDF2/3/6Figure3','YP21.13YP22.15YP23.27YP24.31fusion.68.70.80mgL YP27.8/.0711.43foldnotabstract234percent fusion296percentnotreproduciblefrombodybases lineageYP21textFigure3cumulativeunresolved'),('GGOH','PDF3Figures3/4/5','YP27GGOH115vsWT.40mgL suggestsGGPPdiversionnotdirectpoolorflux no phosphataseidentified no independentTASYsolubilityproof'),('Tags','PDF3/6Figure4','SUMO3.55MBP3.45YP51alone2.01 NusA12.4percentupTrxA15.3down authorreported 3.55/2.01increase76.62percentvsabstract62.3discussion60.6 YP51extra173percentvsbody151.25 no silentcorrection no proteindirectmeasure'),('Multicopy','PDF3/5Figure5','randomrDNAiterativeintegrationselectedbest3perround23.7mgLhighest after3 GGOH115to31.4decline72.7percent notGGPPconversionyield correlationcopypositionselection effectsno exactfunctionalcopyperround'),('CopyMethod','PDF6Figure5','genomicDNAgapdh describedversuswordtranscriptionRTqPCRkit no efficienciescalculation main copy notRNA no proteinamount'),('Reactor','PDF3to6Figure6','M23optimizationM33plusLeuM4 fedbatch5Linitial2L144h101.4mgL OD210 figureM4/M6batchfedbatch conflict glucosefeedresults10xYPDmethods dodecane10analysis20at36hreactor YNBglucose20percentvs20gLothercontextretain'),('Analytics','PDF4to6Figures2to6','2to5triplicateSDbiologicalindependenceunreported noexactP CIs F5bnoobviouserrors GCMSoctadecaneISnotfulltaxadiene calibrationresponsefactorrecovery'),('Table','PDF3Table1','94percentcellfreefractionnotcarbonyield mgL gL microggFW incompatibleunits tablepriorstudiesnotnewmeasure nooverallhostranking'),('Scope','PDF1to8','OnlytaxadienenotTaxol terminal101.4/.02about5070foldcrossconditionsnotoneinterventioneffect historicalfirstGRASclinicalclaimsnotindependentlyverifiedhumanfalseclassificationdeferred')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex8mainpagesreadalloriginalsviewed6Figures1Table7complete300dpi finalcropsviewed endproducttaxadienenotTaxol directsolubilityunmeasured bodyabstractpercentrecomputeddiscrepanciesretained noSI humanreviewfalse','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
