import json,time
import worker as w
d=w.ROOT/'sources'/'KCRKWWRP';rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'));draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft'];images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'reported_fold':2.4,'increase_percent':(2.4-1)*100,'screened_candidate_genes':23,'core_saturation_sites':12,'Nterminal_sites':8,'total_targeted_sites':20,'effective_library_clone_n':None,'biological_replicates_n':None})
claims=[('Identity','PDF1/2/5','JustAcceptedpeerreviewednotrecord6physicalpages5authorsMITWhitehead DOIZoterometadataPDFnotprinted Oct30coverNov4Zotero datesnotmerged'),('Coverage','PDF1to6Scheme1Figures1to2TOC','All6pagesfulltextreadoriginalsviewed4final300dpicropsviewed allavailablepage6preserved originalleftedgeclippedcannotrestore noSIseqspectraFigureS1to17read'),('Strategy','PDF2Scheme1','ThreepositionsTXSupstreamCYPenzymehydrolasepostepoxide outputsisomer5andtargetalcohol2notfinalTaxol TOCTaxolarrowaspirational'),('Mechanism','PDF3Figure1B','PPiorY688basehypothesisvariablechainABPPidockingnotproof scan6noneabolished1retained5 H20text2vsgraphic5'),('Mutagenesis','PDF3/4Figure1ACD','6polar6nearby8Nterminal20sites notknownlibrarycloneN C719AC830Awholecelllowernotkcat S587unknowncatalysisorprotein stability S587Gunknownless.5mgL'),('Target','PDF4Figure1DE','Y688L2.4fold5andcoexpression2authorreported notbarread precisionnotfinalTaxol 140percentincrease manyselectivityonly1decreased5constant noerrorsnexactPmain'),('Names','PDF3/4Figures1/2Scheme1','Q609Gbodysole9vsY609GDEcoexpressionunresolved 9Verticilla3712bodyvs3711B label noSIrawstructure; CDbluegreenlegendconflict92/8priorproportions noautomaticcorrection; OCT11caption10scheme Figure2A9vs11 Bepoxide2vscentral3'),('P450','PDF4Figure2','T380SdominantnewtwooxygencompoundinitialRTMSdiolresemblance actualoxa cyclotaxan10ol11cyclicether+oneOH notordinary2OH targetdiol noeachproposedreactionreconstituted'),('Candidates','PDF4/5','23TaxusfulltranscriptsRACEeachnegativeprofile noindividualexpressionqualitypositiveactivitycontrolmain notallnaturalhydrolasesabsent'),('Limits','PDF5','FundingPewSearleNIHNSFno competingfinancialinterestauthorstatement references22notindependentlyverified nofullTaxolquant nohumanreviewclassificationdeferred')]

labels=[x['label']for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'CurrentCodex6physicalpagesmainreadoriginalsviewedScheme1Figure1Figure2TOC4crops300dpi completeavailableframesoriginalTOCedgeclipped retained noSI mainnumberandlegendconflictsdocumented nofinalTaxolclaim nohumanreview','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review);w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
