import json,time
import worker as w
d=w.ROOT/'sources'/'KM8C68IW'
rec=json.loads((d/'prepared.json').read_text(encoding='utf-8'))
draft=json.loads((d/'codex-draft.json').read_text(encoding='utf-8'))['draft']
images=json.loads((d/'codex-crops.json').read_text(encoding='utf-8'))
w.write_json(d/'codex-arithmetic.json',{'CYP450_A_type':325,'CYP450_non_A_type':324,'CYP450_total':325+324,'ML_approx_combinations':200000,'ML_screened_samples':152,'ML_approx_sampling_percent':152/200000*100,'FW_DW_conversion_performed':False,'titer_to_carbon_yield_conversion_performed':False,'T10_conversion_ratio_WT':2.8,'T10_CYP_content_ratio_WT':9.5,'570_mgL_is_total_oxygenated_taxanes':True,'yeast_paclitaxel_microgL':.97,'yeast_paclitaxel_is_fed_substrate_conversion':True})
claims=[('Identity','Main1/liveZotero200','PrintedReview title6authors331148049DOI10.1016/j.ijbiomac.2025.148049 onlineOct1 2025notZoteroNov'),('Coverage','Main1-20Figures1-7Tables1-2','All20originalpages read and visuallyviewed ninecomplete300dpi finalcrops reviewed includingrotatedTable1 andallTable2rows'),('Search','Main17','PubMedWebofScienceScopus2000to2025oldermanualsupplement morethanthird2020to25; nofullqueriesfloworlastdate narrative notmeta-analysis'),('Pathscope','Main3/9Figure2','19steps authororganization notuniversalfixedsequence taxusinpathomitted deacetylationoutsidescope'),('PAMconflict','Main3Figure2/Main18ref33','PAM expandedammonialyase whilecitedtitleaminomutase retained namingconflict'),('TXS','Main4/6Figure3Table1','Threefolds classIactive metalmotifs inactiveopencrystal modelnotactiveobservation14positions nooverallactivityimproved iso-taxadienefractionnotnetflux'),('Families','Main4/6/7Figure4','325+324=649CYPgenes CYP750CC9functionpreventsCYP725Aonlyselection MEME0displaynotexperimentP'),('CYPstructure','Main7/8Figure5','taxadienevsisotaxadieneroutes sourcebasedinterpretations notallintermediatestrapped Fig5captiondistances4.3/3.8vsBdifferentannotationsnotunified2025copyrightvs2024reference retained'),('T10metrics','Main9/15','Triplemutant conversion2.8CYPcontent9.5differentdenominators no9.5intrinsicefficiency'),('Oxetane','Main9Table1','TOT1epoxideparallelnotnecessaryintermediate severalenzyme/substratereports notuniversalmergedpath'),('BAHD','Main10/11Figure6','acylCoAalcoholamineestersamides fiveACTsamefamily notinterchangeable VSstructureanalogy notTaxuscrystalvalidated motifpredictionnotfunctionproof'),('Production','Main11-15Table2','TaxadieneEcoli1gLyeast528mgL T5OAcyeast95plusminus4nine-dayresin T5OH43.65mgL 570totaloxytaxanesnotT5OH noFWtoDWortitercostranking'),('Geneconflict','Main11Table2','1.82mgLerg20bodyerg12table nooriginalpaperrechecktosilentlycorrect'),('Latepath','Main12/15/16','29.39nggFWref28tablevs29bodyfeedingdiscussion sourceconflict yeast.97plusminus.05microgLfeedbaccatinandbetaphenylalaninenotcompletecarbondeNovo'),('AI','Main16/17Figure7','conceptualDBTL/GEMworkflow externalMcbA/pectinexamplesnotTaxolbenefit152/approx200k.076percent notexactsampling'),('Citationboundary','Main16/Main20refs134135','135flavonolCRISPRactivationnotTaxusTaxolincrease verified132/othersfulltextnotclaimed'),('Transparency','Main17','Authorsdeclarednocompetinginterests fundingU24A20478QNESLOP20230832471485GenBankfigsharesequencesnotindependentlydownloaded dataonrequest humanreviewfalseclassifylater')]
labels=[x['label'] for x in images]
review={'pass':True,'review_status':'codex-source-checked','method':'Current Codex read and viewed all20originalpages and ninefinalcomplete300dpi figure/tablecrops; preserved narrative-review evidence, feeding, units and source inconsistencies; checked derived arithmetic separately','human_full_paper_review':False,'identity_matches':True,'classification_supported':True,'crop_complete':True,'major_issues':[],'figure_coverage':{'expected_labels':labels,'covered_labels':labels,'missing_panels':[],'missing_pages':[]},'verified_claims':[{'claim':a,'source_locator':b,'evidence':c}for a,b,c in claims],'unresolved_source_issues':draft['source_gaps']}
w.write_json(d/'codex-source-review.json',review)
w.validate_structure(draft)
note=w.publish(rec,draft,images,review,d)
w.record_result({'key':rec['key'],'title':rec['title'],'time':time.strftime('%Y-%m-%d %H:%M:%S'),'status':'published','note':note,'images':len(images),'review_status':'codex-source-checked'})
print(json.dumps({'note':note,'images':len(images)},ensure_ascii=False))
